#pragma once
/*
Package /Script/GameplayTags, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "UeMeta.h"
#include "CoreUObject.h"
#include "DeveloperSettings.h"
#include "Engine.h"

class AActor;
class UDataTable;
class UObject;

enum class EGameplayContainerMatchType : uint8
{
    Any                             = 0,
    All                             = 1,
    EGameplayContainerMatchType_MAX = 2,
};

enum class EGameplayTagMatchType : uint8
{
    Explicit                  = 0,
    IncludeParentTags         = 1,
    EGameplayTagMatchType_MAX = 2,
};

enum class EGameplayTagQueryExprType : uint8
{
    Undefined                     = 0,
    AnyTagsMatch                  = 1,
    AllTagsMatch                  = 2,
    NoTagsMatch                   = 3,
    AnyExprMatch                  = 4,
    AllExprMatch                  = 5,
    NoExprMatch                   = 6,
    EGameplayTagQueryExprType_MAX = 7,
};

enum class EGameplayTagSelectionType : uint8
{
    None                          = 0,
    NonRestrictedOnly             = 1,
    RestrictedOnly                = 2,
    All                           = 3,
    EGameplayTagSelectionType_MAX = 4,
};

enum class EGameplayTagSourceType : uint8
{
    Native                     = 0,
    DefaultTagList             = 1,
    TagList                    = 2,
    RestrictedTagList          = 3,
    DataTable                  = 4,
    Invalid                    = 5,
    EGameplayTagSourceType_MAX = 6,
};

struct FGameplayTag
{
    FName TagName;

    FGameplayTag() = default;
    FGameplayTag(FName TagName) {}
};

struct FGameplayTagCategoryRemap
{
    FString BaseCategory;
    TArray<FString> RemapCategories;

    FGameplayTagCategoryRemap() = default;
    FGameplayTagCategoryRemap(FString BaseCategory, TArray<FString> RemapCategories) {}
};

struct FGameplayTagContainer
{
    TArray<FGameplayTag> GameplayTags;
    TArray<FGameplayTag> ParentTags;

    FGameplayTagContainer() = default;
    FGameplayTagContainer(TArray<FGameplayTag> GameplayTags, TArray<FGameplayTag> ParentTags) {}
};

struct FGameplayTagCreationWidgetHelper
{
};

struct FGameplayTagNode
{
};

struct FGameplayTagQuery
{
    int TokenStreamVersion;
    TArray<FGameplayTag> TagDictionary;
    TArray<uint8> QueryTokenStream;
    FString UserDescription;
    FString AutoDescription;

    FGameplayTagQuery() = default;
    FGameplayTagQuery(int TokenStreamVersion, TArray<FGameplayTag> TagDictionary, TArray<uint8> QueryTokenStream, FString UserDescription, FString AutoDescription) {}
};

struct FGameplayTagRedirect
{
    FName OldTagName;
    FName NewTagName;

    FGameplayTagRedirect() = default;
    FGameplayTagRedirect(FName OldTagName, FName NewTagName) {}
};

struct FGameplayTagReferenceHelper
{
};

struct FGameplayTagSource
{
    FName SourceName;
    EGameplayTagSourceType SourceType;
    class UGameplayTagsList* SourceTagList;
    class URestrictedGameplayTagsList* SourceRestrictedTagList;

    FGameplayTagSource() = default;
    FGameplayTagSource(FName SourceName, EGameplayTagSourceType SourceType, class UGameplayTagsList* SourceTagList, class URestrictedGameplayTagsList* SourceRestrictedTagList) {}
};

struct FGameplayTagTableRow : public FTableRowBase
{
    FName Tag;
    FString DevComment;
};

struct FRestrictedConfigInfo
{
    FString RestrictedConfigName;
    TArray<FString> Owners;

    FRestrictedConfigInfo() = default;
    FRestrictedConfigInfo(FString RestrictedConfigName, TArray<FString> Owners) {}
};

struct FRestrictedGameplayTagTableRow : public FGameplayTagTableRow
{
    bool bAllowNonRestrictedChildren;
};

class UBlueprintGameplayTagLibrary : public UBlueprintFunctionLibrary
{
public:
    UE_CLASS("/Script/GameplayTags", "BlueprintGameplayTagLibrary");
    static void AddGameplayTag(FGameplayTagContainer TagContainer, FGameplayTag Tag);
    static void AppendGameplayTagContainers(FGameplayTagContainer InOutTagContainer, FGameplayTagContainer InTagContainer);
    static void BreakGameplayTagContainer(FGameplayTagContainer GameplayTagContainer, TArray<FGameplayTag>& GameplayTags);
    UE_PURE static bool DoesContainerMatchTagQuery(FGameplayTagContainer TagContainer, FGameplayTagQuery tagQuery);
    UE_PURE static bool DoesTagAssetInterfaceHaveTag(TScriptInterface<class IGameplayTagAssetInterface> TagContainerInterface, FGameplayTag Tag);
    UE_PURE static bool EqualEqual_GameplayTag(FGameplayTag A, FGameplayTag B);
    UE_PURE static bool EqualEqual_GameplayTagContainer(FGameplayTagContainer A, FGameplayTagContainer B);
    static void GetAllActorsOfClassMatchingTagQuery(class UObject* WorldContextObject, TSubclassOf<class AActor> actorClass, FGameplayTagQuery GameplayTagQuery, TArray<class AActor*>& OutActors);
    static void GetAllActorsOfClassMatchingTagQuery(TSubclassOf<class AActor> actorClass, FGameplayTagQuery GameplayTagQuery, TArray<class AActor*>& OutActors);
    UE_PURE static FString GetDebugStringFromGameplayTag(FGameplayTag GameplayTag);
    UE_PURE static FString GetDebugStringFromGameplayTagContainer(FGameplayTagContainer TagContainer);
    UE_PURE static int GetNumGameplayTagsInContainer(FGameplayTagContainer TagContainer);
    UE_PURE static FName GetTagName(FGameplayTag GameplayTag);
    UE_PURE static bool HasAllMatchingGameplayTags(TScriptInterface<class IGameplayTagAssetInterface> TagContainerInterface, FGameplayTagContainer OtherContainer);
    UE_PURE static bool HasAllTags(FGameplayTagContainer TagContainer, FGameplayTagContainer OtherContainer, bool bExactMatch);
    UE_PURE static bool HasAnyTags(FGameplayTagContainer TagContainer, FGameplayTagContainer OtherContainer, bool bExactMatch);
    UE_PURE static bool HasTag(FGameplayTagContainer TagContainer, FGameplayTag Tag, bool bExactMatch);
    UE_PURE static bool IsGameplayTagValid(FGameplayTag GameplayTag);
    UE_PURE static bool IsTagQueryEmpty(FGameplayTagQuery tagQuery);
    UE_PURE static FGameplayTagContainer MakeGameplayTagContainerFromArray(TArray<FGameplayTag> GameplayTags);
    UE_PURE static FGameplayTagContainer MakeGameplayTagContainerFromTag(FGameplayTag SingleTag);
    UE_PURE static FGameplayTagQuery MakeGameplayTagQuery(FGameplayTagQuery tagQuery);
    UE_PURE static FGameplayTag MakeLiteralGameplayTag(FGameplayTag Value);
    UE_PURE static FGameplayTagContainer MakeLiteralGameplayTagContainer(FGameplayTagContainer Value);
    UE_PURE static bool MatchesAnyTags(FGameplayTag TagOne, FGameplayTagContainer OtherContainer, bool bExactMatch);
    UE_PURE static bool MatchesTag(FGameplayTag TagOne, FGameplayTag TagTwo, bool bExactMatch);
    UE_PURE static bool NotEqual_GameplayTag(FGameplayTag A, FGameplayTag B);
    UE_PURE static bool NotEqual_GameplayTagContainer(FGameplayTagContainer A, FGameplayTagContainer B);
    UE_PURE static bool NotEqual_TagContainerTagContainer(FGameplayTagContainer A, FString B);
    UE_PURE static bool NotEqual_TagTag(FGameplayTag A, FString B);
    static bool RemoveGameplayTag(FGameplayTagContainer TagContainer, FGameplayTag Tag);
};

class IGameplayTagAssetInterface
{
public:
    UE_CLASS("/Script/GameplayTags", "GameplayTagAssetInterface");
    void GetOwnedGameplayTags(FGameplayTagContainer& TagContainer) const;
    UE_PURE bool HasAllMatchingGameplayTags(FGameplayTagContainer TagContainer) const;
    UE_PURE bool HasAnyMatchingGameplayTags(FGameplayTagContainer TagContainer) const;
    UE_PURE bool HasMatchingGameplayTag(FGameplayTag TagToCheck) const;
};

class UEditableGameplayTagQuery : public UObject
{
public:
    UE_CLASS("/Script/GameplayTags", "EditableGameplayTagQuery");
    FString UserDescription;
    class UEditableGameplayTagQueryExpression* RootExpression;
    FGameplayTagQuery TagQueryExportText_Helper;
};

class UEditableGameplayTagQueryExpression : public UObject
{
public:
    UE_CLASS("/Script/GameplayTags", "EditableGameplayTagQueryExpression");
};

class UEditableGameplayTagQueryExpression_AnyTagsMatch : public UEditableGameplayTagQueryExpression
{
public:
    UE_CLASS("/Script/GameplayTags", "EditableGameplayTagQueryExpression_AnyTagsMatch");
    FGameplayTagContainer Tags;
};

class UEditableGameplayTagQueryExpression_AllTagsMatch : public UEditableGameplayTagQueryExpression
{
public:
    UE_CLASS("/Script/GameplayTags", "EditableGameplayTagQueryExpression_AllTagsMatch");
    FGameplayTagContainer Tags;
};

class UEditableGameplayTagQueryExpression_NoTagsMatch : public UEditableGameplayTagQueryExpression
{
public:
    UE_CLASS("/Script/GameplayTags", "EditableGameplayTagQueryExpression_NoTagsMatch");
    FGameplayTagContainer Tags;
};

class UEditableGameplayTagQueryExpression_AnyExprMatch : public UEditableGameplayTagQueryExpression
{
public:
    UE_CLASS("/Script/GameplayTags", "EditableGameplayTagQueryExpression_AnyExprMatch");
    TArray<class UEditableGameplayTagQueryExpression*> Expressions;
};

class UEditableGameplayTagQueryExpression_AllExprMatch : public UEditableGameplayTagQueryExpression
{
public:
    UE_CLASS("/Script/GameplayTags", "EditableGameplayTagQueryExpression_AllExprMatch");
    TArray<class UEditableGameplayTagQueryExpression*> Expressions;
};

class UEditableGameplayTagQueryExpression_NoExprMatch : public UEditableGameplayTagQueryExpression
{
public:
    UE_CLASS("/Script/GameplayTags", "EditableGameplayTagQueryExpression_NoExprMatch");
    TArray<class UEditableGameplayTagQueryExpression*> Expressions;
};

class UGameplayTagsManager : public UObject
{
public:
    UE_CLASS("/Script/GameplayTags", "GameplayTagsManager");
    TMap<FName, FGameplayTagSource> TagSources;
    TArray<class UDataTable*> GameplayTagTables;
};

class UGameplayTagsList : public UObject
{
public:
    UE_CLASS("/Script/GameplayTags", "GameplayTagsList");
    FString ConfigFileName;
    TArray<FGameplayTagTableRow> GameplayTagList;
};

class URestrictedGameplayTagsList : public UObject
{
public:
    UE_CLASS("/Script/GameplayTags", "RestrictedGameplayTagsList");
    FString ConfigFileName;
    TArray<FRestrictedGameplayTagTableRow> RestrictedGameplayTagList;
};

class UGameplayTagsSettings : public UGameplayTagsList
{
public:
    UE_CLASS("/Script/GameplayTags", "GameplayTagsSettings");
    bool ImportTagsFromConfig;
    bool WarnOnInvalidTags;
    bool ClearInvalidTags;
    bool FastReplication;
    FString InvalidTagCharacters;
    TArray<FGameplayTagCategoryRemap> CategoryRemapping;
    TArray<FSoftObjectPath> GameplayTagTableList;
    TArray<FGameplayTagRedirect> GameplayTagRedirects;
    TArray<FName> CommonlyReplicatedTags;
    int NumBitsForContainerSize;
    int NetIndexFirstBitSegment;
    TArray<FRestrictedConfigInfo> RestrictedConfigFiles;
};

class UGameplayTagsDeveloperSettings : public UDeveloperSettings
{
public:
    UE_CLASS("/Script/GameplayTags", "GameplayTagsDeveloperSettings");
    FString DeveloperConfigName;
    FName FavoriteTagSource;
};

inline bool operator==(const FGameplayTag&, const FGameplayTag&) { return {}; }
inline bool operator==(const FGameplayTagContainer&, const FGameplayTagContainer&) { return {}; }
inline bool operator!=(const FGameplayTag&, const FGameplayTag&) { return {}; }
inline bool operator!=(const FGameplayTagContainer&, const FGameplayTagContainer&) { return {}; }
inline bool operator!=(const FGameplayTagContainer&, const FString&) { return {}; }
inline bool operator!=(const FGameplayTag&, const FString&) { return {}; }