#pragma once
/*
Package /Script/GeometryCacheTracks, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "UeMeta.h"
#include "CoreUObject.h"
#include "MovieScene.h"

class UMovieSceneSection;

struct FMovieSceneGeometryCacheParams
{
    class UGeometryCache* GeometryCacheAsset;
    FFrameNumber FirstLoopStartFrameOffset;
    FFrameNumber StartFrameOffset;
    FFrameNumber EndFrameOffset;
    float PlayRate;
    bool bReverse;
    float StartOffset;
    float EndOffset;
    FSoftObjectPath GeometryCache;

    FMovieSceneGeometryCacheParams() = default;
    FMovieSceneGeometryCacheParams(class UGeometryCache* GeometryCacheAsset, FFrameNumber FirstLoopStartFrameOffset, FFrameNumber StartFrameOffset, FFrameNumber EndFrameOffset, float PlayRate, bool bReverse, float StartOffset, float EndOffset, FSoftObjectPath GeometryCache) {}
};

struct FMovieSceneGeometryCacheSectionTemplateParameters : public FMovieSceneGeometryCacheParams
{
    FFrameNumber SectionStartTime;
    FFrameNumber SectionEndTime;

    FMovieSceneGeometryCacheSectionTemplateParameters() = default;
    FMovieSceneGeometryCacheSectionTemplateParameters(class UGeometryCache* GeometryCacheAsset, FFrameNumber FirstLoopStartFrameOffset, FFrameNumber StartFrameOffset, FFrameNumber EndFrameOffset, float PlayRate, bool bReverse, float StartOffset, float EndOffset, FSoftObjectPath GeometryCache, FFrameNumber SectionStartTime, FFrameNumber SectionEndTime) {}
};

struct FMovieSceneGeometryCacheSectionTemplate : public FMovieSceneEvalTemplate
{
    FMovieSceneGeometryCacheSectionTemplateParameters Params;
};

class UMovieSceneGeometryCacheSection : public UMovieSceneSection
{
public:
    UE_CLASS("/Script/GeometryCacheTracks", "MovieSceneGeometryCacheSection");
    FMovieSceneGeometryCacheParams Params_0;
    static constexpr const char* Params_0__UeName = "Params";
};

class UMovieSceneGeometryCacheTrack : public UMovieSceneNameableTrack
{
public:
    UE_CLASS("/Script/GeometryCacheTracks", "MovieSceneGeometryCacheTrack");
    TArray<class UMovieSceneSection*> AnimationSections;
};
