#pragma once
/*
Package /Script/MovieSceneCapture, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "UeMeta.h"
#include "CoreUObject.h"
#include "Engine.h"
#include "ImageWriteQueue.h"

class UMaterialInterface;
class UTexture;
class UWorld;

enum class EHDRCaptureGamut : uint8
{
    HCGM_Rec709  = 0,
    HCGM_P3DCI   = 1,
    HCGM_Rec2020 = 2,
    HCGM_ACES    = 3,
    HCGM_ACEScg  = 4,
    HCGM_Linear  = 5,
    HCGM_MAX     = 6,
};

enum class EMovieSceneCaptureProtocolState : uint8
{
    Idle                                = 0,
    Initialized                         = 1,
    Capturing                           = 2,
    Finalizing                          = 3,
    EMovieSceneCaptureProtocolState_MAX = 4,
};

struct FCaptureResolution
{
    int ResX;
    int ResY;

    FCaptureResolution() = default;
    FCaptureResolution(int ResX, int ResY) {}
};

struct FCapturedPixels
{
};

struct FCapturedPixelsID
{
    TMap<FName, FName> Identifiers;

    FCapturedPixelsID() = default;
    FCapturedPixelsID(TMap<FName, FName> Identifiers) {}
};

struct FCompositionGraphCapturePasses
{
    TArray<FString> Value;

    FCompositionGraphCapturePasses() = default;
    FCompositionGraphCapturePasses(TArray<FString> Value) {}
};

struct FFrameMetrics
{
    float TotalElapsedTime;
    float FrameDelta;
    int FrameNumber;
    int NumDroppedFrames;

    FFrameMetrics() = default;
    FFrameMetrics(float TotalElapsedTime, float FrameDelta, int FrameNumber, int NumDroppedFrames) {}
};

struct FMovieSceneCaptureSettings
{
    FDirectoryPath OutputDirectory;
    TSubclassOf<class AGameModeBase> GameModeOverride;
    FString OutputFormat;
    bool bOverwriteExisting;
    bool bUseRelativeFrameNumbers;
    int HandleFrames;
    FString MovieExtension;
    uint8 ZeroPadFrameNumbers;
    FFrameRate FrameRate;
    bool bUseCustomFrameRate;
    FFrameRate CustomFrameRate;
    FCaptureResolution Resolution;
    bool bEnableTextureStreaming;
    bool bCinematicEngineScalability;
    bool bCinematicMode;
    bool bAllowMovement;
    bool bAllowTurning;
    bool bShowPlayer;
    bool bShowHUD;
    bool bUsePathTracer;
    int PathTracerSamplePerPixel;

    FMovieSceneCaptureSettings() = default;
    FMovieSceneCaptureSettings(FDirectoryPath OutputDirectory, TSubclassOf<class AGameModeBase> GameModeOverride, FString OutputFormat, bool bOverwriteExisting, bool bUseRelativeFrameNumbers, int HandleFrames, FString MovieExtension, uint8 ZeroPadFrameNumbers, FFrameRate FrameRate, bool bUseCustomFrameRate, FFrameRate CustomFrameRate, FCaptureResolution Resolution, bool bEnableTextureStreaming, bool bCinematicEngineScalability, bool bCinematicMode, bool bAllowMovement, bool bAllowTurning, bool bShowPlayer, bool bShowHUD, bool bUsePathTracer, int PathTracerSamplePerPixel) {}
};

class UMovieSceneCaptureProtocolBase : public UObject
{
public:
    UE_CLASS("/Script/MovieSceneCapture", "MovieSceneCaptureProtocolBase");
    EMovieSceneCaptureProtocolState State;
    UE_PURE EMovieSceneCaptureProtocolState GetState() const;
    UE_PURE bool IsCapturing() const;
};

class UMovieSceneAudioCaptureProtocolBase : public UMovieSceneCaptureProtocolBase
{
public:
    UE_CLASS("/Script/MovieSceneCapture", "MovieSceneAudioCaptureProtocolBase");
};

class UNullAudioCaptureProtocol : public UMovieSceneAudioCaptureProtocolBase
{
public:
    UE_CLASS("/Script/MovieSceneCapture", "NullAudioCaptureProtocol");
};

class UMasterAudioSubmixCaptureProtocol : public UMovieSceneAudioCaptureProtocolBase
{
public:
    UE_CLASS("/Script/MovieSceneCapture", "MasterAudioSubmixCaptureProtocol");
    FString Filename;
};

class UMovieSceneImageCaptureProtocolBase : public UMovieSceneCaptureProtocolBase
{
public:
    UE_CLASS("/Script/MovieSceneCapture", "MovieSceneImageCaptureProtocolBase");
};

class UCompositionGraphCaptureProtocol : public UMovieSceneImageCaptureProtocolBase
{
public:
    UE_CLASS("/Script/MovieSceneCapture", "CompositionGraphCaptureProtocol");
    FCompositionGraphCapturePasses IncludeRenderPasses;
    bool bCaptureFramesInHDR;
    int HDRCompressionQuality;
    EHDRCaptureGamut CaptureGamut;
    FSoftObjectPath PostProcessingMaterial;
    bool bDisableScreenPercentage;
    class UMaterialInterface* PostProcessingMaterialPtr;
};

class UFrameGrabberProtocol : public UMovieSceneImageCaptureProtocolBase
{
public:
    UE_CLASS("/Script/MovieSceneCapture", "FrameGrabberProtocol");
};

class UImageSequenceProtocol : public UFrameGrabberProtocol
{
public:
    UE_CLASS("/Script/MovieSceneCapture", "ImageSequenceProtocol");
};

class UCompressedImageSequenceProtocol : public UImageSequenceProtocol
{
public:
    UE_CLASS("/Script/MovieSceneCapture", "CompressedImageSequenceProtocol");
    int CompressionQuality;
};

class UImageSequenceProtocol_BMP : public UImageSequenceProtocol
{
public:
    UE_CLASS("/Script/MovieSceneCapture", "ImageSequenceProtocol_BMP");
};

class UImageSequenceProtocol_PNG : public UCompressedImageSequenceProtocol
{
public:
    UE_CLASS("/Script/MovieSceneCapture", "ImageSequenceProtocol_PNG");
};

class UImageSequenceProtocol_JPG : public UCompressedImageSequenceProtocol
{
public:
    UE_CLASS("/Script/MovieSceneCapture", "ImageSequenceProtocol_JPG");
};

class UImageSequenceProtocol_EXR : public UImageSequenceProtocol
{
public:
    UE_CLASS("/Script/MovieSceneCapture", "ImageSequenceProtocol_EXR");
    bool bCompressed;
    EHDRCaptureGamut CaptureGamut;
};

class IMovieSceneCaptureInterface
{
public:
    UE_CLASS("/Script/MovieSceneCapture", "MovieSceneCaptureInterface");
};

class UMovieSceneCapture : public UObject
{
public:
    UE_CLASS("/Script/MovieSceneCapture", "MovieSceneCapture");
    FSoftClassPath ImageCaptureProtocolType;
    FSoftClassPath AudioCaptureProtocolType;
    class UMovieSceneImageCaptureProtocolBase* ImageCaptureProtocol;
    class UMovieSceneAudioCaptureProtocolBase* AudioCaptureProtocol;
    FMovieSceneCaptureSettings Settings;
    bool bUseSeparateProcess;
    bool bCloseEditorWhenCaptureStarts;
    FString AdditionalCommandLineArguments;
    FString InheritedCommandLineArguments;
    class UMovieSceneCaptureProtocolBase* GetAudioCaptureProtocol();
    class UMovieSceneCaptureProtocolBase* GetImageCaptureProtocol();
    void SetAudioCaptureProtocolType(TSubclassOf<class UMovieSceneCaptureProtocolBase> ProtocolType);
    void SetImageCaptureProtocolType(TSubclassOf<class UMovieSceneCaptureProtocolBase> ProtocolType);
};

class ULevelCapture : public UMovieSceneCapture
{
public:
    UE_CLASS("/Script/MovieSceneCapture", "LevelCapture");
    bool bAutoStartCapture;
    FGuid PrerequisiteActorId;
};

class UMovieSceneCaptureEnvironment : public UObject
{
public:
    UE_CLASS("/Script/MovieSceneCapture", "MovieSceneCaptureEnvironment");
    static class UMovieSceneAudioCaptureProtocolBase* FindAudioCaptureProtocol();
    static class UMovieSceneImageCaptureProtocolBase* FindImageCaptureProtocol();
    UE_PURE static float GetCaptureElapsedTime();
    UE_PURE static int GetCaptureFrameNumber();
    static bool IsCaptureInProgress();
};

class UUserDefinedCaptureProtocol : public UMovieSceneImageCaptureProtocolBase
{
public:
    UE_CLASS("/Script/MovieSceneCapture", "UserDefinedCaptureProtocol");
    class UWorld* World;
    void OnBeginFinalize();
    void OnCaptureFrame();
    void OnFinalize();
    void OnPauseCapture();
    void OnPixelsReceived(const FCapturedPixels& Pixels, const FCapturedPixelsID& ID, FFrameMetrics FrameMetrics);
    void OnPreTick();
    bool OnSetup();
    void OnStartCapture();
    void OnTick();
    void OnWarmUp();
    void ResolveBuffer(class UTexture* Buffer, const FCapturedPixelsID& BufferID);
    void StartCapturingFinalPixels(const FCapturedPixelsID& StreamID);
    void StopCapturingFinalPixels();
    UE_PURE FString GenerateFilename(const FFrameMetrics& InFrameMetrics) const;
    UE_PURE FFrameMetrics GetCurrentFrameMetrics() const;
    bool OnCanFinalize() const;
};

class UUserDefinedImageCaptureProtocol : public UUserDefinedCaptureProtocol
{
public:
    UE_CLASS("/Script/MovieSceneCapture", "UserDefinedImageCaptureProtocol");
    EDesiredImageFormat Format;
    bool bEnableCompression;
    int CompressionQuality;
    FString GenerateFilenameForBuffer(class UTexture* Buffer, const FCapturedPixelsID& StreamID);
    FString GenerateFilenameForCurrentFrame();
    void WriteImageToDisk(const FCapturedPixels& PixelData, const FCapturedPixelsID& StreamID, const FFrameMetrics& FrameMetrics, bool bCopyImageData);
};

class UVideoCaptureProtocol : public UFrameGrabberProtocol
{
public:
    UE_CLASS("/Script/MovieSceneCapture", "VideoCaptureProtocol");
    bool bUseCompression;
    float CompressionQuality;
};
