#pragma once
/*
Package /Script/NiagaraAnimNotifies, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "UeMeta.h"
#include "CoreUObject.h"
#include "Engine.h"

class UFXSystemComponent;
class UMeshComponent;
class UNiagaraSystem;

class UAnimNotify_PlayNiagaraEffect : public UAnimNotify
{
public:
    UE_CLASS("/Script/NiagaraAnimNotifies", "AnimNotify_PlayNiagaraEffect");
    UE_READONLY class UNiagaraSystem* Template;
    UE_READONLY FVector LocationOffset;
    UE_READONLY FRotator RotationOffset;
    UE_READONLY FVector Scale;
    UE_READONLY bool bAbsoluteScale;
    UE_READONLY bool Attached;
    UE_READONLY FName SocketName;
    class UFXSystemComponent* GetSpawnedEffect() const;
};

class UAnimNotifyState_TimedNiagaraEffect : public UAnimNotifyState
{
public:
    UE_CLASS("/Script/NiagaraAnimNotifies", "AnimNotifyState_TimedNiagaraEffect");
    UE_READONLY class UNiagaraSystem* Template;
    UE_READONLY FName SocketName;
    UE_READONLY FVector LocationOffset;
    UE_READONLY FRotator RotationOffset;
    UE_READONLY bool bDestroyAtEnd;
    class UFXSystemComponent* GetSpawnedEffect(class UMeshComponent* MeshComp) const;
};

class UAnimNotifyState_TimedNiagaraEffectAdvanced : public UAnimNotifyState_TimedNiagaraEffect
{
public:
    UE_CLASS("/Script/NiagaraAnimNotifies", "AnimNotifyState_TimedNiagaraEffectAdvanced");
    float GetNotifyProgress(class UMeshComponent* MeshComp) const;
};
