#pragma once
/*
Package /Script/WmfMediaFactory, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "UeMeta.h"
#include "CoreUObject.h"

class UWmfMediaSettings : public UObject
{
public:
    UE_CLASS("/Script/WmfMediaFactory", "WmfMediaSettings");
    bool AllowNonStandardCodecs;
    bool LowLatency;
    bool NativeAudioOut;
    bool HardwareAcceleratedVideoDecoding;
};
