#pragma once
/*
Every UAssaultRifleUpgrade asset in the game, 4 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::UAssaultRifleUpgrade::Game::WeaponsNTools::AssaultRifle::UPG_Effect_KillAccuracyReset
points at /Game/WeaponsNTools/AssaultRifle/UPG_Effect_KillAccuracyReset.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/FSD.h"

namespace UeAssets::UAssaultRifleUpgrade::Game::WeaponsNTools::AssaultRifle {
UE_ASSET_AT(::UAssaultRifleUpgrade, UPG_Effect_KillAccuracyReset, "/Game/WeaponsNTools/AssaultRifle/UPG_Effect_KillAccuracyReset");
UE_ASSET_AT(::UAssaultRifleUpgrade, UPG_Effect_KillSpeedBoost, "/Game/WeaponsNTools/AssaultRifle/UPG_Effect_KillSpeedBoost");
}
namespace UeAssets::UAssaultRifleUpgrade::Game::WeaponsNTools::AssaultRifle::RFND_S03 {
UE_ASSET_AT(::UAssaultRifleUpgrade, UPG_AssaultRifle_KillAccuracyReset, "/Game/WeaponsNTools/AssaultRifle/RFND_S03/UPG_AssaultRifle_KillAccuracyReset");
UE_ASSET_AT(::UAssaultRifleUpgrade, UPG_AssaultRifle_KillSpeedBoost, "/Game/WeaponsNTools/AssaultRifle/RFND_S03/UPG_AssaultRifle_KillSpeedBoost");
}
