#pragma once
/*
Every UBoscoProjectileAbillity asset in the game, 3 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::UBoscoProjectileAbillity::Game::GameElements::Drone::BA_CryoGrenade
points at /Game/GameElements/Drone/BA_CryoGrenade.
UeAssets::UBoscoProjectileAbillity::All is every one of them, as soft pointers.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/FSD.h"

namespace UeAssets::UBoscoProjectileAbillity {
UE_ASSET_ALL(::UBoscoProjectileAbillity);
}
namespace UeAssets::UBoscoProjectileAbillity::Game::GameElements::Drone {
UE_ASSET_AT(::UBoscoProjectileAbillity, BA_CryoGrenade, "/Game/GameElements/Drone/BA_CryoGrenade");
UE_ASSET_AT(::UBoscoProjectileAbillity, BA_FoamRocket, "/Game/GameElements/Drone/BA_FoamRocket");
UE_ASSET_AT(::UBoscoProjectileAbillity, BA_Rocket, "/Game/GameElements/Drone/BA_Rocket");
}
