#pragma once
/*
Every UCommunicationMutator asset in the game, 1 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::UCommunicationMutator::Game::GameElements::Missions::Mutators::OxygenRich::MUT_OxygenRich
points at /Game/GameElements/Missions/Mutators/OxygenRich/MUT_OxygenRich.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/FSD.h"

namespace UeAssets::UCommunicationMutator::Game::GameElements::Missions::Mutators::OxygenRich {
UE_ASSET_AT(::UCommunicationMutator, MUT_OxygenRich, "/Game/GameElements/Missions/Mutators/OxygenRich/MUT_OxygenRich");
}
