#pragma once
/*
Every UDamageUpgrade asset in the game, 231 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::UDamageUpgrade::Game::GameElements::Drone::Upgrades::UPG_Bosco_PrimaryDamage
points at /Game/GameElements/Drone/Upgrades/UPG_Bosco_PrimaryDamage.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/FSD.h"

namespace UeAssets::UDamageUpgrade::Game::GameElements::Drone::Upgrades {
UE_ASSET_AT(::UDamageUpgrade, UPG_Bosco_PrimaryDamage, "/Game/GameElements/Drone/Upgrades/UPG_Bosco_PrimaryDamage");
UE_ASSET_AT(::UDamageUpgrade, UPG_Bosco_SAAOE, "/Game/GameElements/Drone/Upgrades/UPG_Bosco_SAAOE");
UE_ASSET_AT(::UDamageUpgrade, UPG_Bosco_SAArmorBreak, "/Game/GameElements/Drone/Upgrades/UPG_Bosco_SAArmorBreak");
UE_ASSET_AT(::UDamageUpgrade, UPG_Bosco_SAFear, "/Game/GameElements/Drone/Upgrades/UPG_Bosco_SAFear");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::AssaultRifle {
UE_ASSET_AT(::UDamageUpgrade, UPG_AssaultRifle_ArmorDamage, "/Game/WeaponsNTools/AssaultRifle/UPG_AssaultRifle_ArmorDamage");
UE_ASSET_AT(::UDamageUpgrade, UPG_AssaultRifle_Damage_2, "/Game/WeaponsNTools/AssaultRifle/UPG_AssaultRifle_Damage+2");
UE_ASSET_AT(::UDamageUpgrade, UPG_AssaultRifle_StaggerOnWeakspot, "/Game/WeaponsNTools/AssaultRifle/UPG_AssaultRifle_StaggerOnWeakspot");
UE_ASSET_AT(::UDamageUpgrade, UPG_AssaultRifle_WeakspotDamage, "/Game/WeaponsNTools/AssaultRifle/UPG_AssaultRifle_WeakspotDamage");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::AssaultRifle::Overclocks::OC_BonusesAndPenalties {
UE_ASSET_AT(::UDamageUpgrade, Bonus_Stun_10_AssaultRifle, "/Game/WeaponsNTools/AssaultRifle/Overclocks/OC_BonusesAndPenalties/Bonus_Stun_10_AssaultRifle");
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_Damage_2_AssaultRifle, "/Game/WeaponsNTools/AssaultRifle/Overclocks/OC_BonusesAndPenalties/OC_Bonus_Damage_2_AssaultRifle");
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_WeakpointDamage_20p_AssaultRifle, "/Game/WeaponsNTools/AssaultRifle/Overclocks/OC_BonusesAndPenalties/OC_Bonus_WeakpointDamage_20p_AssaultRifle");
UE_ASSET_AT(::UDamageUpgrade, OC_Penalty_Damage_2_AssaultRifle, "/Game/WeaponsNTools/AssaultRifle/Overclocks/OC_BonusesAndPenalties/OC_Penalty_Damage-2_AssaultRifle");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::AssaultRifle::RFND_S03 {
UE_ASSET_AT(::UDamageUpgrade, UPG_AssaultRifle_Damage_1_B, "/Game/WeaponsNTools/AssaultRifle/RFND_S03/UPG_AssaultRifle_Damage+1_B");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::Autocannon {
UE_ASSET_AT(::UDamageUpgrade, UPG_AutoCannon_A_Damage, "/Game/WeaponsNTools/Autocannon/UPG_AutoCannon_A_Damage");
UE_ASSET_AT(::UDamageUpgrade, UPG_AutoCannon_C_Damage, "/Game/WeaponsNTools/Autocannon/UPG_AutoCannon_C_Damage");
UE_ASSET_AT(::UDamageUpgrade, UPG_AutoCannon_C_RadialDamage, "/Game/WeaponsNTools/Autocannon/UPG_AutoCannon_C_RadialDamage");
UE_ASSET_AT(::UDamageUpgrade, UPG_AutoCannon_D_AmorBreak, "/Game/WeaponsNTools/Autocannon/UPG_AutoCannon_D_AmorBreak");
UE_ASSET_AT(::UDamageUpgrade, UPG_AutoCannon_D_RadialRange, "/Game/WeaponsNTools/Autocannon/UPG_AutoCannon_D_RadialRange");
UE_ASSET_AT(::UDamageUpgrade, UPG_AutoCannon_E_FearOnHit, "/Game/WeaponsNTools/Autocannon/UPG_AutoCannon_E_FearOnHit");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::Autocannon::Overclocks::OC_BonusesAndPenalties {
UE_ASSET_AT(::UDamageUpgrade, Bonus_Damage10_AC, "/Game/WeaponsNTools/Autocannon/Overclocks/OC_BonusesAndPenalties/Bonus_Damage10_AC");
UE_ASSET_AT(::UDamageUpgrade, Bonus_RadialDamage_28_Autocannon, "/Game/WeaponsNTools/Autocannon/Overclocks/OC_BonusesAndPenalties/Bonus_RadialDamage_28_Autocannon");
UE_ASSET_AT(::UDamageUpgrade, Bonus_RadialRange25_AC, "/Game/WeaponsNTools/Autocannon/Overclocks/OC_BonusesAndPenalties/Bonus_RadialRange25_AC");
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_RadialDamage_1_Autocannon, "/Game/WeaponsNTools/Autocannon/Overclocks/OC_BonusesAndPenalties/OC_Bonus_RadialDamage_1_Autocannon");
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_RadialDamage_4_Autocannon, "/Game/WeaponsNTools/Autocannon/Overclocks/OC_BonusesAndPenalties/OC_Bonus_RadialDamage_4_Autocannon");
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_RadialRange_200_Autocannon, "/Game/WeaponsNTools/Autocannon/Overclocks/OC_BonusesAndPenalties/OC_Bonus_RadialRange_200_Autocannon");
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_RadialRange_25P_Autocannon, "/Game/WeaponsNTools/Autocannon/Overclocks/OC_BonusesAndPenalties/OC_Bonus_RadialRange_25P_Autocannon");
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_RadialRange_percent_Autocannon, "/Game/WeaponsNTools/Autocannon/Overclocks/OC_BonusesAndPenalties/OC_Bonus_RadialRange_percent_Autocannon");
UE_ASSET_AT(::UDamageUpgrade, OC_Penalty_Damage_14_Autocannon_, "/Game/WeaponsNTools/Autocannon/Overclocks/OC_BonusesAndPenalties/OC_Penalty_Damage_14_Autocannon_");
UE_ASSET_AT(::UDamageUpgrade, Penalty_DirectDamage_9_AC, "/Game/WeaponsNTools/Autocannon/Overclocks/OC_BonusesAndPenalties/Penalty_DirectDamage-9_AC");
UE_ASSET_AT(::UDamageUpgrade, Penalty_SplashDamage_4_AC, "/Game/WeaponsNTools/Autocannon/Overclocks/OC_BonusesAndPenalties/Penalty_SplashDamage-4_AC");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::Autocannon::Refund_U24 {
UE_ASSET_AT(::UDamageUpgrade, UPG_AutoCannon_D_Stagger, "/Game/WeaponsNTools/Autocannon/Refund_U24/UPG_AutoCannon_D_Stagger");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::BoltActionRifle {
UE_ASSET_AT(::UDamageUpgrade, UPG_M1000_A_Damage, "/Game/WeaponsNTools/BoltActionRifle/UPG_M1000_A_Damage");
UE_ASSET_AT(::UDamageUpgrade, UPG_M1000_D_ArmorBreaking, "/Game/WeaponsNTools/BoltActionRifle/UPG_M1000_D_ArmorBreaking");
UE_ASSET_AT(::UDamageUpgrade, UPG_M1000_D_WeakspotDamage, "/Game/WeaponsNTools/BoltActionRifle/UPG_M1000_D_WeakspotDamage");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::BoltActionRifle::Overclocks::OC_BonusesAndPenalties {
UE_ASSET_AT(::UDamageUpgrade, OC_Penalty_Damage_15_M1000, "/Game/WeaponsNTools/BoltActionRifle/Overclocks/OC_BonusesAndPenalties/OC_Penalty_Damage_15_M1000");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::BurstFirePistol {
UE_ASSET_AT(::UDamageUpgrade, UPG_BurstPistol_A_Damage, "/Game/WeaponsNTools/BurstFirePistol/UPG_BurstPistol_A_Damage");
UE_ASSET_AT(::UDamageUpgrade, UPG_BurstPistol_C_Damage, "/Game/WeaponsNTools/BurstFirePistol/UPG_BurstPistol_C_Damage");
UE_ASSET_AT(::UDamageUpgrade, UPG_BurstPistol_D_ArmorDamage, "/Game/WeaponsNTools/BurstFirePistol/UPG_BurstPistol_D_ArmorDamage");
UE_ASSET_AT(::UDamageUpgrade, UPG_BurstPistol_D_WeakSpot, "/Game/WeaponsNTools/BurstFirePistol/UPG_BurstPistol_D_WeakSpot");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::BurstFirePistol::Overclocks::OCBonusPenalty {
UE_ASSET_AT(::UDamageUpgrade, Bonus_Damage1_BRT, "/Game/WeaponsNTools/BurstFirePistol/Overclocks/OCBonusPenalty/Bonus_Damage1_BRT");
UE_ASSET_AT(::UDamageUpgrade, Bonus_Damage4_BRT, "/Game/WeaponsNTools/BurstFirePistol/Overclocks/OCBonusPenalty/Bonus_Damage4_BRT");
UE_ASSET_AT(::UDamageUpgrade, Bonus_DamageBig_BRT, "/Game/WeaponsNTools/BurstFirePistol/Overclocks/OCBonusPenalty/Bonus_DamageBig_BRT");
UE_ASSET_AT(::UDamageUpgrade, Penalty_Damage_11_BRT, "/Game/WeaponsNTools/BurstFirePistol/Overclocks/OCBonusPenalty/Penalty_Damage-11_BRT");
UE_ASSET_AT(::UDamageUpgrade, Penalty_Damage_3_BRT, "/Game/WeaponsNTools/BurstFirePistol/Overclocks/OCBonusPenalty/Penalty_Damage-3_BRT");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::ChargeBlaster {
UE_ASSET_AT(::UDamageUpgrade, UPG_ChargeBlaster_A_Damage, "/Game/WeaponsNTools/ChargeBlaster/UPG_ChargeBlaster_A_Damage");
UE_ASSET_AT(::UDamageUpgrade, UPG_ChargeBlaster_B_ChargedExplosionRadius, "/Game/WeaponsNTools/ChargeBlaster/UPG_ChargeBlaster_B_ChargedExplosionRadius");
UE_ASSET_AT(::UDamageUpgrade, UPG_Effect_SplashAoE_DirectDMGPenalty_EPC, "/Game/WeaponsNTools/ChargeBlaster/UPG_Effect_SplashAoE_DirectDMGPenalty_EPC");
UE_ASSET_AT(::UDamageUpgrade, UPG_Effect_SplashAoE_EPC, "/Game/WeaponsNTools/ChargeBlaster/UPG_Effect_SplashAoE_EPC");
UE_ASSET_AT(::UDamageUpgrade, UPGEffect_ChargeBlaster_ChargeAoEDMG_1, "/Game/WeaponsNTools/ChargeBlaster/UPGEffect_ChargeBlaster_ChargeAoEDMG_1");
UE_ASSET_AT(::UDamageUpgrade, UPGEffect_ChargeBlaster_ChargeAoEDMG_2, "/Game/WeaponsNTools/ChargeBlaster/UPGEffect_ChargeBlaster_ChargeAoEDMG_2");
UE_ASSET_AT(::UDamageUpgrade, UPGEffect_ChargeBlaster_ChargeDirectDMG_1, "/Game/WeaponsNTools/ChargeBlaster/UPGEffect_ChargeBlaster_ChargeDirectDMG_1");
UE_ASSET_AT(::UDamageUpgrade, UPGEffect_ChargeBlaster_ChargeDirectDMG_2, "/Game/WeaponsNTools/ChargeBlaster/UPGEffect_ChargeBlaster_ChargeDirectDMG_2");
UE_ASSET_AT(::UDamageUpgrade, UPGEffect_FN_NoExplosion_Dmg0, "/Game/WeaponsNTools/ChargeBlaster/UPGEffect_FN_NoExplosion_Dmg0");
UE_ASSET_AT(::UDamageUpgrade, UPGEffect_FN_NoExplosion_RangeMult, "/Game/WeaponsNTools/ChargeBlaster/UPGEffect_FN_NoExplosion_RangeMult");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::ChargeBlaster::Overclocks::OC_BonusAndPenalty {
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_ChargeAoE_DMG_EPC, "/Game/WeaponsNTools/ChargeBlaster/Overclocks/OC_BonusAndPenalty/OC_Bonus_ChargeAoE_DMG_EPC");
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_ChargedDamageRadius_EPC, "/Game/WeaponsNTools/ChargeBlaster/Overclocks/OC_BonusAndPenalty/OC_Bonus_ChargedDamageRadius_EPC");
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_ChargeDirectDMG_EPC, "/Game/WeaponsNTools/ChargeBlaster/Overclocks/OC_BonusAndPenalty/OC_Bonus_ChargeDirectDMG_EPC");
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_NormalAoEDamage5_EPC, "/Game/WeaponsNTools/ChargeBlaster/Overclocks/OC_BonusAndPenalty/OC_Bonus_NormalAoEDamage5_EPC");
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_NormalDamage5_EPC, "/Game/WeaponsNTools/ChargeBlaster/Overclocks/OC_BonusAndPenalty/OC_Bonus_NormalDamage5_EPC");
UE_ASSET_AT(::UDamageUpgrade, OC_Penalty_ChargedExplosionDamage_20_EPC, "/Game/WeaponsNTools/ChargeBlaster/Overclocks/OC_BonusAndPenalty/OC_Penalty_ChargedExplosionDamage-20_EPC");
UE_ASSET_AT(::UDamageUpgrade, OC_Penalty_ChargeDirectDmg_EPC, "/Game/WeaponsNTools/ChargeBlaster/Overclocks/OC_BonusAndPenalty/OC_Penalty_ChargeDirectDmg_EPC");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::CoilGun::Upgrades {
UE_ASSET_AT(::UDamageUpgrade, UPG_Coilgun_A_Damage, "/Game/WeaponsNTools/CoilGun/Upgrades/UPG_Coilgun_A_Damage");
UE_ASSET_AT(::UDamageUpgrade, UPG_EFFECT_Coilgun_SHockwaveDamage, "/Game/WeaponsNTools/CoilGun/Upgrades/UPG_EFFECT_Coilgun_SHockwaveDamage");
UE_ASSET_AT(::UDamageUpgrade, UPG_EFFECT_Coilgun_ShotwaveFearFactor, "/Game/WeaponsNTools/CoilGun/Upgrades/UPG_EFFECT_Coilgun_ShotwaveFearFactor");
UE_ASSET_AT(::UDamageUpgrade, UPG_EFFECT_Coilgun_ShotwaveStunChance, "/Game/WeaponsNTools/CoilGun/Upgrades/UPG_EFFECT_Coilgun_ShotwaveStunChance");
UE_ASSET_AT(::UDamageUpgrade, UPG_EFFECT_Coilgun_ShotwaveStunDuration, "/Game/WeaponsNTools/CoilGun/Upgrades/UPG_EFFECT_Coilgun_ShotwaveStunDuration");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::CombatShotgun {
UE_ASSET_AT(::UDamageUpgrade, UPG_CombatShotgun_D_ArmorBreaking, "/Game/WeaponsNTools/CombatShotgun/UPG_CombatShotgun_D_ArmorBreaking");
UE_ASSET_AT(::UDamageUpgrade, UPG_CombatShotgun_D_Damage_1, "/Game/WeaponsNTools/CombatShotgun/UPG_CombatShotgun_D_Damage+1");
UE_ASSET_AT(::UDamageUpgrade, UPG_Effect_StaggerChance_CShot, "/Game/WeaponsNTools/CombatShotgun/UPG_Effect_StaggerChance_CShot");
UE_ASSET_AT(::UDamageUpgrade, UPG_Effect_StaggerDuration_CShot, "/Game/WeaponsNTools/CombatShotgun/UPG_Effect_StaggerDuration_CShot");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::CombatShotgun::Overclocks::OC_BonusesAndPenalties {
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_Damage_1_CombatShotgun, "/Game/WeaponsNTools/CombatShotgun/Overclocks/OC_BonusesAndPenalties/OC_Bonus_Damage+1_CombatShotgun");
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_Damage_4_CombatShotgun, "/Game/WeaponsNTools/CombatShotgun/Overclocks/OC_BonusesAndPenalties/OC_Bonus_Damage+4_CombatShotgun");
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_StunAllBodyParts_CombatShotgun, "/Game/WeaponsNTools/CombatShotgun/Overclocks/OC_BonusesAndPenalties/OC_Bonus_StunAllBodyParts_CombatShotgun");
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_WeakPointDamage_CombatShotgun, "/Game/WeaponsNTools/CombatShotgun/Overclocks/OC_BonusesAndPenalties/OC_Bonus_WeakPointDamage_CombatShotgun");
UE_ASSET_AT(::UDamageUpgrade, OC_Penalty_Damage_2_CombatSHotgun, "/Game/WeaponsNTools/CombatShotgun/Overclocks/OC_BonusesAndPenalties/OC_Penalty_Damage_2_CombatSHotgun");
UE_ASSET_AT(::UDamageUpgrade, OC_Penalty_Stagger_CShot, "/Game/WeaponsNTools/CombatShotgun/Overclocks/OC_BonusesAndPenalties/OC_Penalty_Stagger_CShot");
UE_ASSET_AT(::UDamageUpgrade, OC_Penalty_StaggerDuration_CShot, "/Game/WeaponsNTools/CombatShotgun/Overclocks/OC_BonusesAndPenalties/OC_Penalty_StaggerDuration_CShot");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::Crossbow::Overclocks::OC_BonusesAndPenalties {
UE_ASSET_AT(::UDamageUpgrade, Bonus_AreaRadius_05_Crossbow, "/Game/WeaponsNTools/Crossbow/Overclocks/OC_BonusesAndPenalties/Bonus_AreaRadius_05_Crossbow");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::Cryospray::Overclocks::OC_BonusesAndPenalties {
UE_ASSET_AT(::UDamageUpgrade, Bonus_Damage_Cryo, "/Game/WeaponsNTools/Cryospray/Overclocks/OC_BonusesAndPenalties/Bonus_Damage_Cryo");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::Cryospray::RFND_S05 {
UE_ASSET_AT(::UDamageUpgrade, UPG_Cryospray_D_Damage, "/Game/WeaponsNTools/Cryospray/RFND_S05/UPG_Cryospray_D_Damage");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::DetPack {
UE_ASSET_AT(::UDamageUpgrade, UPG_DetPack_A_Damage, "/Game/WeaponsNTools/DetPack/UPG_DetPack_A_Damage");
UE_ASSET_AT(::UDamageUpgrade, UPG_DetPack_A_Radius, "/Game/WeaponsNTools/DetPack/UPG_DetPack_A_Radius");
UE_ASSET_AT(::UDamageUpgrade, UPG_DetPack_C_Damage_2, "/Game/WeaponsNTools/DetPack/UPG_DetPack_C_Damage_2");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::DetPack::OLD_Upgrades {
UE_ASSET_AT(::UDamageUpgrade, UPG_DetPack_Driller_A, "/Game/WeaponsNTools/DetPack/OLD_Upgrades/UPG_DetPack_Driller_A");
UE_ASSET_AT(::UDamageUpgrade, UPG_DetPack_Driller_B, "/Game/WeaponsNTools/DetPack/OLD_Upgrades/UPG_DetPack_Driller_B");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::Drills {
UE_ASSET_AT(::UDamageUpgrade, UPG_Drills_A_Damage, "/Game/WeaponsNTools/Drills/UPG_Drills_A_Damage");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::Drills::OldUpgrades {
UE_ASSET_AT(::UDamageUpgrade, UPG_Drills_Damage, "/Game/WeaponsNTools/Drills/OldUpgrades/UPG_Drills_Damage");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::DualMachinePistols {
UE_ASSET_AT(::UDamageUpgrade, UPG_DualMP_A_Damage, "/Game/WeaponsNTools/DualMachinePistols/UPG_DualMP_A_Damage");
UE_ASSET_AT(::UDamageUpgrade, UPG_DualMP_C_Damage2, "/Game/WeaponsNTools/DualMachinePistols/UPG_DualMP_C_Damage2");
UE_ASSET_AT(::UDamageUpgrade, UPG_DualMP_D_Weakspot, "/Game/WeaponsNTools/DualMachinePistols/UPG_DualMP_D_Weakspot");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::DualMachinePistols::Overclocks::OC_BonusesAndPenalties {
UE_ASSET_AT(::UDamageUpgrade, Bonus_ArmorBreak_DualMP, "/Game/WeaponsNTools/DualMachinePistols/Overclocks/OC_BonusesAndPenalties/Bonus_ArmorBreak_DualMP");
UE_ASSET_AT(::UDamageUpgrade, Bonus_DmgBig_DualMP, "/Game/WeaponsNTools/DualMachinePistols/Overclocks/OC_BonusesAndPenalties/Bonus_DmgBig_DualMP");
UE_ASSET_AT(::UDamageUpgrade, Penalty_Dmg_1_DualMP_2, "/Game/WeaponsNTools/DualMachinePistols/Overclocks/OC_BonusesAndPenalties/Penalty_Dmg-1_DualMP_2");
UE_ASSET_AT(::UDamageUpgrade, Penalty_Dmg_3_DualMP, "/Game/WeaponsNTools/DualMachinePistols/Overclocks/OC_BonusesAndPenalties/Penalty_Dmg-3_DualMP");
UE_ASSET_AT(::UDamageUpgrade, Penalty_NoWeakspotBonus_DualMP, "/Game/WeaponsNTools/DualMachinePistols/Overclocks/OC_BonusesAndPenalties/Penalty_NoWeakspotBonus_DualMP");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::DualMachinePistols::Refund_U24 {
UE_ASSET_AT(::UDamageUpgrade, UPG_DualMP_D_Stagger, "/Game/WeaponsNTools/DualMachinePistols/Refund_U24/UPG_DualMP_D_Stagger");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::FlameThrower {
UE_ASSET_AT(::UDamageUpgrade, UPG_Flamethrower_B_Damage, "/Game/WeaponsNTools/FlameThrower/UPG_Flamethrower_B_Damage");
UE_ASSET_AT(::UDamageUpgrade, UPG_Flamethrower_D_Fear, "/Game/WeaponsNTools/FlameThrower/UPG_Flamethrower_D_Fear");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::FlameThrower::Overclocks::OC_BonusesAndPenalties {
UE_ASSET_AT(::UDamageUpgrade, Bonus_Dmg_1_Flamethrower, "/Game/WeaponsNTools/FlameThrower/Overclocks/OC_BonusesAndPenalties/Bonus_Dmg+1_Flamethrower");
UE_ASSET_AT(::UDamageUpgrade, Bonus_DMG_3_Flamethrower, "/Game/WeaponsNTools/FlameThrower/Overclocks/OC_BonusesAndPenalties/Bonus_DMG+3_Flamethrower");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::GatlingGun::Overclocks::OC_BonusesAndPenalties {
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_Damage1, "/Game/WeaponsNTools/GatlingGun/Overclocks/OC_BonusesAndPenalties/OC_Bonus_Damage1");
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_Damage_2, "/Game/WeaponsNTools/GatlingGun/Overclocks/OC_BonusesAndPenalties/OC_Bonus_Damage_2");
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_Damage_5, "/Game/WeaponsNTools/GatlingGun/Overclocks/OC_BonusesAndPenalties/OC_Bonus_Damage_5");
UE_ASSET_AT(::UDamageUpgrade, OC_Penalty_Damage3, "/Game/WeaponsNTools/GatlingGun/Overclocks/OC_BonusesAndPenalties/OC_Penalty_Damage3");
UE_ASSET_AT(::UDamageUpgrade, OC_Penalty_NoStagger, "/Game/WeaponsNTools/GatlingGun/Overclocks/OC_BonusesAndPenalties/OC_Penalty_NoStagger");
UE_ASSET_AT(::UDamageUpgrade, OC_Penalty_NoStaggerDurration, "/Game/WeaponsNTools/GatlingGun/Overclocks/OC_BonusesAndPenalties/OC_Penalty_NoStaggerDurration");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::GatlingGun::Upgrades {
UE_ASSET_AT(::UDamageUpgrade, UPG_Gatling_B_Damage_2, "/Game/WeaponsNTools/GatlingGun/Upgrades/UPG_Gatling_B_Damage+2");
UE_ASSET_AT(::UDamageUpgrade, UPG_Gatling_C_ArmorDamage, "/Game/WeaponsNTools/GatlingGun/Upgrades/UPG_Gatling_C_ArmorDamage");
UE_ASSET_AT(::UDamageUpgrade, UPG_Gatling_C_Stagger_Chance_Effect, "/Game/WeaponsNTools/GatlingGun/Upgrades/UPG_Gatling_C_Stagger_Chance_Effect");
UE_ASSET_AT(::UDamageUpgrade, UPG_Gatling_C_Stagger_Duration_Effect, "/Game/WeaponsNTools/GatlingGun/Upgrades/UPG_Gatling_C_Stagger_Duration_Effect");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::GooCannon::Overclocks::OC_BonusesAndPenalties {
UE_ASSET_AT(::UDamageUpgrade, Bonus_BuckshotDamage, "/Game/WeaponsNTools/GooCannon/Overclocks/OC_BonusesAndPenalties/Bonus_BuckshotDamage");
UE_ASSET_AT(::UDamageUpgrade, Bonus_ChargedShotDamage_GC, "/Game/WeaponsNTools/GooCannon/Overclocks/OC_BonusesAndPenalties/Bonus_ChargedShotDamage_GC");
UE_ASSET_AT(::UDamageUpgrade, Bonus_FragmentDamageNormal_GooCannon, "/Game/WeaponsNTools/GooCannon/Overclocks/OC_BonusesAndPenalties/Bonus_FragmentDamageNormal_GooCannon");
UE_ASSET_AT(::UDamageUpgrade, Bonus_FragmentDamageSmall_GooCannon, "/Game/WeaponsNTools/GooCannon/Overclocks/OC_BonusesAndPenalties/Bonus_FragmentDamageSmall_GooCannon");
UE_ASSET_AT(::UDamageUpgrade, Bonus_NormalShotDamage_GC, "/Game/WeaponsNTools/GooCannon/Overclocks/OC_BonusesAndPenalties/Bonus_NormalShotDamage_GC");
UE_ASSET_AT(::UDamageUpgrade, Penalty_ChargedShotDamage_20_GooCannon, "/Game/WeaponsNTools/GooCannon/Overclocks/OC_BonusesAndPenalties/Penalty_ChargedShotDamage_20_GooCannon");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::GooCannon::Upgrades {
UE_ASSET_AT(::UDamageUpgrade, UPG_Goo_A_AoERadius, "/Game/WeaponsNTools/GooCannon/Upgrades/UPG_Goo_A_AoERadius");
UE_ASSET_AT(::UDamageUpgrade, UPG_Goo_B_DirectDamage_BigGoo, "/Game/WeaponsNTools/GooCannon/Upgrades/UPG_Goo_B_DirectDamage_BigGoo");
UE_ASSET_AT(::UDamageUpgrade, UPG_Goo_C_DirectDamage_NormalGoo, "/Game/WeaponsNTools/GooCannon/Upgrades/UPG_Goo_C_DirectDamage_NormalGoo");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::GrenadeLauncher {
UE_ASSET_AT(::UDamageUpgrade, UPG_GrenadeLauncher_A_Damage, "/Game/WeaponsNTools/GrenadeLauncher/UPG_GrenadeLauncher_A_Damage");
UE_ASSET_AT(::UDamageUpgrade, UPG_GrenadeLauncher_A_Radius, "/Game/WeaponsNTools/GrenadeLauncher/UPG_GrenadeLauncher_A_Radius");
UE_ASSET_AT(::UDamageUpgrade, UPG_GrenadeLauncher_B_Damage, "/Game/WeaponsNTools/GrenadeLauncher/UPG_GrenadeLauncher_B_Damage");
UE_ASSET_AT(::UDamageUpgrade, UPG_GrenadeLauncher_C_ArmorDamage, "/Game/WeaponsNTools/GrenadeLauncher/UPG_GrenadeLauncher_C_ArmorDamage");
UE_ASSET_AT(::UDamageUpgrade, UPG_GrenadeLauncher_D_Radius, "/Game/WeaponsNTools/GrenadeLauncher/UPG_GrenadeLauncher_D_Radius");
UE_ASSET_AT(::UDamageUpgrade, UPG_GrenadeLauncher_D_Stagger, "/Game/WeaponsNTools/GrenadeLauncher/UPG_GrenadeLauncher_D_Stagger");
UE_ASSET_AT(::UDamageUpgrade, UPG_GrenadeLauncher_E_ImpactDamage, "/Game/WeaponsNTools/GrenadeLauncher/UPG_GrenadeLauncher_E_ImpactDamage");
UE_ASSET_AT(::UDamageUpgrade, UPG_GrenadeLauncher_E_ProxTrigger_Radius, "/Game/WeaponsNTools/GrenadeLauncher/UPG_GrenadeLauncher_E_ProxTrigger_Radius");
UE_ASSET_AT(::UDamageUpgrade, UPGEffect_GrenadeLauncher_LessArmorDamage, "/Game/WeaponsNTools/GrenadeLauncher/UPGEffect_GrenadeLauncher_LessArmorDamage");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::GrenadeLauncher::Overclocks::OC_BonusAndPenalty {
UE_ASSET_AT(::UDamageUpgrade, Bonus_AoEDamage_10_PGL, "/Game/WeaponsNTools/GrenadeLauncher/Overclocks/OC_BonusAndPenalty/Bonus_AoEDamage-10_PGL");
UE_ASSET_AT(::UDamageUpgrade, Bonus_Damage300Percent_PGL, "/Game/WeaponsNTools/GrenadeLauncher/Overclocks/OC_BonusAndPenalty/Bonus_Damage300Percent_PGL");
UE_ASSET_AT(::UDamageUpgrade, Bonus_DirectDMG_PGL, "/Game/WeaponsNTools/GrenadeLauncher/Overclocks/OC_BonusAndPenalty/Bonus_DirectDMG_PGL");
UE_ASSET_AT(::UDamageUpgrade, Bonus_Radius50_PGL, "/Game/WeaponsNTools/GrenadeLauncher/Overclocks/OC_BonusAndPenalty/Bonus_Radius50_PGL");
UE_ASSET_AT(::UDamageUpgrade, Bonus_Radius_100_PGL, "/Game/WeaponsNTools/GrenadeLauncher/Overclocks/OC_BonusAndPenalty/Bonus_Radius_100_PGL");
UE_ASSET_AT(::UDamageUpgrade, Penalty_AoEDamage_10_PGL, "/Game/WeaponsNTools/GrenadeLauncher/Overclocks/OC_BonusAndPenalty/Penalty_AoEDamage-10_PGL");
UE_ASSET_AT(::UDamageUpgrade, Penalty_AoEDamage_30_PGL, "/Game/WeaponsNTools/GrenadeLauncher/Overclocks/OC_BonusAndPenalty/Penalty_AoEDamage-30_PGL");
UE_ASSET_AT(::UDamageUpgrade, Penalty_Radius_150_PGL_2, "/Game/WeaponsNTools/GrenadeLauncher/Overclocks/OC_BonusAndPenalty/Penalty_Radius-150_PGL_2");
UE_ASSET_AT(::UDamageUpgrade, Penalty_Radius_50_PGL, "/Game/WeaponsNTools/GrenadeLauncher/Overclocks/OC_BonusAndPenalty/Penalty_Radius-50_PGL");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::GrenadeLauncher::RFND_25 {
UE_ASSET_AT(::UDamageUpgrade, UPG_GrenadeLauncher_D_Damage, "/Game/WeaponsNTools/GrenadeLauncher/RFND_25/UPG_GrenadeLauncher_D_Damage");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::HeavyParticleCannon::Overclocks::OC_BonussesAndPenalties {
UE_ASSET_AT(::UDamageUpgrade, Penalty_AoERange_25_HPC, "/Game/WeaponsNTools/HeavyParticleCannon/Overclocks/OC_BonussesAndPenalties/Penalty_AoERange_25_HPC");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::HeavyParticleCannon::Upgrades {
UE_ASSET_AT(::UDamageUpgrade, UPG_HPC_A_DamageRadius, "/Game/WeaponsNTools/HeavyParticleCannon/Upgrades/UPG_HPC_A_DamageRadius");
UE_ASSET_AT(::UDamageUpgrade, UPG_HPC_A_DirectDamage, "/Game/WeaponsNTools/HeavyParticleCannon/Upgrades/UPG_HPC_A_DirectDamage");
UE_ASSET_AT(::UDamageUpgrade, UPG_HPC_A_WeakpointDamage, "/Game/WeaponsNTools/HeavyParticleCannon/Upgrades/UPG_HPC_A_WeakpointDamage");
UE_ASSET_AT(::UDamageUpgrade, UPG_HPC_D_AoEDamage, "/Game/WeaponsNTools/HeavyParticleCannon/Upgrades/UPG_HPC_D_AoEDamage");
UE_ASSET_AT(::UDamageUpgrade, UPG_HPC_D_ArmorMelting, "/Game/WeaponsNTools/HeavyParticleCannon/Upgrades/UPG_HPC_D_ArmorMelting");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::LineCutter {
UE_ASSET_AT(::UDamageUpgrade, UPG_EFFECT_LineCutter_StunChance, "/Game/WeaponsNTools/LineCutter/UPG_EFFECT_LineCutter_StunChance");
UE_ASSET_AT(::UDamageUpgrade, UPG_EFFECT_LineCutter_StunDuration, "/Game/WeaponsNTools/LineCutter/UPG_EFFECT_LineCutter_StunDuration");
UE_ASSET_AT(::UDamageUpgrade, UPG_LineCutter_B_Damage, "/Game/WeaponsNTools/LineCutter/UPG_LineCutter_B_Damage");
UE_ASSET_AT(::UDamageUpgrade, UPG_LineCutter_D_ArmorDamage, "/Game/WeaponsNTools/LineCutter/UPG_LineCutter_D_ArmorDamage");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::LineCutter::Overclocks::OC_BonusesAndPenalties {
UE_ASSET_AT(::UDamageUpgrade, Bonus_DMG_1_LineCutter, "/Game/WeaponsNTools/LineCutter/Overclocks/OC_BonusesAndPenalties/Bonus_DMG+1_LineCutter");
UE_ASSET_AT(::UDamageUpgrade, Penalty_ArmorDmg_x05_LineCutter, "/Game/WeaponsNTools/LineCutter/Overclocks/OC_BonusesAndPenalties/Penalty_ArmorDmg_x05_LineCutter");
UE_ASSET_AT(::UDamageUpgrade, Penalty_DMG_ForBurning_LineCutter, "/Game/WeaponsNTools/LineCutter/Overclocks/OC_BonusesAndPenalties/Penalty_DMG-ForBurning_LineCutter");
UE_ASSET_AT(::UDamageUpgrade, Penalty_DMGBig_LineCutter, "/Game/WeaponsNTools/LineCutter/Overclocks/OC_BonusesAndPenalties/Penalty_DMGBig_LineCutter");
UE_ASSET_AT(::UDamageUpgrade, Penalty_DMGInitial_LineCutter, "/Game/WeaponsNTools/LineCutter/Overclocks/OC_BonusesAndPenalties/Penalty_DMGInitial_LineCutter");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::LineCutter::RFND29 {
UE_ASSET_AT(::UDamageUpgrade, UPG_LineCutter_C_AmorBreak, "/Game/WeaponsNTools/LineCutter/RFND29/UPG_LineCutter_C_AmorBreak");
UE_ASSET_AT(::UDamageUpgrade, UPG_LineCutter_D_Damage, "/Game/WeaponsNTools/LineCutter/RFND29/UPG_LineCutter_D_Damage");
UE_ASSET_AT(::UDamageUpgrade, UPG_LineCutter_D_Stagger, "/Game/WeaponsNTools/LineCutter/RFND29/UPG_LineCutter_D_Stagger");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::LockOnRifle::Overclocks::OC_BonusesAndPenalties {
UE_ASSET_AT(::UDamageUpgrade, Penalty_Damage_10_LockOnRifle, "/Game/WeaponsNTools/LockOnRifle/Overclocks/OC_BonusesAndPenalties/Penalty_Damage_10_LockOnRifle");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::LockOnRifle::Upgrades {
UE_ASSET_AT(::UDamageUpgrade, UPG_LOR_A_DirectDamage, "/Game/WeaponsNTools/LockOnRifle/Upgrades/UPG_LOR_A_DirectDamage");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::MicroMissileLauncher::Overclocks::OCBonusesAndPenalties {
UE_ASSET_AT(::UDamageUpgrade, Bonus_AoERadius_MML, "/Game/WeaponsNTools/MicroMissileLauncher/Overclocks/OCBonusesAndPenalties/Bonus_AoERadius_MML");
UE_ASSET_AT(::UDamageUpgrade, Bonus_AreaDamage_1_MML, "/Game/WeaponsNTools/MicroMissileLauncher/Overclocks/OCBonusesAndPenalties/Bonus_AreaDamage_1_MML");
UE_ASSET_AT(::UDamageUpgrade, Bonus_AreaDamage_2x_MML, "/Game/WeaponsNTools/MicroMissileLauncher/Overclocks/OCBonusesAndPenalties/Bonus_AreaDamage_2x_MML");
UE_ASSET_AT(::UDamageUpgrade, Bonus_DirectDamage_12_MML, "/Game/WeaponsNTools/MicroMissileLauncher/Overclocks/OCBonusesAndPenalties/Bonus_DirectDamage_12_MML");
UE_ASSET_AT(::UDamageUpgrade, Bonus_DirectDamage_2x_MML, "/Game/WeaponsNTools/MicroMissileLauncher/Overclocks/OCBonusesAndPenalties/Bonus_DirectDamage_2x_MML");
UE_ASSET_AT(::UDamageUpgrade, Penalty_AoERadius_MML, "/Game/WeaponsNTools/MicroMissileLauncher/Overclocks/OCBonusesAndPenalties/Penalty_AoERadius_MML");
UE_ASSET_AT(::UDamageUpgrade, Penalty_AreaDamage_50p_MML, "/Game/WeaponsNTools/MicroMissileLauncher/Overclocks/OCBonusesAndPenalties/Penalty_AreaDamage_50p_MML");
UE_ASSET_AT(::UDamageUpgrade, Penalty_AreaDamage_5_MML, "/Game/WeaponsNTools/MicroMissileLauncher/Overclocks/OCBonusesAndPenalties/Penalty_AreaDamage_5_MML");
UE_ASSET_AT(::UDamageUpgrade, Penalty_AreaDamage_Dumb_MML, "/Game/WeaponsNTools/MicroMissileLauncher/Overclocks/OCBonusesAndPenalties/Penalty_AreaDamage_Dumb_MML");
UE_ASSET_AT(::UDamageUpgrade, Penalty_Butcher_AoERadius_MML_, "/Game/WeaponsNTools/MicroMissileLauncher/Overclocks/OCBonusesAndPenalties/Penalty_Butcher_AoERadius_MML_");
UE_ASSET_AT(::UDamageUpgrade, Penalty_DirectDamage_5_MML, "/Game/WeaponsNTools/MicroMissileLauncher/Overclocks/OCBonusesAndPenalties/Penalty_DirectDamage_5_MML");
UE_ASSET_AT(::UDamageUpgrade, Penalty_DirectDamage_Dumb_MML, "/Game/WeaponsNTools/MicroMissileLauncher/Overclocks/OCBonusesAndPenalties/Penalty_DirectDamage_Dumb_MML");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::MicroMissileLauncher::Upgrades {
UE_ASSET_AT(::UDamageUpgrade, UPG_MML_A_AoERadius, "/Game/WeaponsNTools/MicroMissileLauncher/Upgrades/UPG_MML_A_AoERadius");
UE_ASSET_AT(::UDamageUpgrade, UPG_MML_A_DirectDamage, "/Game/WeaponsNTools/MicroMissileLauncher/Upgrades/UPG_MML_A_DirectDamage");
UE_ASSET_AT(::UDamageUpgrade, UPG_MML_B_ArmorBreaking, "/Game/WeaponsNTools/MicroMissileLauncher/Upgrades/UPG_MML_B_ArmorBreaking");
UE_ASSET_AT(::UDamageUpgrade, UPG_MML_D_AreaDamage, "/Game/WeaponsNTools/MicroMissileLauncher/Upgrades/UPG_MML_D_AreaDamage");
UE_ASSET_AT(::UDamageUpgrade, UPG_MML_D_WeakpointDamage, "/Game/WeaponsNTools/MicroMissileLauncher/Upgrades/UPG_MML_D_WeakpointDamage");
UE_ASSET_AT(::UDamageUpgrade, UPG_MML_E_DamageOverTime, "/Game/WeaponsNTools/MicroMissileLauncher/Upgrades/UPG_MML_E_DamageOverTime");
UE_ASSET_AT(::UDamageUpgrade, UPG_MML_E_StaggerChance, "/Game/WeaponsNTools/MicroMissileLauncher/Upgrades/UPG_MML_E_StaggerChance");
UE_ASSET_AT(::UDamageUpgrade, UPG_MML_E_StaggerDuration, "/Game/WeaponsNTools/MicroMissileLauncher/Upgrades/UPG_MML_E_StaggerDuration");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::MicrowaveGun::Overclocks::Bonuses {
UE_ASSET_AT(::UDamageUpgrade, Penalty_Damage_1_MG, "/Game/WeaponsNTools/MicrowaveGun/Overclocks/Bonuses/Penalty_Damage_1_MG");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::MicrowaveGun::Upgrades {
UE_ASSET_AT(::UDamageUpgrade, UPG_MG_A_DirectDamage, "/Game/WeaponsNTools/MicrowaveGun/Upgrades/UPG_MG_A_DirectDamage");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::Pickaxe::Driller {
UE_ASSET_AT(::UDamageUpgrade, UPG_Pickaxe_Driller_B_DamagePA, "/Game/WeaponsNTools/Pickaxe/Driller/UPG_Pickaxe_Driller_B_DamagePA");
UE_ASSET_AT(::UDamageUpgrade, UPG_Pickaxe_Driller_B_RadiusPA, "/Game/WeaponsNTools/Pickaxe/Driller/UPG_Pickaxe_Driller_B_RadiusPA");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::Pickaxe::Eng {
UE_ASSET_AT(::UDamageUpgrade, UPG_Pickaxe_Eng_B_DamagePA, "/Game/WeaponsNTools/Pickaxe/Eng/UPG_Pickaxe_Eng_B_DamagePA");
UE_ASSET_AT(::UDamageUpgrade, UPG_Pickaxe_Eng_B_RadiusPA, "/Game/WeaponsNTools/Pickaxe/Eng/UPG_Pickaxe_Eng_B_RadiusPA");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::Pickaxe::Gunner {
UE_ASSET_AT(::UDamageUpgrade, UPG_Pickaxe_Gunner_B_DamagePA, "/Game/WeaponsNTools/Pickaxe/Gunner/UPG_Pickaxe_Gunner_B_DamagePA");
UE_ASSET_AT(::UDamageUpgrade, UPG_Pickaxe_Gunner_B_RadiusPA, "/Game/WeaponsNTools/Pickaxe/Gunner/UPG_Pickaxe_Gunner_B_RadiusPA");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::Pickaxe::Scout {
UE_ASSET_AT(::UDamageUpgrade, UPG_Pickaxe_Scout_B_DamagePA, "/Game/WeaponsNTools/Pickaxe/Scout/UPG_Pickaxe_Scout_B_DamagePA");
UE_ASSET_AT(::UDamageUpgrade, UPG_Pickaxe_Scout_B_RadiusPA, "/Game/WeaponsNTools/Pickaxe/Scout/UPG_Pickaxe_Scout_B_RadiusPA");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::Pistol {
UE_ASSET_AT(::UDamageUpgrade, UPG_Pistol_B_Damage, "/Game/WeaponsNTools/Pistol/UPG_Pistol_B_Damage");
UE_ASSET_AT(::UDamageUpgrade, UPG_Pistol_D_Damage2, "/Game/WeaponsNTools/Pistol/UPG_Pistol_D_Damage2");
UE_ASSET_AT(::UDamageUpgrade, UPG_Pistol_D_WeakspotDamage, "/Game/WeaponsNTools/Pistol/UPG_Pistol_D_WeakspotDamage");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::Pistol::Overclocks::OC_BonusesAndPenalties {
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_StaggerChance_Pistol, "/Game/WeaponsNTools/Pistol/Overclocks/OC_BonusesAndPenalties/OC_Bonus_StaggerChance_Pistol");
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_StaggerDuration_Pistol, "/Game/WeaponsNTools/Pistol/Overclocks/OC_BonusesAndPenalties/OC_Bonus_StaggerDuration_Pistol");
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_StaggerNotJustWeakpont_Pistol, "/Game/WeaponsNTools/Pistol/Overclocks/OC_BonusesAndPenalties/OC_Bonus_StaggerNotJustWeakpont_Pistol");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::Pistol::RFND_S04 {
UE_ASSET_AT(::UDamageUpgrade, UPG_Pistol_C_Damage_REFUND, "/Game/WeaponsNTools/Pistol/RFND_S04/UPG_Pistol_C_Damage_REFUND");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::PlasmaCarbine::Overclocks::OC_BonusesAndPenalties {
UE_ASSET_AT(::UDamageUpgrade, Bonus_Damage_8_PlasmaCarbine, "/Game/WeaponsNTools/PlasmaCarbine/Overclocks/OC_BonusesAndPenalties/Bonus_Damage_8_PlasmaCarbine");
UE_ASSET_AT(::UDamageUpgrade, Penalty_Damage_3_PlasmaCarbine, "/Game/WeaponsNTools/PlasmaCarbine/Overclocks/OC_BonusesAndPenalties/Penalty_Damage_3_PlasmaCarbine");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::PlasmaCarbine::Upgrades {
UE_ASSET_AT(::UDamageUpgrade, UPG_Effect_NoAoE, "/Game/WeaponsNTools/PlasmaCarbine/Upgrades/UPG_Effect_NoAoE");
UE_ASSET_AT(::UDamageUpgrade, UPG_Effect_SplashAoE_DirectDMGPenalty_PC, "/Game/WeaponsNTools/PlasmaCarbine/Upgrades/UPG_Effect_SplashAoE_DirectDMGPenalty_PC");
UE_ASSET_AT(::UDamageUpgrade, UPG_Effect_SplashAoE_PC, "/Game/WeaponsNTools/PlasmaCarbine/Upgrades/UPG_Effect_SplashAoE_PC");
UE_ASSET_AT(::UDamageUpgrade, UPG_PlasmaCarbine_B_Damage, "/Game/WeaponsNTools/PlasmaCarbine/Upgrades/UPG_PlasmaCarbine_B_Damage");
UE_ASSET_AT(::UDamageUpgrade, UPG_PlasmaCarbine_D_ArmorBreak, "/Game/WeaponsNTools/PlasmaCarbine/Upgrades/UPG_PlasmaCarbine_D_ArmorBreak");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::Revolver {
UE_ASSET_AT(::UDamageUpgrade, UPG_Revolver_B_Damage_10, "/Game/WeaponsNTools/Revolver/UPG_Revolver_B_Damage+10");
UE_ASSET_AT(::UDamageUpgrade, UPG_Revolver_D_Damage_20, "/Game/WeaponsNTools/Revolver/UPG_Revolver_D_Damage+20");
UE_ASSET_AT(::UDamageUpgrade, UPG_Revolver_D_WeakspotDamage, "/Game/WeaponsNTools/Revolver/UPG_Revolver_D_WeakspotDamage");
UE_ASSET_AT(::UDamageUpgrade, UPG_Revolver_ExplosiveBullets_Explosion, "/Game/WeaponsNTools/Revolver/UPG_Revolver_ExplosiveBullets_Explosion");
UE_ASSET_AT(::UDamageUpgrade, UPG_Revolver_ExplosiveBulletsDamagePenalty, "/Game/WeaponsNTools/Revolver/UPG_Revolver_ExplosiveBulletsDamagePenalty");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::Revolver::Overclocks::OC_BonusesAndPenalties {
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_Dmage100Percent_Revolver, "/Game/WeaponsNTools/Revolver/Overclocks/OC_BonusesAndPenalties/OC_Bonus_Dmage100Percent_Revolver");
UE_ASSET_AT(::UDamageUpgrade, OC_Penalty_Damage20, "/Game/WeaponsNTools/Revolver/Overclocks/OC_BonusesAndPenalties/OC_Penalty_Damage20");
UE_ASSET_AT(::UDamageUpgrade, OC_Penalty_Damage_50p, "/Game/WeaponsNTools/Revolver/Overclocks/OC_BonusesAndPenalties/OC_Penalty_Damage_50p");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::Revolver::RFND_U24 {
UE_ASSET_AT(::UDamageUpgrade, UPG_Revolver_C_Stagger, "/Game/WeaponsNTools/Revolver/RFND_U24/UPG_Revolver_C_Stagger");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::Revolver::RFND_U25 {
UE_ASSET_AT(::UDamageUpgrade, UPG_Revolver_C_ExplosiveBullets, "/Game/WeaponsNTools/Revolver/RFND_U25/UPG_Revolver_C_ExplosiveBullets");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::SMG {
UE_ASSET_AT(::UDamageUpgrade, UPG_ElectricSMG_A_Damage, "/Game/WeaponsNTools/SMG/UPG_ElectricSMG_A_Damage");
UE_ASSET_AT(::UDamageUpgrade, UPG_ElectricSMG_C_Damage, "/Game/WeaponsNTools/SMG/UPG_ElectricSMG_C_Damage");
UE_ASSET_AT(::UDamageUpgrade, UPG_ElectricSMG_D_ArmorBreak, "/Game/WeaponsNTools/SMG/UPG_ElectricSMG_D_ArmorBreak");
UE_ASSET_AT(::UDamageUpgrade, UPG_ElectricSMG_D_WeakspotDamage, "/Game/WeaponsNTools/SMG/UPG_ElectricSMG_D_WeakspotDamage");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::SMG::Overclocks::OC_BonusesAndPenalties {
UE_ASSET_AT(::UDamageUpgrade, Bonus_WeakpointBonus_SMG, "/Game/WeaponsNTools/SMG/Overclocks/OC_BonusesAndPenalties/Bonus_WeakpointBonus_SMG");
UE_ASSET_AT(::UDamageUpgrade, Penlaty_DMG_1_SMG, "/Game/WeaponsNTools/SMG/Overclocks/OC_BonusesAndPenalties/Penlaty_DMG-1_SMG");
UE_ASSET_AT(::UDamageUpgrade, Penlaty_DMG_3_SMG, "/Game/WeaponsNTools/SMG/Overclocks/OC_BonusesAndPenalties/Penlaty_DMG-3_SMG");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::SawedOffShotgun {
UE_ASSET_AT(::UDamageUpgrade, UPG_SawedOff_A_Damage, "/Game/WeaponsNTools/SawedOffShotgun/UPG_SawedOff_A_Damage");
UE_ASSET_AT(::UDamageUpgrade, UPG_SawedOff_C_StaggerChance_Part, "/Game/WeaponsNTools/SawedOffShotgun/UPG_SawedOff_C_StaggerChance_Part");
UE_ASSET_AT(::UDamageUpgrade, UPG_SawedOff_C_StaggerDuration_Part, "/Game/WeaponsNTools/SawedOffShotgun/UPG_SawedOff_C_StaggerDuration_Part");
UE_ASSET_AT(::UDamageUpgrade, UPG_SawedOff_D_ArmorDamage, "/Game/WeaponsNTools/SawedOffShotgun/UPG_SawedOff_D_ArmorDamage");
UE_ASSET_AT(::UDamageUpgrade, UPG_SawedOff_D_Damage_BlastWave, "/Game/WeaponsNTools/SawedOffShotgun/UPG_SawedOff_D_Damage-BlastWave");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::SawedOffShotgun::Overclocks::OC_BonusesAndPenalties {
UE_ASSET_AT(::UDamageUpgrade, Bonus_Damage1_SawedOff, "/Game/WeaponsNTools/SawedOffShotgun/Overclocks/OC_BonusesAndPenalties/Bonus_Damage1_SawedOff");
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_Damage8_SawedOff, "/Game/WeaponsNTools/SawedOffShotgun/Overclocks/OC_BonusesAndPenalties/OC_Bonus_Damage8_SawedOff");
UE_ASSET_AT(::UDamageUpgrade, OC_Bonus_Dmg_BlastWave_SawedOff, "/Game/WeaponsNTools/SawedOffShotgun/Overclocks/OC_BonusesAndPenalties/OC_Bonus_Dmg-BlastWave_SawedOff");
}
namespace UeAssets::UDamageUpgrade::Game::WeaponsNTools::SentryGun::SentryGun_Engineer {
UE_ASSET_AT(::UDamageUpgrade, UPG_EFFECT_SentryGun_D_Damage, "/Game/WeaponsNTools/SentryGun/SentryGun_Engineer/UPG_EFFECT_SentryGun_D_Damage");
UE_ASSET_AT(::UDamageUpgrade, UPG_SentryGun_A_Damage, "/Game/WeaponsNTools/SentryGun/SentryGun_Engineer/UPG_SentryGun_A_Damage");
UE_ASSET_AT(::UDamageUpgrade, UPG_SentryGun_C_ArmorBreaking, "/Game/WeaponsNTools/SentryGun/SentryGun_Engineer/UPG_SentryGun_C_ArmorBreaking");
UE_ASSET_AT(::UDamageUpgrade, UPG_SentryGun_C_StaggerStun, "/Game/WeaponsNTools/SentryGun/SentryGun_Engineer/UPG_SentryGun_C_StaggerStun");
}
