#pragma once
/*
Every UDoubleDrillUpgrade asset in the game, 7 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::UDoubleDrillUpgrade::Game::WeaponsNTools::Drills::UPG_Drills_A_MiningRate
points at /Game/WeaponsNTools/Drills/UPG_Drills_A_MiningRate.
UeAssets::UDoubleDrillUpgrade::All is every one of them, as soft pointers.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/FSD.h"

namespace UeAssets::UDoubleDrillUpgrade {
UE_ASSET_ALL(::UDoubleDrillUpgrade);
}
namespace UeAssets::UDoubleDrillUpgrade::Game::WeaponsNTools::Drills {
UE_ASSET_AT(::UDoubleDrillUpgrade, UPG_Drills_A_MiningRate, "/Game/WeaponsNTools/Drills/UPG_Drills_A_MiningRate");
UE_ASSET_AT(::UDoubleDrillUpgrade, UPG_Drills_A_MoreFuel, "/Game/WeaponsNTools/Drills/UPG_Drills_A_MoreFuel");
UE_ASSET_AT(::UDoubleDrillUpgrade, UPG_Drills_A_MovementPenalty, "/Game/WeaponsNTools/Drills/UPG_Drills_A_MovementPenalty");
UE_ASSET_AT(::UDoubleDrillUpgrade, UPG_Drills_C_MiningRate, "/Game/WeaponsNTools/Drills/UPG_Drills_C_MiningRate");
UE_ASSET_AT(::UDoubleDrillUpgrade, UPG_Drills_C_MoreFuel, "/Game/WeaponsNTools/Drills/UPG_Drills_C_MoreFuel");
UE_ASSET_AT(::UDoubleDrillUpgrade, UPG_Drills_C_MovementPenalty, "/Game/WeaponsNTools/Drills/UPG_Drills_C_MovementPenalty");
UE_ASSET_AT(::UDoubleDrillUpgrade, UPG_Drils_onDamageHeatReduction, "/Game/WeaponsNTools/Drills/UPG_Drils_onDamageHeatReduction");
}
