#pragma once
/*
Every UDualMachinePistolsUpgrade asset in the game, 1 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::UDualMachinePistolsUpgrade::Game::WeaponsNTools::DualMachinePistols::UPG_DualMP_E_MovementBonus
points at /Game/WeaponsNTools/DualMachinePistols/UPG_DualMP_E_MovementBonus.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/FSD.h"

namespace UeAssets::UDualMachinePistolsUpgrade::Game::WeaponsNTools::DualMachinePistols {
UE_ASSET_AT(::UDualMachinePistolsUpgrade, UPG_DualMP_E_MovementBonus, "/Game/WeaponsNTools/DualMachinePistols/UPG_DualMP_E_MovementBonus");
}
