#pragma once
/*
Every UEnemySettings asset in the game, 1 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::UEnemySettings::Game::Game::GameData::GD_EnemySettings
points at /Game/Game/GameData/GD_EnemySettings.
UeAssets::UEnemySettings::All is every one of them, as soft pointers.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/FSD.h"

namespace UeAssets::UEnemySettings {
UE_ASSET_ALL(::UEnemySettings);
}
namespace UeAssets::UEnemySettings::Game::Game::GameData {
UE_ASSET_AT(::UEnemySettings, GD_EnemySettings, "/Game/Game/GameData/GD_EnemySettings");
}
