#pragma once
/*
Every UGrenadeAnimationSet asset in the game, 2 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::UGrenadeAnimationSet::Game::WeaponsNTools::Grenades::AnimationSets::DefaultGrenadeAnimationSet
points at /Game/WeaponsNTools/Grenades/AnimationSets/DefaultGrenadeAnimationSet.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/FSD.h"

namespace UeAssets::UGrenadeAnimationSet::Game::WeaponsNTools::Grenades::AnimationSets {
UE_ASSET_AT(::UGrenadeAnimationSet, DefaultGrenadeAnimationSet, "/Game/WeaponsNTools/Grenades/AnimationSets/DefaultGrenadeAnimationSet");
UE_ASSET_AT(::UGrenadeAnimationSet, LongHandleGrenadeAnimationSet, "/Game/WeaponsNTools/Grenades/AnimationSets/LongHandleGrenadeAnimationSet");
}
