#pragma once
/*
Every UMicroMissileLauncherUpgrade asset in the game, 3 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::UMicroMissileLauncherUpgrade::Game::WeaponsNTools::MicroMissileLauncher::Overclocks::OCBonusesAndPenalties::Bonus_Buckshot_MML
points at /Game/WeaponsNTools/MicroMissileLauncher/Overclocks/OCBonusesAndPenalties/Bonus_Buckshot_MML.
UeAssets::UMicroMissileLauncherUpgrade::All is every one of them, as soft pointers.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/FSD.h"

namespace UeAssets::UMicroMissileLauncherUpgrade {
UE_ASSET_ALL(::UMicroMissileLauncherUpgrade);
}
namespace UeAssets::UMicroMissileLauncherUpgrade::Game::WeaponsNTools::MicroMissileLauncher::Overclocks::OCBonusesAndPenalties {
UE_ASSET_AT(::UMicroMissileLauncherUpgrade, Bonus_Buckshot_MML, "/Game/WeaponsNTools/MicroMissileLauncher/Overclocks/OCBonusesAndPenalties/Bonus_Buckshot_MML");
UE_ASSET_AT(::UMicroMissileLauncherUpgrade, Bonus_H_ShotOffset_MML, "/Game/WeaponsNTools/MicroMissileLauncher/Overclocks/OCBonusesAndPenalties/Bonus_H_ShotOffset_MML");
UE_ASSET_AT(::UMicroMissileLauncherUpgrade, Bonus_V_ShotOffset_MML_2, "/Game/WeaponsNTools/MicroMissileLauncher/Overclocks/OCBonusesAndPenalties/Bonus_V_ShotOffset_MML_2");
}
