#pragma once
/*
Every UMinersManual asset in the game, 1 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::UMinersManual::Game::UI::Menu_MinersManual::BP_MinersManualData
points at /Game/UI/Menu_MinersManual/BP_MinersManualData.
UeAssets::UMinersManual::All is every one of them, as soft pointers.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/FSD.h"

namespace UeAssets::UMinersManual {
UE_ASSET_ALL(::UMinersManual);
}
namespace UeAssets::UMinersManual::Game::UI::Menu_MinersManual {
UE_ASSET_AT(::UMinersManual, BP_MinersManualData, "/Game/UI/Menu_MinersManual/BP_MinersManualData");
}
