#pragma once
/*
Every UModioNamedGlyphsDataAsset asset in the game, 1 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::UModioNamedGlyphsDataAsset::Modio::UI::Styles::NamedGlyphsDataAsset
points at /Modio/UI/Styles/NamedGlyphsDataAsset.
UeAssets::UModioNamedGlyphsDataAsset::All is every one of them, as soft pointers.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/ModioUI.h"

namespace UeAssets::UModioNamedGlyphsDataAsset {
UE_ASSET_ALL(::UModioNamedGlyphsDataAsset);
}
namespace UeAssets::UModioNamedGlyphsDataAsset::Modio::UI::Styles {
UE_ASSET_AT(::UModioNamedGlyphsDataAsset, NamedGlyphsDataAsset, "/Modio/UI/Styles/NamedGlyphsDataAsset");
}
