#pragma once
/*
Every UModifyDynamicStatusEffectDamageBonusUpgrade asset in the game, 2 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::UModifyDynamicStatusEffectDamageBonusUpgrade::Game::WeaponsNTools::GooCannon::Overclocks::OC_BonusesAndPenalties::Penalty_STEDuration_GC
points at /Game/WeaponsNTools/GooCannon/Overclocks/OC_BonusesAndPenalties/Penalty_STEDuration_GC.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/FSD.h"

namespace UeAssets::UModifyDynamicStatusEffectDamageBonusUpgrade::Game::WeaponsNTools::GooCannon::Overclocks::OC_BonusesAndPenalties {
UE_ASSET_AT(::UModifyDynamicStatusEffectDamageBonusUpgrade, Penalty_STEDuration_GC, "/Game/WeaponsNTools/GooCannon/Overclocks/OC_BonusesAndPenalties/Penalty_STEDuration_GC");
}
namespace UeAssets::UModifyDynamicStatusEffectDamageBonusUpgrade::Game::WeaponsNTools::GooCannon::Upgrades {
UE_ASSET_AT(::UModifyDynamicStatusEffectDamageBonusUpgrade, UPG_Goo_C_STEDuration, "/Game/WeaponsNTools/GooCannon/Upgrades/UPG_Goo_C_STEDuration");
}
