#pragma once
/*
Every UNewsTextLists asset in the game, 1 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::UNewsTextLists::Game::Game::Text::News_WordLists
points at /Game/Game/Text/News_WordLists.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/FSD.h"

namespace UeAssets::UNewsTextLists::Game::Game::Text {
UE_ASSET_AT(::UNewsTextLists, News_WordLists, "/Game/Game/Text/News_WordLists");
}
