#pragma once
/*
Every URig asset in the game, 3 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::URig::Game::CharacterStructure::Rig::_3P_Dwarf_Rig_SkeletonRig
points at /Game/CharacterStructure/Rig/3P_Dwarf_Rig_SkeletonRig.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/Engine.h"

namespace UeAssets::URig::Game::CharacterStructure::Rig {
UE_ASSET_AT(::URig, _3P_Dwarf_Rig_SkeletonRig, "/Game/CharacterStructure/Rig/3P_Dwarf_Rig_SkeletonRig");
}
namespace UeAssets::URig::Game::Enemies::FlyingBug::Shooter::Assets {
UE_ASSET_AT(::URig, SK_Flier_Shooter_SkeletonRig, "/Game/Enemies/FlyingBug/Shooter/Assets/SK_Flier_Shooter_SkeletonRig");
}
namespace UeAssets::URig::Game::Enemies::Spider {
UE_ASSET_AT(::URig, SK_Spider_SkeletonRig, "/Game/Enemies/Spider/SK_Spider_SkeletonRig");
}
