#pragma once
/*
Every USawedOffShotgunUpgrade asset in the game, 3 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::USawedOffShotgunUpgrade::Game::WeaponsNTools::SawedOffShotgun::UPG_SawedOff_E_Fear
points at /Game/WeaponsNTools/SawedOffShotgun/UPG_SawedOff_E_Fear.
UeAssets::USawedOffShotgunUpgrade::All is every one of them, as soft pointers.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/FSD.h"

namespace UeAssets::USawedOffShotgunUpgrade {
UE_ASSET_ALL(::USawedOffShotgunUpgrade);
}
namespace UeAssets::USawedOffShotgunUpgrade::Game::WeaponsNTools::SawedOffShotgun {
UE_ASSET_AT(::USawedOffShotgunUpgrade, UPG_SawedOff_E_Fear, "/Game/WeaponsNTools/SawedOffShotgun/UPG_SawedOff_E_Fear");
}
namespace UeAssets::USawedOffShotgunUpgrade::Game::WeaponsNTools::SawedOffShotgun::Overclocks::OC_BonusesAndPenalties {
UE_ASSET_AT(::USawedOffShotgunUpgrade, OC_Bonus_ShotgunJump_SawedOff, "/Game/WeaponsNTools/SawedOffShotgun/Overclocks/OC_BonusesAndPenalties/OC_Bonus_ShotgunJump_SawedOff");
}
namespace UeAssets::USawedOffShotgunUpgrade::Game::WeaponsNTools::SawedOffShotgun::Rfnd25 {
UE_ASSET_AT(::USawedOffShotgunUpgrade, UPG_SawedOff_D_BlastWave, "/Game/WeaponsNTools/SawedOffShotgun/Rfnd25/UPG_SawedOff_D_BlastWave");
}
