#pragma once
/*
Every USchematicPricingTier asset in the game, 5 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::USchematicPricingTier::Game::GameElements::Schematics::Overclocks
points at /Game/GameElements/Schematics/Overclocks.
UeAssets::USchematicPricingTier::All is every one of them, as soft pointers.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/FSD.h"

namespace UeAssets::USchematicPricingTier {
UE_ASSET_ALL(::USchematicPricingTier);
}
namespace UeAssets::USchematicPricingTier::Game::GameElements::Schematics {
UE_ASSET_AT(::USchematicPricingTier, Overclocks, "/Game/GameElements/Schematics/Overclocks");
UE_ASSET_AT(::USchematicPricingTier, Resource, "/Game/GameElements/Schematics/Resource");
UE_ASSET_AT(::USchematicPricingTier, Vanity_1, "/Game/GameElements/Schematics/Vanity_1");
UE_ASSET_AT(::USchematicPricingTier, Vanity_2, "/Game/GameElements/Schematics/Vanity_2");
UE_ASSET_AT(::USchematicPricingTier, Vanity_3, "/Game/GameElements/Schematics/Vanity_3");
}
