#pragma once
/*
Every USeasonSettings asset in the game, 1 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::USeasonSettings::Game::GameElements::Seasons::SeasonSettings
points at /Game/GameElements/Seasons/SeasonSettings.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/FSD.h"

namespace UeAssets::USeasonSettings::Game::GameElements::Seasons {
UE_ASSET_AT(::USeasonSettings, SeasonSettings, "/Game/GameElements/Seasons/SeasonSettings");
}
