#pragma once
/*
Every UShowroomSettings asset in the game, 1 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::UShowroomSettings::Game::Game::GameData::GD_ShowroomSettings
points at /Game/Game/GameData/GD_ShowroomSettings.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/FSD.h"

namespace UeAssets::UShowroomSettings::Game::Game::GameData {
UE_ASSET_AT(::UShowroomSettings, GD_ShowroomSettings, "/Game/Game/GameData/GD_ShowroomSettings");
}
