#pragma once
/*
Every USpecialEventSettings asset in the game, 1 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::USpecialEventSettings::Game::Game::GameData::GD_SpecialEventSettings
points at /Game/Game/GameData/GD_SpecialEventSettings.
UeAssets::USpecialEventSettings::All is every one of them, as soft pointers.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/FSD.h"

namespace UeAssets::USpecialEventSettings {
UE_ASSET_ALL(::USpecialEventSettings);
}
namespace UeAssets::USpecialEventSettings::Game::Game::GameData {
UE_ASSET_AT(::USpecialEventSettings, GD_SpecialEventSettings, "/Game/Game/GameData/GD_SpecialEventSettings");
}
