#pragma once
/*
Every UStatusDamageBonusUpgrade asset in the game, 4 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::UStatusDamageBonusUpgrade::Game::WeaponsNTools::DualMachinePistols::UPG_DualMP_E_ElectricBonus
points at /Game/WeaponsNTools/DualMachinePistols/UPG_DualMP_E_ElectricBonus.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/FSD.h"

namespace UeAssets::UStatusDamageBonusUpgrade::Game::WeaponsNTools::DualMachinePistols {
UE_ASSET_AT(::UStatusDamageBonusUpgrade, UPG_DualMP_E_ElectricBonus, "/Game/WeaponsNTools/DualMachinePistols/UPG_DualMP_E_ElectricBonus");
}
namespace UeAssets::UStatusDamageBonusUpgrade::Game::WeaponsNTools::HeavyParticleCannon::Upgrades {
UE_ASSET_AT(::UStatusDamageBonusUpgrade, UPG_HPC_E_ElectricDamageBonus, "/Game/WeaponsNTools/HeavyParticleCannon/Upgrades/UPG_HPC_E_ElectricDamageBonus");
}
namespace UeAssets::UStatusDamageBonusUpgrade::Game::WeaponsNTools::LockOnRifle::Upgrades {
UE_ASSET_AT(::UStatusDamageBonusUpgrade, ElectricDamageBonus, "/Game/WeaponsNTools/LockOnRifle/Upgrades/ElectricDamageBonus");
}
namespace UeAssets::UStatusDamageBonusUpgrade::Game::WeaponsNTools::SMG {
UE_ASSET_AT(::UStatusDamageBonusUpgrade, UPG_ElectricSMG_D_DamageVsElectrocuted, "/Game/WeaponsNTools/SMG/UPG_ElectricSMG_D_DamageVsElectrocuted");
}
