#pragma once
/*
Every UStickyFlameStatusEffectUpgrade asset in the game, 5 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::UStickyFlameStatusEffectUpgrade::Game::WeaponsNTools::Cryospray::UPG_SticktFrost_IncreaseDamage
points at /Game/WeaponsNTools/Cryospray/UPG_SticktFrost_IncreaseDamage.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/FSD.h"

namespace UeAssets::UStickyFlameStatusEffectUpgrade::Game::WeaponsNTools::Cryospray {
UE_ASSET_AT(::UStickyFlameStatusEffectUpgrade, UPG_SticktFrost_IncreaseDamage, "/Game/WeaponsNTools/Cryospray/UPG_SticktFrost_IncreaseDamage");
UE_ASSET_AT(::UStickyFlameStatusEffectUpgrade, UPG_StickyFrost_IncreaseCold_A, "/Game/WeaponsNTools/Cryospray/UPG_StickyFrost_IncreaseCold_A");
UE_ASSET_AT(::UStickyFlameStatusEffectUpgrade, UPG_StickyFrost_IncreaseCold_D, "/Game/WeaponsNTools/Cryospray/UPG_StickyFrost_IncreaseCold_D");
}
namespace UeAssets::UStickyFlameStatusEffectUpgrade::Game::WeaponsNTools::FlameThrower {
UE_ASSET_AT(::UStickyFlameStatusEffectUpgrade, UPG_Flamethrower_C_StickySlowdown, "/Game/WeaponsNTools/FlameThrower/UPG_Flamethrower_C_StickySlowdown");
}
namespace UeAssets::UStickyFlameStatusEffectUpgrade::Game::WeaponsNTools::FlameThrower::Overclocks::OC_BonusesAndPenalties {
UE_ASSET_AT(::UStickyFlameStatusEffectUpgrade, Bonus_StickyDamage_Flamethrower, "/Game/WeaponsNTools/FlameThrower/Overclocks/OC_BonusesAndPenalties/Bonus_StickyDamage_Flamethrower");
}
