#pragma once
/*
Every UTagVanityStyle asset in the game, 2 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::UTagVanityStyle::Game::Character::Vanity2::Tags::Tag_VanityStyle_Festive
points at /Game/Character/Vanity2/Tags/Tag_VanityStyle_Festive.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/FSD.h"

namespace UeAssets::UTagVanityStyle::Game::Character::Vanity2::Tags {
UE_ASSET_AT(::UTagVanityStyle, Tag_VanityStyle_Festive, "/Game/Character/Vanity2/Tags/Tag_VanityStyle_Festive");
UE_ASSET_AT(::UTagVanityStyle, Tag_VanityStyle_Serious, "/Game/Character/Vanity2/Tags/Tag_VanityStyle_Serious");
}
