#pragma once
/*
Every UTargetStateDamageBonusUpgrade asset in the game, 5 of them, generated by AssetGen/tools/genueassets.py from the game's
AssetRegistry.bin. Do not edit. Each is named by its content path:
    &UeAssets::UTargetStateDamageBonusUpgrade::Game::WeaponsNTools::CoilGun::Upgrades::UPG_EFFECT_DamageVsBurning
points at /Game/WeaponsNTools/CoilGun/Upgrades/UPG_EFFECT_DamageVsBurning.
*/
#include "../UeApi/UeMeta.h"
#include "../UeApi/FSD.h"

namespace UeAssets::UTargetStateDamageBonusUpgrade::Game::WeaponsNTools::CoilGun::Upgrades {
UE_ASSET_AT(::UTargetStateDamageBonusUpgrade, UPG_EFFECT_DamageVsBurning, "/Game/WeaponsNTools/CoilGun/Upgrades/UPG_EFFECT_DamageVsBurning");
}
namespace UeAssets::UTargetStateDamageBonusUpgrade::Game::WeaponsNTools::CombatShotgun::Overclocks::OC_BonusesAndPenalties {
UE_ASSET_AT(::UTargetStateDamageBonusUpgrade, OC_Bonus_BonusVsStun_CombatShotgun, "/Game/WeaponsNTools/CombatShotgun/Overclocks/OC_BonusesAndPenalties/OC_Bonus_BonusVsStun_CombatShotgun");
}
namespace UeAssets::UTargetStateDamageBonusUpgrade::Game::WeaponsNTools::LockOnRifle::Upgrades {
UE_ASSET_AT(::UTargetStateDamageBonusUpgrade, FireDamageBonus, "/Game/WeaponsNTools/LockOnRifle/Upgrades/FireDamageBonus");
}
namespace UeAssets::UTargetStateDamageBonusUpgrade::Game::WeaponsNTools::Pistol {
UE_ASSET_AT(::UTargetStateDamageBonusUpgrade, UPG_Pistol_E_DamageVsBurning, "/Game/WeaponsNTools/Pistol/UPG_Pistol_E_DamageVsBurning");
}
namespace UeAssets::UTargetStateDamageBonusUpgrade::Game::WeaponsNTools::Revolver::Overclocks::OC_BonusesAndPenalties {
UE_ASSET_AT(::UTargetStateDamageBonusUpgrade, OC_Bonus_DamageVsBurning_Revolver, "/Game/WeaponsNTools/Revolver/Overclocks/OC_BonusesAndPenalties/OC_Bonus_DamageVsBurning_Revolver");
}
