#pragma once
/*
Blueprint class _MENU_ServerList_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"
#include "../OnlineSubsystemUtils.h"
#include "../SlateCore.h"
#include "../UMG.h"

class APlayerState;
class UBorder;
class UButton;
class UCircularThrobber;
class UDifficultySetting;
class UGeneratedMission;
class UImage;
class UObject;
class UScrollBox;
class USeason;
class USizeBox;
class UTextBlock;
class UVerticalBox;
class UWidget;
class UWidgetAnimation;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_ButtonScalable2_C; class Basic_CheckBox_C; class Basic_ExpandableMenu_C; class Basic_Menu_ColorBar_C; class Basic_RadioButton_C; class Basic_TextInputField_C; }}}}
namespace Game { namespace UI { namespace Menu_ServerList { class Filter_ServerGameType_C; class Filter_ServerWorkEnvironment_C; class ITM_ServerList_Entry_C; class WND_JoinFailed_C; class WND_JoiningModded_C; class WND_JoiningPassword_C; class WND_Joining_C; }}}
namespace Game { namespace UI { namespace Menu_TopBar { class MENU_SpaceRigTemplate_C; }}}
namespace Game { namespace UI { namespace System { class ITM_OnlineRestricted_C; }}}

namespace Game { namespace UI { namespace Menu_ServerList {

class _MENU_ServerList_C : public UWindowWidget
{
public:
    UE_CLASS("/Game/UI/Menu_ServerList/_MENU_ServerList", "_MENU_ServerList_C");
    using Basic_ButtonScalable2_C = Game::UI::Art::WidgetParts::Basic_ButtonScalable2_C;
    using Basic_CheckBox_C = Game::UI::Art::WidgetParts::Basic_CheckBox_C;
    using Basic_ExpandableMenu_C = Game::UI::Art::WidgetParts::Basic_ExpandableMenu_C;
    using Basic_Menu_ColorBar_C = Game::UI::Art::WidgetParts::Basic_Menu_ColorBar_C;
    using Basic_RadioButton_C = Game::UI::Art::WidgetParts::Basic_RadioButton_C;
    using Basic_TextInputField_C = Game::UI::Art::WidgetParts::Basic_TextInputField_C;
    using Filter_ServerGameType_C = Game::UI::Menu_ServerList::Filter_ServerGameType_C;
    using Filter_ServerWorkEnvironment_C = Game::UI::Menu_ServerList::Filter_ServerWorkEnvironment_C;
    using ITM_OnlineRestricted_C = Game::UI::System::ITM_OnlineRestricted_C;
    using ITM_ServerList_Entry_C = Game::UI::Menu_ServerList::ITM_ServerList_Entry_C;
    using MENU_SpaceRigTemplate_C = Game::UI::Menu_TopBar::MENU_SpaceRigTemplate_C;
    using WND_JoinFailed_C = Game::UI::Menu_ServerList::WND_JoinFailed_C;
    using WND_JoiningModded_C = Game::UI::Menu_ServerList::WND_JoiningModded_C;
    using WND_JoiningPassword_C = Game::UI::Menu_ServerList::WND_JoiningPassword_C;
    using WND_Joining_C = Game::UI::Menu_ServerList::WND_Joining_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* LookingForServers;
    Basic_CheckBox_C* AutoRefresh;
    Basic_Menu_ColorBar_C* Basic_Menu_ColorBar;
    Basic_RadioButton_C* Basic_RadioButton_Open;
    Basic_RadioButton_C* Basic_RadioButton_Password;
    Basic_RadioButton_C* Basic_RadioButton_SD_Close;
    Basic_RadioButton_C* Basic_RadioButton_SD_Far;
    Basic_RadioButton_C* Basic_RadioButton_SD_Medium;
    Basic_RadioButton_C* Basic_RadioButton_SD_World;
    class UBorder* BG_Filters;
    class UBorder* BG_Servers;
    class UBorder* Border_Categories;
    class UBorder* Border_Filters;
    Basic_ButtonScalable2_C* BTN_Full_ServerList;
    Basic_ButtonScalable2_C* BTN_QuickJoin;
    Basic_ButtonScalable2_C* BTN_Refresh;
    class UButton* Button_Complexity;
    class UButton* Button_Distance;
    class UButton* Button_Hazard;
    class UButton* Button_Length;
    class UButton* Button_Mission;
    class UButton* Button_Season;
    class UButton* Button_Team;
    class UButton* Button_Time;
    Basic_CheckBox_C* CHK_Season_12;
    Basic_CheckBox_C* CHK_Season_34;
    Basic_CheckBox_C* CHK_Season_00;
    Basic_CheckBox_C* CHK_Season_05;
    Basic_CheckBox_C* CHK_Season_06;
    class UCircularThrobber* CircularThrobber_0;
    Filter_ServerGameType_C* Filter_ServerGameType;
    Filter_ServerWorkEnvironment_C* Filter_ServerWorkEnvironment;
    class UImage* IMG_MissionIcon;
    ITM_OnlineRestricted_C* ITM_OnlineRestricted;
    ITM_ServerList_Entry_C* ITM_ServerList_Entry;
    ITM_ServerList_Entry_C* ITM_ServerList_Entry_0;
    ITM_ServerList_Entry_C* ITM_ServerList_Entry_1;
    ITM_ServerList_Entry_C* ITM_ServerList_Entry_2;
    ITM_ServerList_Entry_C* ITM_ServerList_Entry_3;
    ITM_ServerList_Entry_C* ITM_ServerList_Entry_4;
    ITM_ServerList_Entry_C* ITM_ServerList_Entry_5;
    ITM_ServerList_Entry_C* ITM_ServerList_Entry_6;
    ITM_ServerList_Entry_C* ITM_ServerList_Entry_7;
    ITM_ServerList_Entry_C* ITM_ServerList_Entry_8;
    ITM_ServerList_Entry_C* ITM_ServerList_Entry_9;
    ITM_ServerList_Entry_C* ITM_ServerList_Entry_10;
    ITM_ServerList_Entry_C* ITM_ServerList_Entry_11;
    MENU_SpaceRigTemplate_C* MENU_SpaceRigTemplate;
    Basic_ExpandableMenu_C* MenuSearchDistance;
    Basic_ExpandableMenu_C* MenuSeasons;
    Basic_ExpandableMenu_C* MenuServerType;
    class UScrollBox* ScrollBox_Servers;
    class UVerticalBox* ScrollBox_Vertical;
    class UVerticalBox* SearchingVBox;
    class USizeBox* Size_Complexity;
    class USizeBox* Size_Distance;
    class USizeBox* Size_Hazard;
    class USizeBox* Size_Length;
    class USizeBox* Size_Mission;
    class USizeBox* Size_Season;
    class USizeBox* Size_Team;
    class USizeBox* Size_Time;
    class UTextBlock* TextDistanceClose;
    class UTextBlock* TextDistanceClose_1;
    class UTextBlock* TextDistanceFar;
    class UTextBlock* TextDistanceFar_1;
    class UTextBlock* TextDistanceMedium;
    class UTextBlock* TextDistanceMedium_1;
    class UTextBlock* TextDistanceWorld;
    class UTextBlock* TextDistanceWorld_1;
    class UTextBlock* TextDistanceWorld_2;
    class UTextBlock* TextOpenServerType;
    class UTextBlock* TextPasswordServerType;
    class UTextBlock* TXT_Category_Complexity;
    class UTextBlock* TXT_Category_filters;
    class UTextBlock* TXT_Category_Hazard;
    class UTextBlock* TXT_Category_Length;
    class UTextBlock* TXT_Category_MissionType;
    class UTextBlock* TXT_Category_Season;
    class UTextBlock* TXT_Category_Team;
    class UTextBlock* TXT_Category_Time;
    class UTextBlock* TXT_Distance;
    class UTextBlock* TXT_NoServersFound;
    Basic_TextInputField_C* TXT_Search;
    class UVerticalBox* VboxNoServerFound;
    WND_Joining_C* JoinServerWidget;
    WND_JoinFailed_C* JoinFailedWidget;
    WND_JoiningPassword_C* JoinServerPasswordWidget;
    WND_JoiningModded_C* JoinServerModdedWidget;
    class UGeneratedMission* RestrictedMission;
    TArray<FBlueprintSessionResult> ServerList;
    TArray<ITM_ServerList_Entry_C*> ServerListEntryCache;
    TArray<ITM_ServerList_Entry_C*> ExistingEntries;
    int ActiveEntryIndex;
    TArray<float> ColumnWidths;
    EServerSortOrder SortingMethod;
    bool SortingReversed;
    TArray<FFriendInfo> NewFriends;
    TArray<FFriendInfo> CurrentFriends;
    class UObject* CurrentFriendSession;
    EBlueprintablePrivilegeResults CurrentOnliineBlockingReason;
    TArray<FString> AllServernameWords;
    bool UGCDisallowed;
    bool isManuallySorted;
    FBlueprintSessionResult CurrentJoiningModdedSession;
    FString CurrentJoiningModdedPassword;
    void ExecuteUbergraph__MENU_ServerList(int EntryPoint);
    void BndEvt___MENU_ServerList_CHK_Season_06_K2Node_ComponentBoundEvent_12_OnCheckStateChanged__DelegateSignature(bool IsChecked);
    void UpdateListAfterSearch();
    void BndEvt___MENU_ServerList_CHK_Season_05_K2Node_ComponentBoundEvent_20_OnCheckStateChanged__DelegateSignature(bool IsChecked);
    void BndEvt___MENU_ServerList_CHK_Season_34_K2Node_ComponentBoundEvent_19_OnCheckStateChanged__DelegateSignature(bool IsChecked);
    void BndEvt___MENU_ServerList_CHK_Season_12_K2Node_ComponentBoundEvent_18_OnCheckStateChanged__DelegateSignature(bool IsChecked);
    void BndEvt___MENU_ServerList_CHK_Season_00_K2Node_ComponentBoundEvent_17_OnCheckStateChanged__DelegateSignature(bool IsChecked);
    void SavegameSwitchCancelled();
    void JoiningBlocked(bool Yes);
    void ModdedSaveLoaded();
    void BndEvt__Filter_ServerGameType_K2Node_ComponentBoundEvent_14_OnSelectionChanged__DelegateSignature();
    void OnJoiningFailed();
    void JoinModdedServer(FBlueprintSessionResult Session, FString Password);
    void OnIsUGCAllowed(class APlayerState* CheckedPlayerState, EBlueprintableUserPrivileges CheckedPrivilege, EBlueprintablePrivilegeResults PrivilegeResult);
    void CreateFriendslist();
    void FriendServerlistShouldBeUpdated();
    void FriendsListUpdated(bool bWasSuccessful, FString ErrorStr);
    void RefreshFriendslist();
    void BndEvt__Button_Distance_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Team_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Length_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Complexity_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Hazard_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Time_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Button_Mission_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__Filter_ServerWorkEnvironment_K2Node_ComponentBoundEvent_6_OnSelectionChanged__DelegateSignature();
    void OnClosed();
    void RefreshServerList();
    void BndEvt__BTN_Refresh_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature();
    void BndEvt__AutoRefresh_K2Node_ComponentBoundEvent_0_OnCheckStateChanged__DelegateSignature(bool IsChecked);
    void BndEvt__Basic_RadioButton_Open_K2Node_ComponentBoundEvent_81_OnCheckStateChanged__DelegateSignature(bool IsChecked);
    void BndEvt__Basic_RadioButton_Password_K2Node_ComponentBoundEvent_69_OnCheckStateChanged__DelegateSignature(bool IsChecked);
    void BndEvt__Basic_RadioButton_SD_World_K2Node_ComponentBoundEvent_3_OnCheckStateChanged__DelegateSignature(bool IsChecked);
    void BndEvt__Basic_RadioButton_SD_Far_K2Node_ComponentBoundEvent_2_OnCheckStateChanged__DelegateSignature(bool IsChecked);
    void BndEvt__Basic_RadioButton_SD_Medium_K2Node_ComponentBoundEvent_1_OnCheckStateChanged__DelegateSignature(bool IsChecked);
    void BndEvt__Basic_RadioButton_SD_Close_K2Node_ComponentBoundEvent_0_OnCheckStateChanged__DelegateSignature(bool IsChecked);
    void OnShown();
    void OnJoiningSession();
    void BndEvt__BTN_ServerList_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void BndEvt__Basic_TextInputField_K2Node_ComponentBoundEvent_1_OnTextChanged__DelegateSignature(FText Text);
    void ClearRestricted();
    void RestrictToMission(class UGeneratedMission* mission);
    void ServelistChanged();
    void Back_Pressed();
    static constexpr const char* Back_Pressed__UeName = "Back Pressed";
    void JoinServerWithPassword(FBlueprintSessionResult Session, FString Password);
    void JoinServerWithoutPassword(FBlueprintSessionResult Session);
    void JoinServer(FBlueprintSessionResult Session);
    UE_COSMETIC void Construct();
    void OnSuccess_0D2A19CF4B5F20488D8E6EB4D68323DE();
    void OnFailure_0D2A19CF4B5F20488D8E6EB4D68323DE();
    void OnSuccess_155E2CBD4AAE55F9B2CDDA92DDA08471();
    void OnFailure_155E2CBD4AAE55F9B2CDDA92DDA08471();
    void OnSuccess_2F44709544BBB762D8D1EDB23AB84A38();
    void OnFailure_2F44709544BBB762D8D1EDB23AB84A38();
    void OnSuccess_0624A35A4162400123C5FFB790E37726();
    void OnFailure_0624A35A4162400123C5FFB790E37726();
    void OnSuccess_155E2CBD4AAE55F9B2CDDA92CC1C4D5F();
    void OnFailure_155E2CBD4AAE55F9B2CDDA92CC1C4D5F();
    void OnSuccess_155E2CBD4AAE55F9B2CDDA9239840B3A();
    void OnFailure_155E2CBD4AAE55F9B2CDDA9239840B3A();
    void CreateSubMenus();
    void PopulateServerList(TArray<FBlueprintSessionResult>& servers);
    UE_COSMETIC FEventReply OnKeyUp(FGeometry MyGeometry, FKeyEvent InKeyEvent);
    void SetSelectedSearchDistance();
    void ShowNoServersFound(bool Visible);
    void AddOrUpdateEntry(const FBlueprintSessionResult& Result, FString& OutServerID, ITM_ServerList_Entry_C*& OutWidget);
    ITM_ServerList_Entry_C* GetCachedEntry();
    void CacheUnusedEntries();
    void SetSearchDistance(ESteamSearchRegion Distance);
    void SetServerType(ESteamServerJoinStatus ServerType);
    void SetSelectedServerType();
    void GetColumnWidths(TArray<float>& OutWidths);
    void SetSortFunction(EServerSortOrder NewSortingMethod);
    void GetActiveDifficulties(TArray<class UDifficultySetting*>& Array);
    void UpdateSearchOptionsFromRestrictedMission();
    void UpdateSearchOptionsFromSearchField();
    void UpdateFromWorkEnvironment();
    void UpdateFromGametype();
    void Disable_Progression_Mods_and_Join(FBlueprintSessionResult Session);
    static constexpr const char* Disable_Progression_Mods_and_Join__UeName = "Disable Progression Mods and Join";
    void GetHoveredEntryInfo(ITM_ServerList_Entry_C*& EntryWidget, float& WidgetMouseOffset, FString& ServerID);
    void GetWidgetMousePosition(class UWidget* InWidget, FVector2D& OutLocalPos);
    UE_COSMETIC FEventReply OnKeyDown(FGeometry MyGeometry, FKeyEvent InKeyEvent);
    void UpdateSeasonSearch();
    void GetActiveSeasons(TArray<class USeason*>& Seasons1);
    void UpdateSeasonHeader();
};

}}}   // namespace Game::UI::Menu_ServerList

using _MENU_ServerList_C = Game::UI::Menu_ServerList::_MENU_ServerList_C;