#pragma once
/*
Blueprint class ABP_Beard_Rig_B_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../AnimGraphRuntime.h"
#include "../Engine.h"
#include "../FSD.h"

namespace Game { namespace CharacterStructure { namespace Rig { namespace Facial_Hair_Rig {

class ABP_Beard_Rig_B_C : public UVanityAnimInstance
{
public:
    UE_CLASS("/Game/CharacterStructure/Rig/Facial_Hair_Rig/ABP_Beard_Rig_B", "ABP_Beard_Rig_B_C");
    FPointerToUberGraphFrame UberGraphFrame;
    FAnimNode_Root AnimGraphNode_Root;
    FAnimNode_RigidBody AnimGraphNode_RigidBody;
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone;
    FAnimNode_SequenceEvaluator AnimGraphNode_SequenceEvaluator;
    FAnimNode_CopyPoseFromMesh AnimGraphNode_CopyPoseFromMesh;
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool;
    void ExecuteUbergraph_ABP_Beard_Rig_B(int EntryPoint);
    void AnimGraph(FPoseLink& AnimGraph_0);
};

}}}}   // namespace Game::CharacterStructure::Rig::Facial_Hair_Rig

using ABP_Beard_Rig_B_C = Game::CharacterStructure::Rig::Facial_Hair_Rig::ABP_Beard_Rig_B_C;