#pragma once
/*
Blueprint class ABP_ExcavationMount_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../AnimGraphRuntime.h"
#include "../Engine.h"

class USingleUsableComponent;

namespace Game { namespace GameElements { namespace Objectives { namespace Excavation { namespace Assets {

class ABP_ExcavationMount_C : public UAnimInstance
{
public:
    UE_CLASS("/Game/GameElements/Objectives/Excavation/Assets/ABP_ExcavationMount", "ABP_ExcavationMount_C");
    FPointerToUberGraphFrame UberGraphFrame;
    FAnimNode_Root AnimGraphNode_Root;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_1;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult;
    FAnimNode_SequenceEvaluator AnimGraphNode_SequenceEvaluator_1;
    FAnimNode_StateResult AnimGraphNode_StateResult_1;
    FAnimNode_SequenceEvaluator AnimGraphNode_SequenceEvaluator;
    FAnimNode_StateResult AnimGraphNode_StateResult;
    FAnimNode_StateMachine AnimGraphNode_StateMachine;
    bool bAssembling;
    float AssemblyTime;
    float AssemblyTimeTarget;
    class USingleUsableComponent* Build_Usable;
    static constexpr const char* Build_Usable__UeName = "Build Usable";
    void ExecuteUbergraph_ABP_ExcavationMount(int EntryPoint);
    void BlueprintInitializeAnimation();
    void BlueprintUpdateAnimation(float DeltaTimeX);
    void AnimGraph(FPoseLink& AnimGraph_0);
};

}}}}}   // namespace Game::GameElements::Objectives::Excavation::Assets

using ABP_ExcavationMount_C = Game::GameElements::Objectives::Excavation::Assets::ABP_ExcavationMount_C;