#pragma once
/*
Blueprint class ABP_Ossiran_Scrab_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../AnimGraphRuntime.h"
#include "../Engine.h"
#include "../FSD.h"

namespace Game { namespace Enemies { namespace Ossiran { namespace Scrab { namespace Assets {

class ABP_Ossiran_Scrab_C : public UScrabAnimInstance
{
public:
    UE_CLASS("/Game/Enemies/Ossiran/Scrab/Assets/ABP_Ossiran_Scrab", "ABP_Ossiran_Scrab_C");
    FPointerToUberGraphFrame UberGraphFrame;
    FAnimNode_Slot AnimGraphNode_Slot_1;
    FAnimNode_Slot AnimGraphNode_Slot;
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool_1;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_11;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_10;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_9;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_8;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_7;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_6;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_5;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_4;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_3;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_2;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_1;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_5;
    FAnimNode_StateResult AnimGraphNode_StateResult_5;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_4;
    FAnimNode_StateResult AnimGraphNode_StateResult_4;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_3;
    FAnimNode_StateResult AnimGraphNode_StateResult_3;
    FAnimNode_RandomPlayer AnimGraphNode_RandomPlayer_1;
    FAnimNode_StateResult AnimGraphNode_StateResult_2;
    FAnimNode_RandomPlayer AnimGraphNode_RandomPlayer;
    FAnimNode_StateResult AnimGraphNode_StateResult_1;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_2;
    FAnimNode_StateResult AnimGraphNode_StateResult;
    FAnimNode_StateMachine AnimGraphNode_StateMachine;
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum_1;
    FAnimNode_RefPose AnimGraphNode_LocalRefPose_3;
    FAnimNode_RefPose AnimGraphNode_LocalRefPose_2;
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool;
    FAnimNode_Root AnimGraphNode_Root;
    FAnimNode_BlendListByEnum AnimGraphNode_BlendListByEnum;
    FAnimNode_RefPose AnimGraphNode_LocalRefPose_1;
    FAnimNode_RefPose AnimGraphNode_LocalRefPose;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_1;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer;
    void ExecuteUbergraph_ABP_Ossiran_Scrab(int EntryPoint);
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Ossiran_Scrab_AnimGraphNode_TransitionResult_F69B0869450DADD70FB202BC9B04493D();
    void AnimGraph(FPoseLink& AnimGraph_0);
};

}}}}}   // namespace Game::Enemies::Ossiran::Scrab::Assets

using ABP_Ossiran_Scrab_C = Game::Enemies::Ossiran::Scrab::Assets::ABP_Ossiran_Scrab_C;