#pragma once
/*
Blueprint class ABP_Flaregun_A_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../AnimGraphRuntime.h"
#include "../Engine.h"

namespace Game { namespace WeaponsNTools { namespace FlareGun {

class ABP_Flaregun_A_C : public UAnimInstance
{
public:
    UE_CLASS("/Game/WeaponsNTools/FlareGun/ABP_Flaregun_A", "ABP_Flaregun_A_C");
    FPointerToUberGraphFrame UberGraphFrame;
    FAnimNode_Root AnimGraphNode_Root;
    FAnimNode_SequenceEvaluator AnimGraphNode_SequenceEvaluator;
    FAnimNode_Slot AnimGraphNode_Slot;
    void ExecuteUbergraph_ABP_Flaregun_A(int EntryPoint);
    void AnimGraph(FPoseLink& AnimGraph_0);
};

}}}   // namespace Game::WeaponsNTools::FlareGun

using ABP_Flaregun_A_C = Game::WeaponsNTools::FlareGun::ABP_Flaregun_A_C;