#pragma once
/*
Blueprint class ABP_Detonator_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../AnimGraphRuntime.h"
#include "../Engine.h"

namespace Game { namespace WeaponsNTools { namespace DetPack {

class ABP_Detonator_C : public UAnimInstance
{
public:
    UE_CLASS("/Game/WeaponsNTools/DetPack/ABP_Detonator", "ABP_Detonator_C");
    FPointerToUberGraphFrame UberGraphFrame;
    FAnimNode_Root AnimGraphNode_Root;
    FAnimNode_Slot AnimGraphNode_Slot;
    FAnimNode_SequenceEvaluator AnimGraphNode_SequenceEvaluator_1;
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool;
    FAnimNode_SequenceEvaluator AnimGraphNode_SequenceEvaluator;
    bool IsOpen;
    void ExecuteUbergraph_ABP_Detonator(int EntryPoint);
    void AnimGraph(FPoseLink& AnimGraph_0);
};

}}}   // namespace Game::WeaponsNTools::DetPack

using ABP_Detonator_C = Game::WeaponsNTools::DetPack::ABP_Detonator_C;