#pragma once
/*
Blueprint class ABP_HydraWeed_Hearth_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../AnimGraphRuntime.h"
#include "../Engine.h"

namespace Game { namespace Enemies { namespace HydraWeed { namespace Assets {

class ABP_HydraWeed_Hearth_C : public UAnimInstance
{
public:
    UE_CLASS("/Game/Enemies/HydraWeed/Assets/ABP_HydraWeed_Hearth", "ABP_HydraWeed_Hearth_C");
    FPointerToUberGraphFrame UberGraphFrame;
    FAnimNode_Root AnimGraphNode_Root;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_3;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_2;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult_1;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_4;
    FAnimNode_StateResult AnimGraphNode_StateResult_3;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_3;
    FAnimNode_StateResult AnimGraphNode_StateResult_2;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_2;
    FAnimNode_StateResult AnimGraphNode_StateResult_1;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_1;
    FAnimNode_StateResult AnimGraphNode_StateResult;
    FAnimNode_StateMachine AnimGraphNode_StateMachine;
    FAnimNode_Slot AnimGraphNode_Slot;
    FAnimNode_ApplyAdditive AnimGraphNode_ApplyAdditive;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer;
    bool IsOpen;
    bool IsDormant;
    void ExecuteUbergraph_ABP_HydraWeed_Hearth(int EntryPoint);
    void OnDormantChanged_Event_0(bool IsDormant_0);
    void OnOpenChanged_Event_0(bool IsOpen_0);
    void BlueprintBeginPlay();
    void AnimGraph(FPoseLink& AnimGraph_0);
};

}}}}   // namespace Game::Enemies::HydraWeed::Assets

using ABP_HydraWeed_Hearth_C = Game::Enemies::HydraWeed::Assets::ABP_HydraWeed_Hearth_C;