#pragma once
/*
Blueprint class ABP_Hair_Rig_E_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../AnimGraphRuntime.h"
#include "../Engine.h"
#include "../FSD.h"

namespace Game { namespace CharacterStructure { namespace Rig { namespace Facial_Hair_Rig {

class ABP_Hair_Rig_E_C : public UVanityAnimInstance
{
public:
    UE_CLASS("/Game/CharacterStructure/Rig/Facial_Hair_Rig/ABP_Hair_Rig_E", "ABP_Hair_Rig_E_C");
    FPointerToUberGraphFrame UberGraphFrame;
    FAnimNode_Root AnimGraphNode_Root;
    FAnimNode_RigidBody AnimGraphNode_RigidBody;
    FAnimNode_CopyPoseFromMesh AnimGraphNode_CopyPoseFromMesh;
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;
    void ExecuteUbergraph_ABP_Hair_Rig_E(int EntryPoint);
    void AnimGraph(FPoseLink& AnimGraph_0);
};

}}}}   // namespace Game::CharacterStructure::Rig::Facial_Hair_Rig

using ABP_Hair_Rig_E_C = Game::CharacterStructure::Rig::Facial_Hair_Rig::ABP_Hair_Rig_E_C;