#pragma once
/*
Blueprint class ABP_Harvester_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../AnimGraphRuntime.h"
#include "../Engine.h"
#include "../FSD.h"

class UAudioComponent;

namespace Game { namespace Critters { namespace Harvester {

class ABP_Harvester_C : public USimpleMovingEnemyAnimInstance
{
public:
    UE_CLASS("/Game/Critters/Harvester/ABP_Harvester", "ABP_Harvester_C");
    FPointerToUberGraphFrame UberGraphFrame;
    FAnimNode_Root AnimGraphNode_Root;
    FAnimNode_Slot AnimGraphNode_Slot;
    FAnimNode_TransitionResult AnimGraphNode_TransitionResult;
    FAnimNode_SequenceEvaluator AnimGraphNode_SequenceEvaluator;
    FAnimNode_StateResult AnimGraphNode_StateResult_1;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer;
    FAnimNode_StateResult AnimGraphNode_StateResult;
    FAnimNode_StateMachine AnimGraphNode_StateMachine;
    class UAudioComponent* HarvestingSound;
    void ExecuteUbergraph_ABP_Harvester(int EntryPoint);
    void AnimNotify_ExitAlive();
    void AnimNotify_EnterAlive();
    void AnimGraph(FPoseLink& AnimGraph_0);
};

}}}   // namespace Game::Critters::Harvester

using ABP_Harvester_C = Game::Critters::Harvester::ABP_Harvester_C;