#pragma once
/*
Blueprint class ABP_Prospector_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../AnimGraphRuntime.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../FSD.h"

namespace Game { namespace Critters { namespace Prospector { namespace Assets {

class ABP_Prospector_C : public UProspectorAnimInstance
{
public:
    UE_CLASS("/Game/Critters/Prospector/Assets/ABP_Prospector", "ABP_Prospector_C");
    FPointerToUberGraphFrame UberGraphFrame;
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool;
    FAnimNode_ModifyBone AnimGraphNode_ModifyBone;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_3;
    FAnimNode_BlendListByInt AnimGraphNode_BlendListByInt;
    FAnimNode_RotationOffsetBlendSpace AnimGraphNode_RotationOffsetBlendSpace;
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_1;
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_1;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_2;
    FAnimNode_Slot AnimGraphNode_Slot;
    FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer_1;
    FAnimNode_ApplyAdditive AnimGraphNode_ApplyAdditive_1;
    FAnimNode_ApplyAdditive AnimGraphNode_ApplyAdditive;
    FAnimNode_Root AnimGraphNode_Root;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer;
    FAnimNode_RigidBody AnimGraphNode_RigidBody;
    FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;
    FVector NewVar_0;
    FVector External_force;
    static constexpr const char* External_force__UeName = "External force";
    void ExecuteUbergraph_ABP_Prospector(int EntryPoint);
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Prospector_AnimGraphNode_BlendListByInt_12F6F3B34348AA6B90DA3687DBCE4E7F();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Prospector_AnimGraphNode_ModifyBone_F0657A5644715BBC7E5BE5A2E64FD1DF();
    void AnimGraph(FPoseLink& AnimGraph_0);
};

}}}}   // namespace Game::Critters::Prospector::Assets

using ABP_Prospector_C = Game::Critters::Prospector::Assets::ABP_Prospector_C;