#pragma once
/*
Blueprint class AFE_TP_GooCannon_DoT_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../FSD.h"

namespace Game { namespace WeaponsNTools { namespace GooCannon {

class AFE_TP_GooCannon_DoT_C : public UAttachedParticlesAfflictionEffect
{
public:
    UE_CLASS("/Game/WeaponsNTools/GooCannon/AFE_TP_GooCannon_DoT", "AFE_TP_GooCannon_DoT_C");
};

}}}   // namespace Game::WeaponsNTools::GooCannon

using AFE_TP_GooCannon_DoT_C = Game::WeaponsNTools::GooCannon::AFE_TP_GooCannon_DoT_C;