#pragma once
/*
Blueprint class AFL_Grenade_IFG_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../FSD.h"

namespace Game { namespace WeaponsNTools { namespace Grenades { namespace IFG {

class AFL_Grenade_IFG_C : public USoundAfflictionEffect
{
public:
    UE_CLASS("/Game/WeaponsNTools/Grenades/IFG/AFL_Grenade_IFG", "AFL_Grenade_IFG_C");
};

}}}}   // namespace Game::WeaponsNTools::Grenades::IFG

using AFL_Grenade_IFG_C = Game::WeaponsNTools::Grenades::IFG::AFL_Grenade_IFG_C;