#pragma once
/*
Blueprint class AIC_Maggot_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class APawn;
class UBehaviorTree;
class UHealthComponentBase;

namespace Game { namespace Critters { namespace Maggot {

class AIC_Maggot_C : public AFSDAIController
{
public:
    UE_CLASS("/Game/Critters/Maggot/AIC_Maggot", "AIC_Maggot_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UBehaviorTree* BehaviorTree;
    void ExecuteUbergraph_AIC_Maggot(int EntryPoint);
    void ReceivePossess(class APawn* PossessedPawn);
    void OnDeath(class UHealthComponentBase* HealthComponent);
    void ReceiveBeginPlay();
};

}}}   // namespace Game::Critters::Maggot

using AIC_Maggot_C = Game::Critters::Maggot::AIC_Maggot_C;