#pragma once
/*
Blueprint class AIC_InfestationLarva_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

namespace Game { namespace Enemies { namespace InfestationLarva {

class AIC_InfestationLarva_C : public AFSDAIController
{
public:
    UE_CLASS("/Game/Enemies/InfestationLarva/AIC_InfestationLarva", "AIC_InfestationLarva_C");
    FPointerToUberGraphFrame UberGraphFrame;
    void ExecuteUbergraph_AIC_InfestationLarva(int EntryPoint);
    void ReceiveBeginPlay();
};

}}}   // namespace Game::Enemies::InfestationLarva

using AIC_InfestationLarva_C = Game::Enemies::InfestationLarva::AIC_InfestationLarva_C;