#pragma once
/*
Blueprint class AIC_Woodlouse_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

namespace Game { namespace Enemies { namespace Woodlouse {

class AIC_Woodlouse_C : public AEnemyAIController
{
public:
    UE_CLASS("/Game/Enemies/Woodlouse/AIC_Woodlouse", "AIC_Woodlouse_C");
    FPointerToUberGraphFrame UberGraphFrame;
    void ExecuteUbergraph_AIC_Woodlouse(int EntryPoint);
    void ReceiveBeginPlay();
};

}}}   // namespace Game::Enemies::Woodlouse

using AIC_Woodlouse_C = Game::Enemies::Woodlouse::AIC_Woodlouse_C;