#pragma once
/*
Blueprint class APB_JellySwarmer_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../AnimGraphRuntime.h"
#include "../Engine.h"
#include "../FSD.h"

namespace Game { namespace Enemies { namespace Jellyfish {

class APB_JellySwarmer_C : public UJellyFishAnimInstance
{
public:
    UE_CLASS("/Game/Enemies/Jellyfish/APB_JellySwarmer", "APB_JellySwarmer_C");
    FPointerToUberGraphFrame UberGraphFrame;
    FAnimNode_Root AnimGraphNode_Root;
    FAnimNode_BlendSpacePlayer AnimGraphNode_BlendSpacePlayer;
    FAnimNode_Slot AnimGraphNode_Slot;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer;
    FAnimNode_ApplyAdditive AnimGraphNode_ApplyAdditive;
    void ExecuteUbergraph_APB_JellySwarmer(int EntryPoint);
    void BlueprintUpdateAnimation(float DeltaTimeX);
    void AnimGraph(FPoseLink& AnimGraph_0);
};

}}}   // namespace Game::Enemies::Jellyfish

using APB_JellySwarmer_C = Game::Enemies::Jellyfish::APB_JellySwarmer_C;