#pragma once
/*
Blueprint class ASI_Maggot_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../AnimGraphRuntime.h"
#include "../AnimationSharing.h"
#include "../Engine.h"

namespace Game { namespace Critters { namespace Maggot {

class ASI_Maggot_C : public UAnimSharingTransitionInstance
{
public:
    UE_CLASS("/Game/Critters/Maggot/ASI_Maggot", "ASI_Maggot_C");
    FPointerToUberGraphFrame UberGraphFrame;
    FAnimNode_Root AnimGraphNode_Root;
    FAnimNode_BlendListByBool AnimGraphNode_BlendListByBool;
    FAnimNode_CopyPoseFromMesh AnimGraphNode_CopyPoseFromMesh_1;
    FAnimNode_CopyPoseFromMesh AnimGraphNode_CopyPoseFromMesh;
    void ExecuteUbergraph_ASI_Maggot(int EntryPoint);
    void AnimGraph(FPoseLink& AnimGraph_0);
};

}}}   // namespace Game::Critters::Maggot

using ASI_Maggot_C = Game::Critters::Maggot::ASI_Maggot_C;