#pragma once
/*
Blueprint class ASS_Maggot_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../AnimationSharing.h"
#include "../Engine.h"

namespace Game { namespace Critters { namespace Maggot {

class ASS_Maggot_C : public UAnimSharingStateInstance
{
public:
    UE_CLASS("/Game/Critters/Maggot/ASS_MAggot", "ASS_Maggot_C");
    FPointerToUberGraphFrame UberGraphFrame;
    FAnimNode_Root AnimGraphNode_Root;
    FAnimNode_SequencePlayer AnimGraphNode_SequencePlayer;
    void ExecuteUbergraph_ASS_Maggot(int EntryPoint);
    void AnimGraph(FPoseLink& AnimGraph_0);
};

}}}   // namespace Game::Critters::Maggot

using ASS_Maggot_C = Game::Critters::Maggot::ASS_Maggot_C;