#pragma once
/*
Blueprint class Basic_Window_CutCorner_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../SlateCore.h"
#include "../UMG.h"

class UNamedSlot;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_Menu_ColorBar_C; }}}}
namespace Game { namespace UI { namespace Menu_MinersManual { class Basic_BG_CutCorner_C; }}}

namespace Game { namespace UI { namespace Art { namespace WidgetParts {

class Basic_Window_CutCorner_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Art/WidgetParts/Basic_Window_CutCorner", "Basic_Window_CutCorner_C");
    using Basic_BG_CutCorner_C = Game::UI::Menu_MinersManual::Basic_BG_CutCorner_C;
    using Basic_Menu_ColorBar_C = Game::UI::Art::WidgetParts::Basic_Menu_ColorBar_C;
    FPointerToUberGraphFrame UberGraphFrame;
    Basic_BG_CutCorner_C* Basic_BG_Window;
    Basic_Menu_ColorBar_C* Basic_Menu_ColorBar;
    class UNamedSlot* Content;
    FMargin ContentPadding;
    float BackgroundOpacity;
    bool ShowBar;
    void ExecuteUbergraph_Basic_Window_CutCorner(int EntryPoint);
    void SetBackgroundTint(FLinearColor InColorAndOpacity);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
};

}}}}   // namespace Game::UI::Art::WidgetParts

using Basic_Window_CutCorner_C = Game::UI::Art::WidgetParts::Basic_Window_CutCorner_C;