#pragma once
/*
Blueprint class Basic_ButtonWithControls_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../UMG.h"

class UBorder;
class UButton;
class UTextBlock;
namespace Game { namespace UI { namespace Global_UI_Elements { class UI_AdvancedLabel_C; }}}

namespace Game { namespace UI { namespace Art { namespace WidgetParts {

class Basic_ButtonWithControls_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Art/WidgetParts/Basic_ButtonWithControls", "Basic_ButtonWithControls_C");
    using UI_AdvancedLabel_C = Game::UI::Global_UI_Elements::UI_AdvancedLabel_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UBorder* BaseLeft;
    class UBorder* BaseMid;
    class UBorder* BaseRight;
    class UButton* Button_0;
    class UTextBlock* TXT_ButtonText;
    UI_AdvancedLabel_C* UI_AdvancedLabel;
    FText ButtonText;
    bool ShowInput;
    FLinearColor Tint_Base;
    FText InputStandardText;
    FText InputControllerOverride;
    TMulticastInlineDelegate<void()> OnClicked;
    uint8 PreviewAs;
    void ExecuteUbergraph_Basic_ButtonWithControls(int EntryPoint);
    void BndEvt__Button_0_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_0_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
};

}}}}   // namespace Game::UI::Art::WidgetParts

using Basic_ButtonWithControls_C = Game::UI::Art::WidgetParts::Basic_ButtonWithControls_C;