#pragma once
/*
Blueprint class Basic_IconWithOutline_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../UMG.h"

class UImage;
class UMaterialInstanceDynamic;
class USizeBox;
class UTexture2D;

namespace Game { namespace UI { namespace Art { namespace WidgetParts {

class Basic_IconWithOutline_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Art/WidgetParts/Basic_IconWithOutline", "Basic_IconWithOutline_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UImage* ICON_MATERIAL;
    class USizeBox* IconSize;
    float Size;
    class UTexture2D* Icon;
    FLinearColor OutlineColor;
    FLinearColor IconColor;
    bool UseOutline;
    bool ThickOutline;
    class UMaterialInstanceDynamic* DynMaterial;
    float IconScale;
    TSoftObjectPtr<class UTexture2D> Shape_Hexagon;
    TSoftObjectPtr<class UTexture2D> Shape_Warning;
    TSoftObjectPtr<class UTexture2D> Shape_Anomaly;
    void ExecuteUbergraph_Basic_IconWithOutline(int EntryPoint);
    void SetIcon(class UTexture2D* Texture);
    void SetTintColor(FLinearColor Color);
    void SetOutlineColor(FLinearColor Color);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
};

}}}}   // namespace Game::UI::Art::WidgetParts

using Basic_IconWithOutline_C = Game::UI::Art::WidgetParts::Basic_IconWithOutline_C;