#pragma once
/*
Blueprint class BP_AutoCannon_ProjectileLauncher_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../FSD.h"

namespace Game { namespace WeaponsNTools { namespace Autocannon {

class BP_AutoCannon_ProjectileLauncher_C : public UProjectileLauncherComponent
{
public:
    UE_CLASS("/Game/WeaponsNTools/Autocannon/BP_AutoCannon_ProjectileLauncher", "BP_AutoCannon_ProjectileLauncher_C");
};

}}}   // namespace Game::WeaponsNTools::Autocannon

using BP_AutoCannon_ProjectileLauncher_C = Game::WeaponsNTools::Autocannon::BP_AutoCannon_ProjectileLauncher_C;