#pragma once
/*
Blueprint class bp_BoneyardSpine_Spawner_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"

class USceneComponent;
class UStaticMeshComponent;
class UTerrainPlacementComponent;

namespace Game { namespace Landscape { namespace Biomes { namespace Biomes_Ingame { namespace BoneYards { namespace Destructables {

class bp_BoneyardSpine_Spawner_C : public AActor
{
public:
    UE_CLASS("/Game/Landscape/Biomes/Biomes_Ingame/BoneYards/Destructables/bp_BoneyardSpine_Spawner", "bp_BoneyardSpine_Spawner_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UStaticMeshComponent* Preview10;
    class UStaticMeshComponent* Preview9;
    class UStaticMeshComponent* Preview8;
    class UStaticMeshComponent* Preview7;
    class UStaticMeshComponent* Preview6;
    class UStaticMeshComponent* Preview5;
    class UStaticMeshComponent* Preview4;
    class UStaticMeshComponent* Preview3;
    class UStaticMeshComponent* Preview2;
    class UStaticMeshComponent* Preview1;
    class USceneComponent* Spawners;
    class UTerrainPlacementComponent* terrainPlacement;
    class USceneComponent* DefaultSceneRoot;
    void ExecuteUbergraph_bp_BoneyardSpine_Spawner(int EntryPoint);
    void OnMatchStarted_BeginPlay();
    void ReceiveBeginPlay();
private:
    struct UeMarkers
    {
        static constexpr const char* Preview10__UeScsNode = "6549ae4faf0285448568f984fe5a18b1";
        static constexpr const char* Preview9__UeScsNode = "70a237e11ecd3d4eb8e327dc29b0d627";
        static constexpr const char* Preview8__UeScsNode = "12d4c976990c5542b59ce74bbf50e034";
        static constexpr const char* Preview7__UeScsNode = "c6c6b52d31c4554d89a8469cbc7838bc";
        static constexpr const char* Preview6__UeScsNode = "c775bb29f09c9e4994f3e860b757cf3b";
        static constexpr const char* Preview5__UeScsNode = "f0d16204216f074283971161d26610af";
        static constexpr const char* Preview4__UeScsNode = "5762cc324653f74aa9b24b88231920c3";
        static constexpr const char* Preview3__UeScsNode = "4c7534dfa33b264c88145db7d1a49e6a";
        static constexpr const char* Preview2__UeScsNode = "173046028f8d86458b84e27851d68ff6";
        static constexpr const char* Preview1__UeScsNode = "85e1f5778e57794a8c66299f2229345e";
        static constexpr const char* Spawners__UeScsNode = "e7239e213251cf42acbb8492d9af51d5";
        static constexpr const char* terrainPlacement__UeScsNode = "3107d757fd56c849909173e93ea5c9e1";
        static constexpr const char* DefaultSceneRoot__UeScsNode = "974df6e15d24bc42a53bd12197431b38";
    };
};

}}}}}}   // namespace Game::Landscape::Biomes::Biomes_Ingame::BoneYards::Destructables

using bp_BoneyardSpine_Spawner_C = Game::Landscape::Biomes::Biomes_Ingame::BoneYards::Destructables::bp_BoneyardSpine_Spawner_C;