#pragma once
/*
Blueprint class bp_Boneyard_DestructibleDebris_Base_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"

class UHealthComponentBase;
class UPathfinderCollisionComponent;
class USceneComponent;
class USimpleHealthComponent;
class USimpleObjectInfoComponent;
class UStaticMeshComponent;
class UTerrainDetectComponent;

namespace Game { namespace Landscape { namespace Biomes { namespace Biomes_Ingame { namespace BoneYards { namespace Destructables {

class bp_Boneyard_DestructibleDebris_Base_C : public AActor
{
public:
    UE_CLASS("/Game/Landscape/Biomes/Biomes_Ingame/BoneYards/Destructables/bp_Boneyard_DestructibleDebris_Base", "bp_Boneyard_DestructibleDebris_Base_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class USimpleObjectInfoComponent* SimpleObjectInfo;
    class UPathfinderCollisionComponent* PathfinderCollision;
    class UStaticMeshComponent* StaticMesh;
    class UTerrainDetectComponent* TerrainDetect;
    class USimpleHealthComponent* SimpleHealth;
    class USceneComponent* DefaultSceneRoot;
    float Destroyed_Particle_Scale;
    void ExecuteUbergraph_bp_Boneyard_DestructibleDebris_Base(int EntryPoint);
    void BndEvt__bp_Boneyard_DestructibleDebris_Base_TerrainDetect_K2Node_ComponentBoundEvent_0_PointRemovedEvent__DelegateSignature(class USceneComponent* Point);
    void BndEvt__SimpleHealth_K2Node_ComponentBoundEvent_1_DeathSig__DelegateSignature(class UHealthComponentBase* HealthComponent);
private:
    struct UeMarkers
    {
        static constexpr const char* SimpleObjectInfo__UeScsNode = "c10b50b14a393447837a0d417e800df1";
        static constexpr const char* PathfinderCollision__UeScsNode = "5a27b0fac2302a41a2a19cc1dccbeb5c";
        static constexpr const char* StaticMesh__UeScsNode = "440d42795ea4944c8d4134060d617604";
        static constexpr const char* TerrainDetect__UeScsNode = "e56700b0f37add43970f23c89e5e7cd2";
        static constexpr const char* SimpleHealth__UeScsNode = "affa61e7eaa00948915cfa503f6ffa56";
        static constexpr const char* DefaultSceneRoot__UeScsNode = "c1d5f14a7f9784488d551d0a5dfcf3cb";
        static constexpr const char* Destroyed_Particle_Scale__UeName = "Destroyed Particle Scale";
    };
};

}}}}}}   // namespace Game::Landscape::Biomes::Biomes_Ingame::BoneYards::Destructables

using bp_Boneyard_DestructibleDebris_Base_C = Game::Landscape::Biomes::Biomes_Ingame::BoneYards::Destructables::bp_Boneyard_DestructibleDebris_Base_C;