#pragma once
/*
Blueprint class BP_Coilgun_Trailsegment_Base_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../FSD.h"

class USceneComponent;

namespace Game { namespace WeaponsNTools { namespace CoilGun {

class BP_Coilgun_Trailsegment_Base_C : public ACoilGunTrailSegment
{
public:
    UE_CLASS("/Game/WeaponsNTools/CoilGun/BP_Coilgun_Trailsegment_Base", "BP_Coilgun_Trailsegment_Base_C");
    class USceneComponent* DefaultSceneRoot;
    static constexpr const char* DefaultSceneRoot__UeScsNode = "28e1f45c5c890d489ba54f9a84ccdd7b";
};

}}}   // namespace Game::WeaponsNTools::CoilGun

using BP_Coilgun_Trailsegment_Base_C = Game::WeaponsNTools::CoilGun::BP_Coilgun_Trailsegment_Base_C;