#pragma once
/*
Blueprint class BP_ExplodingGooPlant_Fast_Medium_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "BP_ExplodingGooPlant_Fast_Base_C.h"

namespace Game { namespace LevelElements { namespace RoomObjects { namespace Hazards { namespace ExplodingGooPlant {

class BP_ExplodingGooPlant_Fast_Medium_C : public Game::LevelElements::RoomObjects::Hazards::ExplodingGooPlant::BP_ExplodingGooPlant_Fast_Base_C
{
public:
    UE_CLASS("/Game/LevelElements/RoomObjects/Hazards/ExplodingGooPlant/BP_ExplodingGooPlant_Fast_Medium", "BP_ExplodingGooPlant_Fast_Medium_C");
};

}}}}}   // namespace Game::LevelElements::RoomObjects::Hazards::ExplodingGooPlant

using BP_ExplodingGooPlant_Fast_Medium_C = Game::LevelElements::RoomObjects::Hazards::ExplodingGooPlant::BP_ExplodingGooPlant_Fast_Medium_C;