#pragma once
/*
Blueprint class BP_EnemyControlState_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class UAnimMontage;

namespace Game { namespace Character { namespace States {

class BP_EnemyControlState_C : public UEnemyControlStateComponent
{
public:
    UE_CLASS("/Game/Character/States/BP_EnemyControlState", "BP_EnemyControlState_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UAnimMontage* GetOnMontage;
    void ExecuteUbergraph_BP_EnemyControlState(int EntryPoint);
    void OnControllingEnemyAttached();
    void OnControllingEnemy(bool IsControlling);
    void OnCompleted_C6BE400543D83DD77DB15BA38DC1ED24(FName NotifyName);
    void OnBlendOut_C6BE400543D83DD77DB15BA38DC1ED24(FName NotifyName);
    void OnInterrupted_C6BE400543D83DD77DB15BA38DC1ED24(FName NotifyName);
    void OnNotifyBegin_C6BE400543D83DD77DB15BA38DC1ED24(FName NotifyName);
    void OnNotifyEnd_C6BE400543D83DD77DB15BA38DC1ED24(FName NotifyName);
};

}}}   // namespace Game::Character::States

using BP_EnemyControlState_C = Game::Character::States::BP_EnemyControlState_C;