#pragma once
/*
Blueprint class BP_Ebonut_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "BP_Collectible_Base_C.h"

class UAudioComponent;
class UHealthComponentBase;
class ULevelGenerationCarverComponent;
class UPathfinderCollisionComponent;
class UPointLightComponent;
class USceneComponent;
class USimpleHealthComponent;
class UStaticMeshComponent;
class UTerrainPlacementComponent;
class UTimelineComponent;

namespace Game { namespace GameElements { namespace Resources { namespace Collectibles { namespace Ebonut {

class BP_Ebonut_C : public Game::GameElements::Resources::Collectibles::BP_Collectible_Base_C
{
public:
    UE_CLASS("/Game/GameElements/Resources/Collectibles/Ebonut/BP_Ebonut", "BP_Ebonut_C");
    FPointerToUberGraphFrame UberGraphFrame_BP_Ebonut_C;
    static constexpr const char* UberGraphFrame_BP_Ebonut_C__UeName = "UberGraphFrame";
    class UStaticMeshComponent* SM_Carver_DropPodDrill001;
    static constexpr const char* SM_Carver_DropPodDrill001__UeScsNode = "97f64651b498b74a8b53cd19fac1e263";
    class ULevelGenerationCarverComponent* LevelGenerationCarver;
    static constexpr const char* LevelGenerationCarver__UeScsNode = "7dfec1d612b25147ab3bd14748d81e7c";
    class UPointLightComponent* PointLight1;
    static constexpr const char* PointLight1__UeScsNode = "3c3e99817a998c46ad80442b6204fe72";
    class UTerrainPlacementComponent* terrainPlacement;
    static constexpr const char* terrainPlacement__UeScsNode = "c505b2861c9a7740a26d5df1579904c1";
    class UPathfinderCollisionComponent* PathfinderWalkable;
    static constexpr const char* PathfinderWalkable__UeScsNode = "03854334f7bdb94f84524839026d53f5";
    class UPointLightComponent* PointLight;
    static constexpr const char* PointLight__UeScsNode = "5966544599604f409055843d800a6d17";
    class USceneComponent* PickupParticleSpawnPoint;
    static constexpr const char* PickupParticleSpawnPoint__UeScsNode = "1bf3b3a96a3ce84584130fd6d88e2fec";
    class UAudioComponent* OpenHit;
    static constexpr const char* OpenHit__UeScsNode = "bb9abe70a9f36940bdd91bcfd8201bbc";
    class UAudioComponent* TwondHit;
    static constexpr const char* TwondHit__UeName = "2ndHit";
    static constexpr const char* TwondHit__UeScsNode = "1c4e7363b5a634458a1eaeea7aa024fd";
    class UAudioComponent* OnestHit;
    static constexpr const char* OnestHit__UeName = "1stHit";
    static constexpr const char* OnestHit__UeScsNode = "50f5cd1fc6f815429d744221be03abbd";
    class UStaticMeshComponent* Shell3;
    static constexpr const char* Shell3__UeScsNode = "295f0db7da6c014882c41d9eb2a2f40f";
    class UStaticMeshComponent* Shell2;
    static constexpr const char* Shell2__UeScsNode = "b886ac3311bad6448961ee92a2988dc0";
    class UStaticMeshComponent* Shell1;
    static constexpr const char* Shell1__UeScsNode = "60be77093aa51345a9509ff67ae0a956";
    class UStaticMeshComponent* CoreMesh;
    static constexpr const char* CoreMesh__UeScsNode = "ab9da9e23633ed4ead39d004514a9da6";
    class USimpleHealthComponent* SimpleHealth;
    static constexpr const char* SimpleHealth__UeScsNode = "145f2a61b0f68b4c9747ed0db2026988";
    class UStaticMeshComponent* BaseMesh;
    static constexpr const char* BaseMesh__UeScsNode = "81dd1c3c31298543aa5c5fb355144465";
    float ScaleDown_NewTrack;
    static constexpr const char* ScaleDown_NewTrack__UeName = "ScaleDown_NewTrack_0_F8D011474F43755B827C2BB8FCF9590F";
    ETimelineDirection ScaleDown__Direction_F8D011474F43755B827C2BB8FCF9590F;
    class UTimelineComponent* ScaleDown;
    float FirstThreshold;
    float SecondThreshold;
    class UStaticMeshComponent* NewVar_0;
    bool CunksAreLoose;
    void ExecuteUbergraph_BP_Ebonut(int EntryPoint);
    void PlayDeath();
    void CrackOpen();
    void SecondHit();
    void FirstHit();
    void PickedUp();
    void RemoveChunks();
    void BndEvt__SimpleHealth_K2Node_ComponentBoundEvent_1_DamageSig__DelegateSignature(float amount);
    void BndEvt__SimpleHealth_K2Node_ComponentBoundEvent_0_DeathSig__DelegateSignature(class UHealthComponentBase* HealthComponent);
    void ScaleDown__UpdateFunc();
    void ScaleDown__FinishedFunc();
    void OnRep_State();
    void ShowOpen2();
};

}}}}}   // namespace Game::GameElements::Resources::Collectibles::Ebonut

using BP_Ebonut_C = Game::GameElements::Resources::Collectibles::Ebonut::BP_Ebonut_C;