#pragma once
/*
Blueprint class BP_FoamPuddle_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class UBoxComponent;
class USimpleObjectInfoComponent;
class USphereComponent;
class UTerrainDetectComponent;
class UTimelineComponent;

namespace Game { namespace GameElements { namespace Missions { namespace Warnings { namespace Plague { namespace CleaningPod { namespace Soaper {

class BP_FoamPuddle_C : public AFoamPuddle
{
public:
    UE_CLASS("/Game/GameElements/Missions/Warnings/Plague/CleaningPod/Soaper/BP_FoamPuddle", "BP_FoamPuddle_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class USimpleObjectInfoComponent* SimpleObjectInfo;
    static constexpr const char* SimpleObjectInfo__UeScsNode = "52857381bce39743ad61d71a9c34f2dd";
    class UBoxComponent* Box;
    static constexpr const char* Box__UeScsNode = "323917cf83e4184abcf2508c87cab05a";
    class USphereComponent* Sphere;
    static constexpr const char* Sphere__UeScsNode = "36e82c022eb1b146a25e6a6b983137ba";
    class UTerrainDetectComponent* TerrainDetect;
    static constexpr const char* TerrainDetect__UeScsNode = "8618417eceebfd4fb21dcb6965ab09de";
    float Timeline_1_NewTrack;
    static constexpr const char* Timeline_1_NewTrack__UeName = "Timeline_1_NewTrack_0_FB8CEE454A0146654CCF979239EF7152";
    ETimelineDirection Timeline_1__Direction_FB8CEE454A0146654CCF979239EF7152;
    class UTimelineComponent* Timeline_1;
    float Timeline_0_NewTrack;
    static constexpr const char* Timeline_0_NewTrack__UeName = "Timeline_0_NewTrack_0_44A611F34AD5A6FAD05E20AB4D1BE0FB";
    ETimelineDirection Timeline_0__Direction_44A611F34AD5A6FAD05E20AB4D1BE0FB;
    class UTimelineComponent* Timeline_0;
    bool ShouldDestroy;
    static constexpr const char* ShouldDestroy__Replicated = "OnRep_ShouldDestory:";
    void ExecuteUbergraph_BP_FoamPuddle(int EntryPoint);
    UE_AUTHORITY_ONLY void SetPuddleLifetime(float LifeTime);
    void ScaleOutAndDestroy();
    void ReceiveBeginPlay();
    void Timeline_1__UpdateFunc();
    void Timeline_1__FinishedFunc();
    void Timeline_0__UpdateFunc();
    void Timeline_0__FinishedFunc();
    void OnRep_ShouldDestory();
};

}}}}}}}   // namespace Game::GameElements::Missions::Warnings::Plague::CleaningPod::Soaper

using BP_FoamPuddle_C = Game::GameElements::Missions::Warnings::Plague::CleaningPod::Soaper::BP_FoamPuddle_C;