#pragma once
/*
Blueprint class BP_FadeScreenSubSystem_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../FSD.h"

namespace Game { namespace Game { namespace SubSystems {

class BP_FadeScreenSubSystem_C : public UFadeScreenSubSystem
{
public:
    UE_CLASS("/Game/Game/SubSystems/BP_FadeScreenSubSystem", "BP_FadeScreenSubSystem_C");
    static BP_FadeScreenSubSystem_C* Get(class UObject* WorldContextObject = nullptr);
};

}}}   // namespace Game::Game::SubSystems

/* Each subsystem's Get: the USubsystemBlueprintLibrary getter for its kind, as the editor's Get node. */
inline Game::Game::SubSystems::BP_FadeScreenSubSystem_C* Game::Game::SubSystems::BP_FadeScreenSubSystem_C::Get(class UObject* WorldContextObject) { return (BP_FadeScreenSubSystem_C*)USubsystemBlueprintLibrary::GetGameInstanceSubsystem(WorldContextObject, BP_FadeScreenSubSystem_C::StaticClass()); }

using BP_FadeScreenSubSystem_C = Game::Game::SubSystems::BP_FadeScreenSubSystem_C;