#pragma once
/*
Blueprint class BP_FossilsBase_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class APlayerCharacter;
class ULevelGenerationCarverComponent;
class USceneComponent;
class USoundBase;
class UTerrainPlacementComponent;

namespace Game { namespace LevelElements { namespace RoomObjects { namespace Fossils {

class BP_FossilsBase_C : public AActor
{
public:
    UE_CLASS("/Game/LevelElements/RoomObjects/Fossils/BP_FossilsBase", "BP_FossilsBase_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UTerrainPlacementComponent* terrainPlacement;
    static constexpr const char* terrainPlacement__UeScsNode = "18aef8b308610f4ab49fd7a94cf85564";
    class ULevelGenerationCarverComponent* LevelGenerationCarver;
    static constexpr const char* LevelGenerationCarver__UeScsNode = "7db56a53d98a2f4291b6f112625807f4";
    class USceneComponent* DefaultSceneRoot;
    static constexpr const char* DefaultSceneRoot__UeScsNode = "d392526625b5b24c97ded21449067236";
    class USoundBase* SpookyAudio;
    float AudioActivationDistance;
    FRandRange RandomScale;
    void ExecuteUbergraph_BP_FossilsBase(int EntryPoint);
    void OnLocalPlayerClose(class APlayerCharacter* Player, bool enteredTrigger);
    void ReceiveBeginPlay();
    void UserConstructionScript();
};

}}}}   // namespace Game::LevelElements::RoomObjects::Fossils

using BP_FossilsBase_C = Game::LevelElements::RoomObjects::Fossils::BP_FossilsBase_C;