#pragma once
/*
Blueprint class BP_FriendlyParasite_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

namespace Game { namespace WeaponsNTools { namespace Grenades { namespace FriendlyShredders {

class BP_FriendlyParasite_C : public AFriendlyParasite
{
public:
    UE_CLASS("/Game/WeaponsNTools/Grenades/FriendlyShredders/BP_FriendlyParasite", "BP_FriendlyParasite_C");
    static constexpr const char* UeDefaultSubobjects = "/Script/FSD.DamageComponent DamageComponent;/Script/FSD.DeepPatherFinderCharacterAfflictionComponent Affliction;/Script/FSD.DeepPathfinderMovement PathfinderMovement;/Script/FSD.DeepPathfinderSceneComponent SceneComponent;/Script/FSD.EnemyHealthComponent HealthComponent;/Script/FSD.EnemyTemperatureComponent Temperature;/Script/Engine.SkeletalMeshComponent Mesh;/Script/Engine.SphereComponent Collision;/Script/Engine.SphereComponent FindEnemyCollision;/Script/FSD.StatusEffectsComponent StatusEffects";
    FPointerToUberGraphFrame UberGraphFrame;
    float MaxParasiteLifetime;
    void ExecuteUbergraph_BP_FriendlyParasite(int EntryPoint);
    void LifetimeExceded();
    void ReceiveBeginPlay();
};

}}}}   // namespace Game::WeaponsNTools::Grenades::FriendlyShredders

using BP_FriendlyParasite_C = Game::WeaponsNTools::Grenades::FriendlyShredders::BP_FriendlyParasite_C;