#pragma once
/*
Blueprint class BP_GunkSeed_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../FSD.h"

class AActor;
class APlayerCharacter;
class UBoxComponent;
class UCarriableComponent;
class UOutlineComponent;
class UPointLightComponent;
class UPrimitiveComponent;
class USimpleObjectInfoComponent;
class USoundBase;
class USphereComponent;
class UStaticMeshComponent;

namespace Game { namespace GameElements { namespace Resources { namespace Collectibles { namespace GunkSeed {

class BP_GunkSeed_C : public AGem
{
public:
    UE_CLASS("/Game/GameElements/Resources/Collectibles/GunkSeed/BP_GunkSeed", "BP_GunkSeed_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UPointLightComponent* PointLight;
    static constexpr const char* PointLight__UeScsNode = "4262a70d4dac35428b6eaf8bfdb16a03";
    class UOutlineComponent* outline;
    static constexpr const char* outline__UeScsNode = "3353286ad0a7e84da1a13f48b3a27e96";
    class USimpleObjectInfoComponent* SimpleObjectInfo;
    static constexpr const char* SimpleObjectInfo__UeScsNode = "9790c991c4e57245a2be0e622923fab8";
    class UStaticMeshComponent* TerrainScannerMesh;
    static constexpr const char* TerrainScannerMesh__UeScsNode = "fb148230ab659041ae247ffa4ce6f7c8";
    class UBoxComponent* Box;
    static constexpr const char* Box__UeScsNode = "15d134dc41ae38409c06878a69b35244";
    class UStaticMeshComponent* Sphere;
    static constexpr const char* Sphere__UeScsNode = "927e67fc5226ff42b5c09e6b82e337c7";
    class UCarriableComponent* Carriable;
    static constexpr const char* Carriable__UeScsNode = "81efaa4adab18946b703c0d047fce5e2";
    class USphereComponent* UseSphere;
    static constexpr const char* UseSphere__UeScsNode = "7a2b37e102580b4db2929a534dae1b7f";
    FVector throwForce;
    class USoundBase* ImpactSound;
    float MaxLength;
    void ExecuteUbergraph_BP_GunkSeed(int EntryPoint);
    void BndEvt__Usable_K2Node_ComponentBoundEvent_3_UsableChangedSignature__DelegateSignature(bool CanUse);
    void BndEvt__Box_K2Node_ComponentBoundEvent_6_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit);
    void BndEvt__Carriable_K2Node_ComponentBoundEvent_2_CarriableEvent__DelegateSignature();
    void BndEvt__Carriable_K2Node_ComponentBoundEvent_1_CarriableEvent__DelegateSignature();
    void Throw(FVector force);
    void BndEvt__Usable_K2Node_ComponentBoundEvent_0_UsedBySignature__DelegateSignature(class APlayerCharacter* User, EInputKeys Key);
    void ReceiveBeginPlay();
};

}}}}}   // namespace Game::GameElements::Resources::Collectibles::GunkSeed

using BP_GunkSeed_C = Game::GameElements::Resources::Collectibles::GunkSeed::BP_GunkSeed_C;