#pragma once
/*
Blueprint class BP_GooExplosiontComponent_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"

class AActor;
class AFSDPawn;
class UEnemyTemperatureComponent;
class UPawnAffliction;
class UPawnAfflictionComponent;
class UStatusEffect;

namespace Game { namespace WeaponsNTools { namespace GooCannon {

class BP_GooExplosiontComponent_C : public UActorComponent
{
public:
    UE_CLASS("/Game/WeaponsNTools/GooCannon/BP_GooExplosiontComponent", "BP_GooExplosiontComponent_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class AFSDPawn* OwningPawn;
    class UEnemyTemperatureComponent* temperature;
    class UPawnAfflictionComponent* Affliction;
    class UStatusEffect* Effect;
    class AActor* Effect_Owner;
    static constexpr const char* Effect_Owner__UeName = "Effect Owner";
    void ExecuteUbergraph_BP_GooExplosiontComponent(int EntryPoint);
    void InitializeEffect(class UStatusEffect* Effect_0, class AActor* EffectOwner);
    void OnAfflictionActivatedEvent_Event_0(class UPawnAffliction* Affliction_0);
    void TryTriggerExplosion();
    void TriggerExplosion();
    void GetFXMeshScale(float& Scale);
};

}}}   // namespace Game::WeaponsNTools::GooCannon

using BP_GooExplosiontComponent_C = Game::WeaponsNTools::GooCannon::BP_GooExplosiontComponent_C;