#pragma once
/*
Blueprint class BP_Geyser_Lava_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"

class AActor;
class UAudioComponent;
class UCapsuleComponent;
class UDamageComponent;
class UExplosionComponent;
class ULevelGenerationCarverComponent;
class UParticleSystemComponent;
class UPathfinderCollisionComponent;
class UPointLightComponent;
class UPrimitiveComponent;
class USceneComponent;
class USimpleObjectInfoComponent;
class UStaticMeshComponent;
class UTerrainDetectComponent;
class UTerrainPlacementComponent;
class UTimelineComponent;
namespace Game { namespace LevelElements { namespace Components { class BP_DamageTriggerComponent_C; }}}

namespace Game { namespace LevelElements { namespace RoomObjects { namespace Hazards { namespace LavaGeyser {

class BP_Geyser_Lava_C : public AActor
{
public:
    UE_CLASS("/Game/LevelElements/RoomObjects/Hazards/LavaGeyser/BP_Geyser_Lava", "BP_Geyser_Lava_C");
    using BP_DamageTriggerComponent_C = Game::LevelElements::Components::BP_DamageTriggerComponent_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UAudioComponent* BoilingAudio;
    static constexpr const char* BoilingAudio__UeScsNode = "1d8c7bf1d290af4bbc8ff897e67cbc4a";
    class UDamageComponent* Damage;
    static constexpr const char* Damage__UeScsNode = "bee11550a835a74aa8e488086e45cfdd";
    class UCapsuleComponent* Capsule;
    static constexpr const char* Capsule__UeScsNode = "78dfdfcb1e238d4cbad1c15e6638ee4e";
    class UPointLightComponent* PointLight1;
    static constexpr const char* PointLight1__UeScsNode = "e83caf021735e7479cc720dc0fdea86b";
    class UPointLightComponent* PointLight;
    static constexpr const char* PointLight__UeScsNode = "0b79a4c876a1c94bbddd7b3f42eebd9e";
    class UStaticMeshComponent* StaticMesh2;
    static constexpr const char* StaticMesh2__UeScsNode = "773c507a387e7d468259d643686759ba";
    class UStaticMeshComponent* StaticMesh1;
    static constexpr const char* StaticMesh1__UeScsNode = "ac91b856cd022846b0b248458f640168";
    class UStaticMeshComponent* StaticMesh;
    static constexpr const char* StaticMesh__UeScsNode = "196620cba8804f4fa531dee0a7741f82";
    class UStaticMeshComponent* Sphere1;
    static constexpr const char* Sphere1__UeScsNode = "7f6524ccb34197418841b32fb19d2815";
    class UStaticMeshComponent* PreviewCube;
    static constexpr const char* PreviewCube__UeScsNode = "725c9f625f9ca0439e041ae5dfbd0445";
    class UStaticMeshComponent* PreviewMesh;
    static constexpr const char* PreviewMesh__UeScsNode = "e65ee299e021bf4bb83530f9f8ff5e99";
    class UTerrainDetectComponent* TerrainDetect;
    static constexpr const char* TerrainDetect__UeScsNode = "a0f309b039c7d940a71e1f4ca813ab95";
    class UTerrainDetectComponent* TerrainDetect3;
    static constexpr const char* TerrainDetect3__UeScsNode = "a5839c7acc38c74e869bc523dd2070df";
    class UTerrainDetectComponent* TerrainDetect2;
    static constexpr const char* TerrainDetect2__UeScsNode = "a7d41abc24729244a121110ddef8948b";
    class UTerrainDetectComponent* TerrainDetect1;
    static constexpr const char* TerrainDetect1__UeScsNode = "856ee5aaf3d8224398b98676957efae8";
    class USceneComponent* TerrainDetectors;
    static constexpr const char* TerrainDetectors__UeScsNode = "b1162913e8ba9f4aaa7f27dbb7d8e0e8";
    class UExplosionComponent* Explosion;
    static constexpr const char* Explosion__UeScsNode = "9d01b32d68c95b43b41d5790897de24f";
    class UParticleSystemComponent* Particle_Idle;
    static constexpr const char* Particle_Idle__UeScsNode = "24311d0f25a00f43ab41a710fa16099c";
    class UParticleSystemComponent* Particle_Erupt;
    static constexpr const char* Particle_Erupt__UeScsNode = "193e7ae38431334bba4a83090218b107";
    class ULevelGenerationCarverComponent* LevelGenerationCarver_Geyser;
    static constexpr const char* LevelGenerationCarver_Geyser__UeScsNode = "4a1e04aa0c897a4b8d3ca50c2e5bacb0";
    class ULevelGenerationCarverComponent* LevelGenerationCarver_Cube;
    static constexpr const char* LevelGenerationCarver_Cube__UeScsNode = "ea3e4de323c2b24c90e2f6d7330a27e1";
    class UTerrainPlacementComponent* terrainPlacement;
    static constexpr const char* terrainPlacement__UeScsNode = "dba958dbbf30e04f9777b6c4feae2182";
    class USimpleObjectInfoComponent* SimpleObjectInfo;
    static constexpr const char* SimpleObjectInfo__UeScsNode = "6e7cb602ce5f2541b69416a550a63ff7";
    class UPathfinderCollisionComponent* PathfinderCollision;
    static constexpr const char* PathfinderCollision__UeScsNode = "63916f1bb9620d47b79a18f5b68daf1e";
    BP_DamageTriggerComponent_C* BP_DamageTriggerComponent;
    static constexpr const char* BP_DamageTriggerComponent__UeScsNode = "8850763a73565b4ab9a5dac57cbdfc90";
    class USceneComponent* SharedRoot;
    static constexpr const char* SharedRoot__UeScsNode = "2d5b4759db48494e8016d686ee5d3aa4";
    float TL_LightIdle_Animation_B5F889F4441C038D5B643AB1334A0B57;
    ETimelineDirection TL_LightIdle__Direction_B5F889F4441C038D5B643AB1334A0B57;
    class UTimelineComponent* TL_LightIdle;
    float TL_LightErupt_Animation_7348656F4781FB277E0ACBB9184D718A;
    ETimelineDirection TL_LightErupt__Direction_7348656F4781FB277E0ACBB9184D718A;
    class UTimelineComponent* TL_LightErupt;
    FVector2D _Max;
    static constexpr const char* _Max__UeName = " Max";
    FVector2D _Max_0;
    static constexpr const char* _Max_0__UeName = " Max";
    float TraceDown;
    bool VolcanoEruptionDanger;
    static constexpr const char* VolcanoEruptionDanger__Replicated = "OnRep_VolcanoEruptionDanger:";
    bool Explode;
    static constexpr const char* Explode__Replicated = "OnRep_Explode:";
    float LightIntensityErupt;
    float LightIntensityIdle;
    void ExecuteUbergraph_BP_Geyser_Lava(int EntryPoint);
    void BndEvt__Capsule_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int OtherBodyIndex);
    void BndEvt__Capsule_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void LightOff();
    void LightOn();
    void Boom();
    void BndEvt__TerrainDetect3_K2Node_ComponentBoundEvent_3_PointRemovedEvent__DelegateSignature(class USceneComponent* Point);
    void BndEvt__TerrainDetect2_K2Node_ComponentBoundEvent_2_PointRemovedEvent__DelegateSignature(class USceneComponent* Point);
    void BndEvt__TerrainDetect1_K2Node_ComponentBoundEvent_1_PointRemovedEvent__DelegateSignature(class USceneComponent* Point);
    void BndEvt__TerrainDetect_K2Node_ComponentBoundEvent_0_PointRemovedEvent__DelegateSignature(class USceneComponent* Point);
    UE_MULTICAST void PlayDamageSound(FVector Location);
    void BurnPlayers();
    void ReceiveBeginPlay();
    void TL_LightIdle__UpdateFunc();
    void TL_LightIdle__FinishedFunc();
    void TL_LightErupt__UpdateFunc();
    void TL_LightErupt__FinishedFunc();
    void OnRep_VolcanoEruptionDanger();
    void OnRep_Explode();
};

}}}}}   // namespace Game::LevelElements::RoomObjects::Hazards::LavaGeyser

using BP_Geyser_Lava_C = Game::LevelElements::RoomObjects::Hazards::LavaGeyser::BP_Geyser_Lava_C;