#pragma once
/*
Blueprint class BP_JukeBox_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../FSD.h"

class AActor;
class APlayerCharacter;
class UAudioComponent;
class UBoxComponent;
class UFSDAchievement;
class UInstantUsable;
class UObject;
class UPrimitiveComponent;
class USceneComponent;
class USoundBase;
class USphereComponent;
class UStaticMeshComponent;
class UTimelineComponent;
class UWidgetComponent;

namespace Game { namespace Art { namespace Environments { namespace ShipTesting {

class BP_JukeBox_C : public AActor
{
public:
    UE_CLASS("/Game/Art/Environments/ShipTesting/BP_JukeBox", "BP_JukeBox_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UStaticMeshComponent* SM_SpaceRig_Jukebox_B;
    class UWidgetComponent* Widget5;
    class UWidgetComponent* Widget4;
    class UWidgetComponent* Widget3;
    class UWidgetComponent* Widget2;
    class UWidgetComponent* Widget1;
    class UWidgetComponent* Widget_Display;
    class UStaticMeshComponent* Jukebox;
    class USphereComponent* DanceSphere;
    class UStaticMeshComponent* SM_Speaker1;
    class UStaticMeshComponent* SM_Speaker;
    class UBoxComponent* Box;
    class UAudioComponent* JukeBox_Random_Cue;
    class UInstantUsable* InstantUsable;
    class USceneComponent* DefaultSceneRoot;
    float Timeline_0_Scale_Transform_97D3E280454882350654EE88E83F3CA7;
    TEnum<ETimelineDirection> Timeline_0__Direction_97D3E280454882350654EE88E83F3CA7;
    class UTimelineComponent* Timeline_0;
    float RotationSpeed;
    bool Can_use;
    int musicIndex;
    FVector Scale;
    TArray<TSoftObjectPtr<class USoundBase>> MusicList;
    class UFSDAchievement* PartyTimeAchievement;
    int PartyTimeDwarves;
    TArray<TSoftObjectPtr<class USoundBase>> SafeMusicList;
    int LocalMusicIndex;
    void ExecuteUbergraph_BP_JukeBox(int EntryPoint);
    void OnSaluteEvent_Event_0();
    void OnStreamerModeChanged(bool NewValue);
    void SetupDisableJukeboxMusic();
    void StopJukebox();
    void Stop_Juke_Box();
    void LoadAndPlay(TSoftObjectPtr<class USoundBase> Music);
    void BndEvt__DanceSphere_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int OtherBodyIndex);
    void BndEvt__DanceSphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void ToggleSpeakerRocking();
    void ReceiveBeginPlay();
    void BndEvt__InstantUsable_K2Node_ComponentBoundEvent_0_UsedBySignature__DelegateSignature(class APlayerCharacter* User, TEnum<EInputKeys> Key);
    void OnLoaded_C15A19DC4718016F57823CA232EE5860(class UObject* Loaded);
    void Timeline_0__UpdateFunc();
    void Timeline_0__FinishedFunc();
    void OnRep_MusicIndex();
    void PayCredits(class APlayerCharacter* User, int amount, bool& Purchased);
    void GetAvailableMusic(TArray<TSoftObjectPtr<class USoundBase>>& OutMusicList);
    void UpdateCurrentMusic();
private:
    struct UeMarkers
    {
        static constexpr const char* SM_SpaceRig_Jukebox_B__UeScsNode = "111ccbe9b325e54f842a8e1748b87933";
        static constexpr const char* Widget5__UeScsNode = "632cc4f88e4bd440a7c7d7233aed2fad";
        static constexpr const char* Widget4__UeScsNode = "575a40e0ca896b40a5c2c509b88a593c";
        static constexpr const char* Widget3__UeScsNode = "c9545cf40d266c4ea1dcf035e6f4876e";
        static constexpr const char* Widget2__UeScsNode = "b8b2aa9a9d807348a487f1a29279de99";
        static constexpr const char* Widget1__UeScsNode = "acf2e6b7139e404d87e0779d350bd53c";
        static constexpr const char* Widget_Display__UeScsNode = "2c63e989d8a115488b034d236ceeea20";
        static constexpr const char* Jukebox__UeScsNode = "c39d354b4df89248aaabb0741d27a817";
        static constexpr const char* DanceSphere__UeScsNode = "4596d2cec1fd9140be6110bd9cd2ee93";
        static constexpr const char* SM_Speaker1__UeScsNode = "62eb76692c694a45a51a6c8fee1be274";
        static constexpr const char* SM_Speaker__UeScsNode = "10048429d7cbbb459703ca494047403b";
        static constexpr const char* Box__UeScsNode = "2b568515b4287040aa3b1bbc5b018752";
        static constexpr const char* JukeBox_Random_Cue__UeScsNode = "142a6f3ef15d70409adc7f4840a4a3f8";
        static constexpr const char* InstantUsable__UeScsNode = "986a4065d8678946960bfce0322296b3";
        static constexpr const char* DefaultSceneRoot__UeScsNode = "af1528ba7b081e4ab5354e6a30a991f7";
        static constexpr const char* Can_use__UeName = "Can use";
        static constexpr const char* musicIndex__Replicated = "OnRep_MusicIndex:";
        static constexpr const char* Stop_Juke_Box__UeName = "Stop Juke Box";
    };
};

}}}}   // namespace Game::Art::Environments::ShipTesting

using BP_JukeBox_C = Game::Art::Environments::ShipTesting::BP_JukeBox_C;