#pragma once
/*
Blueprint class BP_LostPackStart_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class APlayerCharacter;
class UAudioComponent;
class UDialogDataAsset;
class UDropToTerrainComponent;
class UMaterialInstanceDynamic;
class UOutlineComponent;
class UParticleSystemComponent;
class UPointLightComponent;
class USimpleObjectInfoComponent;
class USingleUsableComponent;
class USoundBase;
class USphereComponent;
class UStaticMeshComponent;
class UTerrainDetectComponent;
class UTimelineComponent;

namespace Game { namespace GameElements { namespace Treasure { namespace LostPack {

class BP_LostPackStart_C : public ATreasureBeacon
{
public:
    UE_CLASS("/Game/GameElements/Treasure/LostPack/BP_LostPackStart", "BP_LostPackStart_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UTerrainDetectComponent* TerrainDetect3;
    static constexpr const char* TerrainDetect3__UeScsNode = "2dd8e4a9ef44d249a317afddc1893c8f";
    class UTerrainDetectComponent* TerrainDetect2;
    static constexpr const char* TerrainDetect2__UeScsNode = "54ac85ea743af64c8a01d092481160e0";
    class UTerrainDetectComponent* TerrainDetect1;
    static constexpr const char* TerrainDetect1__UeScsNode = "36d80b6b7a9e3c48b2f661439de10f4a";
    class UParticleSystemComponent* P_LostPack_Scanning1;
    static constexpr const char* P_LostPack_Scanning1__UeScsNode = "76d6c9588e53b948bd398a3600d537e2";
    class UParticleSystemComponent* P_LostPack_Scanning;
    static constexpr const char* P_LostPack_Scanning__UeScsNode = "5dfb6abed25b1e4996260537e7c0e0fb";
    class UAudioComponent* Audio;
    static constexpr const char* Audio__UeScsNode = "68bd9f4213779242a39f0221b607e558";
    class USphereComponent* LaserPointerShpere;
    static constexpr const char* LaserPointerShpere__UeScsNode = "78f30addc619c74ba5e05185840c303b";
    class UPointLightComponent* PointLight;
    static constexpr const char* PointLight__UeScsNode = "fb4b76c9e42c9f40be036d7ad400718a";
    class UStaticMeshComponent* HelmetMesh;
    static constexpr const char* HelmetMesh__UeScsNode = "4afe6d8a44d8af44a2a5a813625eaf8a";
    class UOutlineComponent* outline;
    static constexpr const char* outline__UeScsNode = "79abb6dd6920504c9e8e71354322cb31";
    class UTerrainDetectComponent* TerrainDetect;
    static constexpr const char* TerrainDetect__UeScsNode = "23dbf85c7b24fc4ba3bcbd85ed4e914a";
    class USimpleObjectInfoComponent* SimpleObjectInfo;
    static constexpr const char* SimpleObjectInfo__UeScsNode = "4e12996d1790c74c922696786be661a2";
    class UDropToTerrainComponent* DropToTerrain;
    static constexpr const char* DropToTerrain__UeScsNode = "d1dc4d6534e10448af21656593dc80c7";
    class USphereComponent* Sphere;
    static constexpr const char* Sphere__UeScsNode = "5996b92165466e44b104e0e0d8e4d96f";
    class USingleUsableComponent* SingleUsable;
    static constexpr const char* SingleUsable__UeScsNode = "de28e66af1f53c41a610ce7894d14a1f";
    float LightTimeline_NewTrack;
    static constexpr const char* LightTimeline_NewTrack__UeName = "LightTimeline_NewTrack_0_9C3586C54F34D331F1DA6DBB251F58D5";
    ETimelineDirection LightTimeline__Direction_9C3586C54F34D331F1DA6DBB251F58D5;
    class UTimelineComponent* LightTimeLine;
    class UMaterialInstanceDynamic* DMI;
    class UDialogDataAsset* OnDataDownloadedShout;
    class USoundBase* MapUpdatedAllNotification;
    bool Activated;
    static constexpr const char* Activated__Replicated = "OnRep_Activated:";
    void ExecuteUbergraph_BP_LostPackStart(int EntryPoint);
    UE_MULTICAST void UpdateScanningParticles(bool Active);
    void Used();
    void UpdateLight(float Strength);
    UE_MULTICAST void All_playDownloadSound();
    void StartLightWave();
    void BndEvt__SingleUsable_K2Node_ComponentBoundEvent_2_OnFailed__DelegateSignature();
    void BndEvt__SingleUsable_K2Node_ComponentBoundEvent_1_UsedBySignature__DelegateSignature(class APlayerCharacter* User, EInputKeys Key);
    void BndEvt__SingleUsable_K2Node_ComponentBoundEvent_0_UsedBySignature__DelegateSignature(class APlayerCharacter* User, EInputKeys Key);
    void ReceiveBeginPlay();
    void LightTimeline__NewTrack_1__EventFunc();
    void LightTimeline__UpdateFunc();
    void LightTimeline__FinishedFunc();
    void OnRep_Activated();
};

}}}}   // namespace Game::GameElements::Treasure::LostPack

using BP_LostPackStart_C = Game::GameElements::Treasure::LostPack::BP_LostPackStart_C;