#pragma once
/*
Blueprint class BP_LargeHollowLog_1_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "BP_HugeRoots_Base_C.h"

namespace Game { namespace LevelElements { namespace RoomObjects { namespace HugeCarvers { namespace WoodBranches {

class BP_LargeHollowLog_1_C : public Game::LevelElements::RoomObjects::HugeCarvers::WoodBranches::BP_HugeRoots_Base_C
{
public:
    UE_CLASS("/Game/LevelElements/RoomObjects/HugeCarvers/WoodBranches/BP_LargeHollowLog_1", "BP_LargeHollowLog_1_C");
};

}}}}}   // namespace Game::LevelElements::RoomObjects::HugeCarvers::WoodBranches

using BP_LargeHollowLog_1_C = Game::LevelElements::RoomObjects::HugeCarvers::WoodBranches::BP_LargeHollowLog_1_C;