#pragma once
/*
Blueprint class BP_LasePointer_SecondaryMarker_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "BP_LaserPointer_Marker_C.h"

namespace Game { namespace WeaponsNTools { namespace LaserPointer {

class BP_LasePointer_SecondaryMarker_C : public Game::WeaponsNTools::LaserPointer::BP_LaserPointer_Marker_C
{
public:
    UE_CLASS("/Game/WeaponsNTools/LaserPointer/BP_LasePointer_SecondaryMarker", "BP_LasePointer_SecondaryMarker_C");
    FPointerToUberGraphFrame UberGraphFrame_BP_LasePointer_SecondaryMarker_C;
    static constexpr const char* UberGraphFrame_BP_LasePointer_SecondaryMarker_C__UeName = "UberGraphFrame";
    void ExecuteUbergraph_BP_LasePointer_SecondaryMarker(int EntryPoint);
    void UpdateMaterial();
};

}}}   // namespace Game::WeaponsNTools::LaserPointer

using BP_LasePointer_SecondaryMarker_C = Game::WeaponsNTools::LaserPointer::BP_LasePointer_SecondaryMarker_C;