#pragma once
/*
Blueprint class BP_MagneticArrow_Component_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../FSD.h"

namespace Game { namespace WeaponsNTools { namespace Crossbow { namespace Projectiles {

class BP_MagneticArrow_Component_C : public UCrossbowProjectileMagnetic
{
public:
    UE_CLASS("/Game/WeaponsNTools/Crossbow/Projectiles/BP_MagneticArrow_Component", "BP_MagneticArrow_Component_C");
};

}}}}   // namespace Game::WeaponsNTools::Crossbow::Projectiles

using BP_MagneticArrow_Component_C = Game::WeaponsNTools::Crossbow::Projectiles::BP_MagneticArrow_Component_C;