#pragma once
/*
Blueprint class BP_OxygenRich_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class APlayerCharacter;

namespace Game { namespace GameElements { namespace Missions { namespace Mutators { namespace OxygenRich {

class BP_OxygenRich_C : public URunningMissionBP
{
public:
    UE_CLASS("/Game/GameElements/Missions/Mutators/OxygenRich/BP_OxygenRich", "BP_OxygenRich_C");
    FPointerToUberGraphFrame UberGraphFrame;
    void ExecuteUbergraph_BP_OxygenRich(int EntryPoint);
    void PlayerSpawned(class APlayerCharacter* PlayerCharacter);
    void StartLogic();
};

}}}}}   // namespace Game::GameElements::Missions::Mutators::OxygenRich

using BP_OxygenRich_C = Game::GameElements::Missions::Mutators::OxygenRich::BP_OxygenRich_C;