#pragma once
/*
Blueprint class BP_PersistentExplosionEffect_EPC_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "BP_Damage_Cloud_Base_C.h"

namespace Game { namespace WeaponsNTools { namespace ChargeBlaster {

class BP_PersistentExplosionEffect_EPC_C : public Game::Enemies::BaseItems::BP_Damage_Cloud_Base_C
{
public:
    UE_CLASS("/Game/WeaponsNTools/ChargeBlaster/BP_PersistentExplosionEffect_EPC", "BP_PersistentExplosionEffect_EPC_C");
};

}}}   // namespace Game::WeaponsNTools::ChargeBlaster

using BP_PersistentExplosionEffect_EPC_C = Game::WeaponsNTools::ChargeBlaster::BP_PersistentExplosionEffect_EPC_C;