#pragma once
/*
Blueprint class BP_PeelingBark_1_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"

class UHealthComponentBase;
class USceneComponent;
class USimpleHealthComponent;
class USimpleObjectInfoComponent;
class UStaticMeshComponent;
class UTerrainDetectComponent;
class UTerrainPlacementComponent;

namespace Game { namespace Landscape { namespace Biomes { namespace Biomes_Ingame { namespace HollowBough { namespace Assets { namespace Bark {

class BP_PeelingBark_1_C : public AActor
{
public:
    UE_CLASS("/Game/Landscape/Biomes/Biomes_Ingame/HollowBough/Assets/Bark/BP_PeelingBark_1", "BP_PeelingBark_1_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class USimpleObjectInfoComponent* SimpleObjectInfo;
    class USimpleHealthComponent* SimpleHealth;
    class UTerrainDetectComponent* TerrainDetect;
    class UTerrainPlacementComponent* terrainPlacement;
    class UStaticMeshComponent* StaticMesh;
    class USceneComponent* DefaultSceneRoot;
    void ExecuteUbergraph_BP_PeelingBark_1(int EntryPoint);
    void BndEvt__SimpleHealth_K2Node_ComponentBoundEvent_0_DeathSig__DelegateSignature(class UHealthComponentBase* HealthComponent);
private:
    struct UeMarkers
    {
        static constexpr const char* SimpleObjectInfo__UeScsNode = "f07496ef3fae1749b8a394f5adeadccb";
        static constexpr const char* SimpleHealth__UeScsNode = "f5fb0f9ca4e29c4a827e7bde50be87ee";
        static constexpr const char* TerrainDetect__UeScsNode = "b1cbc5df92761945925afde963f6337c";
        static constexpr const char* terrainPlacement__UeScsNode = "a84e7579ca4b3346a972387f6d70dc8f";
        static constexpr const char* StaticMesh__UeScsNode = "61dea91490f5bc4eb52fa7d65d40e931";
        static constexpr const char* DefaultSceneRoot__UeScsNode = "d2da5caeccf30e4fb5fd83b539c54917";
    };
};

}}}}}}}   // namespace Game::Landscape::Biomes::Biomes_Ingame::HollowBough::Assets::Bark

using BP_PeelingBark_1_C = Game::Landscape::Biomes::Biomes_Ingame::HollowBough::Assets::Bark::BP_PeelingBark_1_C;