#pragma once
/*
Blueprint class BP_RewardDispenser_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class AActor;
class APlayerCharacter;
class UBoxComponent;
class UChildActorComponent;
class UPrimitiveComponent;
class USceneComponent;
class USchematic;
class USkeletalMeshComponent;
class USphereComponent;
namespace Game { namespace GameElements { namespace GameEvents { namespace CoreInfuser { class BP_CoreInfuser_Rewards_Selector_C; }}}}
namespace Game { namespace GameElements { namespace GameEvents { namespace RewardDispenser { class BP_RewardUsableComponent_C; }}}}

namespace Game { namespace GameElements { namespace GameEvents { namespace RewardDispenser {

class BP_RewardDispenser_C : public AEventRewardDispenser
{
public:
    UE_CLASS("/Game/GameElements/GameEvents/RewardDispenser/BP_RewardDispenser", "BP_RewardDispenser_C");
    using BP_CoreInfuser_Rewards_Selector_C = Game::GameElements::GameEvents::CoreInfuser::BP_CoreInfuser_Rewards_Selector_C;
    using BP_RewardUsableComponent_C = Game::GameElements::GameEvents::RewardDispenser::BP_RewardUsableComponent_C;
    FPointerToUberGraphFrame UberGraphFrame;
    BP_RewardUsableComponent_C* BP_RewardUsableComponent;
    class UChildActorComponent* RewardSelectorActor;
    class UBoxComponent* PlayerTrigger;
    class USphereComponent* UsableCollision;
    class USkeletalMeshComponent* SkeletalMesh;
    class USceneComponent* DefaultSceneRoot;
    bool RewardSelectorVisible;
    class APlayerCharacter* NearbyPlayer;
    TMulticastInlineDelegate<void()> OnDispenserFinished;
    void ExecuteUbergraph_BP_RewardDispenser(int EntryPoint);
    void Turn_On_Buttons();
    void OnRewardSelected();
    void On_Selector_Finished(class USchematic* SchematicReward);
    void OnOpenDispenser();
    void Initialize();
    void BndEvt__BP_RewardUsableComponent_K2Node_ComponentBoundEvent_0_UsedBySignature__DelegateSignature(class APlayerCharacter* User, TEnum<EInputKeys> Key);
    void BndEvt__PlayerTrigger_K2Node_ComponentBoundEvent_3_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int OtherBodyIndex);
    void BndEvt__PlayerTrigger_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
    void OnPoweredUp();
    void OnOwnerAssigned();
    void ToggleRewardSelector(bool InVisible);
    void IsPlayerLocallyControlled(bool& LocallyControlled);
    void GetRewardSelector(BP_CoreInfuser_Rewards_Selector_C*& Selector);
    UE_PURE bool IsStateValid();
private:
    struct UeMarkers
    {
        static constexpr const char* BP_RewardUsableComponent__UeScsNode = "477f265087e1ef4592dd70c7e583e212";
        static constexpr const char* RewardSelectorActor__UeScsNode = "1110c65d69f5dc46a98aedd1bdff3dd0";
        static constexpr const char* PlayerTrigger__UeScsNode = "121d422d3bd9d04c923a53f92de00ec8";
        static constexpr const char* UsableCollision__UeScsNode = "2f3f1f91ae28ad4dbd6230ebdcbca372";
        static constexpr const char* SkeletalMesh__UeScsNode = "08b71074c97b77409186f5406238a83a";
        static constexpr const char* DefaultSceneRoot__UeScsNode = "bc87575fae248c408bdd75371def8b65";
        static constexpr const char* Turn_On_Buttons__UeName = "Turn On Buttons";
        static constexpr const char* On_Selector_Finished__UeName = "On Selector Finished";
    };
};

}}}}   // namespace Game::GameElements::GameEvents::RewardDispenser

using BP_RewardDispenser_C = Game::GameElements::GameEvents::RewardDispenser::BP_RewardDispenser_C;