#pragma once
/*
Blueprint class BP_RockCrackerPod_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../FSD.h"

class AFuelLineSegment;
class APlayerCharacter;
class UAudioComponent;
class UAutoCarverComponent;
class UCapsuleComponent;
class UChildActorComponent;
class UDropToTerrainComponent;
class UHealthComponentBase;
class UMaterialInterface;
class UNiagaraComponent;
class UObjectAttackerPositioning;
class UOutlineComponent;
class UOxygenSourceComponent;
class UParticleSystemComponent;
class UPathfinderCollisionComponent;
class USimpleObjectInfoComponent;
class USingleUsableComponent;
class USkeletalMeshComponent;
class UStaticMeshComponent;
class UTerrainDetectComponent;
class UTerrainPlacementComponent;
namespace Game { namespace WeaponsNTools { namespace RockCrackerBuilder { class BP_RockCracker_EndPoint_C; }}}

namespace Game { namespace GameElements { namespace GameEvents { namespace PlagueMeteor {

class BP_RockCrackerPod_C : public ARockCrackerPod
{
public:
    UE_CLASS("/Game/GameElements/GameEvents/PlagueMeteor/BP_RockCrackerPod", "BP_RockCrackerPod_C");
    using BP_RockCracker_EndPoint_C = Game::WeaponsNTools::RockCrackerBuilder::BP_RockCracker_EndPoint_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UChildActorComponent* FuelLineStart;
    static constexpr const char* FuelLineStart__UeScsNode = "bf3b34c2e2b676409914948cf7e34a68";
    class UTerrainPlacementComponent* terrainPlacement;
    static constexpr const char* terrainPlacement__UeScsNode = "bd70e65348eca94a913d27207a9ef4ec";
    class UPathfinderCollisionComponent* PathfinderCollision;
    static constexpr const char* PathfinderCollision__UeScsNode = "6af377cb7d4a2b4fb8d4106dfa48d3fe";
    class USkeletalMeshComponent* SkeletalMesh;
    static constexpr const char* SkeletalMesh__UeScsNode = "6841628b3c06174b90dbe2228a2df094";
    class UNiagaraComponent* N_BrokenSmoke;
    static constexpr const char* N_BrokenSmoke__UeScsNode = "7ae0218e06db4446a7f191a15740fd42";
    class UAudioComponent* RockCrackerPodRunning_Cue;
    static constexpr const char* RockCrackerPodRunning_Cue__UeScsNode = "8312843a450fa643b19ee10d14b63279";
    class UTerrainDetectComponent* TerrainDetect3;
    static constexpr const char* TerrainDetect3__UeScsNode = "744d6b9099373441b737fac5faaf9212";
    class UTerrainDetectComponent* TerrainDetect2;
    static constexpr const char* TerrainDetect2__UeScsNode = "e8ef2f49663e4247879b85d219f9e3d7";
    class UTerrainDetectComponent* TerrainDetect1;
    static constexpr const char* TerrainDetect1__UeScsNode = "309ebfbebdd84f4b8703deaa11c573bf";
    class UStaticMeshComponent* TerrainScannerMesh;
    static constexpr const char* TerrainScannerMesh__UeScsNode = "7f077f968c27e24e9260a5ff990cde28";
    class UChildActorComponent* BP_OxygenTankSound;
    static constexpr const char* BP_OxygenTankSound__UeScsNode = "9bcd85d28de41f49940928a4161f17f8";
    class UChildActorComponent* BP_OxygenTank1;
    static constexpr const char* BP_OxygenTank1__UeScsNode = "948a8a62de098e4ca63de09f919e973c";
    class UChildActorComponent* BP_OxygenTank;
    static constexpr const char* BP_OxygenTank__UeScsNode = "894b42e75289be4995fd77c62591d5c0";
    class UOutlineComponent* outline;
    static constexpr const char* outline__UeScsNode = "6d3838f936a854448138008261abb038";
    class UOxygenSourceComponent* OxygenSource;
    static constexpr const char* OxygenSource__UeScsNode = "44787601355dce4cb4c56d585a12dd17";
    class USimpleObjectInfoComponent* SimpleObjectInfo;
    static constexpr const char* SimpleObjectInfo__UeScsNode = "975695c8c302bd48b900beaf596cfbda";
    class UDropToTerrainComponent* DropToTerrain;
    static constexpr const char* DropToTerrain__UeScsNode = "9aff6118faed1c48b3b09e78b5f197a1";
    class UAutoCarverComponent* AutoCarver;
    static constexpr const char* AutoCarver__UeScsNode = "c9526073985df24287d82901bf9e2984";
    class UCapsuleComponent* RepairCollider;
    static constexpr const char* RepairCollider__UeScsNode = "d4d0655b6e34ce4792ea42761e5e9995";
    class USingleUsableComponent* ReviveUsable;
    static constexpr const char* ReviveUsable__UeScsNode = "33a68b65e1975b4082650f5a932130c2";
    class UObjectAttackerPositioning* ObjectAttackerPositioning;
    static constexpr const char* ObjectAttackerPositioning__UeScsNode = "3f0103bfa1d83b46b5412ce40cb34c2e";
    class UCapsuleComponent* BodyCollision;
    static constexpr const char* BodyCollision__UeScsNode = "eaec7bcc39e1894f85d0e1dd5b0d70f5";
    class USkeletalMeshComponent* SK_DropPod_Drill;
    static constexpr const char* SK_DropPod_Drill__UeScsNode = "ad46b02f3179764d8f0e2061d87258c9";
    FTimerHandle ResizeCarverTimer;
    BP_RockCracker_EndPoint_C* EndPoint;
    class AFuelLineSegment* FirstFuelLineSegment;
    static constexpr const char* FirstFuelLineSegment__Replicated = ":";
    TMulticastInlineDelegate<void()> OnLanded;
    TMulticastInlineDelegate<void(bool Active)> OnEventActiveChanged;
    class UAudioComponent* DrillingSound;
    class UParticleSystemComponent* DrillingParticles;
    FVector FuelLineStartLocation;
    static constexpr const char* FuelLineStartLocation__Replicated = "OnRep_FuelLineStartLocation:";
    void ExecuteUbergraph_BP_RockCrackerPod(int EntryPoint);
    void SwitchYellowLights(bool isGreen);
    void BndEvt__BP_RockCrackerPod_Health_K2Node_ComponentBoundEvent_7_DeathSig__DelegateSignature(class UHealthComponentBase* HealthComponent);
    void OnExitState(ERockCrackerstate PodState_0);
    void OnEnterState(ERockCrackerstate PodState_0);
    void OnFirstFuelLineSegment(class AFuelLineSegment* InFirstSegment);
    void BndEvt__BP_RockCrackerPod_DropToTerrain_K2Node_ComponentBoundEvent_3_OnIsFallingToTerrainChanged__DelegateSignature(bool IsFalling);
    void SetEndPoint(BP_RockCracker_EndPoint_C* EndPoint_0);
    void ResizeCarver();
    void OnDroppodImpact();
    void OnEventEnded(bool wasSuccess);
    void OnEventStarted();
    void BndEvt__BP_RockCrackerPod_ReviveUsable_K2Node_ComponentBoundEvent_2_UsedBySignature__DelegateSignature(class APlayerCharacter* User, EInputKeys Key);
    void ReceiveBeginPlay();
    void UserConstructionScript();
    void UpdateLights(class UMaterialInterface* NewMaterial);
    void OnRep_FuelLineStartLocation();
};

}}}}   // namespace Game::GameElements::GameEvents::PlagueMeteor

using BP_RockCrackerPod_C = Game::GameElements::GameEvents::PlagueMeteor::BP_RockCrackerPod_C;