#pragma once
/*
Blueprint class BP_Salvage_FuelPoint_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "BP_Salvage_Point_C.h"

class UClass;
class UTerrainPlacementComponent;
namespace Game { namespace GameElements { namespace Objectives { namespace Salvage { class BP_Salvage_FuelPod_C; }}}}

namespace Game { namespace GameElements { namespace Objectives { namespace Salvage {

class BP_Salvage_FuelPoint_C : public Game::GameElements::Objectives::Salvage::BP_Salvage_Point_C
{
public:
    UE_CLASS("/Game/GameElements/Objectives/Salvage/BP_Salvage_FuelPoint", "BP_Salvage_FuelPoint_C");
    using BP_Salvage_FuelPod_C = Game::GameElements::Objectives::Salvage::BP_Salvage_FuelPod_C;
    FPointerToUberGraphFrame UberGraphFrame_BP_Salvage_FuelPoint_C;
    static constexpr const char* UberGraphFrame_BP_Salvage_FuelPoint_C__UeName = "UberGraphFrame";
    class UTerrainPlacementComponent* terrainPlacement;
    static constexpr const char* terrainPlacement__UeScsNode = "fa8b0af428dbeb48a829841b90ba6684";
    BP_Salvage_FuelPod_C* pod;
    static constexpr const char* pod__Replicated = ":";
    TArray<TSoftClassPtr<class UClass>> MoveIfCloseTo;
    FVector InitalLocation;
    int TriesToSpawn;
    void ExecuteUbergraph_BP_Salvage_FuelPoint(int EntryPoint);
    void ReceiveBeginPlay();
    void Call_In_Pod();
    static constexpr const char* Call_In_Pod__UeName = "Call In Pod";
    void OnDefenseFail();
    void OnDefenseComplete();
    void OnDefenseStart();
    void EnableRepair();
    void CheckIfCloseToInvalidators(bool& IsClose);
    void SolveTooCloseToInvalidator();
};

}}}}   // namespace Game::GameElements::Objectives::Salvage

using BP_Salvage_FuelPoint_C = Game::GameElements::Objectives::Salvage::BP_Salvage_FuelPoint_C;