#pragma once
/*
Blueprint class BP_SampleExtractionPod_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class UActorTrackingComponent;
class UAudioComponent;
class UAutoCarverComponent;
class UCapsuleComponent;
class UDropToTerrainComponent;
class ULightStrobingComponent;
class UOutlineComponent;
class UParticleSystemComponent;
class UPathfinderCollisionComponent;
class UPointLightComponent;
class UResourceBank;
class UResourceData;
class USceneComponent;
class USimpleObjectInfoComponent;
class USkeletalMeshComponent;
class UTerrainDetectComponent;
class UTerrainPlacementComponent;
class UTerrainScannerStaticMesh;

namespace Game { namespace GameElements { namespace GameEvents { namespace CoreRift {

class BP_SampleExtractionPod_C : public AExpeniteSamplePod
{
public:
    UE_CLASS("/Game/GameElements/GameEvents/CoreRift/BP_ExpeniteSamplePod", "BP_SampleExtractionPod_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class ULightStrobingComponent* LightStrobing;
    static constexpr const char* LightStrobing__UeScsNode = "be55bd4b0ab69b4f9bf9a37a6842029f";
    class UPointLightComponent* PointLight2;
    static constexpr const char* PointLight2__UeScsNode = "e9ca33db3d799c4b84fe709841554b1b";
    class UCapsuleComponent* Capsule;
    static constexpr const char* Capsule__UeScsNode = "6dd6a92f50051d459dc2da98d3432acf";
    class USkeletalMeshComponent* SK_RiftPodDrill2;
    static constexpr const char* SK_RiftPodDrill2__UeScsNode = "26744cdf3ef5c34ab0a81d53971418c0";
    class USkeletalMeshComponent* SK_RiftPodDrill3;
    static constexpr const char* SK_RiftPodDrill3__UeScsNode = "b63f8dbcca8e3646b346d991482d95d0";
    class USkeletalMeshComponent* SK_RiftPodDrill1;
    static constexpr const char* SK_RiftPodDrill1__UeScsNode = "2528e78c869f404f83eb0c64577a080e";
    class UTerrainScannerStaticMesh* TerrainScannerStaticMesh;
    static constexpr const char* TerrainScannerStaticMesh__UeScsNode = "1c3411e080d5af4baa10ee248e9e0f18";
    class UActorTrackingComponent* ActorTracking;
    static constexpr const char* ActorTracking__UeScsNode = "f36c0be81fb1664eb45f27e939e7c170";
    class USimpleObjectInfoComponent* SimpleObjectInfo;
    static constexpr const char* SimpleObjectInfo__UeScsNode = "c6ac8ff495ed8341a47a02a1f93b34c1";
    class USkeletalMeshComponent* SK_RiftPodDoor3;
    static constexpr const char* SK_RiftPodDoor3__UeScsNode = "bd7fea3bb9801a4cb8384c7f06abffe0";
    class USkeletalMeshComponent* SK_RiftPodDoor2;
    static constexpr const char* SK_RiftPodDoor2__UeScsNode = "d02b004e695f2241b31ff969b5b67b5d";
    class USkeletalMeshComponent* SK_RiftPodDoor1;
    static constexpr const char* SK_RiftPodDoor1__UeScsNode = "d58d5bd4bd15e94097209c906735736d";
    class USkeletalMeshComponent* SK_RiftPodDoor4;
    static constexpr const char* SK_RiftPodDoor4__UeScsNode = "d29913af359ef34c955cdf1c8fc18da9";
    class USkeletalMeshComponent* SK_DropPod_Drill;
    static constexpr const char* SK_DropPod_Drill__UeScsNode = "306ed1721055f647bb68403786e4eee2";
    class USkeletalMeshComponent* SK_Sample;
    static constexpr const char* SK_Sample__UeScsNode = "964e0429d59f704b9dc81871dbcdc934";
    class USkeletalMeshComponent* SK_RiftPodDrill;
    static constexpr const char* SK_RiftPodDrill__UeScsNode = "ebab399345d89c4587153cbfd7b504b1";
    class UPointLightComponent* PointLight1;
    static constexpr const char* PointLight1__UeScsNode = "b48e6420a5effd4fbe0a97789ded5604";
    class USkeletalMeshComponent* SK_RiftPod;
    static constexpr const char* SK_RiftPod__UeScsNode = "d66193672cf3ce42abeb21cf19c14de6";
    class USceneComponent* Scene1;
    static constexpr const char* Scene1__UeScsNode = "5f53c0c58a34444e90c711ca55b45de3";
    class UTerrainPlacementComponent* terrainPlacement;
    static constexpr const char* terrainPlacement__UeScsNode = "3ff3da0b62a27b4ab57f888745fa752b";
    class UResourceBank* ResourceBank;
    static constexpr const char* ResourceBank__UeScsNode = "bea87a3393308241bbf11c31984fdbab";
    class UTerrainDetectComponent* TerrainDetect3;
    static constexpr const char* TerrainDetect3__UeScsNode = "29455781fc44c24b9d95029187dd7a36";
    class UTerrainDetectComponent* TerrainDetect2;
    static constexpr const char* TerrainDetect2__UeScsNode = "5b817740af785744beb5bdc6a4d359ed";
    class UTerrainDetectComponent* TerrainDetect1;
    static constexpr const char* TerrainDetect1__UeScsNode = "6818c81a23c65f488c6c0d2f8b4c3553";
    class UDropToTerrainComponent* DropToTerrain;
    static constexpr const char* DropToTerrain__UeScsNode = "da95f8584a33f94b85339da5ee764972";
    class UOutlineComponent* outline;
    static constexpr const char* outline__UeScsNode = "ffba0ac90487ec4aa4a557fdac5caf87";
    class UPathfinderCollisionComponent* PathfinderCollision;
    static constexpr const char* PathfinderCollision__UeScsNode = "4f4f498e33cd4d439340dbed4be05763";
    class UAutoCarverComponent* AutoCarver;
    static constexpr const char* AutoCarver__UeScsNode = "bb7c1d69c0b7cd4baa7cecfcb59a99ba";
    class UParticleSystemComponent* DropParticles1;
    class UParticleSystemComponent* DropParticles2;
    class UAudioComponent* DrillingSoundRef;
    bool SampleCollected;
    static constexpr const char* SampleCollected__Replicated = "OnRep_SampleCollected:";
    TMulticastInlineDelegate<void()> OnSampleAquired;
    TMulticastInlineDelegate<void()> OnTakingOff;
    TMulticastInlineDelegate<void()> OnPodLanded;
    bool Landed;
    static constexpr const char* Landed__Replicated = "OnRep_Landed:";
    void ExecuteUbergraph_BP_SampleExtractionPod(int EntryPoint);
    void OnLanded();
    void OnDroppodCloseToImpact();
    void OnSampleCollected();
    void BndEvt__BP_SampleExtractionPod_ResourceBank_K2Node_ComponentBoundEvent_0_ResourceDelegate__DelegateSignature(class UResourceData* Resource, float amount);
    void OnDroppodImpact();
    void OnDropStarted();
    void UserConstructionScript();
    void OnRep_SampleCollected();
    void SetupBlinking();
    void OnRep_Landed();
};

}}}}   // namespace Game::GameElements::GameEvents::CoreRift

using BP_SampleExtractionPod_C = Game::GameElements::GameEvents::CoreRift::BP_SampleExtractionPod_C;