#pragma once
/*
Blueprint class BP_ShowroomStage_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class USpotLightComponent;
class UStaticMeshComponent;
class UTextureRenderTarget2D;

namespace Game { namespace UI { namespace Showroom {

class BP_ShowroomStage_C : public AShowroomStage
{
public:
    UE_CLASS("/Game/UI/Showroom/BP_ShowroomStage", "BP_ShowroomStage_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class USpotLightComponent* SpotLight;
    static constexpr const char* SpotLight__UeScsNode = "e7b69e074fee4c44b838cb8f741fbfa3";
    class USpotLightComponent* SpotLight1;
    static constexpr const char* SpotLight1__UeScsNode = "fb04e8a6eb2eeb4c9941a9c5992fa4cf";
    class USpotLightComponent* SpotLight2;
    static constexpr const char* SpotLight2__UeScsNode = "adf5aa4374108a40b4c1e365d7437c19";
    class UStaticMeshComponent* StaticMesh;
    static constexpr const char* StaticMesh__UeScsNode = "c59479c5c0b4cf40be1a1f6641aaa8ce";
    void ExecuteUbergraph_BP_ShowroomStage(int EntryPoint);
    void ReceiveBeginPlay();
    class UTextureRenderTarget2D* CreateRenderTarget();
};

}}}   // namespace Game::UI::Showroom

using BP_ShowroomStage_C = Game::UI::Showroom::BP_ShowroomStage_C;