#pragma once
/*
Blueprint class BP_ThornVinesChokingWoodRoots_Base_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"

class UGenerationCleanupComponent;
class ULevelGenerationCarverComponent;
class USceneComponent;
class UStaticMeshComponent;
class UTerrainPlacementComponent;

namespace Game { namespace LevelElements { namespace RoomObjects { namespace HugeCarvers { namespace ThornBranches {

class BP_ThornVinesChokingWoodRoots_Base_C : public AActor
{
public:
    UE_CLASS("/Game/LevelElements/RoomObjects/HugeCarvers/ThornBranches/BP_ThornVinesChokingWoodRoots_Base", "BP_ThornVinesChokingWoodRoots_Base_C");
    class UGenerationCleanupComponent* GenerationCleanup;
    static constexpr const char* GenerationCleanup__UeScsNode = "e8eaebe96d4fdf4c9eb8d995eb3fc048";
    class ULevelGenerationCarverComponent* LevelGenerationCarver_ThornVine;
    static constexpr const char* LevelGenerationCarver_ThornVine__UeScsNode = "c326ed1653b9a541bc6ee3bd0b8fba54";
    class ULevelGenerationCarverComponent* LevelGenerationCarver_BaseRoot;
    static constexpr const char* LevelGenerationCarver_BaseRoot__UeScsNode = "c24345717dbf9a4ab6742850dea37130";
    class UStaticMeshComponent* StaticMesh3;
    static constexpr const char* StaticMesh3__UeScsNode = "394c5eeaee0a2e4a8c2ab13b14e81138";
    class UStaticMeshComponent* StaticMesh2;
    static constexpr const char* StaticMesh2__UeScsNode = "d21b2e9bc5a7854c9e54908cc28d4c3a";
    class UStaticMeshComponent* StaticMesh1;
    static constexpr const char* StaticMesh1__UeScsNode = "1e1ad8793279494c9b36b5b916cb9a5a";
    class UStaticMeshComponent* StaticMesh;
    static constexpr const char* StaticMesh__UeScsNode = "4e3dc8c5735d4a4987edbf94a275297e";
    class UStaticMeshComponent* Cube;
    static constexpr const char* Cube__UeScsNode = "8c3ace183f4e7d4a9020cc57cc5c6b34";
    class UTerrainPlacementComponent* terrainPlacement;
    static constexpr const char* terrainPlacement__UeScsNode = "a028e9e423a03f4ca48784452b256c6e";
    class USceneComponent* DefaultSceneRoot;
    static constexpr const char* DefaultSceneRoot__UeScsNode = "4f86bd5b67049742a0c1e66bed337f6c";
};

}}}}}   // namespace Game::LevelElements::RoomObjects::HugeCarvers::ThornBranches

using BP_ThornVinesChokingWoodRoots_Base_C = Game::LevelElements::RoomObjects::HugeCarvers::ThornBranches::BP_ThornVinesChokingWoodRoots_Base_C;