#pragma once
/*
Blueprint class BP_VP_Pickaxe_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../FSD.h"

namespace Game { namespace WeaponsNTools { namespace Pickaxe {

class BP_VP_Pickaxe_C : public APickaxePreviewActor
{
public:
    UE_CLASS("/Game/WeaponsNTools/Pickaxe/BP_VP_Pickaxe", "BP_VP_Pickaxe_C");
};

}}}   // namespace Game::WeaponsNTools::Pickaxe

using BP_VP_Pickaxe_C = Game::WeaponsNTools::Pickaxe::BP_VP_Pickaxe_C;