#pragma once
/*
Blueprint class BP_ZipLineState_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../FSD.h"

namespace Game { namespace Character { namespace States {

class BP_ZipLineState_C : public UZipLineStateComponent
{
public:
    UE_CLASS("/Game/Character/States/BP_ZipLineState", "BP_ZipLineState_C");
    FPointerToUberGraphFrame UberGraphFrame;
    void ExecuteUbergraph_BP_ZipLineState(int EntryPoint);
    void ReceiveSpeedBoostDeactivated();
    void ReceiveSpeedBoostActivated();
    FVector GetJumpVector(FVector LookVector, FVector CurrentVelocity);
};

}}}   // namespace Game::Character::States

using BP_ZipLineState_C = Game::Character::States::BP_ZipLineState_C;