#pragma once
/*
Blueprint class Cheat_SpawnSandStorm_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../UMG.h"

class UButton;
class UClass;
class UTextBlock;

namespace Game { namespace UI { namespace Menu_Cheats {

class Cheat_SpawnSandStorm_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_Cheats/Cheat_SpawnSandStorm", "Cheat_SpawnSandStorm_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UButton* Button_0;
    class UTextBlock* TextBlock;
    FSoftClassPath NewVar_0;
    TSoftClassPtr<class UClass> NewVar_1;
    void ExecuteUbergraph_Cheat_SpawnSandStorm(int EntryPoint);
    void BndEvt__Button_0_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature();
    UE_COSMETIC void Construct();
};

}}}   // namespace Game::UI::Menu_Cheats

using Cheat_SpawnSandStorm_C = Game::UI::Menu_Cheats::Cheat_SpawnSandStorm_C;