#pragma once
/*
Blueprint class Cheat_SpawnBosco_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class ABosco;
class UButton;
class UTextBlock;

namespace Game { namespace UI { namespace Menu_Cheats {

class Cheat_SpawnBosco_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_Cheats/Cheat_SpawnBosco", "Cheat_SpawnBosco_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UButton* Button_0;
    class UTextBlock* TextBlock;
    TMulticastInlineDelegate<void()> Bosco_spawn_requested;
    static constexpr const char* Bosco_spawn_requested__UeName = "Bosco spawn requested";
    void ExecuteUbergraph_Cheat_SpawnBosco(int EntryPoint);
    void OnBoscoChanged_Event(class ABosco* Bosco);
    void BndEvt__Button_0_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature();
    UE_COSMETIC void Construct();
};

}}}   // namespace Game::UI::Menu_Cheats

using Cheat_SpawnBosco_C = Game::UI::Menu_Cheats::Cheat_SpawnBosco_C;