#pragma once
/*
Blueprint class Cheat_SetPerk_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class UPerkAsset;
class UScrollBox;
namespace Game { namespace UI { namespace Menu_Cheats { class Cheat_SetPerk_Row_C; }}}

namespace Game { namespace UI { namespace Menu_Cheats {

class Cheat_SetPerk_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_Cheats/Cheat_SetPerk", "Cheat_SetPerk_C");
    using Cheat_SetPerk_Row_C = Game::UI::Menu_Cheats::Cheat_SetPerk_Row_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UScrollBox* ScrollBox_79;
    TArray<Cheat_SetPerk_Row_C*> Perk_Rows;
    static constexpr const char* Perk_Rows__UeName = "Perk Rows";
    TArray<class UPerkAsset*> EquippedPerks;
    void ExecuteUbergraph_Cheat_SetPerk(int EntryPoint);
    void Set_Perk_In_Row_State(Cheat_SetPerk_Row_C* Buff_row_to_skip);
    static constexpr const char* Set_Perk_In_Row_State__UeName = "Set Perk In Row State";
    UE_COSMETIC void Construct();
};

}}}   // namespace Game::UI::Menu_Cheats

using Cheat_SetPerk_C = Game::UI::Menu_Cheats::Cheat_SetPerk_C;