#pragma once
/*
Blueprint class Cheat_List_Bosco_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "Cheat_EquipList_C.h"

class AFSDPlayerState;
class UItemID;
class UItemSkin;
class UObject;
namespace Game { namespace UI { namespace Menu_Cheats { namespace VanityCheatWidgets { class Cheat_EquipList_Entry_C; }}}}

namespace Game { namespace UI { namespace Menu_Cheats { namespace VanityCheatWidgets {

class Cheat_List_Bosco_C : public Game::UI::Menu_Cheats::VanityCheatWidgets::Cheat_EquipList_C
{
public:
    UE_CLASS("/Game/UI/Menu_Cheats/VanityCheatWidgets/Cheat_List_Bosco", "Cheat_List_Bosco_C");
    using Cheat_EquipList_Entry_C = Game::UI::Menu_Cheats::VanityCheatWidgets::Cheat_EquipList_Entry_C;
    void ReceiveEntryEquipClick(Cheat_EquipList_Entry_C* InEntryWidget, class UObject* InData, bool InEquipped);
    void ReceiveEntryOwnedClick(Cheat_EquipList_Entry_C* InEntryWidget, class UObject* InData, bool InOwned);
    void GetItemID(class UItemID*& ItemID);
    UE_PURE class AFSDPlayerState* GetState();
    void GetEquippedSkins(class UItemID* ItemID, TArray<class UItemSkin*>& OutSkins);
    void Refresh();
};

}}}}   // namespace Game::UI::Menu_Cheats::VanityCheatWidgets

using Cheat_List_Bosco_C = Game::UI::Menu_Cheats::VanityCheatWidgets::Cheat_List_Bosco_C;