#pragma once
/*
Blueprint class Cheat_SpawnEnemies_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class UCheckBox;
namespace Game { namespace UI { namespace Menu_Cheats { class CheatMenu_BasicButtonWText_C; }}}

namespace Game { namespace UI { namespace Menu_Cheats {

class Cheat_SpawnEnemies_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_Cheats/Cheat_SpawnEnemies", "Cheat_SpawnEnemies_C");
    using CheatMenu_BasicButtonWText_C = Game::UI::Menu_Cheats::CheatMenu_BasicButtonWText_C;
    FPointerToUberGraphFrame UberGraphFrame;
    CheatMenu_BasicButtonWText_C* CheatMenu_BasicButtonWText;
    class UCheckBox* CheckBox_0;
    void ExecuteUbergraph_Cheat_SpawnEnemies(int EntryPoint);
    void BndEvt__CheckBox_0_K2Node_ComponentBoundEvent_6_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked);
    UE_COSMETIC void Construct();
};

}}}   // namespace Game::UI::Menu_Cheats

using Cheat_SpawnEnemies_C = Game::UI::Menu_Cheats::Cheat_SpawnEnemies_C;