#pragma once
/*
Blueprint class ConsoleScreen_PickAxe_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

namespace Game { namespace UI { namespace HUD_SpaceRig { class ConsoleScreen_BGtemplate_C; class ConsoleScreen_Notification_C; }}}

namespace Game { namespace UI { namespace Menu_Pickaxe {

class ConsoleScreen_PickAxe_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_Pickaxe/ConsoleScreen_PickAxe", "ConsoleScreen_PickAxe_C");
    using ConsoleScreen_BGtemplate_C = Game::UI::HUD_SpaceRig::ConsoleScreen_BGtemplate_C;
    using ConsoleScreen_Notification_C = Game::UI::HUD_SpaceRig::ConsoleScreen_Notification_C;
    FPointerToUberGraphFrame UberGraphFrame;
    ConsoleScreen_BGtemplate_C* ConsoleScreen_BGtemplate;
    ConsoleScreen_Notification_C* ConsoleScreen_Notification;
    void ExecuteUbergraph_ConsoleScreen_PickAxe(int EntryPoint);
    void OnItemUINotificationChange();
    UE_COSMETIC void Construct();
};

}}}   // namespace Game::UI::Menu_Pickaxe

using ConsoleScreen_PickAxe_C = Game::UI::Menu_Pickaxe::ConsoleScreen_PickAxe_C;