#pragma once
/*
Blueprint class CP_Oktoberfest_Leatherhosen_Outfit_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../FSD.h"

namespace Game { namespace GameElements { namespace Campaign {

class CP_Oktoberfest_Leatherhosen_Outfit_C : public UCampaign
{
public:
    UE_CLASS("/Game/GameElements/Campaign/CP_Oktoberfest_Leatherhosen_Outfit", "CP_Oktoberfest_Leatherhosen_Outfit_C");
private:
    struct UeMarkers
    {
        static constexpr const char* UeDefaultSubobjects = "/Script/FSD.CamapaignCompletedRequirement CamapaignCompletedRequirement_0;/Script/FSD.CampaignMission CampaignMission_0;/Script/FSD.CampaignMission CampaignMission_1;/Script/FSD.CampaignMission CampaignMission_2;/Script/FSD.CampaignMission CampaignMission_4;/Script/FSD.CampaignMission CampaignMission_5;/Script/FSD.CampaignMission CampaignMission_6;/Script/FSD.ResourceReward CampaignMission_0:ResourceReward_0;/Script/FSD.ResourceReward CampaignMission_1:ResourceReward_0;/Script/FSD.ResourceReward CampaignMission_2:ResourceReward_0;/Script/FSD.ResourceReward CampaignMission_4:ResourceReward_0;/Script/FSD.ResourceReward CampaignMission_5:ResourceReward_0;/Script/FSD.VanityReward CampaignMission_6:VanityReward_0;/Script/FSD.VanityReward CampaignMission_6:VanityReward_1;/Script/FSD.VanityReward CampaignMission_6:VanityReward_2;/Script/FSD.VanityReward CampaignMission_6:VanityReward_3";
    };
};

}}}   // namespace Game::GameElements::Campaign

using CP_Oktoberfest_Leatherhosen_Outfit_C = Game::GameElements::Campaign::CP_Oktoberfest_Leatherhosen_Outfit_C;