#pragma once
/*
Blueprint class DE_BlackoutStout_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class APlayerCharacter;
class UAudioComponent;
class UParticleSystemComponent;

namespace Game { namespace GameElements { namespace Bar { namespace DrinkEffects {

class DE_BlackoutStout_C : public UDrinkEffectComponent
{
public:
    UE_CLASS("/Game/GameElements/Bar/DrinkEffects/DE_BlackoutStout", "DE_BlackoutStout_C");
    FPointerToUberGraphFrame UberGraphFrame;
    bool PEffect;
    class UParticleSystemComponent* Particle_Effect;
    static constexpr const char* Particle_Effect__UeName = "Particle Effect";
    class UAudioComponent* soundComp;
    class UAudioComponent* soundCompDown;
    void ExecuteUbergraph_DE_BlackoutStout(int EntryPoint);
    void OnStopEffect();
    void OnStartEffect(class APlayerCharacter* Character);
};

}}}}   // namespace Game::GameElements::Bar::DrinkEffects

using DE_BlackoutStout_C = Game::GameElements::Bar::DrinkEffects::DE_BlackoutStout_C;