#pragma once
/*
Blueprint class DE_WormholeSpecial_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../FSD.h"

class APlayerCharacter;
namespace Game { namespace GameElements { namespace Bar { namespace DrinkEffects { namespace Wormhole_Assets { class BP_WormholeLocation_Base_C; }}}}}

namespace Game { namespace GameElements { namespace Bar { namespace DrinkEffects {

class DE_WormholeSpecial_C : public UDrinkEffectComponent
{
public:
    UE_CLASS("/Game/GameElements/Bar/DrinkEffects/DE_WormholeSpecial", "DE_WormholeSpecial_C");
    using BP_WormholeLocation_Base_C = Game::GameElements::Bar::DrinkEffects::Wormhole_Assets::BP_WormholeLocation_Base_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class APlayerCharacter* Character;
    FTransform On_Start_Transform;
    static constexpr const char* On_Start_Transform__UeName = "On Start Transform";
    BP_WormholeLocation_Base_C* ActiveWormhole;
    void ExecuteUbergraph_DE_WormholeSpecial(int EntryPoint);
    void Disable_Active_Location_Effects();
    static constexpr const char* Disable_Active_Location_Effects__UeName = "Disable Active Location Effects";
    void Spawn_Teleport_Effects();
    static constexpr const char* Spawn_Teleport_Effects__UeName = "Spawn Teleport Effects";
    void OnStopEffect();
    void OnStartEffect(class APlayerCharacter* Character_0);
    void ReceiveTick(float DeltaSeconds);
    void Set_Original_position();
    static constexpr const char* Set_Original_position__UeName = "Set Original position";
    void IsLastActiveWormholeEffect(bool& was_last_effect);
    void Disable_Older_Active_Wormhole_Effects();
    static constexpr const char* Disable_Older_Active_Wormhole_Effects__UeName = "Disable Older Active Wormhole Effects";
};

}}}}   // namespace Game::GameElements::Bar::DrinkEffects

using DE_WormholeSpecial_C = Game::GameElements::Bar::DrinkEffects::DE_WormholeSpecial_C;