#pragma once
/*
Blueprint class DNA_Wheel_MediumComplex_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "DNA_Wheel_Medium_C.h"

namespace Game { namespace GameElements { namespace Missions {

class DNA_Wheel_MediumComplex_C : public Game::GameElements::Missions::DNA_Wheel_Medium_C
{
public:
    UE_CLASS("/Game/GameElements/Missions/DNA_Wheel_MediumComplex", "DNA_Wheel_MediumComplex_C");
};

}}}   // namespace Game::GameElements::Missions

using DNA_Wheel_MediumComplex_C = Game::GameElements::Missions::DNA_Wheel_MediumComplex_C;