#pragma once
/*
Blueprint class ENE_Spider_Tank_Base_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../FSD.h"
#include "ENE_SpiderBase_Large_C.h"

class UArmorHealthDamageComponent;
class UCapsuleComponent;
class UClass;
class UDamageTag;
class UFSDPhysicalMaterial;
class UMaterialInstanceDynamic;
class UPointLightComponent;
class UStatusEffectsComponent;
class UTimelineComponent;

namespace Game { namespace Enemies { namespace Spider { namespace Tank {

class ENE_Spider_Tank_Base_C : public Game::Enemies::Spider::ENE_SpiderBase_Large_C
{
public:
    UE_CLASS("/Game/Enemies/Spider/Tank/ENE_Spider_Tank_Base", "ENE_Spider_Tank_Base_C");
    FPointerToUberGraphFrame UberGraphFrame_ENE_Spider_Tank_Base_C;
    static constexpr const char* UberGraphFrame_ENE_Spider_Tank_Base_C__UeName = "UberGraphFrame";
    class UCapsuleComponent* Capsule;
    static constexpr const char* Capsule__UeScsNode = "ea2102983e2ba74bb8be9200fc3567ba";
    class UArmorHealthDamageComponent* ArmorHealthDamage;
    static constexpr const char* ArmorHealthDamage__UeScsNode = "2db7b4026a894d4da651588223f2b013";
    class UPointLightComponent* Light_BackBody;
    static constexpr const char* Light_BackBody__UeScsNode = "829a152dd78e214ab098bd6167672c06";
    float ButtTurnOff_TurnOffTime_F69DC0FD4B3F86895DBCE39304B9A3BA;
    ETimelineDirection ButtTurnOff__Direction_F69DC0FD4B3F86895DBCE39304B9A3BA;
    class UTimelineComponent* ButtTurnOff;
    class UClass* AcidCloudClass;
    class UStatusEffectsComponent* NewLocalVar_0;
    class UMaterialInstanceDynamic* ButtMaterial;
    FLinearColor ButtInitialColor;
    FLinearColor ButtFinalColor;
    int SelectedSpecialAttack;
    void ExecuteUbergraph_ENE_Spider_Tank_Base(int EntryPoint);
    void DeathDetailedBase(float amount, const FDamageData& DamageData, const TArray<class UDamageTag*>& Tags_0);
    void StartFadeBody();
    void OnDeathBase();
    void OnRagdoll();
    void ButtTurnOff__UpdateFunc();
    void ButtTurnOff__FinishedFunc();
    void GetEnemySpawnedCount(int& SpawnCount);
    void IsWeakPointDeath(class UFSDPhysicalMaterial* Material, bool& IsWeakPoint);
    void CreateButtDynamicMaterial();
    void GetFXMeshScale(float& Scale);
};

}}}}   // namespace Game::Enemies::Spider::Tank

using ENE_Spider_Tank_Base_C = Game::Enemies::Spider::Tank::ENE_Spider_Tank_Base_C;