#pragma once
/*
Blueprint class ENE_Maggot_SplineTrail_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "ENE_Maggot_C.h"

class USplineTrailComponent;

namespace Game { namespace Critters { namespace Maggot {

class ENE_Maggot_SplineTrail_C : public Game::Critters::Maggot::ENE_Maggot_C
{
public:
    UE_CLASS("/Game/Critters/Maggot/ENE_Maggot_SplineTrail", "ENE_Maggot_SplineTrail_C");
    class USplineTrailComponent* SplineTrail;
private:
    struct UeMarkers
    {
        static constexpr const char* UeDefaultSubobjects = "/Script/FSD.DeepPatherFinderCharacterAfflictionComponent Affliction;/Script/FSD.DeepPathfinderMovement PathfinderMovement;/Script/FSD.DeepPathfinderSceneComponent SceneComponent;/Script/FSD.EnemyTemperatureComponent Temperature;/Script/FSD.SimpleHealthComponent HealthComponent;/Script/Engine.SkeletalMeshComponent Mesh;/Script/FSD.StatusEffectsComponent StatusEffects";
        static constexpr const char* SplineTrail__UeScsNode = "657b8c97cee7b742b1c251cdccb1b9c6";
    };
};

}}}   // namespace Game::Critters::Maggot

using ENE_Maggot_SplineTrail_C = Game::Critters::Maggot::ENE_Maggot_SplineTrail_C;