#pragma once
/*
Blueprint class ENE_Spider_Exploding_Radioactive_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "ENE_Spider_Exploding_C.h"

class UClass;

namespace Game { namespace Enemies { namespace Spider { namespace Exploder {

class ENE_Spider_Exploding_Radioactive_C : public Game::Enemies::Spider::Exploder::ENE_Spider_Exploding_C
{
public:
    UE_CLASS("/Game/Enemies/Spider/Exploder/ENE_Spider_Exploding_Radioactive", "ENE_Spider_Exploding_Radioactive_C");
    FPointerToUberGraphFrame UberGraphFrame_ENE_Spider_Exploding_Radioactive_C;
    static constexpr const char* UberGraphFrame_ENE_Spider_Exploding_Radioactive_C__UeName = "UberGraphFrame";
    class UClass* PostExplosionCloudClass;
    void ExecuteUbergraph_ENE_Spider_Exploding_Radioactive(int EntryPoint);
    void DamageAndCarve();
};

}}}}   // namespace Game::Enemies::Spider::Exploder

using ENE_Spider_Exploding_Radioactive_C = Game::Enemies::Spider::Exploder::ENE_Spider_Exploding_Radioactive_C;