#pragma once
/*
Blueprint class ENE_Spider_Grunt_Base_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "ENE_SpiderBase_Large_C.h"

class USphereComponent;

namespace Game { namespace Enemies { namespace Spider { namespace Grunt {

class ENE_Spider_Grunt_Base_C : public Game::Enemies::Spider::ENE_SpiderBase_Large_C
{
public:
    UE_CLASS("/Game/Enemies/Spider/Grunt/ENE_Spider_Grunt_Base", "ENE_Spider_Grunt_Base_C");
    FPointerToUberGraphFrame UberGraphFrame_ENE_Spider_Grunt_Base_C;
    static constexpr const char* UberGraphFrame_ENE_Spider_Grunt_Base_C__UeName = "UberGraphFrame";
    class USphereComponent* Sphere;
    static constexpr const char* Sphere__UeScsNode = "4518becc93b4614aae8f64164d55cbbb";
    void ExecuteUbergraph_ENE_Spider_Grunt_Base(int EntryPoint);
    void OnRagdoll();
    UE_PURE bool GetIsTargetable() const;
};

}}}}   // namespace Game::Enemies::Spider::Grunt

using ENE_Spider_Grunt_Base_C = Game::Enemies::Spider::Grunt::ENE_Spider_Grunt_Base_C;