#pragma once
/*
Blueprint class ENE_Ossiran_Scrab_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class AActor;
class ACrossbowProjectileStuck;
class UAnimSequenceBase;
class UArmorHealthDamageComponent;
class UDamageTag;
class UFXSystemAsset;
class UHealthComponent;
class UHealthComponentBase;
class UMaterialInterface;
class UMeleeAttackComponent;
class UNiagaraSystem;
class UParticleSystem;
class USoundBase;
class USoundCue;
class USphereComponent;
class UTimelineComponent;

namespace Game { namespace Enemies { namespace Ossiran { namespace Scrab {

class ENE_Ossiran_Scrab_C : public AScrab
{
public:
    UE_CLASS("/Game/Enemies/Ossiran/Scrab/ENE_Ossiran_Scrab", "ENE_Ossiran_Scrab_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class USphereComponent* Sphere;
    class UArmorHealthDamageComponent* ArmorHealthDamage;
    class UMeleeAttackComponent* DiveAttack;
    class UMeleeAttackComponent* ChargeAttack;
    float EmissiveDarken_EmissiveMultiplier_DC93D11547B4F33874A299B7924D16C5;
    TEnum<ETimelineDirection> EmissiveDarken__Direction_DC93D11547B4F33874A299B7924D16C5;
    class UTimelineComponent* EmissiveDarken;
    float DecalSize;
    class USoundBase* AlertedScream;
    class UFXSystemAsset* deathParticles;
    float DeathDuration;
    class USoundCue* deathSound;
    class USoundBase* FleeSound;
    class UMaterialInterface* DeathSplatDecal;
    TArray<class UAnimSequenceBase*> HitReactionsGrounded;
    TArray<class UAnimSequenceBase*> HitReactionsFlying;
    class UNiagaraSystem* GibParticles;
    float DissolveDelay;
    FTimerHandle RagdollTimer;
    class UParticleSystem* ChemExplosionParticles;
    float DeathEmissive;
    void ExecuteUbergraph_ENE_Ossiran_Scrab(int EntryPoint);
    void OnFrozen(class AActor* Source);
    void ReceiveDestroyed();
    void DeathPlasmaExplosion();
    void DeathGibbed();
    void DeathChemicalExplosion();
    void DeathCooked();
    void DeathCorrosive();
    void DeathFrozen();
    void DeathExploded();
    void DeathBurned();
    void DeathWeakpoint();
    void StartDissolve();
    void DissolveAfterRagdoll();
    UE_AUTHORITY_ONLY void BndEvt__ENE_Ossiran_Scrab_HealthComponent_K2Node_ComponentBoundEvent_1_DeathSigDetailed__DelegateSignature(class UHealthComponent* HealthComponent_0, float damageAmount, const FDamageData& DamageData, const TArray<class UDamageTag*>& Tags_0);
    void ReceiveStopFly();
    void ReceiveBeginFly();
    void OnStartedFleeing();
    void BndEvt__ENE_Ossiran_Scrab_HealthComponent_K2Node_ComponentBoundEvent_0_DeathSig__DelegateSignature(class UHealthComponentBase* HealthComponent_0);
    void EmissiveDarken__UpdateFunc();
    void EmissiveDarken__FinishedFunc();
    void PlayDeathFX();
    void OnRep_DeathType();
    void CalculateDissolveDelay(float& Delay);
    void SetBurnMaterialSettings();
    void FindChemicalArrow(class ACrossbowProjectileStuck*& ChemicalArrow);
private:
    struct UeMarkers
    {
        static constexpr const char* UeDefaultSubobjects = "/Script/Engine.AudioComponent WingAudio;/Script/FSD.DeepPatherFinderCharacterAfflictionComponent Affliction;/Script/FSD.DeepPathfinderMovement PathfinderMovement;/Script/FSD.DeepPathfinderSceneComponent SceneComponent;/Script/FSD.EnemyComponent Enemy;/Script/FSD.EnemyHealthComponent HealthComponent;/Script/FSD.EnemyTemperatureComponent Temperature;/Script/FSD.FrozenPawnImpactComponent FrozenImpact;/Script/FSD.HitReactionComponent HitReactions;/Script/FSD.IKComponent IK;/Script/FSD.OutlineComponent Outline;/Script/FSD.PathfinderReactiveTerrainTrackerComponent PathfinderReactiveTerrainTracker;/Script/FSD.PawnAlertComponent Alert;/Script/AIModule.PawnSensingComponent PawnSensing;/Script/FSD.PawnStatsComponent PawnStats;/Script/Engine.SkeletalMeshComponent Mesh;/Script/FSD.StatusEffectsComponent StatusEffects;/Script/FSD.WalkAndFlyEnemyComponent WalkAndFly";
        static constexpr const char* Sphere__UeScsNode = "aaf5124d5dba2844a2023558ef3a7412";
        static constexpr const char* ArmorHealthDamage__UeScsNode = "f7b440701bcb6346bf6323e972a7af47";
        static constexpr const char* DiveAttack__UeScsNode = "1ece54e2a228cf41b913e0e0ef456c7d";
        static constexpr const char* ChargeAttack__UeScsNode = "bdc25d67fe157649bd32c329a40b5ab6";
    };
};

}}}}   // namespace Game::Enemies::Ossiran::Scrab

using ENE_Ossiran_Scrab_C = Game::Enemies::Ossiran::Scrab::ENE_Ossiran_Scrab_C;