#pragma once
/*
Blueprint class ENE_Prospector_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../FSD.h"
#include "../GameplayTags.h"

class AActor;
class AFSDPawn;
class APawn;
class UAlignEnemyComponent;
class UArmorHealthDamageComponent;
class UAudioComponent;
class UCapsuleComponent;
class UEnemyComponent;
class UHealthComponentBase;
class UHealthDamageTracker;
class UMaterialInterface;
class UNiagaraComponent;
class UOutlineComponent;
class UParticleSystemComponent;
class UPawnSensingComponent;
class UPawnStatsComponent;
class UPointLightComponent;
class URectLightComponent;
class UResourceData;
class USkeletalMeshComponent;
class UStaticMeshComponent;
class UWeakpointGlowComponent;
namespace Game { namespace Critters { namespace Prospector { class AIC_Prospector_C; }}}

namespace Game { namespace Critters { namespace Prospector {

class ENE_Prospector_C : public AProspectorRobot
{
public:
    UE_CLASS("/Game/Critters/Prospector/ENE_Prospector", "ENE_Prospector_C");
    using AIC_Prospector_C = Game::Critters::Prospector::AIC_Prospector_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class USkeletalMeshComponent* ShieldMesh;
    class UNiagaraComponent* NS_Idle;
    class UNiagaraComponent* NS_Trail;
    class UNiagaraComponent* Niagara_RadioWaves;
    class UAudioComponent* ProspectingAlarmedIdle_Cue;
    class UAudioComponent* ProspectingDroneStartSampling_Cue;
    class UAudioComponent* ProspectingDroneScreamAlerted_Cue;
    class UAudioComponent* Prospector_Idle_Cue;
    class UAudioComponent* ProspectingDroneStartScanning_Cue;
    class UCapsuleComponent* Capsule;
    class UParticleSystemComponent* Particles_Dirt;
    class UHealthDamageTracker* HealthDamageTracker;
    class UPointLightComponent* PointLight_Eye;
    class URectLightComponent* Light_Exhausts;
    class URectLightComponent* Light_Engine;
    class UPointLightComponent* PointLight_Weakpoint_L;
    class UPointLightComponent* PointLight_Weakpoint_R;
    class UOutlineComponent* outline;
    class UStaticMeshComponent* SM_LightCone001;
    class UWeakpointGlowComponent* WeakpointGlow;
    class UArmorHealthDamageComponent* ArmorHealthDamage;
    class UAlignEnemyComponent* AlignEnemy;
    class UEnemyComponent* enemy;
    class UPawnSensingComponent* PawnSensing;
    class UPawnStatsComponent* PawnStats;
    int WeakpointsLeft;
    class AActor* Target_0;
    bool HasBeenHacked;
    float CooldownDuration;
    int DirtSamplesTaken;
    int MaxDirtSamples;
    FVector2D ChunkValueRange;
    TArray<class UResourceData*> ResourceTypes;
    class UAudioComponent* NewVar_0;
    float ReinforcementsAllowed;
    FTimerHandle SamplingCarveTimer;
    FVector SamplingLocation;
    TArray<class UMaterialInterface*> LightMaterials;
    float AlarmDuration;
    bool BossFightActive;
    FGameplayTagContainer DroneTag;
    bool Shielded;
    float ReinforcementDelay;
    float ReinforcementCooldown;
    TArray<class AFSDPawn*> SpawnedPatrolBots;
    bool SpawnLimitExceeded;
    int SpawnLimit;
    int PatrolBotDifficulty;
    float LimitTimer;
    bool ShouldSpawnDataCell;
    void ExecuteUbergraph_ENE_Prospector(int EntryPoint);
    void SetPhysicsAsset(bool ArmPhysics);
    void OnDeathEvent(class UHealthComponentBase* HealthComponent_0);
    void OnEnemySpawned(class APawn* enemy_0);
    void SpawnDrones(int PatrolBotAmount, int ShredderAmount);
    void TriggerCooldown();
    void ResetSpawn();
    void SmapleCarve();
    void BndEvt__HealthDamageTracker_K2Node_ComponentBoundEvent_0_DamageSig__DelegateSignature(float amount);
    void BndEvt__ArmorHealthDamage_K2Node_ComponentBoundEvent_1_AmorPartDestroyedDelegate__DelegateSignature(FName Name_0);
    void ToggleSampling(bool Active);
    void OnStateEnd(TEnum<EProspectorRobotState> oldState);
    void OnStateBegin(TEnum<EProspectorRobotState> NewState);
    void EjectDataCore();
    void SetNewTaget(class AActor* Target_0);
    void ReceiveBeginPlay();
    void BndEvt__HealthComponent_K2Node_ComponentBoundEvent_9_DeathSig__DelegateSignature(class UHealthComponentBase* HealthComponent_0);
    void BndEvt__PawnSensing_K2Node_ComponentBoundEvent_8_SeePawnDelegate__DelegateSignature(class APawn* Pawn);
    void ToggleScanning(bool IsScanning);
    void BndEvt__HealthComponent_K2Node_ComponentBoundEvent_2_HitSig__DelegateSignature(float Damage, const FDamageData& DamageData, bool anyHealthLost);
    void GetAIController(AIC_Prospector_C*& AsAIC_Prospector);
    void OnRep_Target();
    void SpawnReinforcements(int PatrolBotAmount, int ShredderAmount);
    void Spawn_Dirt_Samples();
    void AddDirtSample();
    void SetupResources();
    void SetupGameplayTags(TArray<FGameplayTag>& TagsToAdd, TArray<FGameplayTag>& TagsToRemove);
    void TriggerAlarmedFeedback(bool BlinkLights);
    void ToggleBossFight(bool IsActive);
    void CheckForDamageCause(class AActor* DamageCauser, bool& ShouldReact);
    void SetUpWeakpointGlowAndMaterial();
    void OnRep_Shielded();
    void SetPatrolBotSpawnLimit();
    void SetSpawnDifficulty(int NumAdditionalPlayers);
    UE_PURE bool GetIsTargetable() const;
private:
    struct UeMarkers
    {
        static constexpr const char* UeDefaultSubobjects = "/Script/FSD.DeepPatherFinderCharacterAfflictionComponent Affliction;/Script/FSD.DeepPathfinderMovement PathfinderMovement;/Script/FSD.DeepPathfinderSceneComponent SceneComponent;/Script/FSD.EnemyHealthComponent HealthComponent;/Script/FSD.EnemyTemperatureComponent Temperature;/Script/Engine.SkeletalMeshComponent Mesh;/Script/FSD.StatusEffectsComponent StatusEffects";
        static constexpr const char* ShieldMesh__UeScsNode = "3a9d58a8936ebb45ab82992633368194";
        static constexpr const char* NS_Idle__UeScsNode = "06fe95d7b9bf724d99025e6fab65e8a6";
        static constexpr const char* NS_Trail__UeScsNode = "4cc581d4bbbe3640982f80b98bdf4bef";
        static constexpr const char* Niagara_RadioWaves__UeScsNode = "e243d38556214941976afcaf84587795";
        static constexpr const char* ProspectingAlarmedIdle_Cue__UeScsNode = "1b32beb3c1689e4cbc456f96a7f9c268";
        static constexpr const char* ProspectingDroneStartSampling_Cue__UeScsNode = "0e24dfbcc432ba4395453723eb281a3a";
        static constexpr const char* ProspectingDroneScreamAlerted_Cue__UeScsNode = "e576ac6f916dba479536bed99060571b";
        static constexpr const char* Prospector_Idle_Cue__UeScsNode = "5269d77d5753c147870f0ce71ff46ed4";
        static constexpr const char* ProspectingDroneStartScanning_Cue__UeScsNode = "456e3a6c4a9e854b938e61f39da1f42b";
        static constexpr const char* Capsule__UeScsNode = "594f451548c0ce43b9a41392d47bc9bc";
        static constexpr const char* Particles_Dirt__UeScsNode = "3c92293972baf242a86b2267605c7b38";
        static constexpr const char* HealthDamageTracker__UeScsNode = "63b5597d3066274d8cfc77ec079fe971";
        static constexpr const char* PointLight_Eye__UeScsNode = "64e7693e5eb3c84099c288e31546b282";
        static constexpr const char* Light_Exhausts__UeScsNode = "5dfcc2f6040b2748b3e13600374ceda1";
        static constexpr const char* Light_Engine__UeScsNode = "c9522993adc36047a9c329d05dfd5dae";
        static constexpr const char* PointLight_Weakpoint_L__UeScsNode = "86f7d6733f3ef94388b3da6bf313eedc";
        static constexpr const char* PointLight_Weakpoint_R__UeScsNode = "c8ee04d51ec2824189d1b353b77d6b2f";
        static constexpr const char* outline__UeScsNode = "63eda70620b33942a35e7788e11b1701";
        static constexpr const char* SM_LightCone001__UeScsNode = "6d6dd39dcd86f54a8c5982ab7dc249a8";
        static constexpr const char* WeakpointGlow__UeScsNode = "5352a6ade5b48d48b7a0fecf0967c7c5";
        static constexpr const char* ArmorHealthDamage__UeScsNode = "84c433c4d1838845bea2a9d02618c7a5";
        static constexpr const char* AlignEnemy__UeScsNode = "7c25f854777268489d51c5d042edcb17";
        static constexpr const char* enemy__UeScsNode = "78c989096952724ea9377bf77bb44787";
        static constexpr const char* PawnSensing__UeScsNode = "2aaf39c38e0c8f4da682d32d219854d3";
        static constexpr const char* PawnStats__UeScsNode = "d4d75d6884bae6459261775e154a23b3";
        static constexpr const char* Target_0__Replicated = "OnRep_Target:";
        static constexpr const char* Shielded__Replicated = "OnRep_Shielded:";
        static constexpr const char* Spawn_Dirt_Samples__UeName = "Spawn Dirt Samples";
    };
};

}}}   // namespace Game::Critters::Prospector

using ENE_Prospector_C = Game::Critters::Prospector::ENE_Prospector_C;