#pragma once
/*
Blueprint class ENE_Maggot_Green1_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "ENE_Maggot_C.h"

namespace Game { namespace Critters { namespace Maggot {

class ENE_Maggot_Green1_C : public Game::Critters::Maggot::ENE_Maggot_C
{
public:
    UE_CLASS("/Game/Critters/Maggot/ENE_Maggot_Green1", "ENE_Maggot_Green1_C");
    FPointerToUberGraphFrame UberGraphFrame_ENE_Maggot_Green1_C;
    void ExecuteUbergraph_ENE_Maggot_Green1(int EntryPoint);
    void Died();
private:
    struct UeMarkers
    {
        static constexpr const char* UeDefaultSubobjects = "/Script/FSD.DeepPatherFinderCharacterAfflictionComponent Affliction;/Script/FSD.DeepPathfinderMovement PathfinderMovement;/Script/FSD.DeepPathfinderSceneComponent SceneComponent;/Script/FSD.EnemyTemperatureComponent Temperature;/Script/FSD.SimpleHealthComponent HealthComponent;/Script/Engine.SkeletalMeshComponent Mesh;/Script/FSD.StatusEffectsComponent StatusEffects";
        static constexpr const char* UberGraphFrame_ENE_Maggot_Green1_C__UeName = "UberGraphFrame";
    };
};

}}}   // namespace Game::Critters::Maggot

using ENE_Maggot_Green1_C = Game::Critters::Maggot::ENE_Maggot_Green1_C;