#pragma once
/*
Blueprint class ENE_Jelly_Spawn_Child_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "ENE_Jelly_Swarmer_C.h"

class UMeleeAttackComponent;

namespace Game { namespace Enemies { namespace Jellyfish {

class ENE_Jelly_Spawn_Child_C : public Game::Enemies::Jellyfish::ENE_Jelly_Swarmer_C
{
public:
    UE_CLASS("/Game/Enemies/Jellyfish/ENE_Jelly_Spawn_Child", "ENE_Jelly_Spawn_Child_C");
    class UMeleeAttackComponent* MeleeAttack;
    static constexpr const char* MeleeAttack__UeScsNode = "c0d02f9c72d6ca42b415db7daa6d5122";
};

}}}   // namespace Game::Enemies::Jellyfish

using ENE_Jelly_Spawn_Child_C = Game::Enemies::Jellyfish::ENE_Jelly_Spawn_Child_C;