#pragma once
/*
Blueprint class ENE_Spider_Shooter_Normal_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "ENE_Spider_Shooter_C.h"

class UProjectileAttackComponent;

namespace Game { namespace Enemies { namespace Spider { namespace Shooter {

class ENE_Spider_Shooter_Normal_C : public Game::Enemies::Spider::Shooter::ENE_Spider_Shooter_C
{
public:
    UE_CLASS("/Game/Enemies/Spider/Shooter/ENE_Spider_Shooter_Normal", "ENE_Spider_Shooter_Normal_C");
    class UProjectileAttackComponent* ProjectileAttack;
    static constexpr const char* ProjectileAttack__UeScsNode = "5672d442fce46048aaa2694dd112bc96";
};

}}}}   // namespace Game::Enemies::Spider::Shooter

using ENE_Spider_Shooter_Normal_C = Game::Enemies::Spider::Shooter::ENE_Spider_Shooter_Normal_C;