#pragma once
/*
Blueprint class ENE_Spider_Grunt_Attacker_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "ENE_Spider_Grunt_Base_C.h"

class UMeleeAttackComponent;
class USimpleArmorDamageComponent;

namespace Game { namespace Enemies { namespace Spider { namespace Grunt { namespace Attacker {

class ENE_Spider_Grunt_Attacker_C : public Game::Enemies::Spider::Grunt::ENE_Spider_Grunt_Base_C
{
public:
    UE_CLASS("/Game/Enemies/Spider/Grunt/Attacker/ENE_Spider_Grunt_Attacker", "ENE_Spider_Grunt_Attacker_C");
    FPointerToUberGraphFrame UberGraphFrame_ENE_Spider_Grunt_Attacker_C;
    static constexpr const char* UberGraphFrame_ENE_Spider_Grunt_Attacker_C__UeName = "UberGraphFrame";
    class UMeleeAttackComponent* MeleeAttack;
    static constexpr const char* MeleeAttack__UeScsNode = "89981e8acc005b428bd16c9d22ae76b3";
    class USimpleArmorDamageComponent* SimpleArmorDamage;
    static constexpr const char* SimpleArmorDamage__UeScsNode = "24dd3dc95610b942b1673844c462eff4";
    void ExecuteUbergraph_ENE_Spider_Grunt_Attacker(int EntryPoint);
    void MakeElite();
};

}}}}}   // namespace Game::Enemies::Spider::Grunt::Attacker

using ENE_Spider_Grunt_Attacker_C = Game::Enemies::Spider::Grunt::Attacker::ENE_Spider_Grunt_Attacker_C;