#pragma once
/*
Blueprint class ESI_Mactera_TripleShooter_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../FSD.h"

class USceneComponent;
class USkeletalMeshComponent;

namespace Game { namespace Enemies { namespace FlyingBug { namespace Shooter {

class ESI_Mactera_TripleShooter_C : public AEnemyShowroomItem
{
public:
    UE_CLASS("/Game/Enemies/FlyingBug/Shooter/ESI_Mactera_TripleShooter", "ESI_Mactera_TripleShooter_C");
    class USkeletalMeshComponent* SkeletalMesh;
    static constexpr const char* SkeletalMesh__UeScsNode = "6bf23ae8fee94a45bd6da9e1a6fa0785";
    class USceneComponent* DefaultSceneRoot;
    static constexpr const char* DefaultSceneRoot__UeScsNode = "633896c7fe35264c9cc037a12bc437c8";
};

}}}}   // namespace Game::Enemies::FlyingBug::Shooter

using ESI_Mactera_TripleShooter_C = Game::Enemies::FlyingBug::Shooter::ESI_Mactera_TripleShooter_C;