#pragma once
/*
Blueprint class ESI_Bomber_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../FSD.h"

class USceneComponent;
class USkeletalMeshComponent;

namespace Game { namespace Enemies { namespace FlyingBug { namespace Bomber {

class ESI_Bomber_C : public AEnemyShowroomItem
{
public:
    UE_CLASS("/Game/Enemies/FlyingBug/Bomber/ESI_Bomber", "ESI_Bomber_C");
    class USkeletalMeshComponent* SkeletalMesh;
    static constexpr const char* SkeletalMesh__UeScsNode = "7c4f9515c4ff99479c086aef6df6858c";
    class USceneComponent* DefaultSceneRoot;
    static constexpr const char* DefaultSceneRoot__UeScsNode = "0a601a00a04cca41bf1e7db92ffd441b";
};

}}}}   // namespace Game::Enemies::FlyingBug::Bomber

using ESI_Bomber_C = Game::Enemies::FlyingBug::Bomber::ESI_Bomber_C;