#pragma once
/*
Blueprint class ESI_BoneCollector_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../FSD.h"

class USceneComponent;
class USkeletalMeshComponent;

namespace Game { namespace GameElements { namespace GameEvents { namespace TunnelEvent { namespace Enemies {

class ESI_BoneCollector_C : public AEnemyShowroomItem
{
public:
    UE_CLASS("/Game/GameElements/GameEvents/TunnelEvent/Enemies/ESI_BoneCollector", "ESI_BoneCollector_C");
    class USkeletalMeshComponent* SK_BoneCollector;
    static constexpr const char* SK_BoneCollector__UeScsNode = "97e9fe746866a14b932a890a4af13cb5";
    class USceneComponent* DefaultSceneRoot;
    static constexpr const char* DefaultSceneRoot__UeScsNode = "f72ef8b3ab915b438027560509f002a2";
};

}}}}}   // namespace Game::GameElements::GameEvents::TunnelEvent::Enemies

using ESI_BoneCollector_C = Game::GameElements::GameEvents::TunnelEvent::Enemies::ESI_BoneCollector_C;