#pragma once
/*
Blueprint class EVENT_DropPodDefense_Uplink_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "EVENT_DropPodDefense_Base_C.h"

namespace Game { namespace GameElements { namespace Objectives { namespace Salvage {

class EVENT_DropPodDefense_Uplink_C : public Game::GameElements::Objectives::Salvage::EVENT_DropPodDefense_Base_C
{
public:
    UE_CLASS("/Game/GameElements/Objectives/Salvage/EVENT_DropPodDefense_Uplink", "EVENT_DropPodDefense_Uplink_C");
    FPointerToUberGraphFrame UberGraphFrame_EVENT_DropPodDefense_Uplink_C;
    static constexpr const char* UberGraphFrame_EVENT_DropPodDefense_Uplink_C__UeName = "UberGraphFrame";
    void ExecuteUbergraph_EVENT_DropPodDefense_Uplink(int EntryPoint);
    void EventFailed();
    void EventSucceded();
};

}}}}   // namespace Game::GameElements::Objectives::Salvage

using EVENT_DropPodDefense_Uplink_C = Game::GameElements::Objectives::Salvage::EVENT_DropPodDefense_Uplink_C;