#pragma once
/*
Blueprint class EWC_Excavation_LaunchPhase_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "EWC_Base_C.h"

namespace Game { namespace Enemies { namespace Waves { namespace WaveControllers {

class EWC_Excavation_LaunchPhase_C : public Game::Enemies::Waves::WaveControllers::EWC_Base_C
{
public:
    UE_CLASS("/Game/Enemies/Waves/WaveControllers/EWC_Excavation_LaunchPhase", "EWC_Excavation_LaunchPhase_C");
    FPointerToUberGraphFrame UberGraphFrame_EWC_Excavation_LaunchPhase_C;
    static constexpr const char* UberGraphFrame_EWC_Excavation_LaunchPhase_C__UeName = "UberGraphFrame";
    TArray<FVector> SpawnLocations;
    void ExecuteUbergraph_EWC_Excavation_LaunchPhase(int EntryPoint);
    void StartWave();
};

}}}}   // namespace Game::Enemies::Waves::WaveControllers

using EWC_Excavation_LaunchPhase_C = Game::Enemies::Waves::WaveControllers::EWC_Excavation_LaunchPhase_C;