#pragma once
/*
Blueprint class EWC_Base_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class UObject;
class USoundCue;

namespace Game { namespace Enemies { namespace Waves { namespace WaveControllers {

class EWC_Base_C : public UEnemyWaveController
{
public:
    UE_CLASS("/Game/Enemies/Waves/WaveControllers/EWC_Base", "EWC_Base_C");
    FPointerToUberGraphFrame UberGraphFrame;
    TArray<TSoftObjectPtr<class USoundCue>> Music;
    FMusicHandle MusicHandle;
    void ExecuteUbergraph_EWC_Base(int EntryPoint);
    void StopWaveMusac();
    void PlayEndWaveMusic();
    void PlayWaveMusac();
    void OnLoaded_8674B549482B9237DC5FDA94C82046A5(class UObject* Loaded);
    void OnLoaded_8674B549482B9237DC5FDA941DC11E00(class UObject* Loaded);
};

}}}}   // namespace Game::Enemies::Waves::WaveControllers

using EWC_Base_C = Game::Enemies::Waves::WaveControllers::EWC_Base_C;