#pragma once
/*
Blueprint class Grenade_PlasmaBoomerang_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../FSD.h"

class UParticleSystemComponent;
class UUpgradableGearComponent;

namespace Game { namespace WeaponsNTools { namespace Grenades { namespace PlasmaBoomerang {

class Grenade_PlasmaBoomerang_C : public APlasmaBoomerang
{
public:
    UE_CLASS("/Game/WeaponsNTools/Grenades/PlasmaBoomerang/Grenade_PlasmaBoomerang", "Grenade_PlasmaBoomerang_C");
    static constexpr const char* UeDefaultSubobjects = "/Script/Engine.BoxComponent Box;/Script/FSD.DamageComponent Damage;/Script/Engine.ProjectileMovementComponent ProjectileMovement;/Script/Engine.SceneComponent MeshPivot;/Script/Engine.SceneComponent Root;/Script/Engine.StaticMeshComponent Mesh";
    class UUpgradableGearComponent* UpgradableGear;
    static constexpr const char* UpgradableGear__UeScsNode = "40e6c27bfc41224db0a577fa0720b8fa";
    class UParticleSystemComponent* P_GrenadeTrail;
    static constexpr const char* P_GrenadeTrail__UeScsNode = "53a9d459d375314ab6c9df727187d2d5";
};

}}}}   // namespace Game::WeaponsNTools::Grenades::PlasmaBoomerang

using Grenade_PlasmaBoomerang_C = Game::WeaponsNTools::Grenades::PlasmaBoomerang::Grenade_PlasmaBoomerang_C;