#pragma once
/*
Blueprint class HUD_PlayerDrone_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"
#include "../SlateCore.h"

class UTextBlock;

namespace Game { namespace GameElements { namespace MovieMode { namespace UI {

class HUD_PlayerDrone_C : public UWindowWidget
{
public:
    UE_CLASS("/Game/GameElements/MovieMode/UI/HUD_PlayerDrone", "HUD_PlayerDrone_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UTextBlock* countdownText;
    float CountDownTimer;
    void ExecuteUbergraph_HUD_PlayerDrone(int EntryPoint);
    UE_COSMETIC void Tick(FGeometry MyGeometry, float InDeltaTime);
};

}}}}   // namespace Game::GameElements::MovieMode::UI

using HUD_PlayerDrone_C = Game::GameElements::MovieMode::UI::HUD_PlayerDrone_C;