#pragma once
/*
Blueprint class HUD_CoolDownBar_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../SlateCore.h"
#include "../UMG.h"

class AItem;
class UCoolDownItemAggregator;
class UImage;

namespace Game { namespace WeaponsNTools { namespace _Crosshairs {

class HUD_CoolDownBar_C : public UUserWidget
{
public:
    UE_CLASS("/Game/WeaponsNTools/_Crosshairs/HUD_CoolDownBar", "HUD_CoolDownBar_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UImage* Progress100;
    class UImage* Progress25;
    class UImage* Progress50;
    class UImage* Progress75;
    TArray<class UImage*> ProgressImages;
    class UCoolDownItemAggregator* CoolDownAggregator;
    int CurrentProgress;
    int OldProgress;
    class AItem* Item;
    void ExecuteUbergraph_HUD_CoolDownBar(int EntryPoint);
    void OnItemSet();
    void OnEquipped();
    void On_UnEquipped();
    static constexpr const char* On_UnEquipped__UeName = "On UnEquipped";
    void ProgressSound();
    UE_COSMETIC void Tick(FGeometry MyGeometry, float InDeltaTime);
    UE_COSMETIC void Construct();
    void Initialize(class UCoolDownItemAggregator* CoolDown, class AItem* Item_0);
};

}}}   // namespace Game::WeaponsNTools::_Crosshairs

using HUD_CoolDownBar_C = Game::WeaponsNTools::_Crosshairs::HUD_CoolDownBar_C;