#pragma once
/*
Blueprint class HUD_Facility_Objective_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class UFacilityObjective;
class UObjective;
class UOverlay;
namespace Game { namespace GameElements { namespace Objectives { namespace Facility { namespace UI { class UI_Facility_Objective_Caretaker_C; class UI_Facility_Objective_PowerStation_C; class UI_Facility_Objective_ShieldEmitter_C; }}}}}
namespace Game { namespace UI { namespace MainOnscreenHUD { namespace Standard { class UI_ImageTinted_C; }}}}

namespace Game { namespace GameElements { namespace Objectives { namespace Facility { namespace UI {

class HUD_Facility_Objective_C : public UOptionalObjectiveWidget
{
public:
    UE_CLASS("/Game/GameElements/Objectives/Facility/UI/HUD_Facility_Objective", "HUD_Facility_Objective_C");
    using UI_Facility_Objective_Caretaker_C = Game::GameElements::Objectives::Facility::UI::UI_Facility_Objective_Caretaker_C;
    using UI_Facility_Objective_PowerStation_C = Game::GameElements::Objectives::Facility::UI::UI_Facility_Objective_PowerStation_C;
    using UI_Facility_Objective_ShieldEmitter_C = Game::GameElements::Objectives::Facility::UI::UI_Facility_Objective_ShieldEmitter_C;
    using UI_ImageTinted_C = Game::UI::MainOnscreenHUD::Standard::UI_ImageTinted_C;
    FPointerToUberGraphFrame UberGraphFrame;
    UI_ImageTinted_C* Background;
    UI_Facility_Objective_Caretaker_C* Caretaker;
    UI_Facility_Objective_PowerStation_C* PowerStation_Left;
    UI_Facility_Objective_PowerStation_C* PowerStation_Right;
    class UOverlay* RootOverlay;
    UI_Facility_Objective_ShieldEmitter_C* ShieldEmitter;
    class UFacilityObjective* Objective;
    void ExecuteUbergraph_HUD_Facility_Objective(int EntryPoint);
    void SetObjective(class UObjective* obj);
};

}}}}}   // namespace Game::GameElements::Objectives::Facility::UI

using HUD_Facility_Objective_C = Game::GameElements::Objectives::Facility::UI::HUD_Facility_Objective_C;