#pragma once
/*
Blueprint class HUD_FieldMedic_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class APlayerCharacter;
class UDownedStateComponent;
class UFloatPerkAsset;
class UUsableComponentBase;
class UWidgetAnimation;
namespace Game { namespace UI { namespace MainOnscreenHUD { class HUD_Hold_Activation_C; }}}

namespace Game { namespace UI { namespace MainOnscreenHUD {

class HUD_FieldMedic_C : public UPerkHUDActivationWidget
{
public:
    UE_CLASS("/Game/UI/MainOnscreenHUD/HUD_FieldMedic", "HUD_FieldMedic_C");
    using HUD_Hold_Activation_C = Game::UI::MainOnscreenHUD::HUD_Hold_Activation_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* AnimIntro;
    HUD_Hold_Activation_C* HUD_Hold_Activation;
    bool Listening;
    class UDownedStateComponent* DownedState;
    class APlayerCharacter* RevivingCharacter;
    void ExecuteUbergraph_HUD_FieldMedic(int EntryPoint);
    void BndEvt__HUD_Hold_Activation_K2Node_ComponentBoundEvent_1_OnHoldingFinished__DelegateSignature();
    void ListenToFirePressed(bool InListen);
    void OnInstantRevivePressed();
    void OnBeginUsing(class UUsableComponentBase* Component);
    void OnEndUsing();
    UE_COSMETIC void Construct();
    void OnEndUsingEvent_Event_0();
    void OnFirePressed();
    void OnBeginUsingEvent_Event_0(class UUsableComponentBase* Component);
    void OnFireReleased();
    void GetPerk(class UFloatPerkAsset*& Perks_FieldMedic);
    void GetInstantRevivablePlayer(class UUsableComponentBase* TargetUseComponent, class APlayerCharacter*& outPlayer);
};

}}}   // namespace Game::UI::MainOnscreenHUD

using HUD_FieldMedic_C = Game::UI::MainOnscreenHUD::HUD_FieldMedic_C;