#pragma once
/*
Blueprint class HUD_Resources_Team_Icon_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../SlateCore.h"
#include "../UMG.h"

class UCappedResource;
class UImage;
class UInvalidationBox;
class UWidgetAnimation;
class UWidgetSwitcher;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_ResourceIcon_C; }}}}
namespace Game { namespace UI { namespace MainOnscreenHUD { namespace Standard { class HUD_DefaultLabel_C; }}}}

namespace Game { namespace UI { namespace MainOnscreenHUD { namespace Resources {

class HUD_Resources_Team_Icon_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/MainOnscreenHUD/Resources/HUD_Resources_Team_Icon", "HUD_Resources_Team_Icon_C");
    using Basic_ResourceIcon_C = Game::UI::Art::WidgetParts::Basic_ResourceIcon_C;
    using HUD_DefaultLabel_C = Game::UI::MainOnscreenHUD::Standard::HUD_DefaultLabel_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* PingAmount;
    class UWidgetSwitcher* AmountSwitcher;
    Basic_ResourceIcon_C* Basic_ResourceIcon;
    class UInvalidationBox* Invalidation;
    HUD_DefaultLabel_C* ResourceAmount;
    class UImage* ResourceCompleted;
    HUD_DefaultLabel_C* ResourceName;
    class UCappedResource* Resource;
    float amount;
    bool HideIfEmpty;
    bool Counting;
    bool Completed;
    void ExecuteUbergraph_HUD_Resources_Team_Icon(int EntryPoint);
    void OnPingAmountFinished();
    UE_COSMETIC void Construct();
    UE_COSMETIC void Tick(FGeometry MyGeometry, float InDeltaTime);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void OnChanged(class UCappedResource* Resource_0, float amount_0);
    void Init_Resource();
    static constexpr const char* Init_Resource__UeName = "Init Resource";
    void SetResource(class UCappedResource* InResource, bool HideIfEmpty_0);
    void UpdateAmount(float DeltaSeconds);
};

}}}}   // namespace Game::UI::MainOnscreenHUD::Resources

using HUD_Resources_Team_Icon_C = Game::UI::MainOnscreenHUD::Resources::HUD_Resources_Team_Icon_C;