#pragma once
/*
Blueprint class HUD_DownedBomb_Activation_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class UDownedStateComponent;
class UWidgetAnimation;
namespace Game { namespace UI { namespace MainOnscreenHUD { class HUD_Hold_Activation_C; }}}

namespace Game { namespace UI { namespace MainOnscreenHUD {

class HUD_DownedBomb_Activation_C : public UPerkHUDActivationWidget
{
public:
    UE_CLASS("/Game/UI/MainOnscreenHUD/HUD_DownedBomb_Activation", "HUD_DownedBomb_Activation_C");
    using HUD_Hold_Activation_C = Game::UI::MainOnscreenHUD::HUD_Hold_Activation_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* AnimIntro;
    HUD_Hold_Activation_C* HUD_Hold_Activation;
    bool PlayerDown;
    class UDownedStateComponent* DownedState;
    void ExecuteUbergraph_HUD_DownedBomb_Activation(int EntryPoint);
    void OnGrenadePressed(bool boolValue);
    void OnEnableDownedBombUIEvent_Event_0(bool Active);
    void BndEvt__HUD_Hold_Activation_K2Node_ComponentBoundEvent_1_OnHoldingFinished__DelegateSignature();
    UE_COSMETIC void Construct();
};

}}}   // namespace Game::UI::MainOnscreenHUD

using HUD_DownedBomb_Activation_C = Game::UI::MainOnscreenHUD::HUD_DownedBomb_Activation_C;