#pragma once
/*
Blueprint class HUD_Radar_AngleMarker_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../UMG.h"

class UImage;
class URadarPointComponent;
class UTextBlock;

namespace Game { namespace UI { namespace Radar {

class HUD_Radar_AngleMarker_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Radar/HUD_Radar_AngleMarker", "HUD_Radar_AngleMarker_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UImage* Image_0;
    class UTextBlock* Text;
    FVector Position;
    FString Name_0;
    static constexpr const char* Name_0__UeName = "Name";
    void ExecuteUbergraph_HUD_Radar_AngleMarker(int EntryPoint);
    UE_COSMETIC void Construct();
    void InitPoint(class URadarPointComponent* RadarComponent, bool& success);
    void Get3dPosition(FVector& Pos);
    void UpdatePoint(float alpha, float verticalDist, bool& destroy);
};

}}}   // namespace Game::UI::Radar

using HUD_Radar_AngleMarker_C = Game::UI::Radar::HUD_Radar_AngleMarker_C;