#pragma once
/*
Blueprint class HUD_PlayerInfection_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../FSD.h"

class UImage;
class UProgressBar;
class USizeBox;
class UWidgetAnimation;

namespace Game { namespace UI { namespace MainOnscreenHUD {

class HUD_PlayerInfection_C : public UFSDUserWidget
{
public:
    UE_CLASS("/Game/UI/MainOnscreenHUD/HUD_PlayerInfection", "HUD_PlayerInfection_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* Appear;
    class UWidgetAnimation* Pulse;
    class UWidgetAnimation* fade;
    class UWidgetAnimation* Warning;
    class UImage* BG;
    class UImage* Glow;
    class UImage* Icon_Temp;
    class USizeBox* RootSize;
    class UProgressBar* TempBar;
    FLinearColor Tint_Infection;
    bool Faded;
    void ExecuteUbergraph_HUD_PlayerInfection(int EntryPoint);
    void OnInfectionStateChangedEvent_Event_0(EInfectionState State);
    void OnInfectionChanged(int IntValue);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    UE_COSMETIC void Construct();
    void UpdateInfection(float InTemperature, float InChange);
    void SetFaded(bool FadeOut);
};

}}}   // namespace Game::UI::MainOnscreenHUD

using HUD_PlayerInfection_C = Game::UI::MainOnscreenHUD::HUD_PlayerInfection_C;