#pragma once
/*
Blueprint class HUD_TabPlayerListEntryV2_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../SlateCore.h"
#include "../UMG.h"

class AFSDPlayerState;
class APlayerCharacter;
class UBorder;
class UNamedSlot;
class UTextBlock;
class UVerticalBox;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class UI_PlayerSpeaking_C; }}}}
namespace Game { namespace UI { namespace Global_UI_Elements { class ITM_CharacterIcon_C; class ITM_HealthBar_C; class ITM_SupplyBar_C; }}}
namespace Game { namespace UI { namespace HUD_SpaceRig { class UI_NameTags_C; }}}

namespace Game { namespace UI { namespace Menu_Tab {

class HUD_TabPlayerListEntryV2_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_Tab/HUD_TabPlayerListEntryV2", "HUD_TabPlayerListEntryV2_C");
    using ITM_CharacterIcon_C = Game::UI::Global_UI_Elements::ITM_CharacterIcon_C;
    using ITM_HealthBar_C = Game::UI::Global_UI_Elements::ITM_HealthBar_C;
    using ITM_SupplyBar_C = Game::UI::Global_UI_Elements::ITM_SupplyBar_C;
    using UI_NameTags_C = Game::UI::HUD_SpaceRig::UI_NameTags_C;
    using UI_PlayerSpeaking_C = Game::UI::Art::WidgetParts::UI_PlayerSpeaking_C;
    FPointerToUberGraphFrame UberGraphFrame;
    ITM_SupplyBar_C* AmmoBar;
    class UBorder* Border_CharacterLevel;
    class UBorder* Border_PlayerRank;
    class UTextBlock* DATA_ClassName;
    class UTextBlock* DATA_PlayerName;
    class UVerticalBox* InfoBox;
    ITM_CharacterIcon_C* ITM_CharacterIcon;
    ITM_HealthBar_C* ITM_HealthBar;
    class UTextBlock* PingText;
    class UNamedSlot* PutStuffHere_Rightside;
    UI_NameTags_C* UI_NameTags;
    UI_PlayerSpeaking_C* UI_PlayerSpeaking;
    class UVerticalBox* VerticalBox_AmmoHealth;
    class AFSDPlayerState* PlayerState;
    FSlateFontInfo NameFont;
    void ExecuteUbergraph_HUD_TabPlayerListEntryV2(int EntryPoint);
    void CharacterChanged(class APlayerCharacter* PlayerCharacter);
    void ShowInfoBar(bool shouldShow);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    UE_COSMETIC void Tick(FGeometry MyGeometry, float InDeltaTime);
    void Set_Data(class AFSDPlayerState* State);
    static constexpr const char* Set_Data__UeName = "Set Data";
    void UpdateVolatileStats();
    void UpdatePlayerClass();
};

}}}   // namespace Game::UI::Menu_Tab

using HUD_TabPlayerListEntryV2_C = Game::UI::Menu_Tab::HUD_TabPlayerListEntryV2_C;