#pragma once
/*
Blueprint class HUD_SentryGunManager_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class APlayerCharacter;
class ARecallableSentryGunItem;
class UHUDVisibilityGroup;
class UHorizontalBox;
class UImage;
class UInventoryComponent;
class UVerticalBox;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_HUD_BracketWindowBig_Single_C; }}}}
namespace Game { namespace UI { namespace Global_UI_Elements { class UI_AdvancedLabel_C; }}}
namespace Game { namespace UI { namespace MainOnscreenHUD { namespace Standard { class HUD_DefaultLabel_C; }}}}
namespace Game { namespace WeaponsNTools { namespace SentryGun { namespace SentryGun_Engineer { class HUD_SentryGunWidget_C; }}}}

namespace Game { namespace WeaponsNTools { namespace SentryGun { namespace SentryGun_Engineer {

class HUD_SentryGunManager_C : public UUserWidget
{
public:
    UE_CLASS("/Game/WeaponsNTools/SentryGun/SentryGun_Engineer/HUD_SentryGunManager", "HUD_SentryGunManager_C");
    using Basic_HUD_BracketWindowBig_Single_C = Game::UI::Art::WidgetParts::Basic_HUD_BracketWindowBig_Single_C;
    using HUD_DefaultLabel_C = Game::UI::MainOnscreenHUD::Standard::HUD_DefaultLabel_C;
    using HUD_SentryGunWidget_C = Game::WeaponsNTools::SentryGun::SentryGun_Engineer::HUD_SentryGunWidget_C;
    using UI_AdvancedLabel_C = Game::UI::Global_UI_Elements::UI_AdvancedLabel_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UHorizontalBox* AmmoHolder;
    HUD_DefaultLabel_C* AmmoLabel;
    Basic_HUD_BracketWindowBig_Single_C* Basic_HUD_BracketWindowBig_Single;
    class UImage* ICON_SentryBG;
    class UImage* ICON_SentryOutline;
    class UHorizontalBox* KeyHolder;
    UI_AdvancedLabel_C* KeyLabel;
    Basic_HUD_BracketWindowBig_Single_C* RecallWindow;
    class UVerticalBox* Root;
    class UInventoryComponent* Inventory;
    class ARecallableSentryGunItem* Item;
    int PreviewSentryCount;
    class UHUDVisibilityGroup* VisibilityGroup;
    TArray<HUD_SentryGunWidget_C*> SentryWidgets;
    class APlayerCharacter* Character;
    bool LaserpointerEquipped;
    void ExecuteUbergraph_HUD_SentryGunManager(int EntryPoint);
    void OnLaserPointerReleased_Event();
    void OnLaserPointerPressed_Event();
    void Setup_Dynamic_Visibility();
    static constexpr const char* Setup_Dynamic_Visibility__UeName = "Setup Dynamic Visibility";
    void OnSentryStateChanged_Event();
    void Update_Dynamic_Visibility();
    static constexpr const char* Update_Dynamic_Visibility__UeName = "Update Dynamic Visibility";
    void OnItemCurrentAmountChanged(int amount);
    void OnActiveItemsChanged(class ARecallableSentryGunItem* Item_0);
    void OnItemsLoaded();
    UE_COSMETIC void Construct();
    void AddSentry(int Index_0);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void OutOfAmmo(bool& OutOfAmmo_0);
    void ItemEquipped(bool& IsEquipped);
};

}}}}   // namespace Game::WeaponsNTools::SentryGun::SentryGun_Engineer

using HUD_SentryGunManager_C = Game::WeaponsNTools::SentryGun::SentryGun_Engineer::HUD_SentryGunManager_C;