#pragma once
/*
Blueprint class HUD_Progressbar_Hacking_Base_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"
#include "HUD_BossFight_BaseEntry_C.h"

class AFacilityHackingPod;
class IBossFightInterface;
class UEnemyTemperatureReplicatorComponent;
class UProgressBar;
class UWidgetAnimation;
namespace Game { namespace UI { namespace MainOnscreenHUD { namespace BossFight { class ITM_BossFightContainer_C; }}}}

namespace Game { namespace UI { namespace MainOnscreenHUD { namespace BossFight {

class HUD_Progressbar_Hacking_Base_C : public Game::UI::MainOnscreenHUD::BossFight::HUD_BossFight_BaseEntry_C
{
public:
    UE_CLASS("/Game/UI/MainOnscreenHUD/BossFight/HUD_Progressbar_Hacking_Base", "HUD_Progressbar_Hacking_Base_C");
    using ITM_BossFightContainer_C = Game::UI::MainOnscreenHUD::BossFight::ITM_BossFightContainer_C;
    FPointerToUberGraphFrame UberGraphFrame_HUD_Progressbar_Hacking_Base_C;
    static constexpr const char* UberGraphFrame_HUD_Progressbar_Hacking_Base_C__UeName = "UberGraphFrame";
    class UWidgetAnimation* ArmorFullAnim;
    class UWidgetAnimation* ArmorHitAnim;
    class UWidgetAnimation* HitAnim;
    ITM_BossFightContainer_C* ITM_BossFightContainer;
    class UProgressBar* ProgressBar_Main;
    class UEnemyTemperatureReplicatorComponent* TemperatureReplicator;
    FTimerHandle HealthRefreshHandler;
    bool KillCue;
    class AFacilityHackingPod* ListenPod;
    FText HackingText;
    FText BrokenConnectionText;
    FText RebootText;
    void ExecuteUbergraph_HUD_Progressbar_Hacking_Base(int EntryPoint);
    void SetListenPod(class AFacilityHackingPod* pod);
    void UpdateBarState(EHackingPodState State);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void OnProgress(float hackProgress);
    void OnFightRemoved(TScriptInterface<class IBossFightInterface> BossFight_0);
    void OnRemoveBossFight();
    UE_COSMETIC void Construct();
};

}}}}   // namespace Game::UI::MainOnscreenHUD::BossFight

using HUD_Progressbar_Hacking_Base_C = Game::UI::MainOnscreenHUD::BossFight::HUD_Progressbar_Hacking_Base_C;