#pragma once
/*
Blueprint class HUD_MinersManualNotification_Manager_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../FSD.h"
#include "../UMG.h"

class UVerticalBox;

namespace Game { namespace UI { namespace MainOnscreenHUD { namespace MinersManualNotifications {

class HUD_MinersManualNotification_Manager_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/MainOnscreenHUD/MinersManualNotifications/HUD_MinersManualNotification_Manager", "HUD_MinersManualNotification_Manager_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UVerticalBox* VerticalBox_NotificationHolder;
    float NotificationScreenTime;
    void ExecuteUbergraph_HUD_MinersManualNotification_Manager(int EntryPoint);
    void OnMinersManualNotification(EMinersManualSection Section, FGuid ObjectID, FText Text);
    UE_COSMETIC void Construct();
};

}}}}   // namespace Game::UI::MainOnscreenHUD::MinersManualNotifications

using HUD_MinersManualNotification_Manager_C = Game::UI::MainOnscreenHUD::MinersManualNotifications::HUD_MinersManualNotification_Manager_C;