#pragma once
/*
Blueprint class ITEM_SpaceRig_PersonalCharacterLevel_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../UMG.h"

class AFSDPlayerState;
class APlayerCharacter;
class UCanvasPanel;
namespace Game { namespace UI { namespace Global_UI_Elements { class ITM_CharacterBuffIcon_C; class ITM_CharacterData_C; class ITM_CharacterIcon_C; }}}

namespace Game { namespace UI { namespace HUD_SpaceRig {

class ITEM_SpaceRig_PersonalCharacterLevel_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/HUD_SpaceRig/ITEM_SpaceRig_PersonalCharacterLevel", "ITEM_SpaceRig_PersonalCharacterLevel_C");
    using ITM_CharacterBuffIcon_C = Game::UI::Global_UI_Elements::ITM_CharacterBuffIcon_C;
    using ITM_CharacterData_C = Game::UI::Global_UI_Elements::ITM_CharacterData_C;
    using ITM_CharacterIcon_C = Game::UI::Global_UI_Elements::ITM_CharacterIcon_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UCanvasPanel* CanvasPanel_Base;
    ITM_CharacterBuffIcon_C* ITM_CharacterBuffIcon;
    ITM_CharacterData_C* ITM_CharacterData;
    ITM_CharacterIcon_C* ITM_CharacterIcon;
    FLinearColor Tint_Edge;
    FLinearColor Tint_Class;
    class AFSDPlayerState* PlayerState;
    class APlayerCharacter* SelectedCharacter;
    bool TOGGLE__PlayerName;
    static constexpr const char* TOGGLE__PlayerName__UeName = "TOGGLE: PlayerName";
    bool TOGGLE__XP_Display;
    static constexpr const char* TOGGLE__XP_Display__UeName = "TOGGLE: XP Display";
    void ExecuteUbergraph_ITEM_SpaceRig_PersonalCharacterLevel(int EntryPoint);
    void OnCharacterStatsChanged_Event(class AFSDPlayerState* PlayerState_0);
    void OnPlayerCharacterSpawned(class APlayerCharacter* PlayerCharacter);
    void Update(class APlayerCharacter* Character);
    UE_COSMETIC void Construct();
};

}}}   // namespace Game::UI::HUD_SpaceRig

using ITEM_SpaceRig_PersonalCharacterLevel_C = Game::UI::HUD_SpaceRig::ITEM_SpaceRig_PersonalCharacterLevel_C;