#pragma once
/*
Blueprint class ITM_LoadOut_PerksEquip_Item_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class UBorder;
class UButton;
class UImage;
class UPerkAsset;
class UPlayerCharacterID;
class USoundBase;
class UWidget;
class UWidgetSwitcher;
namespace Game { namespace UI { namespace HUD_SpaceRig { namespace KPI { class UI_PerkIcon_C; }}}}

namespace Game { namespace UI { namespace Menu_Loadout { namespace Perks {

class ITM_LoadOut_PerksEquip_Item_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_Loadout/Perks/ITM_LoadOut_PerksEquip_Item", "ITM_LoadOut_PerksEquip_Item_C");
    using UI_PerkIcon_C = Game::UI::HUD_SpaceRig::KPI::UI_PerkIcon_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UBorder* Background;
    class UBorder* FrameBorder;
    class UImage* IconLocked;
    class UWidgetSwitcher* IconSwitcher;
    class UButton* ItemButton;
    class UBorder* SelectionBorder;
    UI_PerkIcon_C* UI_PerkIcon;
    bool ItemHovered;
    bool ItemSelected;
    bool ItemLocked;
    class UPerkAsset* PerkAsset;
    TMulticastInlineDelegate<void(ITM_LoadOut_PerksEquip_Item_C* Item)> OnClicked;
    bool ShowBorder;
    class USoundBase* ClickAudio;
    bool IsRetirementIcon;
    class UPlayerCharacterID* CharacterClass;
    void ExecuteUbergraph_ITM_LoadOut_PerksEquip_Item(int EntryPoint);
    void BndEvt__ItemButton_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__ItemButton_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__ItemButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
    void Set_Selected(bool IsSelected);
    static constexpr const char* Set_Selected__UeName = "Set Selected";
    void Set_Perk(class UPerkAsset* PerkAsset_0);
    static constexpr const char* Set_Perk__UeName = "Set Perk";
    void Refresh();
    UE_COSMETIC void Construct();
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void IsItemLocked(bool& ItemLocked_0);
    class UWidget* CreateToolTip();
    void GetPerkAsset(class UPerkAsset*& PerkAsset_0) const;
};

}}}}   // namespace Game::UI::Menu_Loadout::Perks

using ITM_LoadOut_PerksEquip_Item_C = Game::UI::Menu_Loadout::Perks::ITM_LoadOut_PerksEquip_Item_C;