#pragma once
/*
Blueprint class ITM_LoadoutIcon_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class UBorder;
class UButton;
class UImage;
class UTexture2D;

namespace Game { namespace UI { namespace Menu_Loadout { namespace LoadoutSelection {

class ITM_LoadoutIcon_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_Loadout/LoadoutSelection/ITM_LoadoutIcon", "ITM_LoadoutIcon_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UBorder* Background;
    class UImage* Image_Icon;
    class UButton* LoadoutButton;
    class UBorder* SelectionBorder;
    TMulticastInlineDelegate<void(class UTexture2D* Texture, int Param_Index_0)> OnClicked;
    int Index_0;
    static constexpr const char* Index_0__UeName = "Index";
    void ExecuteUbergraph_ITM_LoadoutIcon(int EntryPoint);
    void BndEvt__Button_0_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_0_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature();
    void SetData(class UTexture2D* Texture, int Param_Index_0);
    void BndEvt__Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
};

}}}}   // namespace Game::UI::Menu_Loadout::LoadoutSelection

using ITM_LoadoutIcon_C = Game::UI::Menu_Loadout::LoadoutSelection::ITM_LoadoutIcon_C;