#pragma once
/*
Blueprint class ITM_CommunityGoal_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../FSD.h"
#include "../SlateCore.h"

class UButton;
class UCheckBox;
class UCommunityGoal;
class UCommunityGoalFaction;
class UImage;
class UProgressBar;
class USizeBox;
class UTextBlock;
class UWidget;
namespace Game { namespace UI { namespace HUD_SpaceRig { namespace CommunityTerminal { class ITM_CommunityGoalRewardToolTip_C; class ITM_FactionToolTip_C; }}}}
namespace Game { namespace UI { namespace MainOnscreenHUD { namespace Standard { class UI_ImageTinted_C; }}}}
namespace Game { namespace UI { namespace _GlobalAssets { namespace MaskedImage { class UI_GradientMasked_Image_C; }}}}

namespace Game { namespace UI { namespace HUD_SpaceRig { namespace CommunityTerminal {

class ITM_CommunityGoal_C : public UFSDUserWidget
{
public:
    UE_CLASS("/Game/UI/HUD_SpaceRig/CommunityTerminal/ITM_CommunityGoal", "ITM_CommunityGoal_C");
    using ITM_CommunityGoalRewardToolTip_C = Game::UI::HUD_SpaceRig::CommunityTerminal::ITM_CommunityGoalRewardToolTip_C;
    using ITM_FactionToolTip_C = Game::UI::HUD_SpaceRig::CommunityTerminal::ITM_FactionToolTip_C;
    using UI_GradientMasked_Image_C = Game::UI::_GlobalAssets::MaskedImage::UI_GradientMasked_Image_C;
    using UI_ImageTinted_C = Game::UI::MainOnscreenHUD::Standard::UI_ImageTinted_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UButton* BackgroundButton;
    class UTextBlock* BronzeGoalNumber;
    class UButton* Button_Goal_0;
    class UButton* Button_Goal_1;
    class UButton* Button_Goal_2;
    class UCheckBox* CheckBox_Goal_Bronze;
    class UCheckBox* CheckBox_Goal_Gold;
    class UCheckBox* CheckBox_Goal_Silver;
    class USizeBox* CurrentSizebox;
    class UTextBlock* CurrentTextBlock;
    class UButton* FactionIconToolTip;
    class UTextBlock* GoalText;
    class UTextBlock* GoldGoalNumber;
    class UImage* Icon;
    class UImage* Image_Bronze;
    class UImage* Image_Gold;
    class UImage* Image_Silver;
    class UProgressBar* ProgressBar_0;
    class UProgressBar* ProgressBar_1;
    class UProgressBar* ProgressBar_2;
    class UTextBlock* SilverGoalNumber;
    class UTextBlock* TitleText;
    UI_GradientMasked_Image_C* UI_GradientMasked_Image;
    UI_ImageTinted_C* UI_ImageTinted;
    UI_ImageTinted_C* UI_ImageTinted_267;
    FText Title;
    int TitleSize;
    FSlateBrush IconImage;
    FProgressBarStyle BarStyle;
    float Progress0;
    float Progress1;
    float Progress2;
    FLinearColor FillColor;
    float AnimTime;
    float TotalAnimTime;
    FString CurrentGoalID;
    class UCommunityGoal* CurrentGoal;
    float CurrentValue;
    int CurrentMembers;
    class UCommunityGoalFaction* Faction;
    bool IsShowingCurrentPlayerFaction;
    TMulticastInlineDelegate<void(class UCommunityGoalFaction* Faction_0, class UCommunityGoal* Goal)> HoverStarted;
    TMulticastInlineDelegate<void()> HoverEnded;
    ITM_CommunityGoalRewardToolTip_C* ToolTip;
    ITM_FactionToolTip_C* FactionToolTip;
    void ExecuteUbergraph_ITM_CommunityGoal(int EntryPoint);
    void BndEvt__FactionIconToolTip_K2Node_ComponentBoundEvent_9_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__FactionIconToolTip_K2Node_ComponentBoundEvent_8_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_2_K2Node_ComponentBoundEvent_7_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_1_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_0_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_2_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_1_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Goal_0_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature();
    void CheckFaction();
    void BndEvt__BackgroundButton_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_58_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature();
    void SetGoal(FString GoalID, float GoalValue, int Members, bool ForceRefresh);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void SetCommunityGoal(FText Goal, float Bronze_Progress, float Silver_Progress, float Gold_Progress);
    UE_COSMETIC void Tick(FGeometry MyGeometry, float InDeltaTime);
    void ResetAnim();
    void SetFaction(class UCommunityGoalFaction* Faction_0);
    void UpdateIcon();
    void UpdateTitle();
    void DoToolTip(class UWidget* ToolTipTarget, int Tier);
    void DoFactionToolTip();
};

}}}}   // namespace Game::UI::HUD_SpaceRig::CommunityTerminal

using ITM_CommunityGoal_C = Game::UI::HUD_SpaceRig::CommunityTerminal::ITM_CommunityGoal_C;