#pragma once
/*
Blueprint class ITM_Season_LevelUp_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class UImage;
class UTextBlock;
class UWidgetAnimation;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_Menu_ColorBar_C; }}}}

namespace Game { namespace UI { namespace Menu_Seasons {

class ITM_Season_LevelUp_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_Seasons/ITM_Season_LevelUp", "ITM_Season_LevelUp_C");
    using Basic_Menu_ColorBar_C = Game::UI::Art::WidgetParts::Basic_Menu_ColorBar_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* Intro;
    Basic_Menu_ColorBar_C* Basic_Menu_ColorBar;
    Basic_Menu_ColorBar_C* Basic_Menu_ColorBar_1;
    Basic_Menu_ColorBar_C* Basic_Menu_ColorBar_2;
    Basic_Menu_ColorBar_C* Basic_Menu_ColorBar_3;
    class UImage* Image_Background_Black;
    class UImage* Image_Background_Smoke;
    class UTextBlock* TextBlock_60;
    int Level;
    void ExecuteUbergraph_ITM_Season_LevelUp(int EntryPoint);
    void PlayIntro();
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
};

}}}   // namespace Game::UI::Menu_Seasons

using ITM_Season_LevelUp_C = Game::UI::Menu_Seasons::ITM_Season_LevelUp_C;