#pragma once
/*
Blueprint class ITM_CampaignCompletedRequirement_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class UCamapaignCompletedRequirement;
class UImage;
class UTextBlock;

namespace Game { namespace GameElements { namespace Campaign { namespace Requirements {

class ITM_CampaignCompletedRequirement_C : public UUserWidget
{
public:
    UE_CLASS("/Game/GameElements/Campaign/Requirements/ITM_CampaignCompletedRequirement", "ITM_CampaignCompletedRequirement_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UImage* Image_73;
    class UTextBlock* T_CampaignText;
    bool RequirementMet;
    class UCamapaignCompletedRequirement* CampaignReq;
    void ExecuteUbergraph_ITM_CampaignCompletedRequirement(int EntryPoint);
    UE_COSMETIC void Construct();
};

}}}}   // namespace Game::GameElements::Campaign::Requirements

using ITM_CampaignCompletedRequirement_C = Game::GameElements::Campaign::Requirements::ITM_CampaignCompletedRequirement_C;