#pragma once
/*
Blueprint class ITM_Job_Section_Header_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class UImage;
class UTextBlock;

namespace Game { namespace UI { namespace Menu_Jobs { namespace JobsV2_Redesign {

class ITM_Job_Section_Header_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_Jobs/JobsV2_Redesign/ITM_Job_Section_Header", "ITM_Job_Section_Header_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UImage* BG_Gradient;
    class UTextBlock* TextBlock_Header;
    FText HeaderText;
    void ExecuteUbergraph_ITM_Job_Section_Header(int EntryPoint);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
};

}}}}   // namespace Game::UI::Menu_Jobs::JobsV2_Redesign

using ITM_Job_Section_Header_C = Game::UI::Menu_Jobs::JobsV2_Redesign::ITM_Job_Section_Header_C;