#pragma once
/*
Blueprint class ITM_Mod_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../SimpleUGC.h"
#include "../UMG.h"

class UButton;
class UHorizontalBox;
class UImage;
class USizeBox;
class UTextBlock;
class UTexture2DDynamic;
class UUGCPackage;
class UWidget;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_CheckBox_C; class Basic_Image_C; }}}}
namespace Game { namespace UI { namespace Menu_EscapeMenu { namespace Modding { class ITM_Modding_Menu_C; }}}}
namespace Game { namespace UI { namespace ToolTips { class Basic_ToolTip_C; }}}

namespace Game { namespace UI { namespace Menu_EscapeMenu { namespace Modding {

class ITM_Mod_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_EscapeMenu/Modding/ITM_Mod", "ITM_Mod_C");
    using Basic_CheckBox_C = Game::UI::Art::WidgetParts::Basic_CheckBox_C;
    using Basic_Image_C = Game::UI::Art::WidgetParts::Basic_Image_C;
    using Basic_ToolTip_C = Game::UI::ToolTips::Basic_ToolTip_C;
    using ITM_Modding_Menu_C = Game::UI::Menu_EscapeMenu::Modding::ITM_Modding_Menu_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UImage* Background;
    class UImage* backgroundOutline;
    class UButton* ButtonAuthorURL;
    class UButton* ButtonImage;
    class UButton* ButtonTitle;
    Basic_CheckBox_C* CheckBox_Enabled;
    class UHorizontalBox* ContentBox;
    class UTextBlock* DeprecatedLabel;
    class USizeBox* EntrySizeBox;
    class UImage* Image_Separator;
    Basic_Image_C* ImgCrashed;
    Basic_Image_C* ImgVersion;
    class UHorizontalBox* LeftBox;
    class UTextBlock* ModDescriptionTextbox;
    class UTextBlock* ModDownloadVersionText;
    class UImage* ModifiedImg;
    class UTextBlock* ModMadeByTextBox;
    class UTextBlock* ModNameTextBox;
    class UTextBlock* ModSlotNumber;
    class UTextBlock* ModStatusText;
    class UImage* ModThumbnail;
    class UTextBlock* ModVersionText;
    class USizeBox* ThumbnailSizeBox;
    FString ModName;
    FString ModVersion;
    FString ModURL;
    FString ModCategory;
    EUGCApprovalStatus ModStatus;
    FString ModDescription;
    FString ModAuthor;
    FString ModAuthorURL;
    bool IsModMounted;
    bool PendingModMounting;
    TMulticastInlineDelegate<void(ITM_Mod_C* ManipulatedModItem)> OnActivationChanged;
    bool IsModDeprecated;
    class UUGCPackage* UGCPackage;
    bool CompactMode;
    bool Crashed;
    bool DependencyRemoved;
    Basic_ToolTip_C* VersionTooltip;
    TArray<ITM_Mod_C*> ParentModItems;
    TArray<ITM_Mod_C*> DependentModItems;
    bool ShowStatus;
    bool WrongVersion;
    TArray<FString> NamesOfDependencies;
    EUGCDownloadVersion ModDownloadVersion;
    ITM_Modding_Menu_C* Modding_Menu;
    static constexpr const char* Modding_Menu__UeName = "Modding Menu";
    void ExecuteUbergraph_ITM_Mod(int EntryPoint);
    void CustomEvent_1();
    void CustomEvent_0(FString LastURL);
    void RequestDependencyNames();
    void SetModActivationChangedForceParents(bool IsChecked);
    void SetModActivationChanged(bool IsChecked);
    void Refresh();
    void BndEvt__ButtonImage_K2Node_ComponentBoundEvent_9_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__ButtonImage_K2Node_ComponentBoundEvent_8_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__ButtonImage_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__ButtonModURL_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__ButtonModURL_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__ButtonAuthorURL_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__ButtonModURL_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
    void UpdateModifed();
    UE_COSMETIC void Construct();
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void BndEvt__Basic_CheckBox_K2Node_ComponentBoundEvent_0_OnCheckStateChanged__DelegateSignature(bool IsChecked);
    void SetData(FString InModName, FString InModVersion, FString InModURL, FString InModCategory, EUGCApprovalStatus InModStatus, EUGCDownloadVersion InModDownloadVersion, FString InModDescription, FString InModAuthor, FString InModAuthorURL, bool InModIsMounted, bool InModPendingMounted, bool InModIsDeprecated, bool InDependencyRemoved, bool InShowStatus, bool InCrashed, bool InWrongVersion);
    void SetColors();
    void GetStatusText(bool InShowStatus, EUGCApprovalStatus InStatus, FText& OutStatus);
    void GetTruncatedString(FString inString, int InMaxLength, FString& OutResult);
    void GetStringOrDefault(FString inString, FText InDefault, FString& OutValue);
    void OnThumbnailFetched(class UTexture2DDynamic* ModioModThumbnail);
    void GetStatusToolTip(bool InShowStatus, EUGCApprovalStatus InStatus, FText& OutStatus);
    void SetCompactMode(bool SimpleMode);
    void HasCrashed(bool& OutHasCrashed);
    void On_Overlay_Closed();
    static constexpr const char* On_Overlay_Closed__UeName = "On Overlay Closed";
    void SetModEnabled(bool InEnabled);
    void ResetModEnabled();
    void OnModStateDependencyChanged(bool IsChecked, bool ShouldDisableCheckmark, bool& HasChanged);
    void CheckGameVersionBeforeEnable(bool InEnabled);
    class UWidget* CreateversionTooltip();
    void FindParentsInArray(TArray<class UWidget*> PotentialParents);
    UE_PURE class UWidget* GetDependencyCheckboxTooltip();
    void SetFromPackage(class UUGCPackage* InPackage);
    void CheckIfSavedInSlot();
    void GetDownloadVersionText(EUGCDownloadVersion InDownloadVersion, FText& OutStatus);
    void GetDownloadVersionToolTip(EUGCDownloadVersion InStatus, FText& OutStatus);
    void ITM_Mod_AutoGenFunc(FString LastURL);
};

}}}}   // namespace Game::UI::Menu_EscapeMenu::Modding

using ITM_Mod_C = Game::UI::Menu_EscapeMenu::Modding::ITM_Mod_C;