#pragma once
/*
Blueprint class ITM_CommunityGoalRewardToolTip_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../FSD.h"

class UCommunityGoal;
class UCommunityGoalFaction;
class USizeBox;
class UVerticalBox;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_Menu_MinimalWindow_C; }}}}

namespace Game { namespace UI { namespace HUD_SpaceRig { namespace CommunityTerminal {

class ITM_CommunityGoalRewardToolTip_C : public UFSDUserWidget
{
public:
    UE_CLASS("/Game/UI/HUD_SpaceRig/CommunityTerminal/ITM_CommunityGoalRewardToolTip", "ITM_CommunityGoalRewardToolTip_C");
    using Basic_Menu_MinimalWindow_C = Game::UI::Art::WidgetParts::Basic_Menu_MinimalWindow_C;
    FPointerToUberGraphFrame UberGraphFrame;
    Basic_Menu_MinimalWindow_C* Basic_Menu_MinimalWindow;
    class UVerticalBox* RewardMainBox;
    class UVerticalBox* RewardSpecificBox;
    class USizeBox* SizeBox_4;
    class UCommunityGoalFaction* Faction;
    class UCommunityGoal* CurrentGoal;
    FVector2D Size;
    int CurrentTier;
    void ExecuteUbergraph_ITM_CommunityGoalRewardToolTip(int EntryPoint);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void SetFaction(class UCommunityGoalFaction* Faction_0);
    void BuildResources(int Tier);
    void SetGoalResultTier(int Tier, class UCommunityGoal* Goal);
    UE_PURE int TotalTiers();
    void SetGoal(class UCommunityGoal* Goal);
};

}}}}   // namespace Game::UI::HUD_SpaceRig::CommunityTerminal

using ITM_CommunityGoalRewardToolTip_C = Game::UI::HUD_SpaceRig::CommunityTerminal::ITM_CommunityGoalRewardToolTip_C;