#pragma once
/*
Blueprint class Itm_HeaderCategory_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../SlateCore.h"
#include "../UMG.h"

class UButton;
class UImage;
class UTextBlock;

namespace Game { namespace UI { namespace Menu_MinersManual {

class Itm_HeaderCategory_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_MinersManual/Itm_HeaderCategory", "Itm_HeaderCategory_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UButton* Button_Main;
    class UTextBlock* ButtonText;
    class UImage* Filled_Left;
    class UImage* Filled_Middle;
    class UImage* Filled_Right;
    class UImage* Outline_Left;
    class UImage* Outline_Middle;
    class UImage* Outline_Right;
    FText Text;
    bool IsSelected;
    bool UseFlatLeftside;
    TMulticastInlineDelegate<void()> OnClicked;
    void ExecuteUbergraph_Itm_HeaderCategory(int EntryPoint);
    void SetText(FText Text_0);
    void BndEvt__Button_Main_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Main_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_Main_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
    void SetColor(FSlateColor Filled, FSlateColor outline, FSlateColor Text_0);
    void SetSelected(bool IsSelected_0);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
};

}}}   // namespace Game::UI::Menu_MinersManual

using Itm_HeaderCategory_C = Game::UI::Menu_MinersManual::Itm_HeaderCategory_C;