#pragma once
/*
Blueprint class ITM_SupplyBarItem_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class UImage;
class UWidgetAnimation;

namespace Game { namespace UI { namespace Global_UI_Elements {

class ITM_SupplyBarItem_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Global_UI_Elements/ITM_SupplyBarItem", "ITM_SupplyBarItem_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* AnimBlink;
    class UImage* IMG_Border;
    class UImage* IMG_Inner;
    bool IsActivated;
    bool IsBlinking;
    float BlinkUnder;
    void ExecuteUbergraph_ITM_SupplyBarItem(int EntryPoint);
    void OnBlinkingFinished();
    UE_COSMETIC void Construct();
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void SetOn(bool IsOn);
    void SetProgress(float InProgress);
};

}}}   // namespace Game::UI::Global_UI_Elements

using ITM_SupplyBarItem_C = Game::UI::Global_UI_Elements::ITM_SupplyBarItem_C;