#pragma once
/*
Blueprint class ITM_DeepDiveHeader_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class UDeepDive;
class UImage;
class USizeBox;
class UTextBlock;
namespace Game { namespace UI { namespace Menu_MissionStart { class ITM_DeepDiveHeaderElite_C; }}}
namespace Game { namespace UI { namespace _GlobalAssets { class ShadowBG_C; }}}

namespace Game { namespace UI { namespace Menu_MissionStart {

class ITM_DeepDiveHeader_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_MissionStart/ITM_DeepDiveHeader", "ITM_DeepDiveHeader_C");
    using ITM_DeepDiveHeaderElite_C = Game::UI::Menu_MissionStart::ITM_DeepDiveHeaderElite_C;
    using ShadowBG_C = Game::UI::_GlobalAssets::ShadowBG_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UImage* Image_188;
    class UImage* Image_304;
    ITM_DeepDiveHeaderElite_C* ITM_DeepDiveHeaderElite;
    ShadowBG_C* ShadowBG;
    class USizeBox* SizeBox_0;
    class UTextBlock* TXT_DeepDive_BG;
    class UTextBlock* TXT_DeepDive_Front;
    FText Header_Contents;
    static constexpr const char* Header_Contents__UeName = "Header Contents";
    bool EliteActive;
    void ExecuteUbergraph_ITM_DeepDiveHeader(int EntryPoint);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void SetHeaderContents(FText Header_Contents_0);
    void SetEliteActive(bool EliteActive_0);
    void FromDeepDive(class UDeepDive* InDeepDive);
    void FromActiveDeepDive();
};

}}}   // namespace Game::UI::Menu_MissionStart

using ITM_DeepDiveHeader_C = Game::UI::Menu_MissionStart::ITM_DeepDiveHeader_C;