#pragma once
/*
Blueprint class ITM_ItemIcon_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../SlateCore.h"
#include "../UMG.h"

class UImage;
class UItemData;
class UItemID;
class UOverlay;
class USizeBox;
class UWidgetSwitcher;

namespace Game { namespace UI { namespace Menu_Loadout {

class ITM_ItemIcon_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_Loadout/ITM_ItemIcon", "ITM_ItemIcon_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UImage* BottomImage;
    class USizeBox* Icon_SizeBox;
    class UOverlay* IconOverlay;
    class UImage* PreviewImage;
    class UImage* TopImage;
    class UWidgetSwitcher* TypeSwitcher;
    class UItemData* ItemData;
    int Height;
    FMargin IconPadding;
    bool UsePreviewImage;
    void ExecuteUbergraph_ITM_ItemIcon(int EntryPoint);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void SetItemData(class UItemData* InItemData);
    void SetHeight(int InHeight);
    void SetIconPadding(FMargin InIconPadding);
    void SetUsePreviewImage(bool InUsePreviewImage);
    void FromItemID(class UItemID* InItem);
};

}}}   // namespace Game::UI::Menu_Loadout

using ITM_ItemIcon_C = Game::UI::Menu_Loadout::ITM_ItemIcon_C;