#pragma once
/*
Blueprint class Loadout_GrenadeProxy_PlasmaBoomerang_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "Loadout_GrenadeProxy_Ball_C.h"

namespace Game { namespace WeaponsNTools { namespace Grenades { namespace PlasmaBoomerang {

class Loadout_GrenadeProxy_PlasmaBoomerang_C : public Game::WeaponsNTools::Grenades::Loadout_GrenadeProxy_Ball_C
{
public:
    UE_CLASS("/Game/WeaponsNTools/Grenades/PlasmaBoomerang/Loadout_GrenadeProxy_PlasmaBoomerang", "Loadout_GrenadeProxy_PlasmaBoomerang_C");
};

}}}}   // namespace Game::WeaponsNTools::Grenades::PlasmaBoomerang

using Loadout_GrenadeProxy_PlasmaBoomerang_C = Game::WeaponsNTools::Grenades::PlasmaBoomerang::Loadout_GrenadeProxy_PlasmaBoomerang_C;