#pragma once
/*
Blueprint class LoreScreen_Traversal_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "LoreScreen_Master_C.h"

class UAudioComponent;
class UPlayerCharacterID;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_IconWithOutline_C; }}}}
namespace Game { namespace UI { namespace Menu_MinersManual { namespace Containers { class Lore_Container_PictureOverText_C; }}}}
namespace Game { namespace UI { namespace Menu_MinersManual { namespace InfoScreens { class LoreScreen_Template_C; }}}}

namespace Game { namespace UI { namespace Menu_MinersManual { namespace InfoScreens { namespace Basics {

class LoreScreen_Traversal_C : public Game::UI::Menu_MinersManual::InfoScreens::LoreScreen_Master_C
{
public:
    UE_CLASS("/Game/UI/Menu_MinersManual/InfoScreens/Basics/LoreScreen_Traversal", "LoreScreen_Traversal_C");
    using Basic_IconWithOutline_C = Game::UI::Art::WidgetParts::Basic_IconWithOutline_C;
    using LoreScreen_Template_C = Game::UI::Menu_MinersManual::InfoScreens::LoreScreen_Template_C;
    using Lore_Container_PictureOverText_C = Game::UI::Menu_MinersManual::Containers::Lore_Container_PictureOverText_C;
    FPointerToUberGraphFrame UberGraphFrame_LoreScreen_Traversal_C;
    static constexpr const char* UberGraphFrame_LoreScreen_Traversal_C__UeName = "UberGraphFrame";
    Basic_IconWithOutline_C* DrillerIcon;
    Basic_IconWithOutline_C* EngineerIcon;
    Basic_IconWithOutline_C* GunnarIcon;
    Lore_Container_PictureOverText_C* Lore_Container_PictureOverText1;
    Lore_Container_PictureOverText_C* Lore_Container_PictureOverText2;
    Lore_Container_PictureOverText_C* Lore_Container_PictureOverText3;
    Lore_Container_PictureOverText_C* Lore_Container_PictureOverText4;
    LoreScreen_Template_C* LoreScreen_Template;
    Basic_IconWithOutline_C* ScoutIcon;
    class UAudioComponent* HoverSound;
    class UPlayerCharacterID* DrillerID;
    class UPlayerCharacterID* ScoutID;
    class UPlayerCharacterID* GunnerID;
    class UPlayerCharacterID* EngineerID;
    void ExecuteUbergraph_LoreScreen_Traversal(int EntryPoint);
    void RefreshContent();
    UE_COSMETIC void Construct();
};

}}}}}   // namespace Game::UI::Menu_MinersManual::InfoScreens::Basics

using LoreScreen_Traversal_C = Game::UI::Menu_MinersManual::InfoScreens::Basics::LoreScreen_Traversal_C;