#pragma once
/*
Blueprint class Lore_Container_CombatTip_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class UImage;
class URichTextBlock;
class UTextBlock;
class UVerticalBox;
class UWidgetAnimation;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_Window_CutCorner_C; }}}}

namespace Game { namespace UI { namespace Menu_MinersManual { namespace Containers {

class Lore_Container_CombatTip_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_MinersManual/Containers/Lore_Container_CombatTip", "Lore_Container_CombatTip_C");
    using Basic_Window_CutCorner_C = Game::UI::Art::WidgetParts::Basic_Window_CutCorner_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* Intro;
    Basic_Window_CutCorner_C* Basic_Window;
    class UImage* Image_ExclamaitonMark;
    class URichTextBlock* RichTextBlock_Body;
    class UTextBlock* TextBlock_Headline;
    class UVerticalBox* VerticalBox_19;
    FText Headline;
    FText Text;
    void ExecuteUbergraph_Lore_Container_CombatTip(int EntryPoint);
    void PlayIntro();
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void SetText(FText Headline_0, FText Body);
};

}}}}   // namespace Game::UI::Menu_MinersManual::Containers

using Lore_Container_CombatTip_C = Game::UI::Menu_MinersManual::Containers::Lore_Container_CombatTip_C;