#pragma once
/*
Blueprint class Lore_Container_Basics_Info_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../Slate.h"
#include "../SlateCore.h"
#include "../UMG.h"

class UHorizontalBox;
class UImage;
class UMinersManualData;
class URichTextBlock;
class USizeBox;
class UTextBlock;
class UVerticalBox;
class UWidget;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_Menu_ColorBar_C; }}}}

namespace Game { namespace UI { namespace Menu_MinersManual { namespace Containers {

class Lore_Container_Basics_Info_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_MinersManual/Containers/Lore_Container_Basics_Info", "Lore_Container_Basics_Info_C");
    using Basic_Menu_ColorBar_C = Game::UI::Art::WidgetParts::Basic_Menu_ColorBar_C;
    FPointerToUberGraphFrame UberGraphFrame;
    Basic_Menu_ColorBar_C* ColorbarTextSeparator;
    class UHorizontalBox* HorizontalBox_Outer;
    class UImage* Image_Front;
    class UImage* Image_Item;
    class URichTextBlock* RichTextBlock_Body;
    class USizeBox* SizeBox_Image;
    class UTextBlock* TextBlock_Header;
    class UVerticalBox* VerticalBox_Text;
    class UMinersManualData* Data;
    bool MoveImageToRightSide;
    void ExecuteUbergraph_Lore_Container_Basics_Info(int EntryPoint);
    void SetAlignment(ETextJustify Text, EHorizontalAlignment Image);
    void AddItem(class UWidget* Content, EHorizontalAlignment InHorizontalAlignment, EVerticalAlignment InVerticalAlignment, FMargin InPadding, ESlateSizeRule Size_Rule);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
};

}}}}   // namespace Game::UI::Menu_MinersManual::Containers

using Lore_Container_Basics_Info_C = Game::UI::Menu_MinersManual::Containers::Lore_Container_Basics_Info_C;