#pragma once
/*
Blueprint class LoreScreen_MissionWarnings_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "LoreScreen_Master_C.h"

class UAudioComponent;
class UScrollBox;
class UUniformGridPanel;
namespace Game { namespace UI { namespace Menu_MinersManual { namespace InfoScreens { class LoreScreen_Template_C; }}}}

namespace Game { namespace UI { namespace Menu_MinersManual { namespace InfoScreens {

class LoreScreen_MissionWarnings_C : public Game::UI::Menu_MinersManual::InfoScreens::LoreScreen_Master_C
{
public:
    UE_CLASS("/Game/UI/Menu_MinersManual/InfoScreens/LoreScreen_MissionWarnings", "LoreScreen_MissionWarnings_C");
    using LoreScreen_Template_C = Game::UI::Menu_MinersManual::InfoScreens::LoreScreen_Template_C;
    FPointerToUberGraphFrame UberGraphFrame_LoreScreen_MissionWarnings_C;
    static constexpr const char* UberGraphFrame_LoreScreen_MissionWarnings_C__UeName = "UberGraphFrame";
    LoreScreen_Template_C* LoreScreen_Template;
    class UScrollBox* ScrollBox_List;
    class UUniformGridPanel* UniformGridPanel_ItemHolder;
    class UAudioComponent* HoverSound;
    void ExecuteUbergraph_LoreScreen_MissionWarnings(int EntryPoint);
    void RefreshContent();
    UE_COSMETIC void Construct();
};

}}}}   // namespace Game::UI::Menu_MinersManual::InfoScreens

using LoreScreen_MissionWarnings_C = Game::UI::Menu_MinersManual::InfoScreens::LoreScreen_MissionWarnings_C;