#pragma once
/*
Blueprint class Menu_StatusScreen_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class UButton;
class UImage;
class UObject;
class UTextBlock;
class UWidgetAnimation;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_IconWithOutline_C; }}}}
namespace Game { namespace UI { namespace Menu_EscapeMenu { class ITM_EscMenu_BriefingV2_C; class ITM_PreventDuplicateCharacters_C; class ITM_PrivatePublic_C; class ITM_WeaponAndPerkInfo_C; }}}
namespace Game { namespace UI { namespace Menu_Seasons { class ITM_SeasonLogo_C; }}}
namespace Game { namespace UI { namespace Menu_Tab { class HUD_TabPlayerListEntry_InteractableV2_C; class HUD_TabPlayerList_InteractableV2_C; }}}

namespace Game { namespace UI { namespace Menu_EscapeMenu {

class Menu_StatusScreen_C : public UWindowWidget
{
public:
    UE_CLASS("/Game/UI/Menu_EscapeMenu/Menu_StatusScreen", "Menu_StatusScreen_C");
    using Basic_IconWithOutline_C = Game::UI::Art::WidgetParts::Basic_IconWithOutline_C;
    using HUD_TabPlayerListEntry_InteractableV2_C = Game::UI::Menu_Tab::HUD_TabPlayerListEntry_InteractableV2_C;
    using HUD_TabPlayerList_InteractableV2_C = Game::UI::Menu_Tab::HUD_TabPlayerList_InteractableV2_C;
    using ITM_EscMenu_BriefingV2_C = Game::UI::Menu_EscapeMenu::ITM_EscMenu_BriefingV2_C;
    using ITM_PreventDuplicateCharacters_C = Game::UI::Menu_EscapeMenu::ITM_PreventDuplicateCharacters_C;
    using ITM_PrivatePublic_C = Game::UI::Menu_EscapeMenu::ITM_PrivatePublic_C;
    using ITM_SeasonLogo_C = Game::UI::Menu_Seasons::ITM_SeasonLogo_C;
    using ITM_WeaponAndPerkInfo_C = Game::UI::Menu_EscapeMenu::ITM_WeaponAndPerkInfo_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* LoadoutClicked;
    Basic_IconWithOutline_C* Basic_IconWithOutline;
    class UButton* Button_Loadout;
    class UTextBlock* dataReadout;
    class UTextBlock* dataReadout_isModded;
    class UTextBlock* dataReadout_SeedString;
    HUD_TabPlayerList_InteractableV2_C* FriendsTab;
    class UImage* Image_BottomSmoke;
    class UImage* Image_GradientBottom;
    class UImage* Image_Separator_2;
    ITM_EscMenu_BriefingV2_C* ITM_EscMenu_BriefingV2;
    ITM_PreventDuplicateCharacters_C* ITM_PreventDuplicateCharacters;
    ITM_PrivatePublic_C* ITM_PrivatePublic;
    ITM_SeasonLogo_C* ITM_SeasonLogo;
    ITM_WeaponAndPerkInfo_C* ITM_WeaponAndPerkInfo1;
    HUD_TabPlayerListEntry_InteractableV2_C* LocalPlayer;
    class UImage* PlayerCharacterImage;
    class UTextBlock* TextBlock;
    class UTextBlock* TextBlock_3;
    TMulticastInlineDelegate<void(class UObject* IdentifyingObject, bool OpenSpecificPage, EMinersManualSinglePage page)> OpenMinersManual;
    void ExecuteUbergraph_Menu_StatusScreen(int EntryPoint);
    void OnMenuClosed();
    void OnMenuOpened();
    void RefreshShowroom();
    void BndEvt__ITM_EscMenu_BriefingV2_K2Node_ComponentBoundEvent_7_BiomeClicked__DelegateSignature();
    void BndEvt__Button_Loadout_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature();
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void BndEvt__ITM_EscMenu_BriefingV2_K2Node_ComponentBoundEvent_3_WarningClicked__DelegateSignature();
    void BndEvt__ITM_EscMenu_BriefingV2_K2Node_ComponentBoundEvent_2_MutatorClicked__DelegateSignature();
    void BndEvt__ITM_EscMenu_BriefingV2_K2Node_ComponentBoundEvent_1_MissionTypeClicked__DelegateSignature();
    void Close();
    void Update();
    UE_COSMETIC void Construct();
};

}}}   // namespace Game::UI::Menu_EscapeMenu

using Menu_StatusScreen_C = Game::UI::Menu_EscapeMenu::Menu_StatusScreen_C;