#pragma once
/*
Blueprint class ModioModBrowserMenuBarWidget_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../ModioUI.h"

class UModioInputBindingImage;
namespace Game { namespace UI { namespace Menu_StartScreen { class UI_InfoScreen_C; }}}

namespace Modio { namespace UI { namespace Browser { namespace Views {

class ModioModBrowserMenuBarWidget_C : public UModioMenuBar
{
public:
    UE_CLASS("/Modio/UI/Browser/Views/ModioModBrowserMenuBarWidget", "ModioModBrowserMenuBarWidget_C");
    using UI_InfoScreen_C = Game::UI::Menu_StartScreen::UI_InfoScreen_C;
    class UModioInputBindingImage* ProfileDownloadQueueInputHint;
    UI_InfoScreen_C* UI_Screen;
    static constexpr const char* UI_Screen__UeName = "UI Screen";
};

}}}}   // namespace Modio::UI::Browser::Views

using ModioModBrowserMenuBarWidget_C = Modio::UI::Browser::Views::ModioModBrowserMenuBarWidget_C;