#pragma once
/*
Blueprint class OBJ_1st_Escort_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../FSD.h"

class UClass;
class UHealthComponentBase;
class UTexture2D;

namespace Game { namespace GameElements { namespace Objectives { namespace Escort {

class OBJ_1st_Escort_C : public UEscortObjective
{
public:
    UE_CLASS("/Game/GameElements/Objectives/Escort/OBJ_1st_Escort", "OBJ_1st_Escort_C");
    FPointerToUberGraphFrame UberGraphFrame;
    TSoftClassPtr<class UClass> GarageBeacon;
    bool MuleClass;
    FSoftObjectPath EscortMuleClass;
    bool MuleDead;
    void ExecuteUbergraph_OBJ_1st_Escort(int EntryPoint);
    void FinalEvent();
    void OnAllDwarvesDown();
    void SpawnGarage();
    void OnMuleDied(class UHealthComponentBase* HealthComponent);
    void OnEscortMuleSpawnedEvent();
    void ReceiveBeginPlay();
    FText GetObjectiveDescription(float missionLength);
    class UTexture2D* GetObjectiveIcon() const;
    UE_PURE FText GetInMissionText() const;
    UE_PURE int GetObjectiveAmount(float missionLength) const;
};

}}}}   // namespace Game::GameElements::Objectives::Escort

using OBJ_1st_Escort_C = Game::GameElements::Objectives::Escort::OBJ_1st_Escort_C;