#pragma once
/*
Blueprint class Options_MouseY_Sensitivity_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class UBorder;
class UButton;
class UHorizontalBox;
class USpinBox;
class UTextBlock;
class UWidgetSwitcher;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_Slider_C; }}}}

namespace Game { namespace UI { namespace Menu_Options {

class Options_MouseY_Sensitivity_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_Options/Options_MouseY_Sensitivity", "Options_MouseY_Sensitivity_C");
    using Basic_Slider_C = Game::UI::Art::WidgetParts::Basic_Slider_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UBorder* BaseMid;
    Basic_Slider_C* Basic_Slider;
    class UHorizontalBox* ManualSensitivityInput;
    class USpinBox* SensitivityInput;
    class UButton* ToggleManualinput;
    class UTextBlock* TXT_ButtonText;
    class UWidgetSwitcher* WidgetSwitcher_207;
    bool UseSpinboxInput;
    int CurrentSpinboxValue;
    void ExecuteUbergraph_Options_MouseY_Sensitivity(int EntryPoint);
    void BndEvt__Button_152_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__SensitivityInput_K2Node_ComponentBoundEvent_0_OnSpinBoxValueChangedEvent__DelegateSignature(float InValue);
    void BndEvt__Basic_Slider_K2Node_ComponentBoundEvent_1_OnValueChanged__DelegateSignature(float Value);
    void ShowOptions();
    void UINeedsUpdate();
    UE_COSMETIC void Construct();
};

}}}   // namespace Game::UI::Menu_Options

using Options_MouseY_Sensitivity_C = Game::UI::Menu_Options::Options_MouseY_Sensitivity_C;