#pragma once
/*
Blueprint class Options_Tab_Saves_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_Option_C; }}}}
namespace Game { namespace UI { namespace Menu_Options { class Options_ResetProgress_C; class Options_RestoreSave_C; }}}
namespace Game { namespace UI { namespace Menu_SaveSlots { class Menu_SaveSlots_C; }}}

namespace Game { namespace UI { namespace Menu_Options {

class Options_Tab_Saves_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_Options/Options_Tab_Saves", "Options_Tab_Saves_C");
    using Basic_Option_C = Game::UI::Art::WidgetParts::Basic_Option_C;
    using Menu_SaveSlots_C = Game::UI::Menu_SaveSlots::Menu_SaveSlots_C;
    using Options_ResetProgress_C = Game::UI::Menu_Options::Options_ResetProgress_C;
    using Options_RestoreSave_C = Game::UI::Menu_Options::Options_RestoreSave_C;
    FPointerToUberGraphFrame UberGraphFrame;
    Menu_SaveSlots_C* Menu_SaveSlots;
    Options_ResetProgress_C* Options_ResetProgress;
    Options_RestoreSave_C* Options_RestoreSave;
    Basic_Option_C* Reset_Progress;
    Basic_Option_C* Restore_Save;
    TMulticastInlineDelegate<void()> SettingsChanged;
    void ExecuteUbergraph_Options_Tab_Saves(int EntryPoint);
    UE_COSMETIC void Construct();
};

}}}   // namespace Game::UI::Menu_Options

using Options_Tab_Saves_C = Game::UI::Menu_Options::Options_Tab_Saves_C;