#pragma once
/*
Blueprint class PRJ_HydraWeedSpawn_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class UAudioComponent;
class UParticleSystem;
class UParticleSystemComponent;
class USoundBase;

namespace Game { namespace Enemies { namespace HydraWeed {

class PRJ_HydraWeedSpawn_C : public AHydraWeedSpawnProjectile
{
public:
    UE_CLASS("/Game/Enemies/HydraWeed/PRJ_HydraWeedSpawn", "PRJ_HydraWeedSpawn_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UAudioComponent* Audio;
    static constexpr const char* Audio__UeScsNode = "e6ee98d9a464584cb87b070acb619b99";
    class UParticleSystemComponent* ParticleSystem;
    static constexpr const char* ParticleSystem__UeScsNode = "9ba7433eaf265f449df6210e939b9430";
    class UParticleSystem* SeedImpactParticles;
    class USoundBase* SeedImpactSound;
    void ExecuteUbergraph_PRJ_HydraWeedSpawn(int EntryPoint);
    void OnImpacted(bool PredictedImpact, const FHitResult& HitResult);
    void ReceiveBeginPlay();
    bool NewFunction_0();
};

}}}   // namespace Game::Enemies::HydraWeed

using PRJ_HydraWeedSpawn_C = Game::Enemies::HydraWeed::PRJ_HydraWeedSpawn_C;