#pragma once
/*
Blueprint class PRJ_PlatformMaker_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../FSD.h"

class UStaticMesh;
class UStaticMeshComponent;
class UTerrainMaterial;
class UTimelineComponent;

namespace Game { namespace WeaponsNTools { namespace PlatformGun {

class PRJ_PlatformMaker_C : public APlatformProjectile
{
public:
    UE_CLASS("/Game/WeaponsNTools/PlatformGun/PRJ_PlatformMaker", "PRJ_PlatformMaker_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UStaticMeshComponent* Projectile;
    static constexpr const char* Projectile__UeScsNode = "606338a13cc77942a4e351f7fece69cb";
    float Timeline_0_NewTrack;
    static constexpr const char* Timeline_0_NewTrack__UeName = "Timeline_0_NewTrack_1_6344ADF74893FE5BE85A6CA2C1A57EE3";
    ETimelineDirection Timeline_0__Direction_6344ADF74893FE5BE85A6CA2C1A57EE3;
    class UTimelineComponent* Timeline_0;
    float Diameter;
    float PlatformCreationDelay__seconds_;
    static constexpr const char* PlatformCreationDelay__seconds___UeName = "PlatformCreationDelay (seconds)";
    class UStaticMesh* PlatformCarverMesh;
    FVector PlatformScale;
    class UTerrainMaterial* FoamMaterial;
    void ExecuteUbergraph_PRJ_PlatformMaker(int EntryPoint);
    void UseFallDmgAndBugRepellant();
    void UseBugRepellantMaterial();
    void UseLessFallDamageMaterial();
    void SetCarverMeshScale(FVector Scale);
    void Set_Carver_mesh(class UStaticMesh* Mesh_to_use);
    static constexpr const char* Set_Carver_mesh__UeName = "Set Carver mesh";
    void ReceiveBeginPlay();
    void OnImpacted(bool PredictedImpact, FHitResult HitResult);
    void Timeline_0__UpdateFunc();
    void Timeline_0__FinishedFunc();
};

}}}   // namespace Game::WeaponsNTools::PlatformGun

using PRJ_PlatformMaker_C = Game::WeaponsNTools::PlatformGun::PRJ_PlatformMaker_C;