#pragma once
/*
Blueprint class PRJ_Crye_SnowBall_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class UDamageComponent;
class UParticleSystemComponent;
class UProjectileExplosion;
class UStaticMeshComponent;

namespace Game { namespace WeaponsNTools { namespace Cryospray {

class PRJ_Crye_SnowBall_C : public AProjectile
{
public:
    UE_CLASS("/Game/WeaponsNTools/Cryospray/PRJ_Crye_SnowBall", "PRJ_Crye_SnowBall_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UDamageComponent* Damage;
    static constexpr const char* Damage__UeScsNode = "bb2b1f0014dc9e49a3e150208e62078e";
    class UProjectileExplosion* ProjectileExplosion;
    static constexpr const char* ProjectileExplosion__UeScsNode = "5cec1b2d7b2c664d9ac52df42d95bf1e";
    class UStaticMeshComponent* StaticMesh;
    static constexpr const char* StaticMesh__UeScsNode = "028ca520dc8e994db813eac046e7b34a";
    class UParticleSystemComponent* ParticleSystem;
    static constexpr const char* ParticleSystem__UeScsNode = "444be9a852389745acd2bbb1b35aed8a";
    void ExecuteUbergraph_PRJ_Crye_SnowBall(int EntryPoint);
    void OnImpacted(bool PredictedImpact, FHitResult HitResult);
};

}}}   // namespace Game::WeaponsNTools::Cryospray

using PRJ_Crye_SnowBall_C = Game::WeaponsNTools::Cryospray::PRJ_Crye_SnowBall_C;