#pragma once
/*
Blueprint class PRJ_BombSpitter_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class UDamageComponent;
class UProjectileExplosion;
class USimpleHealthComponent;
class USphereComponent;
class UStaticMeshComponent;

namespace Game { namespace LevelElements { namespace RoomObjects { namespace Hazards { namespace BombSpitter {

class PRJ_BombSpitter_C : public AProjectile
{
public:
    UE_CLASS("/Game/LevelElements/RoomObjects/Hazards/BombSpitter/PRJ_BombSpitter", "PRJ_BombSpitter_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UDamageComponent* Damage;
    class USphereComponent* Sphere;
    class USimpleHealthComponent* SimpleHealth;
    class UProjectileExplosion* ProjectileExplosion;
    class UStaticMeshComponent* Projectile;
    void ExecuteUbergraph_PRJ_BombSpitter(int EntryPoint);
    UE_MULTICAST void GoBoom();
    void BndEvt__SimpleHealth_K2Node_ComponentBoundEvent_0_HitSig__DelegateSignature(float Damage_0, const FDamageData& DamageData, bool anyHealthLost);
    void OnImpacted(bool PredictedImpact, const FHitResult& HitResult);
private:
    struct UeMarkers
    {
        static constexpr const char* UeDefaultSubobjects = "/Script/FSD.FSDProjectileMovementComponent ProjectileComponent;/Script/Engine.SphereComponent SphereComponent";
        static constexpr const char* Damage__UeScsNode = "de2b151408492c4fbe7dcd2bfdb405ec";
        static constexpr const char* Sphere__UeScsNode = "2a0ba2903406ec48bded4f6c719afe8c";
        static constexpr const char* SimpleHealth__UeScsNode = "0cda0c40a0506d46840c277a77b49b50";
        static constexpr const char* ProjectileExplosion__UeScsNode = "166a86ef795b2b4b9fbf7ca1b276ec4c";
        static constexpr const char* Projectile__UeScsNode = "0b08041ec1e98941a249f9e831d40f52";
    };
};

}}}}}   // namespace Game::LevelElements::RoomObjects::Hazards::BombSpitter

using PRJ_BombSpitter_C = Game::LevelElements::RoomObjects::Hazards::BombSpitter::PRJ_BombSpitter_C;