#pragma once
/*
Blueprint class PRJ_BigGoo_Buckshot_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "PRJ_BaseBigGooProjectile_C.h"

namespace Game { namespace WeaponsNTools { namespace GooCannon {

class PRJ_BigGoo_Buckshot_C : public Game::WeaponsNTools::GooCannon::PRJ_BaseBigGooProjectile_C
{
public:
    UE_CLASS("/Game/WeaponsNTools/GooCannon/PRJ_BigGoo_Buckshot", "PRJ_BigGoo_Buckshot_C");
private:
    struct UeMarkers
    {
        static constexpr const char* UeDefaultSubobjects = "/Script/FSD.FSDProjectileMovementComponent ProjectileComponent;/Script/Engine.SphereComponent SphereComponent";
    };
};

}}}   // namespace Game::WeaponsNTools::GooCannon

using PRJ_BigGoo_Buckshot_C = Game::WeaponsNTools::GooCannon::PRJ_BigGoo_Buckshot_C;