#pragma once
/*
Blueprint class PRW_MicrowaveGun_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../FSD.h"

class USceneComponent;
class USkeletalMeshComponent;
class UStaticMeshComponent;

namespace Game { namespace WeaponsNTools { namespace MicrowaveGun {

class PRW_MicrowaveGun_C : public AItemPreviewActor
{
public:
    UE_CLASS("/Game/WeaponsNTools/MicrowaveGun/PRW_MicrowaveGun", "PRW_MicrowaveGun_C");
    class USkeletalMeshComponent* SkeletalMesh;
    static constexpr const char* SkeletalMesh__UeScsNode = "b0160e47e80d78498fb34fd940038273";
    class UStaticMeshComponent* StaticMesh;
    static constexpr const char* StaticMesh__UeScsNode = "1a8fbd0ab013754188b7160fa1d5bd9c";
    class USceneComponent* DefaultSceneRoot;
    static constexpr const char* DefaultSceneRoot__UeScsNode = "94aec48dc62b334b812216271850cbfe";
};

}}}   // namespace Game::WeaponsNTools::MicrowaveGun

using PRW_MicrowaveGun_C = Game::WeaponsNTools::MicrowaveGun::PRW_MicrowaveGun_C;