#pragma once
/*
Blueprint class PRW_CoilGun_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../FSD.h"

class USceneComponent;
class USkeletalMeshComponent;

namespace Game { namespace WeaponsNTools { namespace CoilGun {

class PRW_CoilGun_C : public AItemPreviewActor
{
public:
    UE_CLASS("/Game/WeaponsNTools/CoilGun/PRW_CoilGun", "PRW_CoilGun_C");
    class USkeletalMeshComponent* SkeletalMesh;
    static constexpr const char* SkeletalMesh__UeScsNode = "7879a6f31acffa4da0a9e6807ab00c5f";
    class USceneComponent* DefaultSceneRoot;
    static constexpr const char* DefaultSceneRoot__UeScsNode = "89348bb35dcf584597d2342de3c5330f";
};

}}}   // namespace Game::WeaponsNTools::CoilGun

using PRW_CoilGun_C = Game::WeaponsNTools::CoilGun::PRW_CoilGun_C;