#pragma once
/*
Blueprint class PRW_CombatShotgun_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../FSD.h"

class USceneComponent;
class USkeletalMeshComponent;

namespace Game { namespace WeaponsNTools { namespace CombatShotgun {

class PRW_CombatShotgun_C : public AItemPreviewActor
{
public:
    UE_CLASS("/Game/WeaponsNTools/CombatShotgun/PRW_CombatShotgun", "PRW_CombatShotgun_C");
    class USkeletalMeshComponent* SkeletalMesh;
    static constexpr const char* SkeletalMesh__UeScsNode = "4229f1028e99134e80a962087e4ab3bc";
    class USceneComponent* DefaultSceneRoot;
    static constexpr const char* DefaultSceneRoot__UeScsNode = "0dec234eb3ce21448c884352b20da4e0";
};

}}}   // namespace Game::WeaponsNTools::CombatShotgun

using PRW_CombatShotgun_C = Game::WeaponsNTools::CombatShotgun::PRW_CombatShotgun_C;