#pragma once
/*
Blueprint class PRW_PickAxe_Scout_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "PRW_PickAxe_C.h"

namespace Game { namespace WeaponsNTools { namespace Pickaxe {

class PRW_PickAxe_Scout_C : public Game::WeaponsNTools::Pickaxe::PRW_PickAxe_C
{
public:
    UE_CLASS("/Game/WeaponsNTools/Pickaxe/PRW_PickAxe_Scout", "PRW_PickAxe_Scout_C");
private:
    struct UeMarkers
    {
        static constexpr const char* UeDefaultSubobjects = "/Script/Engine.SceneComponent RootComponent;/Script/Engine.SceneComponent TP_RootComponent";
    };
};

}}}   // namespace Game::WeaponsNTools::Pickaxe

using PRW_PickAxe_Scout_C = Game::WeaponsNTools::Pickaxe::PRW_PickAxe_Scout_C;