#pragma once
/*
Blueprint class SCREEN_MissionComplete_DeepDive_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "SCREEN_MissionComplete_Base_C.h"
#include "../SlateCore.h"
#include "../UMG.h"

class UCappedResource;
class UDeepDive;
class UFSDLabelWidget;
class UHorizontalBox;
class UTextBlock;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_ButtonScalable2_C; }}}}
namespace Game { namespace UI { namespace Menu_MIssionCompleteMK2 { class ITM_DeepDiveStatus_Animator_C; class ITM_DeepDiveStatus_Stage_C; }}}
namespace Game { namespace UI { namespace Menu_MissionStart { class ITM_CharacterDeepDive_C; class ITM_DeepDiveHeader_C; class ITM_DeepDive_MisCompBG_C; }}}

namespace Game { namespace UI { namespace Menu_MIssionCompleteMK2 {

class SCREEN_MissionComplete_DeepDive_C : public Game::UI::Menu_MIssionCompleteMK2::SCREEN_MissionComplete_Base_C
{
public:
    UE_CLASS("/Game/UI/Menu_MIssionCompleteMK2/SCREEN_MissionComplete_DeepDive", "SCREEN_MissionComplete_DeepDive_C");
    using Basic_ButtonScalable2_C = Game::UI::Art::WidgetParts::Basic_ButtonScalable2_C;
    using ITM_CharacterDeepDive_C = Game::UI::Menu_MissionStart::ITM_CharacterDeepDive_C;
    using ITM_DeepDiveHeader_C = Game::UI::Menu_MissionStart::ITM_DeepDiveHeader_C;
    using ITM_DeepDiveStatus_Animator_C = Game::UI::Menu_MIssionCompleteMK2::ITM_DeepDiveStatus_Animator_C;
    using ITM_DeepDiveStatus_Stage_C = Game::UI::Menu_MIssionCompleteMK2::ITM_DeepDiveStatus_Stage_C;
    using ITM_DeepDive_MisCompBG_C = Game::UI::Menu_MissionStart::ITM_DeepDive_MisCompBG_C;
    FPointerToUberGraphFrame UberGraphFrame_SCREEN_MissionComplete_DeepDive_C;
    static constexpr const char* UberGraphFrame_SCREEN_MissionComplete_DeepDive_C__UeName = "UberGraphFrame";
    Basic_ButtonScalable2_C* BTN_Continue;
    class UTextBlock* Data_CodeName;
    class UFSDLabelWidget* DATA_MissionTime;
    class UTextBlock* Data_Region;
    class UHorizontalBox* DATA_Resources;
    ITM_DeepDive_MisCompBG_C* ITM_DeepDive_MisCompBG;
    ITM_DeepDiveHeader_C* ITM_DeepDiveHeader;
    ITM_DeepDiveStatus_Stage_C* ITM_DeepDiveStage_0;
    ITM_DeepDiveStatus_Stage_C* ITM_DeepDiveStage_1;
    ITM_DeepDiveStatus_Stage_C* ITM_DeepDiveStage_2;
    ITM_DeepDiveStatus_Animator_C* ITM_DeepDiveStatus_Animator;
    ITM_CharacterDeepDive_C* Player1;
    ITM_CharacterDeepDive_C* Player2;
    ITM_CharacterDeepDive_C* Player3;
    ITM_CharacterDeepDive_C* Player4;
    class UTextBlock* TXT_Codename;
    class UTextBlock* TXT_Region;
    TArray<ITM_CharacterDeepDive_C*> CharacterItems;
    TArray<ITM_DeepDiveStatus_Stage_C*> stages;
    bool CountDownBegun;
    bool ContinueClicked;
    bool AnimationsFinished;
    void ExecuteUbergraph_SCREEN_MissionComplete_DeepDive(int EntryPoint);
    void InitializeScreen();
    void OnDeepDiveContinueCountdownChanged();
    void Update_Continue_Button();
    static constexpr const char* Update_Continue_Button__UeName = "Update Continue Button";
    void Click_Continue();
    static constexpr const char* Click_Continue__UeName = "Click Continue";
    void Setup_Count_Down();
    static constexpr const char* Setup_Count_Down__UeName = "Setup Count Down";
    void OnUpdateCountDown();
    void BndEvt__BTN_Continue_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();
    void UpdateMissionTime(int Value);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void BeginScreen();
    void CreateResources();
    void AddResource(class UCappedResource* Resource);
    UE_PURE class UDeepDive* GetCurrentDeepDive();
    UE_COSMETIC FEventReply OnKeyUp(FGeometry MyGeometry, FKeyEvent InKeyEvent);
    UE_PURE bool IsValidResource(class UCappedResource* Resource) const;
};

}}}   // namespace Game::UI::Menu_MIssionCompleteMK2

using SCREEN_MissionComplete_DeepDive_C = Game::UI::Menu_MIssionCompleteMK2::SCREEN_MissionComplete_DeepDive_C;