#pragma once
/*
Blueprint class SCREEN_MissionComplete_Season_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class UCanvasPanel;
class UHorizontalBox;
class UImage;
class UReward;
class UTextBlock;
class UUniformGridPanel;
class UVerticalBox;
class UWidgetAnimation;
class UWidgetSwitcher;
namespace Game { namespace UI { namespace Global_UI_Elements { class UI_GlowBackground_C; }}}
namespace Game { namespace UI { namespace Menu_Seasons { class ITM_SeasonProgressBar_C; class ITM_Season_Challenge_C; class ITM_Season_RewardImageSingle_C; }}}

namespace Game { namespace UI { namespace Menu_MIssionCompleteMK2 {

class SCREEN_MissionComplete_Season_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_MIssionCompleteMK2/SCREEN_MissionComplete_Season", "SCREEN_MissionComplete_Season_C");
    using ITM_SeasonProgressBar_C = Game::UI::Menu_Seasons::ITM_SeasonProgressBar_C;
    using ITM_Season_Challenge_C = Game::UI::Menu_Seasons::ITM_Season_Challenge_C;
    using ITM_Season_RewardImageSingle_C = Game::UI::Menu_Seasons::ITM_Season_RewardImageSingle_C;
    using UI_GlowBackground_C = Game::UI::Global_UI_Elements::UI_GlowBackground_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* SeasonMultiplierIntro;
    class UWidgetAnimation* LevelUpSmoke;
    class UWidgetAnimation* RemoveLevelUpBanner;
    class UWidgetAnimation* Appear;
    class UWidgetAnimation* PerformancePointShake;
    class UWidgetAnimation* HideEvents;
    class UWidgetAnimation* NewRewardIntro;
    class UImage* Twox;
    static constexpr const char* Twox__UeName = "2x";
    class UCanvasPanel* CanvasPanel_PPCounting;
    class UHorizontalBox* HB_PointsGained;
    class UHorizontalBox* HorizontalBox_Challenges;
    class UImage* Icon_SeasonXP;
    class UImage* Image_559;
    class UImage* Image_BG;
    class UImage* Image_BG_Topline_1;
    class UImage* Image_BottomSmoke;
    class UImage* Image_Line;
    class UImage* Image_Line_1;
    class UImage* Image_OktoberfestBeer;
    ITM_SeasonProgressBar_C* ITM_SeasonProgressBar;
    class UImage* NoiseImage;
    class UImage* PlayerCharacterImage;
    class UTextBlock* Text_XP_Gained;
    UI_GlowBackground_C* UI_GlowBackground;
    class UUniformGridPanel* UniformGridPanel_Rewards;
    class UImage* Unseasoned;
    class UVerticalBox* VBox_Events;
    class UVerticalBox* VBox_LevelUpHolder;
    class UVerticalBox* VerticalBox_Rewards;
    class UVerticalBox* VerticalBox_SeasonMultiplier;
    class UVerticalBox* VerticalBox_XPGain;
    class UWidgetSwitcher* WidgetSwitcher_CountPP;
    TMulticastInlineDelegate<void()> SeasonFlowFinished;
    int tmpIndex;
    int currXPCount;
    TArray<ITM_Season_Challenge_C*> Challenges;
    bool FirstReward;
    TArray<FSeasonLevel> Rewards;
    int RewardIndex;
    bool IsRewardFlowActive;
    bool IsUnseasoned;
    void ExecuteUbergraph_SCREEN_MissionComplete_Season(int EntryPoint);
    void StartEventsXP();
    void StartXPMultiplierFlow();
    void ShowNextReward();
    UE_COSMETIC void Destruct();
    void RefreshShowroom();
    void OnRewardIntroFinished();
    void LevelReached(int Level);
    void OnAddPoints_Event(ITM_Season_Challenge_C* Challenge);
    void CreateChallenges();
    void OnAppeared();
    void PlayIntro();
    void HideEventsFinished();
    void ContinueReward1();
    void PIE_UpdateXPText();
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void OnShowLevelRewards(int Level);
    UE_COSMETIC void Construct();
    void FlowFinished();
    void StartChallenges();
    void StartSeasonFlow();
    void RewardIntroFinished();
    void AddRewardWithAnim(class UReward* Reward, ITM_Season_RewardImageSingle_C*& RewardWidget);
    void AddPoints(int Points);
    void AddLevelUpBanner(int Level);
    void SequenceEvent__ENTRYPOINTSCREEN_MissionComplete_Season_0();
};

}}}   // namespace Game::UI::Menu_MIssionCompleteMK2

using SCREEN_MissionComplete_Season_C = Game::UI::Menu_MIssionCompleteMK2::SCREEN_MissionComplete_Season_C;