#pragma once
/*
Blueprint class ShowProfile_ToolTip_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../UMG.h"

class UImage;
class URichTextSizable;
class UTextBlock;
class UWidget;
class UWidgetAnimation;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_Menu_MinimalWindow_C; }}}}

namespace Game { namespace UI { namespace ToolTips {

class ShowProfile_ToolTip_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/ToolTips/ShowProfile_ToolTip", "ShowProfile_ToolTip_C");
    using Basic_Menu_MinimalWindow_C = Game::UI::Art::WidgetParts::Basic_Menu_MinimalWindow_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* AnimFadeIn;
    class UWidgetAnimation* Intro;
    class UImage* BackgroundImage;
    Basic_Menu_MinimalWindow_C* Basic_Menu_MinimalWindow;
    class UTextBlock* CountryTxt;
    class UTextBlock* ServernameTxt;
    class URichTextSizable* ShowProfileTxt;
    FText Text;
    FVector2D Position;
    FVector2D Alignment;
    FText ServerName;
    FText CountryName;
    void ExecuteUbergraph_ShowProfile_ToolTip(int EntryPoint);
    void Set_Tool_Tip_Owner(class UWidget* Owner);
    static constexpr const char* Set_Tool_Tip_Owner__UeName = "Set Tool Tip Owner";
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void SetTarget(class UWidget* Target_Widget);
    void SetText(FText ToolTip, FText Region, FText Name_0);
    void SetPostionAndAlignment(FVector2D InPosition, FVector2D InAlignment);
    void FadeIn(float Duration);
};

}}}   // namespace Game::UI::ToolTips

using ShowProfile_ToolTip_C = Game::UI::ToolTips::ShowProfile_ToolTip_C;