#pragma once
/*
Blueprint class STE_Revolver_Neurotoxin_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../FSD.h"

namespace Game { namespace WeaponsNTools { namespace Revolver {

class STE_Revolver_Neurotoxin_C : public UStatusEffect
{
public:
    UE_CLASS("/Game/WeaponsNTools/Revolver/STE_Revolver_Neurotoxin", "STE_Revolver_Neurotoxin_C");
private:
    struct UeMarkers
    {
        static constexpr const char* UeDefaultSubobjects = "/Script/FSD.DotStatusEffectItem DotStatusEffectItem_0;/Script/FSD.StatChangeStatusEffectItem StatChangeStatusEffectItem_0";
    };
};

}}}   // namespace Game::WeaponsNTools::Revolver

using STE_Revolver_Neurotoxin_C = Game::WeaponsNTools::Revolver::STE_Revolver_Neurotoxin_C;