#pragma once
/*
Blueprint class STE_HarmlessSmoke_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../FSD.h"

namespace Game { namespace WeaponsNTools { namespace SupplyPod {

class STE_HarmlessSmoke_C : public UStatusEffect
{
public:
    UE_CLASS("/Game/WeaponsNTools/SupplyPod/STE_HarmlessSmoke", "STE_HarmlessSmoke_C");
};

}}}   // namespace Game::WeaponsNTools::SupplyPod

using STE_HarmlessSmoke_C = Game::WeaponsNTools::SupplyPod::STE_HarmlessSmoke_C;