#pragma once
/*
Blueprint class STE_StickyGooRT_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../FSD.h"

namespace Game { namespace Landscape { namespace ReactiveTerrain {

class STE_StickyGooRT_C : public UStatusEffect
{
public:
    UE_CLASS("/Game/Landscape/ReactiveTerrain/STE_StickyGooRT", "STE_StickyGooRT_C");
};

}}}   // namespace Game::Landscape::ReactiveTerrain

using STE_StickyGooRT_C = Game::Landscape::ReactiveTerrain::STE_StickyGooRT_C;