#pragma once
/*
Blueprint class STE_WoodlouseColdResistance_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../FSD.h"

namespace Game { namespace Enemies { namespace Woodlouse {

class STE_WoodlouseColdResistance_C : public UStatusEffect
{
public:
    UE_CLASS("/Game/Enemies/Woodlouse/STE_WoodlouseColdResistance", "STE_WoodlouseColdResistance_C");
};

}}}   // namespace Game::Enemies::Woodlouse

using STE_WoodlouseColdResistance_C = Game::Enemies::Woodlouse::STE_WoodlouseColdResistance_C;