#pragma once
/*
Blueprint class STE_Stalker_slowdown_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../FSD.h"

namespace Game { namespace Enemies { namespace Spider { namespace Stalker {

class STE_Stalker_slowdown_C : public UStatusEffect
{
public:
    UE_CLASS("/Game/Enemies/Spider/Stalker/STE_Stalker_slowdown", "STE_Stalker_slowdown_C");
};

}}}}   // namespace Game::Enemies::Spider::Stalker

using STE_Stalker_slowdown_C = Game::Enemies::Spider::Stalker::STE_Stalker_slowdown_C;