#pragma once
/*
Blueprint class STE_FrostGeyser1_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../FSD.h"

namespace Game { namespace LevelElements { namespace RoomObjects { namespace Hazards { namespace FrostGeyser {

class STE_FrostGeyser1_C : public UStatusEffect
{
public:
    UE_CLASS("/Game/LevelElements/RoomObjects/Hazards/FrostGeyser/STE_FrostGeyser1", "STE_FrostGeyser1_C");
};

}}}}}   // namespace Game::LevelElements::RoomObjects::Hazards::FrostGeyser

using STE_FrostGeyser1_C = Game::LevelElements::RoomObjects::Hazards::FrostGeyser::STE_FrostGeyser1_C;