#pragma once
/*
Blueprint class STE_Spider_Lobber_Puddle_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../FSD.h"

namespace Game { namespace Enemies { namespace Spider { namespace Lobber {

class STE_Spider_Lobber_Puddle_C : public UStatusEffect
{
public:
    UE_CLASS("/Game/Enemies/Spider/Lobber/STE_Spider_Lobber_Puddle", "STE_Spider_Lobber_Puddle_C");
private:
    struct UeMarkers
    {
        static constexpr const char* UeDefaultSubobjects = "/Script/FSD.DotStatusEffectItem DotStatusEffectItem_0";
    };
};

}}}}   // namespace Game::Enemies::Spider::Lobber

using STE_Spider_Lobber_Puddle_C = Game::Enemies::Spider::Lobber::STE_Spider_Lobber_Puddle_C;