#pragma once
/*
Blueprint class TestLobbyGameMode_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../OnlineSubsystemUtils.h"

class USceneComponent;

namespace Game { namespace UI { namespace Menu_Lobby {

class TestLobbyGameMode_C : public AGameMode
{
public:
    UE_CLASS("/Game/UI/Menu_Lobby/TestLobbyGameMode", "TestLobbyGameMode_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class USceneComponent* DefaultSceneRoot;
    static constexpr const char* DefaultSceneRoot__UeScsNode = "230646e1a711da45a311bf5be84aaaaf";
    void ExecuteUbergraph_TestLobbyGameMode(int EntryPoint);
    void Join_Session(FBlueprintSessionResult Session_Result);
    static constexpr const char* Join_Session__UeName = "Join Session";
    void OnSuccess_CAB842EC41BAFB8B6D6C0595A9F96FB4();
    void OnFailure_CAB842EC41BAFB8B6D6C0595A9F96FB4();
};

}}}   // namespace Game::UI::Menu_Lobby

using TestLobbyGameMode_C = Game::UI::Menu_Lobby::TestLobbyGameMode_C;