#pragma once
/*
Blueprint class TOOLTIP_ServerEntry_Biome_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../SlateCore.h"
#include "../UMG.h"

class UBiome;
class UImage;
class URichTextSizable;
class UTextBlock;
class UVerticalBox;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_Menu_MinimalWindow_C; }}}}

namespace Game { namespace UI { namespace Menu_ServerList {

class TOOLTIP_ServerEntry_Biome_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_ServerList/TOOLTIP_ServerEntry_Biome", "TOOLTIP_ServerEntry_Biome_C");
    using Basic_Menu_MinimalWindow_C = Game::UI::Art::WidgetParts::Basic_Menu_MinimalWindow_C;
    FPointerToUberGraphFrame UberGraphFrame;
    Basic_Menu_MinimalWindow_C* Basic_Menu_MinimalWindow;
    class UImage* BiomeImage;
    class UTextBlock* BiomeName;
    class UVerticalBox* ContentBox;
    class UImage* PlanetZoneImage;
    class URichTextSizable* ShowProfileText;
    FSlateFontInfo ResourceFont;
    class UBiome* Biome;
    void ExecuteUbergraph_TOOLTIP_ServerEntry_Biome(int EntryPoint);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void SetData(class UBiome* InBiome);
};

}}}   // namespace Game::UI::Menu_ServerList

using TOOLTIP_ServerEntry_Biome_C = Game::UI::Menu_ServerList::TOOLTIP_ServerEntry_Biome_C;