#pragma once
/*
Blueprint class TSK_RandomPointFromOrigin_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../AIModule.h"
#include "../CoreUObject.h"
#include "../Engine.h"

class AAIController;
class APawn;
class UDeepPathfinderMovement;

namespace Game { namespace GameElements { namespace Drone { namespace Tasks {

class TSK_RandomPointFromOrigin_C : public UBTTask_BlueprintBase
{
public:
    UE_CLASS("/Game/GameElements/Drone/Tasks/TSK_RandomPointFromOrigin", "TSK_RandomPointFromOrigin_C");
    FPointerToUberGraphFrame UberGraphFrame;
    bool FindAtDistance;
    FBlackboardKeySelector Origin;
    float Distance;
    FBlackboardKeySelector LocationKey;
    FVector OriginVec;
    FVector Vector;
    void ExecuteUbergraph_TSK_RandomPointFromOrigin(int EntryPoint);
    void ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn);
    void snap(bool snap_0, class UDeepPathfinderMovement* Path, FVector Origin_0);
    void ActorOrVector();
};

}}}}   // namespace Game::GameElements::Drone::Tasks

using TSK_RandomPointFromOrigin_C = Game::GameElements::Drone::Tasks::TSK_RandomPointFromOrigin_C;