#pragma once
/*
Blueprint class TSK_SetBool_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../AIModule.h"
#include "../Engine.h"

class AActor;

namespace Game { namespace AI { namespace Tasks {

class TSK_SetBool_C : public UBTTask_BlueprintBase
{
public:
    UE_CLASS("/Game/AI/Tasks/TSK_SetBool", "TSK_SetBool_C");
    FPointerToUberGraphFrame UberGraphFrame;
    FBlackboardKeySelector Key;
    bool Value;
    void ExecuteUbergraph_TSK_SetBool(int EntryPoint);
    void ReceiveExecute(class AActor* OwnerActor);
};

}}}   // namespace Game::AI::Tasks

using TSK_SetBool_C = Game::AI::Tasks::TSK_SetBool_C;