#pragma once
/*
Blueprint class UI_DLC_Season_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class UButton;
class UCanvasPanel;
class UGameDLC;
class UImage;
class UWidgetAnimation;

namespace Game { namespace UI { namespace Menu_Seasons {

class UI_DLC_Season_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_Seasons/UI_DLC_Season", "UI_DLC_Season_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* Click;
    class UWidgetAnimation* Hover;
    class UWidgetAnimation* Idle;
    class UButton* Button_Outer;
    class UCanvasPanel* CanvasPanel_Outer;
    class UImage* DLCImage;
    class UImage* Shadow;
    class UGameDLC* DLC;
    void ExecuteUbergraph_UI_DLC_Season(int EntryPoint);
    void BndEvt__Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
    void Refresh();
    void BndEvt__Button_0_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_0_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature();
    UE_COSMETIC void Construct();
    void OpenDLCInSteamBrowser();
};

}}}   // namespace Game::UI::Menu_Seasons

using UI_DLC_Season_C = Game::UI::Menu_Seasons::UI_DLC_Season_C;