#pragma once
/*
Blueprint class UI_Facility_Objective_Caretaker_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class UFacilityObjective;
class UObjective;
namespace Game { namespace GameElements { namespace Objectives { namespace Facility { class BP_MainFacility_DataVault_C; }}}}
namespace Game { namespace UI { namespace MainOnscreenHUD { namespace Standard { class UI_ImageTinted_C; }}}}

namespace Game { namespace GameElements { namespace Objectives { namespace Facility { namespace UI {

class UI_Facility_Objective_Caretaker_C : public UOptionalObjectiveWidget
{
public:
    UE_CLASS("/Game/GameElements/Objectives/Facility/UI/UI_Facility_Objective_Caretaker", "UI_Facility_Objective_Caretaker_C");
    using BP_MainFacility_DataVault_C = Game::GameElements::Objectives::Facility::BP_MainFacility_DataVault_C;
    using UI_ImageTinted_C = Game::UI::MainOnscreenHUD::Standard::UI_ImageTinted_C;
    FPointerToUberGraphFrame UberGraphFrame;
    UI_ImageTinted_C* Img_Caretaker_Outline;
    UI_ImageTinted_C* Img_Caretaker_Solid;
    UI_ImageTinted_C* Img_Shield;
    bool ShieldOn;
    bool CaretakerDestroyed;
    BP_MainFacility_DataVault_C* mainFacility;
    class UFacilityObjective* Objective;
    void ExecuteUbergraph_UI_Facility_Objective_Caretaker(int EntryPoint);
    void FacilityActivated();
    void SetMainFacility(BP_MainFacility_DataVault_C* InMainFacility);
    void OnObjectiveUpdated(class UObjective* Objective_0);
    void SetObjective(class UObjective* obj);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void Refresh();
    void TryFindMainFacility();
    void GetCaretakerIsAlive(bool& IsAlive);
};

}}}}}   // namespace Game::GameElements::Objectives::Facility::UI

using UI_Facility_Objective_Caretaker_C = Game::GameElements::Objectives::Facility::UI::UI_Facility_Objective_Caretaker_C;