#pragma once
/*
Blueprint class UI_HackingTool_Progress_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../UMG.h"

class UHorizontalBox;
class UImage;

namespace Game { namespace WeaponsNTools { namespace HackingTool { namespace UI {

class UI_HackingTool_Progress_C : public UUserWidget
{
public:
    UE_CLASS("/Game/WeaponsNTools/HackingTool/UI/UI_HackingTool_Progress", "UI_HackingTool_Progress_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UHorizontalBox* BulletsBox;
    int MaxStages;
    int CurrentStage;
    TArray<class UImage*> stages;
    TArray<class UImage*> Transitions;
    TMulticastInlineDelegate<void(int InNewStage, int InTotalStages)> OnNextStage;
    FVector2D BulletSize;
    FVector2D SeparatorSize;
    void ExecuteUbergraph_UI_HackingTool_Progress(int EntryPoint);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void SetMaxStages(int MaxStages_0);
    void SetCurrentStage(int InCurrentStage);
    void NextStage();
    void GetCurrentStage(int& CurrentStage_0);
    void Update(int InCurrent, int InMax);
    void GetMaxStages(int& MaxStages_0) const;
};

}}}}   // namespace Game::WeaponsNTools::HackingTool::UI

using UI_HackingTool_Progress_C = Game::WeaponsNTools::HackingTool::UI::UI_HackingTool_Progress_C;