#pragma once
/*
Blueprint class UI_InfoScreen_BackEndNotification_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"
#include "../UMG.h"

class UImage;
class USizeBox;
class UTextBlock;
class UWidgetAnimation;

namespace Game { namespace UI { namespace Menu_StartScreen {

class UI_InfoScreen_BackEndNotification_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_StartScreen/UI_InfoScreen_BackEndNotification", "UI_InfoScreen_BackEndNotification_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* Blink;
    class UTextBlock* Body_Text;
    class UTextBlock* Header_Text;
    class UImage* LeftDot;
    class USizeBox* OptionalSize;
    class UImage* RightDot;
    FBackendNotificationEvent Notification;
    FSizeBoxSettings SizeSettings;
    void ExecuteUbergraph_UI_InfoScreen_BackEndNotification(int EntryPoint);
    UE_COSMETIC void Construct();
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void SetNotification(FBackendNotificationEvent InNotification);
};

}}}   // namespace Game::UI::Menu_StartScreen

using UI_InfoScreen_BackEndNotification_C = Game::UI::Menu_StartScreen::UI_InfoScreen_BackEndNotification_C;