#pragma once
/*
Blueprint class UI_InfoScreen_DLCwidget_Setup_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class UButton;
class UGameDLC;
class UImage;
class UTexture2D;
class UWidgetAnimation;

namespace Game { namespace UI { namespace Menu_StartScreen {

class UI_InfoScreen_DLCwidget_Setup_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_StartScreen/UI_InfoScreen_DLCwidget_Setup", "UI_InfoScreen_DLCwidget_Setup_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* Idle;
    class UButton* Button_0;
    class UImage* Image_BG;
    class UImage* Image_Flash;
    class UTexture2D* Image;
    class UGameDLC* GameDLC;
    TMulticastInlineDelegate<void(class UGameDLC* DLC)> OnClicked;
    TMulticastInlineDelegate<void(class UGameDLC* DLC)> OnHovered;
    TMulticastInlineDelegate<void(class UGameDLC* DLC)> OnUnhovered;
    void ExecuteUbergraph_UI_InfoScreen_DLCwidget_Setup(int EntryPoint);
    void BndEvt__Button_0_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_0_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void PlayAnim();
};

}}}   // namespace Game::UI::Menu_StartScreen

using UI_InfoScreen_DLCwidget_Setup_C = Game::UI::Menu_StartScreen::UI_InfoScreen_DLCwidget_Setup_C;