#pragma once
/*
Blueprint class UI_LoadingTips_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../SlateCore.h"
#include "../UMG.h"

class UBorder;
class UCanvasPanel;
class UHorizontalBox;
class UImage;
class UTextBlock;
class UWidgetAnimation;
namespace Game { namespace UI { namespace Global_UI_Elements { class UI_AdvancedLabel_C; }}}

namespace Game { namespace UI { namespace Tips {

class UI_LoadingTips_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Tips/UI_LoadingTips", "UI_LoadingTips_C");
    using UI_AdvancedLabel_C = Game::UI::Global_UI_Elements::UI_AdvancedLabel_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* FadeIn;
    class UWidgetAnimation* FadeOut;
    class UBorder* Border_0;
    class UTextBlock* HintCategoryText;
    class UTextBlock* HintDescription;
    class UBorder* HintHolder;
    UI_AdvancedLabel_C* HintInputLabel;
    class UHorizontalBox* HorizontalBox_2;
    class UImage* Image_0;
    class UImage* Image_1;
    class UImage* Image_2;
    class UImage* Image_3;
    class UCanvasPanel* RootCanvas;
    float Timer;
    float TimeToDisplay;
    bool HasfadedOut;
    int ListLength;
    int PreviewHintIndex;
    uint8 PreviewInputAs;
    void ExecuteUbergraph_UI_LoadingTips(int EntryPoint);
    void OnFadeOutFinished();
    void OnFadeInFinished();
    void Show_Hint(int Index_0);
    static constexpr const char* Show_Hint__UeName = "Show Hint";
    UE_COSMETIC void Tick(FGeometry MyGeometry, float InDeltaTime);
    UE_COSMETIC void Construct();
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
};

}}}   // namespace Game::UI::Tips

using UI_LoadingTips_C = Game::UI::Tips::UI_LoadingTips_C;