#pragma once
/*
Blueprint class UI_LockOn_TargetCounter_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class UWidgetAnimation;
namespace Game { namespace UI { namespace MainOnscreenHUD { namespace Standard { class UI_ImageTinted_C; }}}}

namespace Game { namespace WeaponsNTools { namespace LockOnRifle { namespace UI {

class UI_LockOn_TargetCounter_C : public UUserWidget
{
public:
    UE_CLASS("/Game/WeaponsNTools/LockOnRifle/UI/UI_LockOn_TargetCounter", "UI_LockOn_TargetCounter_C");
    using UI_ImageTinted_C = Game::UI::MainOnscreenHUD::Standard::UI_ImageTinted_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* AnimPing;
    UI_ImageTinted_C* Background;
    UI_ImageTinted_C* Foreground;
    bool IsOn;
    void ExecuteUbergraph_UI_LockOn_TargetCounter(int EntryPoint);
    void Ping();
    void SetOn(bool InIsOn);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void Refresh();
};

}}}}   // namespace Game::WeaponsNTools::LockOnRifle::UI

using UI_LockOn_TargetCounter_C = Game::WeaponsNTools::LockOnRifle::UI::UI_LockOn_TargetCounter_C;