#pragma once
/*
Blueprint class UI_MediaPlayer_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class UImage;
class UWidgetAnimation;

namespace Game { namespace UI { namespace MENU_Merch {

class UI_MediaPlayer_C : public UMediaPlayerWidget
{
public:
    UE_CLASS("/Game/UI/MENU_Merch/UI_MediaPlayer", "UI_MediaPlayer_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* AnimFadeIn;
    class UImage* FadeInImage;
    void ExecuteUbergraph_UI_MediaPlayer(int EntryPoint);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void ReceiveStateChanged(EMediaPlayerState InState);
    UE_COSMETIC void Construct();
    void UpdateState();
};

}}}   // namespace Game::UI::MENU_Merch

using UI_MediaPlayer_C = Game::UI::MENU_Merch::UI_MediaPlayer_C;