#pragma once
/*
Blueprint class UI_RewardUnlock_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class UHorizontalBox;
class UImage;
class UPlayerCharacterID;
class USizeBox;
class UTextBlock;
class UTexture;
class UTexture2D;
class UWidgetAnimation;
class UWidgetSwitcher;
namespace Game { namespace UI { namespace Menu_Wardrobe { class ITM_GeneratedIcon_Item_C; }}}

namespace Game { namespace UI { namespace HUD_SpaceRig { namespace CampaignNotifications {

class UI_RewardUnlock_C : public URewardWidget
{
public:
    UE_CLASS("/Game/UI/HUD_SpaceRig/CampaignNotifications/UI_RewardUnlock", "UI_RewardUnlock_C");
    using ITM_GeneratedIcon_Item_C = Game::UI::Menu_Wardrobe::ITM_GeneratedIcon_Item_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* CelebrateAnim;
    class UImage* BigImage;
    class USizeBox* BigImageSize;
    class UHorizontalBox* HorizontalBox_1;
    class UImage* IconLeft;
    class UImage* IconRight;
    class UWidgetSwitcher* ImageSwitcher;
    ITM_GeneratedIcon_Item_C* ITM_GeneratedIcon;
    class UTextBlock* UnlockedText;
    class UTextBlock* UnlockTitle;
    void ExecuteUbergraph_UI_RewardUnlock(int EntryPoint);
    void PlayReceiveAnim();
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void GetUnlockDetails(bool& IsHidden, FText& OutTitle, class UTexture*& Icon, FLinearColor& IconTint, class UTexture2D*& BigImage_0);
    void SelectCharacterID(class UPlayerCharacterID* OptionalID, class UPlayerCharacterID*& OutputPin);
};

}}}}   // namespace Game::UI::HUD_SpaceRig::CampaignNotifications

using UI_RewardUnlock_C = Game::UI::HUD_SpaceRig::CampaignNotifications::UI_RewardUnlock_C;