#pragma once
/*
Blueprint class UI_RewardUnlock_SkinUnlock_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class UHorizontalBox;
class UImage;
class UOverlay;
class UPlayerCharacterID;
class USizeBox;
class UTextBlock;
class UTexture;
class UWidgetAnimation;
namespace Game { namespace UI { namespace Global_UI_Elements { class ITM_CharacterIcon_C; }}}
namespace Game { namespace UI { namespace Menu_Wardrobe { class ITM_GeneratedIcon_Item_C; }}}

namespace Game { namespace UI { namespace HUD_SpaceRig { namespace CampaignNotifications {

class UI_RewardUnlock_SkinUnlock_C : public URewardWidget
{
public:
    UE_CLASS("/Game/UI/HUD_SpaceRig/CampaignNotifications/UI_RewardUnlock_SkinUnlock", "UI_RewardUnlock_SkinUnlock_C");
    using ITM_CharacterIcon_C = Game::UI::Global_UI_Elements::ITM_CharacterIcon_C;
    using ITM_GeneratedIcon_Item_C = Game::UI::Menu_Wardrobe::ITM_GeneratedIcon_Item_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* CelebrateAnim;
    class UImage* CategoryIcon;
    class USizeBox* CategorySizer;
    class UOverlay* IconOverlay;
    ITM_CharacterIcon_C* ITM_CharacterIcon;
    ITM_GeneratedIcon_Item_C* ITM_GeneratedIcon;
    class UTextBlock* Subtitle;
    class UHorizontalBox* TextAndCharacterBox;
    class UTextBlock* UnlockTitle;
    void ExecuteUbergraph_UI_RewardUnlock_SkinUnlock(int EntryPoint);
    UE_COSMETIC void Construct();
    void PlayReceiveAnim();
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void GetUnlockDetails(FText& OutTitle, FText& OutSubTitle, class UTexture*& Icon);
    void SelectCharacterID(class UPlayerCharacterID* OptionalID, class UPlayerCharacterID*& OutputPin);
    void SetCharacterIcon(class UPlayerCharacterID* characterID, class UPlayerCharacterID*& OutCharacterID);
};

}}}}   // namespace Game::UI::HUD_SpaceRig::CampaignNotifications

using UI_RewardUnlock_SkinUnlock_C = Game::UI::HUD_SpaceRig::CampaignNotifications::UI_RewardUnlock_SkinUnlock_C;