#pragma once
/*
Blueprint class UI_RockCracker_Connection_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class UCanvasPanel;
class UImage;
class UOverlay;
class UTextBlock;
class UWidgetAnimation;
namespace Game { namespace GameElements { namespace Objectives { namespace Refinery { class ITM_Pipeline_BrokenIcon_C; }}}}
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_Image_C; class Basic_ProgressBar_C; }}}}

namespace Game { namespace UI { namespace Art { namespace MainOnScreenHUD { namespace MeteorCrackerEvent {

class UI_RockCracker_Connection_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Art/MainOnScreenHUD/MeteorCrackerEvent/UI_RockCracker_Connection", "UI_RockCracker_Connection_C");
    using Basic_Image_C = Game::UI::Art::WidgetParts::Basic_Image_C;
    using Basic_ProgressBar_C = Game::UI::Art::WidgetParts::Basic_ProgressBar_C;
    using ITM_Pipeline_BrokenIcon_C = Game::GameElements::Objectives::Refinery::ITM_Pipeline_BrokenIcon_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* CrackerActive;
    class UWidgetAnimation* AnimCableProgress;
    class UOverlay* Cable_Anim;
    Basic_Image_C* Cable_Bg;
    ITM_Pipeline_BrokenIcon_C* ITM_Pipeline_BrokenIcon;
    class UImage* Line_RightPercent;
    class UImage* Pod_Broken;
    Basic_ProgressBar_C* Pod_Health;
    Basic_Image_C* RockCracker_Filled;
    class UCanvasPanel* RootCanvas;
    class UTextBlock* TextBlock_HealthPercent;
    float CableAnimProgress;
    float Health;
    bool PlayCableAnim;
    bool LeftSide;
    bool Inversed;
    bool EventStarted;
    void ExecuteUbergraph_UI_RockCracker_Connection(int EntryPoint);
    void CableConnected();
    void CrackerBuild();
    void SetEventStarted();
    void PlayActiveAnim(bool Active);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void SetCableAnimProgress(float InValue);
    void SetHealth(float InHealth);
    void SetPlayCableAnim(bool InPlay);
};

}}}}}   // namespace Game::UI::Art::MainOnScreenHUD::MeteorCrackerEvent

using UI_RockCracker_Connection_C = Game::UI::Art::MainOnScreenHUD::MeteorCrackerEvent::UI_RockCracker_Connection_C;