#pragma once
/*
Blueprint class UI_RandomizeLoadoutWithUndo_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class APlayerCharacter;
class UBorder;
class UButton;
class UImage;
class UPlayerCharacterID;
class UVerticalBox;
class UWidgetAnimation;
namespace Game { namespace UI { namespace Menu_Wardrobe { class UI_RandomizeIcon_C; class UI_UndoIcon_C; }}}

namespace Game { namespace UI { namespace Menu_Wardrobe {

class UI_RandomizeLoadoutWithUndo_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_Wardrobe/UI_RandomizeLoadoutWithUndo", "UI_RandomizeLoadoutWithUndo_C");
    using UI_RandomizeIcon_C = Game::UI::Menu_Wardrobe::UI_RandomizeIcon_C;
    using UI_UndoIcon_C = Game::UI::Menu_Wardrobe::UI_UndoIcon_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* OnHoverV2;
    class UWidgetAnimation* OnHover;
    class UBorder* Background;
    class UButton* Button_Dice;
    class UButton* Button_HoverCheck;
    class UButton* Button_Randomize;
    class UButton* Button_Undo;
    class UBorder* FrameBorder;
    class UImage* Image_Dice;
    class UBorder* SelectionBorder;
    UI_RandomizeIcon_C* UI_RandomizeIcon;
    UI_UndoIcon_C* UI_UndoIcon;
    class UVerticalBox* VerticalBox_Buttons;
    TArray<FLoadoutCopy> Loadouts;
    bool RandomizeVanity;
    bool RandomizeWeapons;
    bool RandomizePickaxe;
    int CurrIndex;
    TMulticastInlineDelegate<void()> LoadoutRefreshed;
    bool IsButtonsOut;
    class UPlayerCharacterID* characterID;
    void ExecuteUbergraph_UI_RandomizeLoadoutWithUndo(int EntryPoint);
    void SetCharacter(class UPlayerCharacterID* characterID_0);
    void OnHoverAnimFinished();
    UE_COSMETIC void Construct();
    void Clear();
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void BndEvt__UI_RandomizeLoadoutWithUndo_Button_Undo_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__UI_RandomizeLoadoutWithUndo_Button_Undo_K2Node_ComponentBoundEvent_9_OnButtonHoverEvent__DelegateSignature();
    void CheckHide();
    void BndEvt__UI_RandomizeLoadoutWithUndo_Button_HoverCheck_K2Node_ComponentBoundEvent_8_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__UI_RandomizeLoadoutWithUndo_Button_HoverCheck_K2Node_ComponentBoundEvent_7_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__UI_RandomizeLoadoutWithUndo_Button_ShowRandomize_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__UI_RandomizeLoadoutWithUndo_Button_ShowRandomize_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature();
    void SetHovered(bool IsHovered_0);
    void BndEvt__UI_RandomizeLoadoutWithUndo_ShuffleButton_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__UI_RandomizeLoadoutWithUndo_ShuffleButton_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__UI_RandomizeLoadoutWithUndo_Button_Undo_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature();
    void BndEvt__UI_RandomizeLoadoutWithUndo_ShuffleButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature();
    void GetCharacter(class APlayerCharacter*& AsPlayer_Character);
    void GetCharacterID(class UPlayerCharacterID*& characterID_0);
};

}}}   // namespace Game::UI::Menu_Wardrobe

using UI_RandomizeLoadoutWithUndo_C = Game::UI::Menu_Wardrobe::UI_RandomizeLoadoutWithUndo_C;