#pragma once
/*
Blueprint class UI_ShoutBox_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class APlayerCharacter;
class UFSDLabelWidget;
class UImage;
class UTextBlock;
class UWidgetAnimation;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_HUD_BracketWindowSmall_C; }}}}

namespace Game { namespace UI { namespace MainOnscreenHUD { namespace Subtitles {

class UI_ShoutBox_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/MainOnscreenHUD/Subtitles/UI_ShoutBox", "UI_ShoutBox_C");
    using Basic_HUD_BracketWindowSmall_C = Game::UI::Art::WidgetParts::Basic_HUD_BracketWindowSmall_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* AnimIntro;
    class UImage* CharacterIcon;
    class UTextBlock* DATA_Class;
    class UTextBlock* DATA_Distance;
    class UFSDLabelWidget* DATA_Message;
    Basic_HUD_BracketWindowSmall_C* ShoutWindow;
    FTimerHandle TimeoutHandle;
    bool ShoutActive;
    TMulticastInlineDelegate<void(bool InShoutActive)> OnShoutActiveChanged;
    void ExecuteUbergraph_UI_ShoutBox(int EntryPoint);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void ShoutStart(class APlayerCharacter* InSender, FText InText, float InDuration);
    void OnShoutEnd();
    void SetDistance(float InDistance);
    void UpdateBoxWidth();
};

}}}}   // namespace Game::UI::MainOnscreenHUD::Subtitles

using UI_ShoutBox_C = Game::UI::MainOnscreenHUD::Subtitles::UI_ShoutBox_C;