#pragma once
/*
Blueprint class UI_SimpleAngleIndicator_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../SlateCore.h"
#include "../UMG.h"

class UCanvasPanel;
class USizeBox;
class UWidgetAnimation;
namespace Game { namespace UI { namespace MainOnscreenHUD { namespace Standard { class UI_ImageTinted_C; }}}}

namespace Game { namespace WeaponsNTools { namespace _Crosshairs { namespace NewCrossHairs {

class UI_SimpleAngleIndicator_C : public UUserWidget
{
public:
    UE_CLASS("/Game/WeaponsNTools/_Crosshairs/NewCrossHairs/UI_SimpleAngleIndicator", "UI_SimpleAngleIndicator_C");
    using UI_ImageTinted_C = Game::UI::MainOnscreenHUD::Standard::UI_ImageTinted_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* AnimFadeIn;
    UI_ImageTinted_C* ArrowLeft;
    UI_ImageTinted_C* ArrowRight;
    class UCanvasPanel* ClippingCanvas;
    class USizeBox* SizeRanges;
    float Angle;
    float HeightOffset;
    FVector2D ClippingSize;
    float ArrowSize;
    float ArrowOffset;
    void ExecuteUbergraph_UI_SimpleAngleIndicator(int EntryPoint);
    UE_COSMETIC void Construct();
    UE_COSMETIC void Tick(FGeometry MyGeometry, float InDeltaTime);
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void SetAngle(float AngleDegrees);
};

}}}}   // namespace Game::WeaponsNTools::_Crosshairs::NewCrossHairs

using UI_SimpleAngleIndicator_C = Game::WeaponsNTools::_Crosshairs::NewCrossHairs::UI_SimpleAngleIndicator_C;