#pragma once
/*
Blueprint class W_TutorialDepositGold_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "W_TutorialContent_Base_C.h"

class UResourceBank;

namespace Game { namespace UI { namespace Tutorial {

class W_TutorialDepositGold_C : public Game::UI::Tutorial::W_TutorialContent_Base_C
{
public:
    UE_CLASS("/Game/UI/Tutorial/W_TutorialDepositGold", "W_TutorialDepositGold_C");
    FPointerToUberGraphFrame UberGraphFrame_W_TutorialDepositGold_C;
    float Gold_Mined;
    float GoldToMine;
    float StartAmount;
    void ExecuteUbergraph_W_TutorialDepositGold(int EntryPoint);
    void FinishedDepositing(class UResourceBank* ResourceBank);
    void UpdateText();
    void OnShown();
private:
    struct UeMarkers
    {
        static constexpr const char* UberGraphFrame_W_TutorialDepositGold_C__UeName = "UberGraphFrame";
        static constexpr const char* Gold_Mined__UeName = "Gold Mined";
    };
};

}}}   // namespace Game::UI::Tutorial

using W_TutorialDepositGold_C = Game::UI::Tutorial::W_TutorialDepositGold_C;