#pragma once
/*
Blueprint class WeaponDisplay_AssaultRifle_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "WeaponDisplay_Base_AmmoCount_C.h"

class UHorizontalBox;
class UImage;
class UTextBlock;
namespace Game { namespace Art { namespace _TestingGrounds { namespace UItesting { class AnimatedStaticOverlay_WithScanlines_LightVersion_C; }}}}

namespace Game { namespace UI { namespace WeaponDisplays {

class WeaponDisplay_AssaultRifle_C : public Game::UI::WeaponDisplays::WeaponDisplay_Base_AmmoCount_C
{
public:
    UE_CLASS("/Game/UI/WeaponDisplays/WeaponDisplay_AssaultRifle", "WeaponDisplay_AssaultRifle_C");
    using AnimatedStaticOverlay_WithScanlines_LightVersion_C = Game::Art::_TestingGrounds::UItesting::AnimatedStaticOverlay_WithScanlines_LightVersion_C;
    FPointerToUberGraphFrame UberGraphFrame_WeaponDisplay_AssaultRifle_C;
    static constexpr const char* UberGraphFrame_WeaponDisplay_AssaultRifle_C__UeName = "UberGraphFrame";
    class UHorizontalBox* AmmoBox;
    class UTextBlock* AmmoCount;
    AnimatedStaticOverlay_WithScanlines_LightVersion_C* AnimatedStaticOverlay_WithScanlines_LightVersion;
    class UImage* Image_88;
    class UTextBlock* MaxAmmo;
    void ExecuteUbergraph_WeaponDisplay_AssaultRifle(int EntryPoint);
    void SetClipCount(int Value);
    void SetTotalCount(int Value);
};

}}}   // namespace Game::UI::WeaponDisplays

using WeaponDisplay_AssaultRifle_C = Game::UI::WeaponDisplays::WeaponDisplay_AssaultRifle_C;