#pragma once
/*
Blueprint class WeaponDisplay_Drill_Heat_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class AItem;
class UImage;
class UTextBlock;
class UWidgetAnimation;

namespace Game { namespace WeaponsNTools { namespace Drills {

class WeaponDisplay_Drill_Heat_C : public UUserWidget
{
public:
    UE_CLASS("/Game/WeaponsNTools/Drills/WeaponDisplay_Drill_Heat", "WeaponDisplay_Drill_Heat_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* Flash;
    class UImage* Image_88;
    class UImage* Image_131;
    class UTextBlock* TextBlock_440;
    class UTextBlock* TextBlock_HeatValue;
    class AItem* Item;
    void ExecuteUbergraph_WeaponDisplay_Drill_Heat(int EntryPoint);
    void OnEquipped();
    void On_UnEquipped();
    static constexpr const char* On_UnEquipped__UeName = "On UnEquipped";
    void Init(class AItem* Item_0);
    UE_COSMETIC void Construct();
    void SetHeatValue(float HeatPercentage, bool overheated);
};

}}}   // namespace Game::WeaponsNTools::Drills

using WeaponDisplay_Drill_Heat_C = Game::WeaponsNTools::Drills::WeaponDisplay_Drill_Heat_C;