#pragma once
/*
Blueprint class WeaponDisplay_Crossbow_AmmoCount_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class ACrossbow;
class AItem;
class UTextBlock;
class UTexture2D;
class UWidgetSwitcher;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_Image_C; }}}}

namespace Game { namespace WeaponsNTools { namespace Crossbow {

class WeaponDisplay_Crossbow_AmmoCount_C : public UUserWidget
{
public:
    UE_CLASS("/Game/WeaponsNTools/Crossbow/WeaponDisplay_Crossbow_AmmoCount", "WeaponDisplay_Crossbow_AmmoCount_C");
    using Basic_Image_C = Game::UI::Art::WidgetParts::Basic_Image_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetSwitcher* ArrowSwitcher;
    Basic_Image_C* EffectArrow;
    Basic_Image_C* SimpleArrow;
    class UTextBlock* Text_Default;
    class AItem* Item;
    class ACrossbow* Crossbow;
    void ExecuteUbergraph_WeaponDisplay_Crossbow_AmmoCount(int EntryPoint);
    void OnCrossbowUnEquipped();
    void OnCrossbowEquipped();
    void OnItemSet();
    void OnArrowChanged(bool InDefaultArrow);
    void OnAmountChanged(int amount);
    void SetItem(class AItem* InItem);
    void Refresh();
    void GetArrowIcon(class UTexture2D*& OutIcon);
};

}}}   // namespace Game::WeaponsNTools::Crossbow

using WeaponDisplay_Crossbow_AmmoCount_C = Game::WeaponsNTools::Crossbow::WeaponDisplay_Crossbow_AmmoCount_C;