#pragma once
/*
Blueprint class Widget_DropPod_BiomeRadar_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../UMG.h"

class UBiome;
class UGeneratedMission;
class UImage;
class UTextBlock;
class UVerticalBox;
class UWidgetAnimation;
class UWidgetSwitcher;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_Menu_ColorBar_C; class Basic_ResourceIcon_C; }}}}
namespace Game { namespace UI { namespace MainOnscreenHUD { namespace Standard { class UI_ImageTinted_C; }}}}
namespace Game { namespace UI { namespace _GlobalAssets { namespace MaskedImage { class UI_MaskedImage_C; }}}}

namespace Game { namespace Art { namespace DropPod { namespace Widgets {

class Widget_DropPod_BiomeRadar_C : public UUserWidget
{
public:
    UE_CLASS("/Game/Art/DropPod/Widgets/Widget_DropPod_BiomeRadar", "Widget_DropPod_BiomeRadar_C");
    using Basic_Menu_ColorBar_C = Game::UI::Art::WidgetParts::Basic_Menu_ColorBar_C;
    using Basic_ResourceIcon_C = Game::UI::Art::WidgetParts::Basic_ResourceIcon_C;
    using UI_ImageTinted_C = Game::UI::MainOnscreenHUD::Standard::UI_ImageTinted_C;
    using UI_MaskedImage_C = Game::UI::_GlobalAssets::MaskedImage::UI_MaskedImage_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* RadarRotation;
    class UWidgetAnimation* DeepDiveLogo;
    Basic_Menu_ColorBar_C* Basic_Menu_ColorBar;
    Basic_ResourceIcon_C* Basic_ResourceIcon;
    Basic_ResourceIcon_C* Basic_ResourceIcon_0;
    class UTextBlock* DATA_PlanetaryRegionName;
    class UVerticalBox* DeepDive;
    class UImage* Gradient;
    class UVerticalBox* NoDeepDive;
    class UImage* RadarOutline;
    class UImage* RadarSweep;
    class UTextBlock* TextBlock_0;
    UI_ImageTinted_C* UI_ImageTinted;
    UI_MaskedImage_C* UI_MaskedImage;
    class UVerticalBox* VerticalBox_MissionData;
    class UWidgetSwitcher* WidgetSwitcher_1;
    float Depth;
    float Angle;
    class UBiome* Biome;
    void ExecuteUbergraph_Widget_DropPod_BiomeRadar(int EntryPoint);
    void OnGeneratedMissionChanged(class UGeneratedMission* OutGeneratedMission);
    UE_COSMETIC void Construct();
    void SetGeneratedMission(class UGeneratedMission* In_Mission);
};

}}}}   // namespace Game::Art::DropPod::Widgets

using Widget_DropPod_BiomeRadar_C = Game::Art::DropPod::Widgets::Widget_DropPod_BiomeRadar_C;