#pragma once
/*
Blueprint class WidgetCabinPlayerName_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../UMG.h"

class UImage;
class UTextBlock;

namespace Game { namespace Art { namespace Environments { namespace SpaceRig {

class WidgetCabinPlayerName_C : public UUserWidget
{
public:
    UE_CLASS("/Game/Art/Environments/SpaceRig/WidgetCabinPlayerName", "WidgetCabinPlayerName_C");
    class UImage* Image_0;
    class UTextBlock* NameText;
    void SetPlayerName(FText NewName);
    void SetColor(FLinearColor Color);
};

}}}}   // namespace Game::Art::Environments::SpaceRig

using WidgetCabinPlayerName_C = Game::Art::Environments::SpaceRig::WidgetCabinPlayerName_C;