#pragma once
/*
Blueprint class WND_MisSel_MissionDescription_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"
#include "../UMG.h"

class UBorder;
class UButton;
class UGeneratedMission;
class UImage;
class UMissionTemplate;
class UTextBlock;
class UVerticalBox;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_Menu_ColorBar_C; class Icon_ClassLevel_C; }}}}
namespace Game { namespace UI { namespace Menu_MissionSelectionMK3 { class ITM_MisDesMutator_C; class ITM_MisSel_DotMarker_CaveDifficulty_C; class ITM_MisSel_DotMarker_MissionLength_C; class ITM_MisSel_MissionIconBasic_C; class ITM_MisSel_ObjectivePrimary_C; class ITM_MisSel_ObjectiveSecondary_C; }}}
namespace Game { namespace UI { namespace _GlobalAssets { class BlurBackground_C; }}}

namespace Game { namespace UI { namespace Menu_MissionSelectionMK3 {

class WND_MisSel_MissionDescription_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_MissionSelectionMK3/WND_MisSel_MissionDescription", "WND_MisSel_MissionDescription_C");
    using Basic_Menu_ColorBar_C = Game::UI::Art::WidgetParts::Basic_Menu_ColorBar_C;
    using BlurBackground_C = Game::UI::_GlobalAssets::BlurBackground_C;
    using ITM_MisDesMutator_C = Game::UI::Menu_MissionSelectionMK3::ITM_MisDesMutator_C;
    using ITM_MisSel_DotMarker_CaveDifficulty_C = Game::UI::Menu_MissionSelectionMK3::ITM_MisSel_DotMarker_CaveDifficulty_C;
    using ITM_MisSel_DotMarker_MissionLength_C = Game::UI::Menu_MissionSelectionMK3::ITM_MisSel_DotMarker_MissionLength_C;
    using ITM_MisSel_MissionIconBasic_C = Game::UI::Menu_MissionSelectionMK3::ITM_MisSel_MissionIconBasic_C;
    using ITM_MisSel_ObjectivePrimary_C = Game::UI::Menu_MissionSelectionMK3::ITM_MisSel_ObjectivePrimary_C;
    using ITM_MisSel_ObjectiveSecondary_C = Game::UI::Menu_MissionSelectionMK3::ITM_MisSel_ObjectiveSecondary_C;
    using Icon_ClassLevel_C = Game::UI::Art::WidgetParts::Icon_ClassLevel_C;
    FPointerToUberGraphFrame UberGraphFrame;
    Basic_Menu_ColorBar_C* Basic_Menu_ColorBar_C_0;
    Basic_Menu_ColorBar_C* Basic_Menu_ColorBar_C_1;
    BlurBackground_C* BlurBackground;
    class UBorder* Border_PlayerRankNeeded;
    class UButton* Button_MissionInfo;
    class UBorder* CampaignInfo;
    Basic_Menu_ColorBar_C* ColorBar_Bottom;
    class UTextBlock* DATADescription_Assignment;
    class UTextBlock* DATADescription_Assignment_Locked;
    class UTextBlock* DataMissionName;
    class UTextBlock* DATAMissionType;
    ITM_MisSel_DotMarker_CaveDifficulty_C* DotMarker_Complexity;
    ITM_MisSel_DotMarker_MissionLength_C* DotMarker_Length;
    Icon_ClassLevel_C* Icon_ClassLevel;
    class UImage* Image_0;
    class UImage* Image_93;
    ITM_MisSel_MissionIconBasic_C* ITEM_MissionSelection_MissionIconBasic_C_100;
    ITM_MisDesMutator_C* ITM_MisDes_Modifier;
    ITM_MisSel_ObjectivePrimary_C* ITM_MisSel_ObjectivePrimary;
    ITM_MisSel_ObjectiveSecondary_C* ITM_MisSel_ObjectiveSecondary;
    class UBorder* Locked;
    class UTextBlock* TextBlock_Rank;
    class UTextBlock* TXTCaveComplexity;
    class UTextBlock* TXTMissionLength;
    class UVerticalBox* vboxMissionModifiers;
    class UVerticalBox* vboxMissionWindow;
    class UVerticalBox* VerticalBox_Objectives;
    class UMissionTemplate* MissionTemplate;
    void ExecuteUbergraph_WND_MisSel_MissionDescription(int EntryPoint);
    void BndEvt__WND_MisSel_MissionDescription_Button_MissionInfo_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__WND_MisSel_MissionDescription_Button_MissionInfo_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature();
    void BndEvt__Button_MissionInfo_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void SetData(class UGeneratedMission* mission, FGameDifficulty Difficulty);
    void HandleAssignments(class UGeneratedMission* mission, FGameDifficulty& optionalDifficulty);
};

}}}   // namespace Game::UI::Menu_MissionSelectionMK3

using WND_MisSel_MissionDescription_C = Game::UI::Menu_MissionSelectionMK3::WND_MisSel_MissionDescription_C;