#pragma once
/*
Blueprint class WND_Trading_DailyDeal_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../CoreUObject.h"
#include "../Engine.h"
#include "../FSD.h"
#include "../UMG.h"

class UImage;
class UOverlay;
class UResourceData;
class UTextBlock;
class UVerticalBox;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_ButtonCutCorner_C; }}}}
namespace Game { namespace UI { namespace Menu_Trading { class ITM_Trading_DailyDeal_C; }}}
namespace Game { namespace UI { namespace _GlobalAssets { class BlurBackground_C; }}}

namespace Game { namespace UI { namespace Menu_Trading {

class WND_Trading_DailyDeal_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/Menu_Trading/WND_Trading_DailyDeal", "WND_Trading_DailyDeal_C");
    using Basic_ButtonCutCorner_C = Game::UI::Art::WidgetParts::Basic_ButtonCutCorner_C;
    using BlurBackground_C = Game::UI::_GlobalAssets::BlurBackground_C;
    using ITM_Trading_DailyDeal_C = Game::UI::Menu_Trading::ITM_Trading_DailyDeal_C;
    FPointerToUberGraphFrame UberGraphFrame;
    Basic_ButtonCutCorner_C* B_Trade;
    BlurBackground_C* BlurBackground;
    class UImage* DailyDealHeadline_BG;
    class UImage* I_PosterOutline;
    class UImage* Icon_Refresh;
    ITM_Trading_DailyDeal_C* ITM_DailyDeal2;
    class UImage* MineralTraderHeadline_Outline;
    class UOverlay* Overlay_DealHolder;
    class UOverlay* Overlay_SoldOut;
    class UTextBlock* Text_;
    class UTextBlock* Text_TimeToNext;
    class UVerticalBox* V_DailyDeal;
    FRandomStream RandomStream;
    FTimerHandle Timer;
    FDailyDeal CurrDeal;
    TMulticastInlineDelegate<void()> OnDealBought;
    void ExecuteUbergraph_WND_Trading_DailyDeal(int EntryPoint);
    void OnCreditsChanged(int Credits);
    void OnResourceAmountChanged(class UResourceData* Resource, float currentAmount);
    UE_COSMETIC void Construct();
    void BndEvt__B_Trade_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature(Basic_ButtonCutCorner_C* Button);
    void UpdateTime();
    void Refresh();
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void Yes_D21FAC5A44FF696C3525F18876AC316A();
    void No_D21FAC5A44FF696C3525F18876AC316A();
    void FormatDailyDealResources(TMap<class UResourceData*, int>& Resources);
};

}}}   // namespace Game::UI::Menu_Trading

using WND_Trading_DailyDeal_C = Game::UI::Menu_Trading::WND_Trading_DailyDeal_C;