#pragma once
/*
Blueprint class WND_ForgeAvailableMessage_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

namespace Game { namespace UI { namespace HUD_SpaceRig {

class WND_ForgeAvailableMessage_C : public UWindowWidget
{
public:
    UE_CLASS("/Game/UI/HUD_SpaceRig/WND_ForgeAvailableMessage", "WND_ForgeAvailableMessage_C");
    FPointerToUberGraphFrame UberGraphFrame;
    void ExecuteUbergraph_WND_ForgeAvailableMessage(int EntryPoint);
    void OnShown();
};

}}}   // namespace Game::UI::HUD_SpaceRig

using WND_ForgeAvailableMessage_C = Game::UI::HUD_SpaceRig::WND_ForgeAvailableMessage_C;