#pragma once
/*
Blueprint class WND_CharacterRetirement_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"
#include "../SlateCore.h"
#include "../UMG.h"

class UAudioComponent;
class UBorder;
class UFSDLabelWidget;
class UHorizontalBox;
class UPlayerCharacterID;
class UResourceData;
class USizeBox;
class UWidgetAnimation;
class UWindowWidget;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_ButtonScalable2_C; class Basic_Menu_ColorBar_C; class Basic_Menu_LargeWindowWithHeader_C; class UI_PlayerSpeaking_List_C; }}}}
namespace Game { namespace UI { namespace Menu_Crafting { class ITM_Craft_ResourceBig_C; }}}
namespace Game { namespace UI { namespace Menu_MIssionCompleteMK2 { class OVERLAY_RetirementGranted_C; }}}
namespace Game { namespace UI { namespace MissionControl { class MissionControl_MainDialogue_C; }}}
namespace Game { namespace UI { namespace _GlobalAssets { class BlurBackground_C; }}}

namespace Game { namespace UI { namespace CharacterSelectionMK2 { namespace Retirement {

class WND_CharacterRetirement_C : public UWindowWidget
{
public:
    UE_CLASS("/Game/UI/CharacterSelectionMK2/Retirement/WND_CharacterRetirement", "WND_CharacterRetirement_C");
    using Basic_ButtonScalable2_C = Game::UI::Art::WidgetParts::Basic_ButtonScalable2_C;
    using Basic_Menu_ColorBar_C = Game::UI::Art::WidgetParts::Basic_Menu_ColorBar_C;
    using Basic_Menu_LargeWindowWithHeader_C = Game::UI::Art::WidgetParts::Basic_Menu_LargeWindowWithHeader_C;
    using BlurBackground_C = Game::UI::_GlobalAssets::BlurBackground_C;
    using ITM_Craft_ResourceBig_C = Game::UI::Menu_Crafting::ITM_Craft_ResourceBig_C;
    using MissionControl_MainDialogue_C = Game::UI::MissionControl::MissionControl_MainDialogue_C;
    using OVERLAY_RetirementGranted_C = Game::UI::Menu_MIssionCompleteMK2::OVERLAY_RetirementGranted_C;
    using UI_PlayerSpeaking_List_C = Game::UI::Art::WidgetParts::UI_PlayerSpeaking_List_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* AnimPanBackground;
    class UWidgetAnimation* FadeOut;
    class UWidgetAnimation* WarningPulse;
    class UBorder* BackgroundFade;
    Basic_Menu_ColorBar_C* Basic_Menu_ColorBar;
    Basic_Menu_LargeWindowWithHeader_C* Basic_Menu_LargeWindowWithHeader;
    BlurBackground_C* BlurBackground;
    Basic_ButtonScalable2_C* BTN_No;
    Basic_ButtonScalable2_C* BTN_Yes;
    class UFSDLabelWidget* Cost_Label;
    class USizeBox* DialogBox;
    class UHorizontalBox* HorizontalBox_Cost;
    ITM_Craft_ResourceBig_C* ITM_Craft_ResourceBig;
    MissionControl_MainDialogue_C* MissionControl;
    OVERLAY_RetirementGranted_C* OVERLAY_RetirementGranted;
    Basic_ButtonScalable2_C* SkipButton;
    UI_PlayerSpeaking_List_C* UI_PlayerSpeaking_List;
    class UPlayerCharacterID* characterID;
    TMap<class UResourceData*, int> RetirementCost;
    int RetiredCount;
    class UAudioComponent* CharacterAudio;
    class UAudioComponent* FanfareAudio;
    class UAudioComponent* MissionControlAudio;
    FTimerHandle MissionControlTimer;
    bool SkipRequested;
    void ExecuteUbergraph_WND_CharacterRetirement(int EntryPoint);
    void OnRewardsClosed(class UWindowWidget* Window);
    void TestRetire();
    void AfterMissionControlSpeak();
    void BndEvt__SkipButton_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature();
    void OnClosed();
    void Stop_Character_Audio();
    static constexpr const char* Stop_Character_Audio__UeName = "Stop Character Audio";
    void FadeInBackground(float Duration);
    void Retire();
    void BndEvt__OVERLAY_RetirementGranted_K2Node_ComponentBoundEvent_1_OnFinished__DelegateSignature();
    void HideMouseCursor();
    void OnShown();
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
    void BndEvt__BTN_Yes_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();
    void SetData(class UPlayerCharacterID* characterID_0);
    void BndEvt__BTN_No_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature();
    void OnSuccess_8D7CEF664ECE349247F068951073F0FE();
    void OnFailure_8D7CEF664ECE349247F068951073F0FE();
    void BuildCostList();
    UE_PURE bool IsAudioFinished(class UAudioComponent* InAudioComponent);
    void StopAudio(class UAudioComponent* InAudioComponent);
    UE_COSMETIC FEventReply OnKeyUp(FGeometry MyGeometry, FKeyEvent InKeyEvent);
};

}}}}   // namespace Game::UI::CharacterSelectionMK2::Retirement

using WND_CharacterRetirement_C = Game::UI::CharacterSelectionMK2::Retirement::WND_CharacterRetirement_C;