#pragma once
/*
Blueprint class WND_MissionBar_DeepDive_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../SlateCore.h"
#include "../UMG.h"

class UBorder;
class UHorizontalBox;
class UImage;
class UTextBlock;
class UWidgetAnimation;
namespace Game { namespace UI { namespace Art { namespace WidgetParts { class Basic_Menu_ColorBar_C; }}}}
namespace Game { namespace UI { namespace HUD_SpaceRig { namespace MissionOverview { class ITM_DeepDive_Codename_C; class ITM_Gear_Bar_C; }}}}
namespace Game { namespace UI { namespace Menu_MissionStart { class ITM_DeepDiveHeader_C; }}}
namespace Game { namespace UI { namespace _GlobalAssets { namespace MaskedImage { class UI_GradientMasked_Image_C; }}}}

namespace Game { namespace UI { namespace HUD_SpaceRig { namespace MissionOverview {

class WND_MissionBar_DeepDive_C : public UUserWidget
{
public:
    UE_CLASS("/Game/UI/HUD_SpaceRig/MissionOverview/WND_MissionBar_DeepDive", "WND_MissionBar_DeepDive_C");
    using Basic_Menu_ColorBar_C = Game::UI::Art::WidgetParts::Basic_Menu_ColorBar_C;
    using ITM_DeepDiveHeader_C = Game::UI::Menu_MissionStart::ITM_DeepDiveHeader_C;
    using ITM_DeepDive_Codename_C = Game::UI::HUD_SpaceRig::MissionOverview::ITM_DeepDive_Codename_C;
    using ITM_Gear_Bar_C = Game::UI::HUD_SpaceRig::MissionOverview::ITM_Gear_Bar_C;
    using UI_GradientMasked_Image_C = Game::UI::_GlobalAssets::MaskedImage::UI_GradientMasked_Image_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* Intro;
    Basic_Menu_ColorBar_C* Basic_Menu_ColorBar;
    Basic_Menu_ColorBar_C* Basic_Menu_ColorBar_C_0;
    Basic_Menu_ColorBar_C* Basic_Menu_ColorBar_C_1;
    Basic_Menu_ColorBar_C* Basic_Menu_ColorBar_C_2;
    Basic_Menu_ColorBar_C* Basic_Menu_ColorBar_C_3;
    Basic_Menu_ColorBar_C* Basic_Menu_ColorBar_C_4;
    class UImage* BGgradient;
    class UBorder* Center;
    class UBorder* edgeL;
    class UBorder* edgeR;
    class UHorizontalBox* HorizontalBox_Attention;
    class UImage* Image_0;
    ITM_DeepDive_Codename_C* ITM_DeepDive_Codename;
    ITM_DeepDiveHeader_C* ITM_DeepDiveHeader;
    ITM_Gear_Bar_C* ITM_Gear_Bar;
    class UBorder* MtopBG;
    class UTextBlock* TextBlock_2;
    class UImage* TopSlantL;
    class UImage* TopSlantR;
    class UTextBlock* TXT_Attention;
    UI_GradientMasked_Image_C* UI_GradientMasked_Image;
    void ExecuteUbergraph_WND_MissionBar_DeepDive(int EntryPoint);
    UE_COSMETIC void Tick(FGeometry MyGeometry, float InDeltaTime);
    UE_COSMETIC void Construct();
    UE_COSMETIC void PreConstruct(bool IsDesignTime);
};

}}}}   // namespace Game::UI::HUD_SpaceRig::MissionOverview

using WND_MissionBar_DeepDive_C = Game::UI::HUD_SpaceRig::MissionOverview::WND_MissionBar_DeepDive_C;