#pragma once
/*
Blueprint class WPN_Pickaxe_Scout_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "WPN_Pickaxe_C.h"

namespace Game { namespace WeaponsNTools { namespace Pickaxe { namespace Scout {

class WPN_Pickaxe_Scout_C : public Game::WeaponsNTools::Pickaxe::WPN_Pickaxe_C
{
public:
    UE_CLASS("/Game/WeaponsNTools/Pickaxe/Scout/WPN_Pickaxe_Scout", "WPN_Pickaxe_Scout_C");
};

}}}}   // namespace Game::WeaponsNTools::Pickaxe::Scout

using WPN_Pickaxe_Scout_C = Game::WeaponsNTools::Pickaxe::Scout::WPN_Pickaxe_Scout_C;