#pragma once
/*
Blueprint class WPN_Pistol_A_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class AFSDPlayerState;
class UCrosshairAggregator;
class UFirstPersonStaticMeshComponent;
class UFirstPersonWidgetComponent;
class UHitscanComponent;
class UPointLightComponent;
class USkinEffect;
class UStaticMeshComponent;

namespace Game { namespace WeaponsNTools { namespace Pistol {

class WPN_Pistol_A_C : public ABasicPistol
{
public:
    UE_CLASS("/Game/WeaponsNTools/Pistol/WPN_Pistol_A", "WPN_Pistol_A_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UStaticMeshComponent* TP_Animation_Mag;
    static constexpr const char* TP_Animation_Mag__UeScsNode = "cce5afd4f311754c89a2cc9691bea4c1";
    class UFirstPersonStaticMeshComponent* FP_Animation_Mag;
    static constexpr const char* FP_Animation_Mag__UeScsNode = "7b3536563438f34589ccfbb94a8ad755";
    class UFirstPersonWidgetComponent* FirstPersonWidget;
    static constexpr const char* FirstPersonWidget__UeScsNode = "1a8703c1ae7a4f43a4d01d28fe486346";
    class UFirstPersonStaticMeshComponent* FirstPersonStaticMesh;
    static constexpr const char* FirstPersonStaticMesh__UeScsNode = "f1bef49315c74a46af0683265d909c09";
    class UFirstPersonStaticMeshComponent* FP_Mag;
    static constexpr const char* FP_Mag__UeScsNode = "544078af8a55fc4cb17e20d577de8da5";
    class UStaticMeshComponent* TP_Mag;
    static constexpr const char* TP_Mag__UeScsNode = "e713e825b1b13b43ae0304cec1a54997";
    class UPointLightComponent* MuzzlePointLight;
    static constexpr const char* MuzzlePointLight__UeScsNode = "d81895c14f838642a4ab04da0cfb0d0f";
    class UCrosshairAggregator* CrosshairAggregator;
    static constexpr const char* CrosshairAggregator__UeScsNode = "9db288b98389e04781277486bcc60c7a";
    class UHitscanComponent* HitScan;
    static constexpr const char* HitScan__UeScsNode = "7191aaf8a6b6a1458efec313637c9a0a";
    void ExecuteUbergraph_WPN_Pistol_A(int EntryPoint);
    void OnSkinChanged(class USkinEffect* Skin);
    void Receive_ReloadEnd();
    void Receive_ReloadBegin();
    void ReceiveBeginPlay();
    void UserConstructionScript();
    void GetGearStatEntry(class AFSDPlayerState* PlayerState, TArray<FGearStatEntry> Stats) const;
    class UFirstPersonStaticMeshComponent* Receive_GetFPAnimationEventMesh() const;
    class UStaticMeshComponent* Receive_GetTPAnimationEventMesh() const;
};

}}}   // namespace Game::WeaponsNTools::Pistol

using WPN_Pistol_A_C = Game::WeaponsNTools::Pistol::WPN_Pistol_A_C;