#pragma once
/*
Blueprint class WPN_GrenadeLauncher_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class AFSDPlayerState;
class UCrosshairAggregator;
class UFirstPersonWidgetComponent;
class UItemUpgrade;
class UProjectileLauncherComponent;

namespace Game { namespace WeaponsNTools { namespace GrenadeLauncher {

class WPN_GrenadeLauncher_C : public AAmmoDrivenWeapon
{
public:
    UE_CLASS("/Game/WeaponsNTools/GrenadeLauncher/WPN_GrenadeLauncher", "WPN_GrenadeLauncher_C");
    FPointerToUberGraphFrame UberGraphFrame;
    class UFirstPersonWidgetComponent* FirstPersonWidget;
    static constexpr const char* FirstPersonWidget__UeScsNode = "b835adb0eac3694f8bc12709554d5fd0";
    class UCrosshairAggregator* CrosshairAggregator;
    static constexpr const char* CrosshairAggregator__UeScsNode = "6162824bbd52a245966e2560abaa4729";
    class UProjectileLauncherComponent* projectileLauncher;
    static constexpr const char* projectileLauncher__UeScsNode = "9b95c6f3b74fcc40a79f45df250ee43f";
    void ExecuteUbergraph_WPN_GrenadeLauncher(int EntryPoint);
    void CustomEvent1(class UItemUpgrade* Event);
    void ReceiveBeginPlay();
    void GetGearStatEntry(class AFSDPlayerState* PlayerState, TArray<FGearStatEntry> Stats) const;
};

}}}   // namespace Game::WeaponsNTools::GrenadeLauncher

using WPN_GrenadeLauncher_C = Game::WeaponsNTools::GrenadeLauncher::WPN_GrenadeLauncher_C;