#pragma once
/*
Blueprint class WPN_CoilGun_C, generated by AssetGen/tools/genueapi.py. Do not edit.

A member is here if and only if AssetGen can compile a use of it.
*/
#include "../UeMeta.h"
#include "../Engine.h"
#include "../FSD.h"

class AActor;
class AFSDPlayerState;
class APlayerCharacter;
class UAllPiercingHitscanComponent;
class UAudioComponent;
class UCrosshairAggregator;
class UDamageComponent;
class UFSDAudioComponent;
class UFirstPersonWidgetComponent;
class UParticleSystemComponent;
class UPointLightComponent;
class USceneComponent;
class USkinEffect;
class USoundBase;
class UTimelineComponent;
namespace Game { namespace WeaponsNTools { namespace ChargeBlaster { class WeaponDisplay_ChargeBlaster_AmmoCounter_C; class WeaponDisplay_ChargeBlaster_Heat_C; }}}
namespace Game { namespace WeaponsNTools { namespace CoilGun { class WeaponDisplay_Coilgun_Charge_C; }}}

namespace Game { namespace WeaponsNTools { namespace CoilGun {

class WPN_CoilGun_C : public ACoilGun
{
public:
    UE_CLASS("/Game/WeaponsNTools/CoilGun/WPN_CoilGun", "WPN_CoilGun_C");
    using WeaponDisplay_ChargeBlaster_AmmoCounter_C = Game::WeaponsNTools::ChargeBlaster::WeaponDisplay_ChargeBlaster_AmmoCounter_C;
    using WeaponDisplay_ChargeBlaster_Heat_C = Game::WeaponsNTools::ChargeBlaster::WeaponDisplay_ChargeBlaster_Heat_C;
    using WeaponDisplay_Coilgun_Charge_C = Game::WeaponsNTools::CoilGun::WeaponDisplay_Coilgun_Charge_C;
    FPointerToUberGraphFrame UberGraphFrame;
    class UFSDAudioComponent* CoilGunChargeGlow;
    class UFSDAudioComponent* CoilGunCharge;
    class UFirstPersonWidgetComponent* Widget_ChargeNew;
    class USceneComponent* Scene;
    class UDamageComponent* FireExplosionDamage;
    class UAllPiercingHitscanComponent* AllPiercingHitscan;
    class UAudioComponent* AC_ChargeLevel;
    class UPointLightComponent* MuzzlePointLight;
    class UCrosshairAggregator* CrosshairAggregator;
    float FadeTimeline_ChargeFade_C49992004992D09AEFEFFF997C5FEA5C;
    float FadeTimeline_SoundFade_C49992004992D09AEFEFFF997C5FEA5C;
    float FadeTimeline_LightFade_C49992004992D09AEFEFFF997C5FEA5C;
    TEnum<ETimelineDirection> FadeTimeline__Direction_C49992004992D09AEFEFFF997C5FEA5C;
    class UTimelineComponent* FadeTimeline;
    WeaponDisplay_Coilgun_Charge_C* ChargeUI;
    WeaponDisplay_ChargeBlaster_Heat_C* OverheatUI;
    WeaponDisplay_ChargeBlaster_AmmoCounter_C* AmmoUI;
    int ChargeLevel;
    class UAudioComponent* AC_Heat;
    class USoundBase* TemperatureAudio;
    class USoundBase* OverheatedAudio;
    class UAudioComponent* AC_ChargeSpinUp;
    class UParticleSystemComponent* OverheatEmitterInstance;
    float ChargeReached;
    class UParticleSystemComponent* BrokeShieldBoostParticles;
    class UAudioComponent* BrokeShieldBoostSound;
    FRuntimeFloatCurve HeatMaterialCurve;
    class UAudioComponent* AC_Heat_0;
    bool HasFearTrail;
    void ExecuteUbergraph_WPN_CoilGun(int EntryPoint);
    UE_MULTICAST UE_RELIABLE void All_PlayFireKillEffects(FVector_NetQuantize Location);
    void Receive_Overheated();
    void OnShieldBrokenBoost();
    void OnShieldBrokeBoostStopped();
    void OnChargeChanged_Event_0(float charge);
    void ReceiveBeginPlay();
    void RecieveStoppedCharging(float ChargeProgress_0);
    void RecieveStartedCharging();
    void OnFireKill(class AActor* Target);
    void AddedToInventory(class APlayerCharacter* ItemOwner);
    void OnSkinChanged(class USkinEffect* Skin);
    void ReceiveOverheatedChanged(bool isOverheated);
    void RecieveUnequipped();
    void FadeTimeline__UpdateFunc();
    void FadeTimeline__FinishedFunc();
    void UserConstructionScript();
    void HandleChargeAudio(float charge);
    void HandleHeatAudio();
    void FadeOutIfValid(class UAudioComponent*& AC);
    void GetGearStatEntry(class AFSDPlayerState* PlayerState, TArray<FGearStatEntry>& Stats) const;
private:
    struct UeMarkers
    {
        static constexpr const char* UeDefaultSubobjects = "/Script/FSD.AmmoDriveWeaponAggregator Aggregator;/Script/FSD.CoilgunTrailSpawner TrailSpawner;/Script/FSD.DamageComponent BlastDamage;/Script/FSD.DamageComponent MoleDamage;/Script/FSD.DamageComponent NormalDamage;/Script/FSD.DamageComponent OverchargeDamage;/Script/FSD.DamageComponent ShotwaveDamage;/Script/FSD.DamageConversionBonus NormalDamage:DamageConversionBonus_0;/Script/FSD.FirstPersonSkeletalMeshComponent FPMesh;/Script/Niagara.NiagaraComponent FP_OverchargeIndicatorParticles;/Script/Niagara.NiagaraComponent FullyChargedParticles;/Script/Niagara.NiagaraComponent TP_FullchargeParticles;/Script/Engine.SceneComponent Root;/Script/Engine.SkeletalMeshComponent TPMesh;/Script/FSD.SkinnableComponent Skinnable;/Script/FSD.SkinUnlock Upgradable:SkinUnlock_2;/Script/FSD.SkinUnlock Upgradable:SkinUnlock_3;/Script/FSD.SkinUnlock Upgradable:SkinUnlock_4;/Script/FSD.UpgradableItemComponent Upgradable";
        static constexpr const char* CoilGunChargeGlow__UeScsNode = "f0e518855af1b241b0b7d6c4c6f7df07";
        static constexpr const char* CoilGunCharge__UeScsNode = "984a2260ceb791429e477cb2e2a1cd25";
        static constexpr const char* Widget_ChargeNew__UeScsNode = "05abeabdd48efb4596cf6a9b6c5b66ba";
        static constexpr const char* Scene__UeScsNode = "b469cdbd4e5700479b2e5538e2718f32";
        static constexpr const char* FireExplosionDamage__UeScsNode = "191d3bb2473ff146b843d6bde23d2d46";
        static constexpr const char* AllPiercingHitscan__UeScsNode = "41ca589d611ecd42aee6e77b93499bf3";
        static constexpr const char* AC_ChargeLevel__UeScsNode = "7acb3a7e6c29af4cb3ee93ad46e3ce73";
        static constexpr const char* MuzzlePointLight__UeScsNode = "d81895c14f838642a4ab04da0cfb0d0f";
        static constexpr const char* CrosshairAggregator__UeScsNode = "9db288b98389e04781277486bcc60c7a";
    };
};

}}}   // namespace Game::WeaponsNTools::CoilGun

using WPN_CoilGun_C = Game::WeaponsNTools::CoilGun::WPN_CoilGun_C;